### ISSUE TITLE
all: add an API for Key/Value database

### ISSUE THREAD

**Issue by medyagh** [google/go-cloud#1017]
I have a feature request, for simple insert/update for key/value database such as Google Cloud Datastore/Firebase and AWS DynamoDB. 

I wonder if that is something other people like to see?

**Comment by vangent** [comment]
Thanks for the request! It's on our list of things to consider, but no timeline as of yet.

**Comment by philippgille** [comment]
@medyagh: Until that's implemented here, you can try out philippgille/gokv. Among embedded DBs (bbolt, BadgerDB), distributed key-value stores (Redis, Consul, etcd) and others (Memcached, PostgreSQL, CockroachDB, Apache Ignite), there are also cloud-specific implementations for Google Cloud Datastore, Amazon DynamoDB and Azure Table Storage. Google Cloud Firestore, Azure CosmosDB and Alibaba Cloud Table Store are on the roadmap. I'd be very happy about feedback!

And maybe I can help working on this issue? What would be the next step? Who decides on how the interface should look like?

**Comment by jba** [comment]
Sounds awesome! I've got some thoughts on this which I'll write up soon. Unfortunately it's not a high priority for us this quarter, but we can certainly work on design.

**Comment by medyagh** [comment]
@philippgille that is a really cool project thanks for sharing, it would be cool if there was something like gokv wth query-ing feature.

**Comment by vangent** [comment]
We're working on this now; search issues for "docstore".
