### ISSUE TITLE
blob/fileblob: repeated slashes fails test

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#1081]
If you add the following test case to `drivertest.testKeys`:

```go
{
  description: "repeatedfwdslashes",
  key: "///foo///bar///baz",
},
```

it fails the test.

(I'd also like to see tests for `./` and `../` while we're here. I like malicious inputs.)

**Comment by vangent** [comment]
I'm not sure this is fixable for us; it fails the test for S3 as well.

If you create a blob with key = `x//y//z` in S3, it is saved as `x/y/z`. In GCS, it is saved as `x//y//z`.

`../` also appears to be treated specially by providers (not sure if it's consistent).

We've already noted unusual behavior (from Azure) with `\` characters as well.

@zombiezen WDYT about documenting this in `blob.go`? I.e., if you want to stay compatible, avoid backslashes and repeated forward slashes in your blob names.

**Comment by zombiezen** [comment]
Can we just make these be errors in the concrete type? Seems preferable to allowing them to work in some places but having really surprising behavior in others. (I realize there's overlap with #905, but this is finally giving me a good test case to run through in my head.)

**Comment by vangent** [comment]
That's one possibility. I'm not sure it entirely avoids the problem, as blobs with the weird names could have been created through some other mechanism. But it might be better than nothing.
