### ISSUE TITLE
pubsub: TestSendReceiveTwo fails for gcppubsub in record mode

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#1097]
Here is the output:

```
[ ~/gocloud.dev/pubsub/gcppubsub ] go test -record
ERROR: 2019/01/10 11:12:09 pickfirstBalancer: failed to NewSubConn: rpc error: code = Canceled desc = grpc: the client connection is closing
--- FAIL: TestConformance (10.28s)
    --- FAIL: TestConformance/TestSendReceiveTwo (5.34s)
        replay.go:187: Recording into golden file testdata/TestConformance/TestSendReceiveTwo.replay
        drivertest.go:233: sub #1: Sort({[]*pubsub.Message})[1->?]:
            	-: &pubsub.Message{Body: []uint8{0x32}, Metadata: map[string]string{"a": "2"}, ack: (func())(0x01424a50), isAcked: true}
            	+: <non-existent>
            Sort({[]*pubsub.Message})[?->1]:
            	-: <non-existent>
            	+: &pubsub.Message{Body: []uint8{0x31}, Metadata: map[string]string{"a": "1"}}
FAIL
exit status 1
FAIL	gocloud.dev/pubsub/gcppubsub	10.432s
```

Here's what I think is happening. `TestSendReceive` publishes to the test topic but only drains the messages from one of the subscriptions. Then `TestSendReceiveTwo` publishes more messages to the topic, but ends up getting the messages from `TestSendReceive` in the second subscription because `TestSendReceive` didn't drain that subscription. I guess non-deterministic ordering is playing into this as well.

The solutions proposed by @jba and @vangent in https://github.com/google/go-cloud/issues/1091 should work here. I suggest we start with draining since it's the least disruptive. If it's too flakey we can go with creating and destroying subscriptions.

**Comment by ijt** [comment]
I just tried the draining approach and it means that lots of additional time is spent waiting for the timeouts in the draining function. Creating and destroying the subscriptions on each run would probably be faster and more reliable.

**Comment by jba** [comment]
How long were you waiting for? I think one second should be enough.

**Comment by vangent** [comment]
Also, note that you only have to do the drain in --record mode.

**Comment by vangent** [comment]
> Also, note that you only have to do the drain in --record mode.

Hmm maybe not, never mind.

**Comment by jba** [comment]
Draining should happen only when recording, _before_ turning on the recorder.

**Comment by ijt** [comment]
If we go with draining then it also has to happen after running a test like
TestSendReceive that publishes but doesn't receive all messages in all of
the queues.

Draining is slow and flakey though, whereas creating and destroying
subscriptions should be faster and more reliable.
