### ISSUE TITLE
docs: clarify README about where to run "go get" from

### ISSUE THREAD

**Issue by medyagh** [google/go-cloud#1106]
I am using most of google's libraries to build a web app and I am using  "gocloud.dev v0.8.0" 

and when I call gcsblob.OpenBucket function, it expects me to pass

```ctx context.,  bucketName string,client *gcp.HTTPClient, opts *Options```

however in the source code for gocloud.dev v0.8.0 the signature is different (swapped bucket and client)
```
func openBucket(ctx context.Context, client *gcp.HTTPClient, bucketName string, opts *Options) (*bucket, error) {
```

my guess there is some conflict with other google libraries in .mod, but i am not sure.
here is how my mod file looks like

```

require (
	cloud.google.com/go v0.34.0
	github.com/boj/redistore v0.0.0-20180917114910-cd5dcc76aeff // indirect
	github.com/foolin/gin-template v0.0.0-20180515083052-089e62d1d723
	github.com/gin-contrib/sse v0.0.0-20170109093832-22d885f9ecc7 // indirect
	github.com/gin-gonic/contrib v0.0.0-20181101072842-54170a7b0b4b
	github.com/gin-gonic/gin v1.3.0
	github.com/gorilla/sessions v1.1.3 // indirect
	github.com/json-iterator/go v1.1.5 // indirect
	github.com/mattn/go-isatty v0.0.4 // indirect
	github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd // indirect
	github.com/modern-go/reflect2 v1.0.1 // indirect
	gocloud.dev v0.8.0
	golang.org/x/oauth2 v0.0.0-20190110195249-fd3eaa146cbb
	google.golang.org/api v0.1.0
	gopkg.in/go-playground/assert.v1 v1.2.1 // indirect
	gopkg.in/go-playground/validator.v8 v8.18.2 // indirect
```

**Comment by jba** [comment]
In https://github.com/google/go-cloud/blob/v0.8.0/blob/gcsblob/gcsblob.go has
```
func OpenBucket(ctx context.Context, bucketName string, client *gcp.HTTPClient, ...
```
Where are you getting your source from?

**Comment by vangent** [comment]
[HEAD](https://github.com/google/go-cloud/blob/master/blob/gcsblob/gcsblob.go#L155) has 

```
func OpenBucket(ctx context.Context, client *gcp.HTTPClient, bucketName string, opts *Options)
```

so I suspect you are using `v0.8.0` but looking at the source from head. We changed the order of arguments in https://github.com/google/go-cloud/pull/989.

Your code should work fine with `v0.8.0` using the old signature, but you will have to update it when you update to use `v0.9.0` (which doesn't exist yet). Sorry for the breaking change; we are trying to keep them to a minimum but we haven't yet released a `v1.0.0` (see https://semver.org/).

**Comment by medyagh** [comment]
Thanks for the response/

The problem is, if the user follows the Installation instructions on this projects Readme.

```
go get gocloud.dev
go get github.com/google/wire/cmd/wire
```

it will copy the HEAD to your $GOPATH/src/

and then inside your app, if you use `go mod`  to generate the dependencies, the go mod tool pins it down to `v0.8.0` in the `go.mod` file

and then when you try to build it, the go compiler yells at you that the signature is not correct. (also your editor uses the GOPATH Head one so it constantly yells at you that the signature is wrong)

so if you use go mod for dependency it is not possible to compile the code. Maybe could make it clear in the README not to use go mod.

**Comment by vangent** [comment]
Hi @medyagh, thanks for the info. I'll send an update to our README next week to clarify this. I believe that if you `cd` into your project, `go get` will do the right thing (it will use modules if your project uses modules, otherwise it will fetch source code from HEAD). It looks like you probably ran `go get` from somewhere else, and it decided not to use modules, and then when you started using modules in your project, things got confused. You should be able to delete the HEAD source entirely if you are using modules.
