### ISSUE TITLE
all: add OpenCensus metrics

### ISSUE THREAD

**Issue by jba** [google/go-cloud#1130]
We should add some basic OpenCensus metrics to our APIs.

## How OpenCensus Metrics Work

- A _measure_ describes a metric. E.g. the latency of an RPC. A measure can have _tags_ which classify it, like the name of the RPC and the status code it returned. So each measure can represent a multidimensional set of time series. Metrics and tags are named.
- A _view_ combines a metric with a way to aggregate its measurements. E.g. a distribution over the latencies of multiple RPC calls. You need a view to actually collect data. A view doesn't do anything unless it's _registered_. Views are named, often with the same name as the metric.
- An _exporter_ writes metric data to a backend, like Stackdriver or Prometheus. When a program registers an exporter, it periodically collects and transmits data from the registered views. 

A library's job is to define measures, and instrument the code to take measurements. The main program's job is to register views and exporters. Defining views over measures can be done by either, but usually the library defines some views that are likely to be useful.

## Proposal

Each Go Cloud API should define at least two views in its concrete type, one counting the number of calls to a driver method, the other providing a distribution over the latency of the calls. Following the naming conventions of the [OpenCensus gRPC plugin](https://godoc.org/go.opencensus.io/plugin/ocgrpc), we'll call these
`gocloud.dev/A/completed_calls` and `gocloud.dev/A/roundtrip_latency`, where `A` is the API name. 
We'll parameterize the first by two tags, one for the name of the driver method and one for the error code (see #1124). The latency will only be tagged by method name. (I'm following the `ocgrpc` package here, which presumably omits error code from the latency because it's not that interesting and would require a lot of space to store.)

The concrete package will define a single global variable, `OpenCensusViews`, that contains a slice of these views (and any others the API wishes to define). This makes it easy for programs to register all the views.

We add the metrics to the concrete type to avoid duplicating work in the drivers. But this may be too crude for driver methods that do a lot of work (like multiple RPCs). We might define additional measures in the driver for such methods. The driver package's init method can add those views to the API package's `OpenCensusViews` slice.

Here is what the definitions might look like for pubsub:
```
var (
    latencyMeasure = stats.Float64(
        "gocloud.dev/pubsub/roundtrip_latency",
        "Latency of driver method",
        stats.UnitMilliseconds)

    OpenCensusViews = []*view.View{
        {
            Name:        "gocloud.dev/pubsub/completed_calls",
            Measure:     latencyMeasure,
            Description: "Count of driver calls by method and status.",
            TagKeys:     []tag.Key{keyMethod, keyStatus},
            Aggregation: view.Count(),
        },
        {
            Name:        "gocloud.dev/pubsub/roundtrip_latency",
            Measure:     latencyMeasure,
            Description: "Distribution of round-trip latency, by method.",
            TagKeys:     []tag.Key{keyMethod},
            Aggregation: millisDistribution,
        },
    }

    keyMethod, _ = tag.NewKey("gocloud_method")
    keyStatus, _ = tag.NewKey("gocloud_status")

    millisDistribution = view.Distribution( /* to be determined */ )
)
```
This code borrows heavily from the `ocgrpc` package linked above.

Note that the same measure is used for both views: one view counts the number of measurements, the other adds their values to a distribution.

Clearly, a lot of this code could be factored out into a common package.

**Comment by vangent** [comment]
Overalls looks good to me. A couple of comments:

* Should we add the provider (probably the provider impl package name) as a tag as well? E.g. "gcppubsub" or "rabbitpubsub". Users may be collecting metrics across multiple providers, and want to distinguish them. We can probably get it via reflection on the `driver.Driver`.

* You have suggested metrics for the driver calls, but that might be weird from a user perspective, since they are not directly calling them. Why not provide metrics for the concrete type calls instead (or possibly, in addition)?

**Comment by jba** [comment]
Both of those SGTM.

**Comment by vangent** [comment]
This is done, right?

**Comment by jba** [comment]
Yes.
