### ISSUE TITLE
all: consider hiding NewXXX methods

### ISSUE THREAD

**Issue by jba** [google/go-cloud#1131]
The `NewXXX` methods in the concrete type package (e.g. `pubsub.NewTopic`) are for use by drivers only, but they appear in the godoc as top-level functions with signatures:

-----------------------

<h4 id="NewTopic" data-kind="f">func <a title="View Source" href="https://github.com/google/go-cloud/tree/master/pubsub/pubsub.go#L128">NewTopic</a> <a class="permalink" href="#NewTopic">&para;</a> </h4>
  <div class="funcdecl decl"><pre>func NewTopic(d <a href="/gocloud.dev/pubsub/driver">driver</a>.<a href="/gocloud.dev/pubsub/driver#Topic">Topic</a>) *<a href="#Topic">Topic</a></pre></div><p>
   NewTopic makes a pubsub.Topic from a driver.Topic.
   It is for use by provider implementations.
</p>

------------------------------

We could hide them better like so:
```
// NewTopic is for use by provider implementations.
var NewTopic = newTopic

func newTopic(d driver.Topic) *Topic { ...}
```

The godoc for the variable would not appear in the table of contents, and the signature is completely hidden, so the function is much less salient.

**Comment by vangent** [comment]
Clever, I like it :-).
