### ISSUE TITLE
Update "Contributing" in README to mention Azure support

### ISSUE THREAD

**Issue by eliben** [google/go-cloud#1148]
In the "Contributing" section of the README it currently says:

The GitHub repository at google/go-cloud currently contains Google Cloud Platform and Amazon Web Services implementations as examples to prove everything is working. Unfortunately, we cannot support every cloud provider directly from the project.

Now that there's some Azure support, should the README call it out, or should we wait until more of the APIs are implemented for Azure?

**Comment by ijt** [comment]
It's strange that it says "as examples to prove everything is working." They aren't just examples. We want people to actually use them in real projects. Maybe we should strike that bit.

**Comment by ijt** [comment]
We currently have an Azure implementation of `blob` and someone is working on an Azure implementation of `pubsub`. I suggest we wait until we have Azure `pubsub` to add Azure to the README.

**Comment by vangent** [comment]
No, sorry, style problem. Updated.

**Comment by eliben** [comment]
@vangent +1, I'll prepare a PR for this
