### ISSUE TITLE
blob/gcsblob: Feature Request : Get  "Name" in blob iterator. (rather than Key)

### ISSUE THREAD

**Issue by medyagh** [google/go-cloud#1149]
I need an easy way to get filename in an itterator.

for example this code is using the (`cloud.google.com/go/storage`) library:

```
	it := inputbucket.Objects(ctx, &storage.Query{
		Prefix:    prefix,
		Delimiter: "/",
	})

	for {
		attrs, err := it.Next()
		if err == iterator.Done {
			break
		}

                 // **1
		if attrs.Name != "foo.bar"{
                       // do something
		}
	}

```

but the similar code using go-cloud library, would give me `Key` instead of `Name`.  (See **1)

the Key gives me 3 values separated by space (dates and time and filename). not pleasant to parse it myself.

**Comment by vangent** [comment]
> the Key gives me 3 values separated by space (dates and time and filename).

Can you give a snippet of your code using Go Cloud `blob`? Which provider implementation are you using? `ListObject.Key` should be the blob name, are you sure you're not using `ListObject.String()` or something?

**Comment by medyagh** [comment]
@vangent sorry for the late response, I just added this to the tutorial in this repo

```
	b, err := setupBucket(context.Background(), *cloud, *bucketName)
	it := b.List(nil)
	for {
		attrs, err := it.Next(ctx)
		if err == iterator.Done {
			break
		}

		// **1
		if attrs.Name != "foo.bar" {
			// do something
		}

	}
```

(trying to do same code I posted in the issue) but attrs here does NOT have `.Name` like the GCS library.
instead it has `.Key` and unfortunately when you print out the `.Key` it is not the same as the filename in the bucket.

it is a metadata with dates and filename included, which means I have to parse it to get the file name.

**Comment by vangent** [comment]
Which provider are you using?

I added the code below to the tutorial and ran it against GCP, and it prints `gopher.png` as I would expect (not something with dates).

```
+       it := b.List(nil)
+       for {
+               attrs, err := it.Next(ctx)
+               if err == io.EOF {
+                       break
+               }
+               fmt.Println(attrs.Key)
+       }
```

Are you sure you aren't printing out the entire `ListObject`?

**Comment by medyagh** [comment]
@vangent I ran it against GCP, but my file has Versions, so maybe try the same experiment with a file that has been edited or re-uploaded 3 times. I think in those cases it gives you not the filename.

**Comment by vangent** [comment]
@medyagh thanks for following up.

By "Versions", do you mean [Object Versioning](https://cloud.google.com/storage/docs/object-versioning)? I tried that, and still don't see anything other than the filename.

*   I create a bucket.
*   I enabled Object Versioning using gsutil.
*   I upload a file and modified it a few times.
*   I verified that multiple versions exist using `gsutil ls -a`.
*   I ran the modified tutorial that uses `blob.List`.
*   --> Only a single filename was returned, and it was "gopher.png".

It looks like the GCS Go API that we're using underneath the hood does support listing of multiple version of the same file (see the `Versions` option on `Query`: https://godoc.org/cloud.google.com/go/storage#Query), but we're not setting it: https://github.com/google/go-cloud/blob/master/blob/gcsblob/gcsblob.go#L213).

Could you maybe send the output of 

```
gsutil ls gs://<YOUR BUCKET NAME>>
```

?

**Comment by medyagh** [comment]
@vangent it is weird I can not replicate it anymore,

but I looked at my container logs, here is the output I had seen.
```
myfilenam1334.txt 2019-01-09 01:14:17.959 +0000 UTC 23652036
```

The only weird thing that I had change in code was my ListOptions  `ListOptions{Prefix: "users/"}`

I am gonna close this issue. but will reopen if I can replicate it again.
