### ISSUE TITLE
postgres: provide a specific postgres.DB type for type-safe usage

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#1150]
There are extensive differences between valid queries on MySQL and Postgres dbs, such that it doesn't necessarily make sense to allow a connection to a MySQL database to be passed into a function that is making Postgres queries. See http://mwiki.gichd.org/IM/Difference_MySQL_PostGreSQL for some differences.

As a counterargument, @zombiezen has pointed out that most applications only connect to a single database so they wouldn't need to worry about accidentally passing the wrong db connection. He also mentioned that using libraries requiring `sql.DB`s would be less convenient, requiring a cast or a dot access on each call if we do it this way.

**Comment by ijt** [comment]
I would suggest that such libraries should be coded against interfaces anyway. Maybe we can make some PRs along those lines.

**Comment by zombiezen** [comment]
I don't think a library like [`sqlx`](http://jmoiron.github.io/sqlx/) should be coded against an interface: `*sql.DB` seems perfectly appropriate. Introducing a type conversion or field for our users would be inconvenient. Other libraries that want to persist data probably shouldn't assume SQL and should use an interface.

All this leads me to think that introducing such a type doesn't benefit the user enough to warrant the additional API surface.

**Comment by ijt** [comment]
All right, closing it out then.
