### ISSUE TITLE
pubsub/gcppubsub: tests hang after upgrade to grpc v1.18.0

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#1151]
To reproduce:

1. Check out from HEAD.
2. `go get google.golang.org/grpc@v1.18.0`
3. `cd pubsub/gcppubsub`
4. `go test`

-> hang

5. `go get google.golang.org/grpc@v1.15.0`
6. `go test` 

-> works

**Comment by jba** [comment]
I filed grpc/grpc-go#2592.

**Comment by jba** [comment]
Fixed by #1159.
