### ISSUE TITLE
all: add open-by-name functions to all APIs

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#1174]
(This grew out of #931 and is now a larger effort, so opening a bigger-scoped issue.)

A very common use case when developing a portable application is to want to use a local implementation for development and then use the real implementation in production. Commonly, developers don't want to have two different build configurations to do this: they just want to be able to change by command-line flag. Right now, this is difficult to do: every application using Go Cloud would have to develop their own mechanism for specifying which provider resource they want to use. (This would be similar to SQL connection strings, but I think we want to keep credentials explicitly passed.)

I'm going to iterate on the blob URL-opening API, and once that gets to a place we're happy with, then I'd like to duplicate the API for our other portable APIs (pub/sub, secrets, runtimevar, and SQL).

**Comment by ijt** [comment]
Can you give a concrete example of what this would look like in a particular case?

**Comment by zombiezen** [comment]
I do not have a design yet, but #1145 was one iteration of this idea. @ijt, can you be more specific about what information you're aiming to glean?

**Comment by ijt** [comment]
Right, #1145 looks like a useful example of this.

**Comment by ijt** [comment]
I didn't have anything specific in mind, just wanted to see an example.

**Comment by jba** [comment]
I'm against doing this now, for several reasons:
- It's just a convenience feature; it adds no new functionality.
- No one has asked for it. The only known use is in Hugo, and that is just for blob. (I don't object to blob URLs.)
- We'll spend a lot of time figuring out how to shoehorn everything into strings, avoiding global registries, and other design issues. (Evidence: we've already done so.) Ross, I think your time is better spent on Go Cloud Init, which has a much higher potential to get us users.
- It will be a never-ending drag on our productivity. If we do it, then every time we add an option to any provider, we will have to figure out how to destringify it and what the flag/query-param name for it will be, and we'll have to hook it up.

**Comment by zombiezen** [comment]
Unavailability of this feature blocks users who want to create a [Twelve-Factor Application](https://12factor.net/) (specifically [IV. Backing Services](https://12factor.net/backing-services)). They would need to roll their own solution, which I think would make supporting infrastructure around Go CDK-based applications hard to work with. I think Go CDK having an opinion helps here.

**Comment by vangent** [comment]
Per discussions, @zombiezen is doing this for `blob`, and @shantuo will do it for `runtimevar`, `secrets`, `pubsub`.
