### ISSUE TITLE
sql: add top-level mysql and postgres open functions

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#1175]
While there is already an `Open` function in the standard `database/sql` package, I think we should consider including our own. @ijt has already pointed out offline that it's strange that we don't have anything in the mysql and postgres top-level directories (although he's thinking more along the lines of #1150). IMO the automatic instrumentation that we provide for AWS and GCP are useful enough to merit our own `Open` function.

(We likely want to use the design from #1174, so one can think of this as a sub-issue of that.)

**Comment by Zyqsempai** [comment]
Sounds interesting;) Can i help with that?

**Comment by ijt** [comment]
Sure, please feel free to send a pull request.

**Comment by zombiezen** [comment]
Yes! We just finalized the [URLs design](https://github.com/google/go-cloud/blob/master/internal/docs/design.md#urls), so make sure your PR follows that pattern. See #1282 for an example of this for the blob package.

**Comment by Zyqsempai** [comment]
cool, thanks, guys.

**Comment by Zyqsempai** [comment]
@zombiezen @ijt  Hi guys, i have a question during the implementation, so in GCP postgres we have some extra connections params https://github.com/google/go-cloud/blob/master/postgres/cloudpostgres/cloudpostgres.go#L90 how they will be presented in the connection url? like a rawQuery?
By connection url i mean ofcourse something like that `postgresql://other@localhost/otherdb?connect_timeout=10&application_name=myapp
`

**Comment by zombiezen** [comment]
What about (really rough sketch, don't take too much stock in this):

```
cloudpostgres://user:password@project/region/instance/databaseName?query
```

where `query` is passed through to [`Params.Values`](https://github.com/google/go-cloud/blob/6838e153f0aa8a29e0a6b6eb4120eabc7bbb3109/postgres/cloudpostgres/cloudpostgres.go#L52)?

**Comment by zombiezen** [comment]
Also, in terms of PR sequencing, it might be good to just start with one PR that exports the URL opening functions for just one of the top-level packages (i.e. mysql or postgres), includes a plain database opener, but doesn't hook up the Cloud SQL/RDS openers yet. This would allow us to figure out the structure and then fill in the rest later, rather than trying to figure out all the details up-front.

**Comment by Zyqsempai** [comment]
@zombiezen great news, thank you for merging it.
The next step will be, to implement the same for plain MySql? Or better to continue with postgreSql?

**Comment by zombiezen** [comment]
Your call. I'm happy to review either of those.

**Comment by zombiezen** [comment]
Oh whoops: the function exists but keeping this open until #1735 and #1736 land.

**Comment by Zyqsempai** [comment]
@zombiezen Please check all the related PR's #1735 #1736 and #1975

**Comment by zombiezen** [comment]
I have the MySQL openers ready in local branches, but I need #2371 to go through first so that the `URLOpener`s can be created correctly in Guestbook.
