### ISSUE TITLE
all: update non-local examples to compile but not run instead of expecting failure

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#1177]
The examples should ideally be fairly realistic and easy to copy and paste into real apps without too much modification. The output should show things working, not failures due to not being able to assume the example can access the network.

That's not the current situation though. For example, in `blob/gcsblob/example_test.go` the [expected output](https://github.com/google/go-cloud/blob/d22bb640872cc897bb38b124f1ce8c55197fda27/blob/gcsblob/example_test.go#L70) is 

> ReadAll failed due to invalid credentials.

One possible solution would be to put a line like this at the top of the example_test.go files:
```
// +build !no_network
```
and then pass `-tag=no_network` to `go test` within Travis. A downside would be that these examples would not be built or run from Travis, though presumably we would find out quickly if they are broken since people would try them and report any issues they find. 

This solution isn't perfect, but I think it beats the current situation where our examples don't really make sense.

**Comment by ijt** [comment]
@vangent, @zombiezen what do you think?

**Comment by jba** [comment]
Remove `// Output`?

**Comment by ijt** [comment]
@jba, that makes it so the example doesn't run under any circumstances when `go test` is invoked.

**Comment by zombiezen** [comment]
Right, but examples will always be compiled, which I think is more of the assurance we need. I'm not seeing the benefit to running the examples versus the cost to clarity that you cite in your problem statement.

**Comment by ijt** [comment]
Fair enough. Let's go with that for now.

**Comment by vangent** [comment]
Please wait, I have an opinion :-).

**Comment by ijt** [comment]
It seems like there's a lot of copy/pasted boilerplate within option 2. I don't see a way around it without adding something like `gcp.FakeDefaultCredentials` but I doubt whether anyone would be willing to approve adding that.

**Comment by vangent** [comment]
Yea, generally I think it's preferable to have copy/paste boilerplate in examples than to factor out to helper functions, unless the helper functions are really not useful, because the helper code aren't included in the example code. `gcp.FakeInvalidCredentials` might be OK though, as we'd presumably have a comment telling the user that they should use `gcp.DefaultCredentials()` instead.

**Comment by jba** [comment]
> because the helper code aren't included in the example code.

Note this sentence from https://godoc.org/testing:

> The entire test file is presented as the example when it contains a single example function, at least one other function, type, variable, or constant declaration, and no test or benchmark functions.

**Comment by jba** [comment]
Not that I'm necessarily advocating for helper functions.

**Comment by zombiezen** [comment]
@ijt, I'm assuming by boilerplate you mean the lines changed in #1184. I don't see a good reason not to just have `gcp.DefaultCredentials` spelled out there.

**Comment by zombiezen** [comment]
(Sorry, hit send too early:)

I think it's actually incredibly useful in each of the provider packages to show a realistic example of how we set it up. For the concrete type, IMO it's fine for an example to show something like:

```go
// Bucket obtained from a provider package.
var bucket *blob.Bucket

// Do something with bucket...
r, err := bucket.NewReader(ctx, "foo", nil)
if err != nil {
  log.Fatal(err)
}
_ = r
```

My rationale is that it would be straightforward for someone to copy+paste the GCS code and then the operation code and have it work with minimal edits. WDYT?

**Comment by ijt** [comment]
@zombiezen I think I see a good reason not to use `gcp.DefaultCredentials` there: it would then be possible for an example test to accidentally mutate someone's project.

I'm not really sure what you're getting at. Maybe we should chat offline?

**Comment by zombiezen** [comment]
I'm on the side of examples only need to compile, not run. If we have code that's only being covered by example tests, that's problematic. Examples should ideally be as close to something that's useful for a developer to do. Setting up a bucket for a particular provider is a good example, reading from a generic bucket already obtained is another. Strive for A+ copypasta.

**Comment by ijt** [comment]
@zombiezen, fair point. Also, we should probably be getting additional coverage via non-example tests.

This would entail:
1. reverting my `gcp.FakeDefaultCredentials` change (#1184)
2. removing the // Output lines from the example tests
3. adding new conformance tests like `TestOpenBucket` and corresponding harness methods

**Comment by vangent** [comment]
OK, it sounds like there's consensus here. I'll do the cleanup.
