### ISSUE TITLE
pubsub: add sample showing how to use Wire with pubsub

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#1183]
One possibility is to update the existing gcmsg example to use Wire.

**Comment by ijt** [comment]
@zombiezen, how do you think we should lay things like this out? How about

samples
  pubsub
     gcmsg
        wire
        nowire

?

**Comment by vangent** [comment]
IMHO -- I'm not sure we need a pubsub-specific example for Wire.

**Comment by ijt** [comment]
You're probably right. Closing this out.
