### ISSUE TITLE
pubsub: in conformance test suite, verify that all driver errors are wrapped before being returned (beta requirement)

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#1245]

**Comment by ijt** [comment]
I must admit that even though I filed this issue, I'm not quite sure what it means (copied from a spreadsheet). @vangent, can you point to an example or a description of what this would look like? I didn't find anything when searching for "wrap" in blob/drivertest/drivertest.go.

**Comment by ijt** [comment]
Assigning to @vangent for clarification.

**Comment by vangent** [comment]
https://github.com/google/go-cloud/blob/master/blob/blob_test.go#L152

**Comment by ijt** [comment]
Okay, it looks like this has already been done for pubsub: https://github.com/google/go-cloud/blob/05daf99d0801aa66ffa9e7234edc0adb07d5fc0a/pubsub/pubsub_test.go#L361.
