### ISSUE TITLE
pubsub: awspubsub benchmark reports 10msgs/sec, so profile and fix top bottleneck

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#1270]

**Comment by ijt** [comment]
Here are some more numbers:

| gocdk pkg | msgs/sec | note |
|---|---|---|
|awspubsub|10|
|gcppubsub|310|
|mempubsub|286k|
|rabbitpubsub|144k|local instance|

The AWS driver appears to be making one RPC per message when sending and receiving, and that would probably explain a lot of why it's so slow. One expedient way to speed it up might be to call the AWS API funcs in multiple goroutines. There do not appear to be batch-based funcs in the AWS Go APIs for these things.

**Comment by vangent** [comment]
After PR #1344, updated stats:

| gocdk pkg | send msgs/sec | receive msgs/sec | notes |
|---|---|---|---|
|awspubsub|660|411| |
|gcppubsub|247|2911| |
|mempubsub|333k|460k| |
|rabbitpubsub|116k|8.4k| local instance |

**Comment by vangent** [comment]
Notes: those stats were with 

```
	const (
		nMessages          = 1000
		concurrencySend    = 100
		concurrencyReceive = 100
	)
```

and with awspubsub region set to us-west-1.

**Comment by ijt** [comment]
A ~50x improvement is nothing to sneeze at. Looks fixed to me.

**Comment by vangent** [comment]
I'm still working on this....
