### ISSUE TITLE
all: improve documentation and examples for "As"

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#1274]
@eliben reported that it was confusing.

* The documentation probably shouldn't link to design.md, unless it's for a rationale about why we've implemented it this way.
* Need example code.
* ...?

**Comment by eliben** [comment]
I was thinking where to move the provider/API-agnostic part of the documentation of `As`. One option is the landing page, but a better option may be just the big package comment in `doc.go`. This seems like too low-level detail-y for the landing page, and has the advantage of not having to link to non godoc/github resources from the code.

The `docs.go` package comment could have a section named "Accessing provider-specific types" that would explain what blob's bucket.As now explains, perhaps with relevant details from design.md; then we won't have to repeat this same documentation blurb in all the places in the code, instead just linking to the package comment. And we'll also remove the relevant parts from design.md

WDYT?

**Comment by vangent** [comment]
Per meatspace discussion, I think it will be useful to have an explicit example per concrete API, ideally for each type of 'As' supported by that API.

**Comment by eliben** [comment]
OK, next steps:

1. Move user-facing `As` documentation from `design.md` into `doc.go`
2. Add examples of `As` usage for concrete types

**Comment by eliben** [comment]
Added a bunch of examples for sub-packages. Pubsub remaining. Will address that next

**Comment by eliben** [comment]
I believe this is now fixed. If something specific is found missing, let's open new issues for that
