### ISSUE TITLE
server: install monitoring exporter

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#13]
**EDIT 2019-07-09 Adding more context to this issue:**

### Is your feature request related to a problem? Please describe.

Right now, a server using the Go CDK server package can configure the OpenCensus trace exporter, but not the [metric exporter](https://godoc.org/go.opencensus.io/metric/metricexport#Exporter).

### Describe the solution you'd like

A new field on `*server.Options` to initialize the metrics exporter.

**Comment by zombiezen** [comment]
@clausti, are you still working on this issue? It might be a good one for @jba to take since he's working on metrics.

**Comment by jba** [comment]
I'd rather we spread the knowledge, but I'll do it if no one else wants to.

**Comment by clausti** [comment]
I haven't worked on this, no. I don't mind if someone else takes it.

**Comment by renilJoseph** [comment]
hi. i would like to work on this.

**Comment by jba** [comment]
Great! I believe the right starting point is [`ochttp.Handler`](https://godoc.org/go.opencensus.io/plugin/ochttp#Handler). Let us know if you have any questions or need more help.

**Comment by bvwells** [comment]
@zombiezen, @jba - I've added an initial implementation of OpenCensus stats exporter. Hope this is okay and what you were after. 

At the moment, it is using the default http server views and no propagation is set. I can put some tests around this if needed.

**Comment by eliben** [comment]
Thanks for the contribution, @bvwells 
We're not looking at adding features to the server at this time - I should have closed this issue earlier, sorry for the confusion.

**Comment by bvwells** [comment]
@eliben, no problems. I guess it might be worth waiting for OpenTelemetry....
