### ISSUE TITLE
sql: add support for Azure SQL providers

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#1305]
Investigate what SQL options Azure supports (SQLServer? hosted MySQL? hosted Postgres?) and add support for them similar to what we have for AWS and GCP.

For SQL support, we basically just have helpers for opening the existing `sql.DB` type.

@vsaroopchand in case you're interested.
@zombiezen who has done most of the existing support.

**Comment by vangent** [comment]
Once this is fixed, we should also update the Azure part of the Guestbook sample to use a hosted SQL offering, and at that point we should also be able to run guestbook from an Azure VM (currently, it's running locally connecting to a local MySQL instance).

**Comment by vsaroopchand** [comment]
Relational or Non-relational? The Azure Relational DB (AWS RDS equivalent) is Azure SQL which is a PaaS SQL service. The Non-relational service is CosmosDB which offers a MonboDb Driver Impl. along with a non-sql API. The CosmosDB sample is [here](https://github.com/Azure-Samples/azure-sdk-for-go-samples/tree/master/cosmosdb); the Azure SQL sample is [here](https://github.com/Azure-Samples/azure-sdk-for-go-samples/tree/master/sql)

**Comment by zombiezen** [comment]
This is specifically referring to relational databases. Does Azure Relational DB only support MSSQL, or does it host MySQL/PostgreSQL as well?

**Comment by vsaroopchand** [comment]
There are managed services for both [PostgresSQL ](https://azure.microsoft.com/en-us/services/postgresql/)and [MySQL](https://azure.microsoft.com/en-us/services/mysql/). I am going to test the cloudpostgres package with an Azure PostgresSQL instance to see if that can be refactored to support Azure. There might be some differences in ports, etc. but should be possible unless you prefer a separate package for Azure PostgresSQL?

**Comment by zombiezen** [comment]
Thanks for the links. From quickly browsing the docs, it looks like Azure's offering is much closer to RDS than Cloud SQL in terms of code required: Azure serves using a [CA not in the roots](https://docs.microsoft.com/en-us/azure/mysql/howto-configure-ssl). The connection code (which should be in a separate package) should have a hook for the CA certificate fetching, and then open the connection with OpenCensus instrumentation.

**Comment by vsaroopchand** [comment]
I'll take this up now that Secrets is merged.
