### ISSUE TITLE
runtimevar: add support for Azure

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#1314]
* Investigate Azure equivalent to AWS Param Store or GCP Runtime Configurator.
* If any are found, add `runtimevar` for at least one.

**Comment by vangent** [comment]
Note: if we add something here, we should update the Azure section of the Guestbook sample to use it. Today it is using `blobvar` based on a blob in Azure Storage.

**Comment by eliben** [comment]
@vsaroopchand is this something you might be interested in looking at?
