### ISSUE TITLE
secrets: add Azure support

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#1315]
* Investigate Azure equivalent for AWS KMS or GCP KMS.
* If any, add `secrets` support.

**Comment by vsaroopchand** [comment]
I can help with this implementation. I already did a review but found some interesting dependencies.  BTW, the service to wrap is the Azure KeyVault, the SDK is [here](https://github.com/Azure/azure-sdk-for-go/tree/master/services/keyvault/v7.0/keyvault)

**Comment by shantuo** [comment]
Thanks @vsaroopchand ! KeyVault looks like the perfect candidate for this.
