### ISSUE TITLE
pubsub: subscribing queues to topics on AWS conformance tests is broken

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#1328]
See https://github.com/aws/aws-sdk-go/issues/2415. That issue has a response with a possible solution.

**Comment by vangent** [comment]
I've been trying to add a new test (for non-UTF8 bodies), and I can't even get the tests to create subscriptions anymore.

It created the topic, but no subscription....

**Comment by ijt** [comment]
Looking into it.

**Comment by vangent** [comment]
> It created the topic, but no subscription....
I was looking under SNS instead of SQS. To manually subscribe, you go to SQS and subscribe from there.
