### ISSUE TITLE
pubsub: no longer assume persistence in conformance tests

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#1370]
NATS core doesn't work this way. The client side subscriptions have to be set up before msgs are sent to the topics in order for the client subscriptions to get the messages.

**Comment by ijt** [comment]
Also, something has to be receiving from the subscriptions while the sending is happening. I suspect we'll have to do something different than the current ReceiveBatch calls to make this work.

**Comment by jba** [comment]
> something has to be receiving from the subscriptions while the sending is happening

What if that isn't true? Does the server just drop messages on the floor? It doesn't cache them at all?

**Comment by ijt** [comment]
Following up on our chat offline, I'm closing this out since we agreed to at least explore the possibility of having a new API for non-persistent messaging systems.
