### ISSUE TITLE
pubsub: ReceiveBatch() does not have optimal behavior

### ISSUE THREAD

**Issue by derekcollison** [google/go-cloud#1377]
### Is your feature request related to a problem? Please describe.

ReceiveBatch is the driver to receive messages. It passes in a context and a maxMessages. In an optimal state this function should tell me a desired return state, number of messages wanted, and then let the context's deadline dictate how long I should wait to reach that state.

In the simple TestSendReceive while implementing the NATS driver, this test hung. The test sends three messages, then calls Receive() which is a singelton but that calls ReceiveBatch on the impl. However it will change maxMessages based on processing time metrics. So in this case the NATS implementation got a maxMessages of 1000 and a non-deadline context. So I camped out waiting until a context deadline or cancellation to receive 1000 messages.

### Describe the solution you'd like

I have seen other drivers that fudge on a polling interval or use the impl to work around this problem. I think ReceiveBatch should take a deadline based context and also include the desired number of messages such that no extra time is wasted waiting for a small poll based timeout etc.

Since the higher level API that user's will use only seems to have Receive, we could make an assumption that the answer is always 1 as the desired state, but if there are extra messages already there we can return those as well.

### Describe alternatives you've considered

I could detect no deadline and put an artificial/random deadline as a new context from the one passed in.

**Comment by jba** [comment]
Sorry for the delay, Derek. I just got back from vacation today.

The problem with using the context deadline is that it might represent the maximum amount of time a client is willing to wait before canceling the operation. For instance, the context argument to `Receive` could represent a timeout from a client elsewhere on the network. Of course, callers of `Receive` could always create and pass in a new context with a shorter timeout, but that feels like a heavy burden for our users.

I think there are two ways to write `ReceiveBatch` for NATS:
1. Always return exactly one message. That may be fine, if the NATS driver is doing its own batching. 
2. Call `NextMsg` with a small timeout, like 50ms. The RabbitMQ implementation does something like that.

I would start with (1) and see what the performance looks like. (We have [benchmarks](https://github.com/google/go-cloud/blob/master/pubsub/drivertest/drivertest.go#L181).)

**Comment by derekcollison** [comment]
The small timeout is not correct IMO. What I implemented was we pull all that is available in the client. If we have at least one we return. If we do not have any we will go into a wait based on the context. If the context does not have a deadline I believe we return an error.

**Comment by jba** [comment]
That sounds fine, except that it should be OK to pass a context with no deadline, and that should mean "wait forever". That's how most Go functions that take contexts work.

**Comment by derekcollison** [comment]
I could never imagine writing any production code that could block forever. IMHO.

**Comment by jba** [comment]
Not forever; until an event occurs, whose occurrence we can't _a priori_ bound by a fixed time.

PubSub systems are great examples of that. I want to receive all the messages from this subscription, as long as I'm running. My only purpose in life is to receive a message, process it, and wait for the next one. What should my context timeout be? An hour? But the topic is only published to on Sundays. A week? Maybe it's only published to on _Superbowl_ Sundays.

**Comment by jba** [comment]
Actually, those are both bad examples in that the events occur at known intervals. Imagine some event that occurs rarely, with no obvious upper bound.

**Comment by derekcollison** [comment]
I think its ok for now in how you guys intended it and how we implemented it for go-cloud. Closing for now, feel free to open back up if needed.
