### ISSUE TITLE
all: make a new subpackage for at-most-once pubsubs like NATS core, Redis, ZeroMQ

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#1378]
The existing `pubsub` package is an awkward fit for NATS core, Redis pubsub, and ZeroMQ for the following reasons:

1. At-most-once pubsub providers do not require or directly support acknowledgment. Acking would have to be a no-op, which could be misleading.
2. At-most-once pubsub providers allow freely publishing messages to topics with any string for their name, like `connection.Publish("topic1", "message")`. To support this on at-least-once pubsub providers such as GCP pubsub, we would have to add support for dynamically creating topics and then possibly add some way to keep them from accumulating on the server. Such a garbage collection scheme seems well beyond the scope of what the Go CDK is trying to do.
3. At-most-once pubsub providers allow dynamically creating lightweight subscriptions. Supporting equivalent functionality within at-least-once providers would require a way to prevent accumulation of zombie subscriptions, similar to the issue with topics in reason 2.

Having a subpackage that supports the full functionality of at-most-once pubsub systems would make it possible to write portable apps that can dynamically publish to sets of topics that change over time, and have a varying number of clients subscribing. For example, this could be used to write an IRC-style app or client/server games.

The package could be called something like `dynpubsub` or `pubsublite`.

Here is a sketch of what using it could look like, based on a subset of the `go-nats` client example:

```go
import (
    "gocloud.dev/pubsublite"
    "gocloud.dev/pubsublite/natspsl"  // or redispsl, etc.
)

con, err := natspsl.Connect(natspsl.DefaultURL)
defer con.Close()
con.Publish("foo-topic", []byte("hello world")
con.Subscribe("foo-topic", func(m *natspsl.Message) {
   fmt.Println("got message: ", string(m.Body))
})
```

/cc @vangent, @zombiezen, @jba, @derekcollison.

**Comment by derekcollison** [comment]
I like the general idea. I think that these systems, at least NATS, don't only do pub/sub but layer RPC on top of it which is useful to developers, so may consider adding that as a general API.

**Comment by ijt** [comment]
If it can be layered on top, do you think it would make sense to put this RPC functionality into a utils subpackage, like `pubsublite/pslutils`?

**Comment by derekcollison** [comment]
Feels core to me, but maybe others will have an opinion.

**Comment by vangent** [comment]
We're also tracking this in #1368, so closing. Creating a subpackage is one option but not one that we're currently leaning toward.

**Comment by jba** [comment]
We've decided to support at-most-once pubsub providers using our existing `pubsub` package. The main reason is that we can't neatly divide systems into at-most-once and at-least-once. For instance, both Kafka and Azure Service Bus can be configured to act as either, on a per-subscription basis.

**Comment by covrom** [comment]
Driver for Redis is here https://github.com/covrom/redispubsub
