### ISSUE TITLE
blob/all: Bucket.Exists(ctx, key string) (bool, error)

### ISSUE THREAD

**Issue by tamalsaha** [google/go-cloud#1385]
I am looking for a way to test if a `key` exists or not. It is sort of like File.Exists api. Is there a way to do this currently? If not, can this be supported without reading the full file?

**Comment by vangent** [comment]
`Bucket.Attributes` is the cheapest way to determine whether a blob exists:

https://godoc.org/gocloud.dev/blob#Bucket.Attributes

```
If the blob does not exist, Attributes returns an error for which gcerrors.Code will return gcerrors.NotFound.
```

I'll leave this open to consider adding an explicit `Exists` call as a wrapper for that to make this more obvious.
