### ISSUE TITLE
all: Consider adding an Auditing API

### ISSUE THREAD

**Issue by josephlewis42** [google/go-cloud#1386]
### Is your feature request related to a problem? Please describe.

As far as I can tell there's no cross-cloud way to write audit events which would make building certain types of servers much easier.

### Describe the solution you'd like

A function I could call to populate the "Who did what to whom?" audit entry and have that logged to the appropriate cloud's audit system to be searchable at a later time in their interface.

### Describe alternatives you've considered

* Keeping an audit log in the database -- this isn't accessible to most users.
* Writing events to the application logs -- not ideal because they get mixed in with other logs of various usefulness.

**Comment by vangent** [comment]
Hi @josephlewis42 , could you reference a few cloud provider APIs that would implement this? E.g., which AWS / GCP / Azure APIs would this cover?

**Comment by josephlewis42** [comment]
Hi @vangent,

It looks like I was mistaken, I thought access to Stackdriver audit was public. It looks like the same goes for AWS CloudTrail and Azure's Audit Logs.
