### ISSUE TITLE
pubsub: add aws support to gcmsg sample

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#1391]

**Comment by vangent** [comment]
We might as well wait until we have URL support for `pubsub` to do this; we'll probably get it for free then. Assigning to Tuo to verify.

**Comment by ijt** [comment]
I feel some urgency about it because I want to use this sample for the Go
SF talk on Wednesday.

**Comment by ijt** [comment]
I think I will just make a fork of this sample in my own private repo for the talk. Then there is no pressure on this.
