### ISSUE TITLE
server: add request metrics

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#14]
**EDIT 2019-07-09 Adding more context to this issue:**

### Is your feature request related to a problem? Please describe.

Right now, a server using the Go CDK server package will automatically capture OpenCensus traces, but will not capture request metrics like `opencensus.io/http/server/request_count`. Go CDK servers should send these metrics out of the box.

### Describe the solution you'd like

A new field on `*server.Options` that to initialize the metrics exporter (#13), and for the server's request handler to use [`ochttp.Handler`](https://godoc.org/go.opencensus.io/plugin/ochttp#Handler).

**Comment by zombiezen** [comment]
@clausti, are you still working on this issue? It might be a good one for @jba to take since he's working on metrics.

**Comment by clausti** [comment]
I have not worked on this, no. I don't mind if someone else takes it.

**Comment by Tazer** [comment]
When looking around a little there seem to be a http plugin for open census **ochttp**
https://github.com/census-instrumentation/opencensus-go/blob/master/examples/http/helloworld_server/main.go#L89

Not sure if it even would be a possibility to use that plugin? Anyway they have some defined standard metrics 

Server:
https://github.com/census-instrumentation/opencensus-go/blob/master/plugin/ochttp/stats.go#L226
Client: 
https://github.com/census-instrumentation/opencensus-go/blob/master/plugin/ochttp/stats.go#L137

**Comment by jba** [comment]
You should use that plugin. See https://code.googlesource.com/google-api-go-client/+/refs/heads/master/transport/http/dial.go.
