### ISSUE TITLE
wire: interface type in Value expression not available at runtime

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#140]
If a user writes something like:

```go
var MySet = wire.NewSet(wire.Value(http.Handler(nil)))
```

or even:

```go
var MySet = wire.NewSet(wire.Value(io.Reader(os.Stdin)))
```

Then the interface type information isn't available at runtime.  This was the other problem I identified in #98, but is not being addressed by #104.  I don't have a good answer for how to fix this one, though.

**Comment by vangent** [comment]
@zombiezen I need clarification of what needs to be done to fix this. Is it to split Value (which currently accepts any value) into Value (non-interfaces) and InterfaceValue(interfaces)?

**Comment by zombiezen** [comment]
Yes.
