### ISSUE TITLE
pubsub: add a local implementation that works across process boundaries

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#1405]
We currently have `mempubsub`, but it only works with topics / subscriptions fully contained within a process. If I have one application that only sends messages, and another application that only receives them, we don't have a local testing story (other than a RabbitMQ local server, which is pretty heavyweight).

We could:
* add a `filepubsub`, using the filesystem to store messages
* update `mempubsub` to have a `server` mode where it can start a local server and make simple RPCs

**Comment by asim** [comment]
Within Go Micro we hack this by using our service discovery abstraction along with the transport e.g multicast dns and point to point http. I'd advise adding http pubsub where one can act as a broker for others.

**Comment by jba** [comment]
@asim, I think that's essentially what we mean by `mempubsub` in server mode. But you're probably right in that it should be a separate package, even if it uses the same data structures as `mempubsub`.

**Comment by gedw99** [comment]
The multicast DNS approach is great.

I am also curious about using NATS streaming as a local implementation too ? Seems to make sense since it's pure golang. Still needs a db underneath it of course.

We use NATS this way for local development currently.

**Comment by vangent** [comment]
We are using NATS in a Docker container and that seems to work great.
