### ISSUE TITLE
server: associate application logs with requests

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#1426]
During my talk at Go SF, @rakyll asked whether the server package correlates application logs with the HTTP requests that generated them. App Engine has this feature on some of its runtimes, and it's quite useful.

**Comment by zombiezen** [comment]
This would definitely be useful for diagnostics. As others have observed, the main blocker is needing a prevailing Go logging library that takes in a `context.Context` such that we could associate log entries with trace spans.

Related issues: census-instrumentation/opencensus-specs#130 and census-instrumentation/opencensus-go#950.

**Comment by rakyll** [comment]
For now, users are able to retrieve the span context from the incoming request via:

```
import "go.opencensus.io/trace"

sc := trace.FromContext(req.Context()).SpanContext()
```

They can extend their app logs with the current span context.

**Comment by zombiezen** [comment]
Ah sorry for the imprecision. What I mean to say is most logging libraries have function signatures like this:

```go
package mylog

// Print sends some things to my logger.
// It does not have a Context. :(
func Print(args ...interface{})
```

So I'm not aware of a good hook point where we can ensure that logs get correlated. We could introduce our own logging package, but we don't have enough time to design a new portable API right now.

While researching my reply, I realized that the `requestlog` package does not include trace span information, which it should be able to include. I'll open a separate issue for that.
