### ISSUE TITLE
all: URL openers should ignore unsupported query parameters

### ISSUE THREAD

**Issue by shantuo** [google/go-cloud#1435]
It seems to be a common practice that unsupported query parameters get thrown away instead of error out. We should consider doing that. Thoughts welcome.

**Comment by vangent** [comment]
@zombiezen @jba thoughts on this?

**Comment by zombiezen** [comment]
That practice seems common for URLs in the web sense, but it seems like it could hide misspellings of query parameters if we ignore them in this context.

**Comment by vangent** [comment]
@clausti @eliben any thoughts? Sorry, I should have asked everyone or no one :-).

**Comment by jba** [comment]
I agree with @zombiezen. Check everything you can.

**Comment by clausti** [comment]
@zombiezen, @jba what would *not* ignoring them look like, in this context?

**Comment by vangent** [comment]
@clausti 	-- the current code processes URL parameters it knows about, and returns an error if the URL has parameters it *doesn't* know about.

Example: https://github.com/google/go-cloud/blob/master/blob/fileblob/fileblob_test.go#L220

**Comment by clausti** [comment]
I think I'm in favor of the error for unknown params in the URL openers. When serving web requests, query params can be arbitrarily added by anyone, and one ought to expect there will, stochastically, be extraneous garbage best ignored. But the identifiers fed to the CDK url openers are expected to be the user's own config, and it does seem better to me, to let them know if something unexpected is in there.

**Comment by vangent** [comment]
Sounds like we're unanimous on checking, so closing.
