### ISSUE TITLE
pubsub: portable type performance improvements for Receive

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#1441]
#691 tracked one performance improvement for `pubsub`: dynamically setting the batch size for `Receive`.

Other ideas that were discussed on that issue included:

* Currently, we don't call `ReceiveBatch` until the message queue is empty. We could make the call earlier to avoid periods where there aren't any messages for the application to process. TBD: what does "earlier" mean?

* We could call `ReceiveBatch` concurrently. Or (possibly preferably) we could modify the driver interface to indicate that we WON'T do that, if we find that we don't need to for good performance.

**Comment by ijt** [comment]
Why is this P1? Has anyone reported this as a problem?

**Comment by vangent** [comment]
I've made a bunch of performance improvements attached to this issue and others. Closing.
