### ISSUE TITLE
pubsub/azure: support option to not lock/ack messages

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#1442]
Apparently the Azure client supports a mode where receiving a message automatically deletes it from the server (as opposed to what we've currently implemented, which is Lock + delete after Ack).

Once #1368 is done, we should support the "auto delete" mode.

**Comment by vsaroopchand** [comment]
Yes, please assign to me. I am familiar with this feature. Also, I did send a PR to add Bulk AKS in the Azure SDK. This will simplify the current implementation.

**Comment by vangent** [comment]
Thanks @vsaroopchand !

See #1368 for our strategy for this:

```
Drivers that don't support ack will accept a function from the user to be used as a replacement. That function should be a required argument to the subscription constructor (OpenSubscription or CreateSubscription). The constructor should panic if the argument is nil.
```

It sounds like "auto delete" mode will be an `Option` for the Azure client. So, there should be an accompanying `Option` to provide the function, and the constructor should fail if "auto delete" is enabled but no function is provided (IMHO, panic is too strong here, but @jba may disagree; we can discuss on the PR). The function should be returned from `AckFunc`.

The user is expected to supply a function that logs a warning, does nothing, or panics.

**Comment by jba** [comment]
The constructor returning an error is fine.

But a simpler design is to have just a single option, the ack function. If non-nil, it implies you want auto-delete mode. (In other words, follow the same convention as `driver.Subscription.AckFunc`.) 

The hard part is finding a good name for the option. Maybe `AckFuncForReceiveAndDelete`?

**Comment by vsaroopchand** [comment]
@jba see my comment on #1368
