### ISSUE TITLE
all: allow URL openers to have an API-specific prefix to the scheme

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#1453]
E.g., `blob+mem://` should work as well as `mem://`.

This will be useful for determining which API an arbitrary URL belongs to.

Implementation thoughts:

* The API-specific `Register` function (e.g. `blob.RegisterBucket`) could always register the requested scheme as well as `<api name>+<scheme>`.

* Alternatively, the API-specific `Open` function could check for the known `<api name>+` prefix and strip it.

@zombiezen 
@clausti

**Comment by clausti** [comment]
Tentatively: at scheme registration seems like the the correct place for this solution.

**Comment by vangent** [comment]
Note: the prefix needs to include not just the API ("pubsub"), but also the type ("topic" or "subscription"). It might be fine for some APIs to allow a default type.
