### ISSUE TITLE
blob/fileblob: invalid cross-device link when TMPDIR is on different partition than file path

### ISSUE THREAD

**Issue by BurntSushi** [google/go-cloud#1459]
### Describe the bug

On Linux, when `TMPDIR` is on a different partition than the bucket's file path, the initial write of bytes will succeed, but closing the bucket will fail with "invalid cross-device link." This appears to be due to the fact that `os.Rename` is used to move a file from `TMPDIR` to its ultimate location, but this may cross a file partition. (For example, when your `TMPDIR` is on a tmpfs and the bucket's path is somewhere else.)

### To Reproduce

I don't know whether this impacts other operating systems besides Linux, but:

* Setup a new bucket using `blob/fileblob` and make sure its path is on a different partition than what `TMPDIR` points to.
* Write data.
* Call `Close` and check the error. The error should give you "invalid cross-device link."

## Expected behavior

I think the expected behavior is that `blob/fileblob` works regardless of whether `TMPDIR` is on a different partition than the path of the bucket.

### Version

v0.9.0

### Additional context

I believe this is the specific part in the code where this happens: https://github.com/google/go-cloud/blob/abf519aefe1cdeab2694e5ca67c8e3647b869deb/blob/fileblob/fileblob.go#L502-L506

I don't know what the right way to fix this is for this project. I can brainstorm a few approaches:

1. Declare that this is a shortcoming of the fileblob backend and document it as a bug.
2. Don't use `os.Rename` and instead use something like `io.Copy`. (This is kind of a rabbit hole since implementing a correct and efficient platform agnostic file copy function is actually pretty hard.) But if `fileblob` is meant only for development purposes, then you could justify the unconditional use of `io.Copy`. Even though it will be slower, it should always be correct.
3. Allow configuring the temporary directory and/or choose a temporary directory below the path for the bucket.

For myself, I was able to work-around this bug by riffing off idea (3) by setting `TMPDIR` to a directory that is on the same partition as the bucket's directory.

**Comment by vangent** [comment]
Hi @BurntSushi thanks for the detailed error report! I believe another contributor already fixed this in #1156. If you update to version `v0.10.0` or `v0.11.0` you should get the fix.

**Comment by BurntSushi** [comment]
@vangent Awesome, thanks! Apologies for the noise.
