### ISSUE TITLE
pubsub: add MQTT driver

### ISSUE THREAD

**Issue by diegohce** [google/go-cloud#1466]
Add MQTT driver to pubsub package to ease message exchange between microservices and IoT stuff.

**Comment by jba** [comment]
@diegohce, this isn't on our roadmap, but if you're interested in contributing, we'd love to talk.

**Comment by diegohce** [comment]
I'll give it a try and let you know if I dare to publish :-)

**Comment by jba** [comment]
One important point: we're probably not going to accept more contributions to this repo, so I'd suggest creating a new repo. We're still interested in reviewing the code and helping you develop, and we are seriously considering giving third-party contributions gocloud.dev import paths. In other words, even though your code would live in a separate repo, users would still import "gocloud.dev/pubsub/mqttpubsub".

**Comment by diegohce** [comment]
Hey! Sounds fair to me! Thanks! I'll fork this repo and probably get back to you when I have something decent. Is that ok?

**Comment by jba** [comment]
Sure. You're welcome to fork for development purposes, but the end state should be a repo that contains only your driver, at top level. I believe that's the only way we can give it the right import path.

**Comment by diegohce** [comment]
Ok. Great! I'll start digging on guidelines, other pubsub drivers code and Go MQTT implementations. This will be my first contribution to any Go related team so, thanks in advance for your patience :-)

**Comment by qmuntal** [comment]
@diegohce any progress on the mqtt driver?

**Comment by diegohce** [comment]
I'm sorry. Couldn't even start coding due to medical and job issues.

**Comment by filinvadim** [comment]
I'm on it

**Comment by filinvadim** [comment]
Feel free to use: https://github.com/filinvadim/go-cloud-pubsub-mqtt
