### ISSUE TITLE
internal/docs: move design.MD content somewhere more user-friendly

### ISSUE THREAD

**Issue by clausti** [google/go-cloud#1469]
Per @eliben's [comment](https://github.com/google/go-cloud/pull/1464#issuecomment-469902370) on the PR to update design.md, move this sort of documentation to a more user-friendly/accessible place.

**Comment by eliben** [comment]
It probably makes sense to leave some of `design.md` where it currently is but +1 on evaluating what should be moved out. #1448 recently moved out the escape hatches stuff, as an example

**Comment by zombiezen** [comment]
I always hold up [What nobody tells you about documentation](https://www.divio.com/blog/documentation/) as a pretty good article about how to think about documentation audiences. I think the current documents gives pretty good coverage for contributors:

-  **Tutorials:** Our workflow is GitHub, so we gain the benefit of lots of GitHub tutorials.
-  **How-to Guides:** CONTRIBUTING.md
-  **Explanation:** internal/docs/design.md
-  **Reference:** CONTRIBUTING.md + API documentation

On the user side, the situation is more bleak, which I think should be addressed:

-  **Tutorials:** samples/tutorial and samples/guestbook
-  **How-to Guides:** Not many, but the Go package code examples maybe?
-  **Explanation:** Not really present.
-  **Reference:** Go docs

IMO we're missing How-to Guides and Explanation documents aimed at users. These can likely borrow elements from existing contributor-aimed documentation, but probably would focus on different things.

**Comment by zombiezen** [comment]
I'm planning on addressing this by adding new pages to gocloud.dev. I will likely airlift appropriate portions of design.md to form the new content with some light editing.

**Comment by zombiezen** [comment]
I think the user-relevant parts to understand are:

- URLs
- Portable type + driver
- Escape hatches
- Dev+Ops roles

To be clear, the existing sections are fine where they are now, but probably will cross-link with each other.
