### ISSUE TITLE
all: consistent naming of parameters in ErrorAs

### ISSUE THREAD

**Issue by eliben** [google/go-cloud#1474]
Our `ErrorAs` methods refer to the second parameter either as `i` (blob, runtimevar, etc.) or `target` (pubsub).

These should be made consistent. Even though `target` is less common, it seems more descriptive to me so I would prefer to align all names to `target`.

Objections?

**Comment by eliben** [comment]
@zombiezen @vangent

**Comment by vangent** [comment]
+1 for being consistent.

I'd lean toward `i` though, because that's what's used in all of the other `As` functions.

**Comment by eliben** [comment]
I don't feel strongly about this. Will send PR to align to `i`
