### ISSUE TITLE
blob: support for OpenStack Swift

### ISSUE THREAD

**Issue by Scapal** [google/go-cloud#1482]
Could you add support for OpenStack Swift object storage in the blob package ?
I'm currently using github.com/ncw/swift for those.

**Comment by vangent** [comment]
Hi @Scapal , thanks for you interest in the Go CDK!

As stated [here](https://github.com/google/go-cloud#contributing), we cannot support every cloud provider directly from the project; however, we encourage contributions in separate repositories. If you're interested in contributing an OpenStack Swift driver, let us know.

**Comment by vangent** [comment]
FYI, it looks like Swift supports the S3 API:
https://www.swiftstack.com/docs/admin/middleware/s3_middleware.html

So, you can probably use the `s3blob` provider and point it at your Swift cluster. If you try this, please let us know how it goes!
