### ISSUE TITLE
secrets: add more conformance/provider specific tests to improve coverage

### ISSUE THREAD

**Issue by shantuo** [google/go-cloud#1536]

**Comment by shantuo** [comment]
gcpkms and awskms is ~80%, the uncovered lines are mostly handling errors from failed client creation/API calling, since we have only tens of LOC in those files.

I have another PR for Vault and I think it might be ok to close this bug after that. @vangent WDYT?

**Comment by vangent** [comment]
SGTM

**Comment by shantuo** [comment]
I was going to add a test for vault's setup code for OpenKeeperURL with no environment variable set, but the init runs inside a `sync.Once`, the test will affect other tests for Open. I'm going to close this issue now. If we think there are other tests missing, we can re-open it or create separate issues.
