### ISSUE TITLE
server: health check endpoints are not logged

### ISSUE THREAD

**Issue by enocom** [google/go-cloud#155]
I configure a server like so:

```
opts := &server.Options{
    RequestLogger: requestlog.NewNCSALogger(os.Stdout, func(err error) {
        log.Printf("Whoops! Error: %s", err)
    }),
}
s := server.New(opts)
// ... listen and serve, etc.
```

When I send a request to `/`, I get a nice log message.

When I send a request to `/healthz/liveness` or `/healthz/readiness`, I get no message.

**Comment by zombiezen** [comment]
In reviewing this, let's add a comment to the `server` docs and we can call this good.

**Comment by enocom** [comment]
Will do.
