### ISSUE TITLE
pubsub: support NATS streaming

### ISSUE THREAD

**Issue by jba** [google/go-cloud#1559]
Now that we have support for NATS, it would be nice to support NATS Streaming with the same driver. It would give users a choice between at-most-once and at-least-once NATS implementations.

@derekcollison would that be a lot work? Is that something you want to take on? (At your convenience, of course.)

**Comment by derekcollison** [comment]
How would they chose?

**Comment by jba** [comment]
Probably different constructor functions. E.g. `CreateStreamingTopic`, `CreateStreamingSubscription`.

**Comment by derekcollison** [comment]
I guess that is what I am questioning. If there is more and more provider specific stuff what does the abstraction layer really provide?

**Comment by jba** [comment]
By leaving the setup to the providers, we can have smaller and more portable APIs.

So although there will be two more `Create` methods in the provider, and people have to write NATS-specific code to construct the right objects and pass them to those `Create` methods, they will end up with a `pubsub.Topic` and `pubsub.Subscription` that the bulk of the app can use portably.

**Comment by srikrsna** [comment]
We want this feature as well and made the driver implementation [here](https://github.com/appointy/gocloud-nats). 

I am happy to contribute, once the design is finalised.

**Comment by vangent** [comment]
Can the driver be made as a simple extension to the existing, non-streaming NATS driver? It's a bit hard to tell from your linked driver, but it looks like it's mostly the same as the existing one.

I.e., could we just add a boolean to `topic` and `subscription`, new constructors that set the boolean, and have only minor conditional behavior based on the boolean?

**Comment by derekcollison** [comment]
I would have to take a closer look again, but IIRC they API was more setup for streaming so probably could just extend it.

**Comment by srikrsna** [comment]
The Connection URL is exactly the same, in addition to that cluster id and client id are required with option of using as part of a queue group to avoid duplicate processing. Apart from these we can acknowledge the message manually.

**Comment by vangent** [comment]
If it is a relatively simple extension to the existing driver, please send a PR.

**Comment by derekcollison** [comment]
I would be happy to review a PR as well. Don't have the time atm to do this myself however.

**Comment by derekcollison** [comment]
We should look at adding JetStream to this, not STAN.
