### ISSUE TITLE
pubsub: rename package names to be their actual product name

### ISSUE THREAD

**Issue by shantuo** [google/go-cloud#1561]
Carrying over the [discussion](https://github.com/google/go-cloud/pull/1544#discussion_r265356720) here. I propose to rename `awspubsub` to `awssnssqs`, `azurepubsub` to `azureservicebus` or `azuresb`. The idea is it is clear which product we implement since there might be more than one offering per provider. All of our other API's try to follow this convention. If we decide to do it we should probably do it before next release.

What do you think? @jba

**Comment by vangent** [comment]
@jba I can do this if you think it's reasonable.

**Comment by jba** [comment]
If you both think it makes sense, then I'm fine with it. `awssnssqs` is a mouthful, though.
