### ISSUE TITLE
pubsub: consider dampening maxMessages

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#1567]
Currently `maxMessages` for receiving batches of messages starts at 1, and is subsequently set to a value that should get enough messages to process in 2 seconds (capped at 1000):
https://github.com/google/go-cloud/blob/master/pubsub/pubsub.go#L408

At startup, and with fast message processing times, this means we go from a batch size of 1 to a batch size of 1000 in one step, based on the processing time of a single message.

I think we should dampen this a bit to make it less noisy. It may take a little longer to ramp up at startup, but should be more stable once things are going.

Since the "how long does it take us to process a message" variable [already has dampening](https://github.com/google/go-cloud/blob/master/pubsub/pubsub.go#L356), one option would be to initialize it to `desiredQueueDuration` instead of to 0. I tried this using `mempubsub`'s Benchmark, and it looks like:

```
maxMessages: 1 based on avgProcessTime 2.000000
maxMessages: 2 based on avgProcessTime 1.900000
maxMessages: 2 based on avgProcessTime 1.900000
maxMessages: 2 based on avgProcessTime 1.629013
maxMessages: 2 based on avgProcessTime 1.396675
maxMessages: 2 based on avgProcessTime 1.260500
maxMessages: 2 based on avgProcessTime 1.197475
maxMessages: 2 based on avgProcessTime 1.026685
maxMessages: 3 based on avgProcessTime 0.926584
maxMessages: 3 based on avgProcessTime 0.794430
maxMessages: 3 based on avgProcessTime 0.681125
maxMessages: 4 based on avgProcessTime 0.614715
maxMessages: 5 based on avgProcessTime 0.475655
maxMessages: 6 based on avgProcessTime 0.368054
maxMessages: 8 based on avgProcessTime 0.270554
maxMessages: 12 based on avgProcessTime 0.179492
maxMessages: 21 based on avgProcessTime 0.096991
maxMessages: 61 based on avgProcessTime 0.033032
maxMessages: 1000 based on avgProcessTime 0.001523
```

We could make that more aggressive by modifying `decay` if we want.
Note that it starts fairly slow and gets exponential faster; this is because each batch contains a different number of messages; the batch with 61 messages decays the processing time 61 times.

Another option would be to explicitly dampen `maxMessages`; e.g., keep track of the last `maxMessages` size, compute a new ideal value based on `avgProcessTime`, and split the difference.

@jba thoughts?

**Comment by jba** [comment]
Maybe a warmup period, à la [`ewma`](https://github.com/VividCortex/ewma/blob/master/ewma.go#L96)?
