### ISSUE TITLE
pubsub/azure: clean up testSBSubscription

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#1569]
`testSBSubscription` is called from `ReceiveBatch`, I think some of these checks should move to the constructor and the expensive one should only happen once.

**Comment by vsaroopchand** [comment]
A couple of issues with this - the unit tests expect ReceiveBatch to fail if topic or subscription does not exist at Receive time, not at OpenSubscription time. Although I don't like testSbSubscription, unless the tests change I don't see how you can do without it.

**Comment by vangent** [comment]
The tests pass with the PR I sent... The verification that the subscription exists does happen in `ReceiveBatch`, not at `Open` (although there are `nil` checks in `Open`).

**Comment by vsaroopchand** [comment]
PR looks good. BTW, we recently released the SB SDK v0.3.0 which adds batch disposition, telemetry and other bug changes. The batch disposition will simplify SendBatch to a one liner. I will send a PR with these changes once #1599 is merged
