### ISSUE TITLE
all: hook up apidiff to identify breaking changes

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#1570]
https://github.com/golang/exp/tree/master/apidiff

Apparently @jadekler has hooked it up for the cloud.google.com/go repo.

@jba FYI

**Comment by jadekler** [comment]
The cloud.google.com/go part is still WIP, but we've implemented it in several other repos. PTAL https://github.com/google/go-genproto/blob/master/internal/kokoro/check_incompat_changes.sh for an example.
