### ISSUE TITLE
docstore/dynamodocstore: support set types

### ISSUE THREAD

**Issue by jba** [google/go-cloud#1583]
I noticed that the `dynamodbattribute` package's [Marshal](https://godoc.org/github.com/aws/aws-sdk-go/service/dynamodb/dynamodbattribute#Marshal) method will encode a `[][]byte` as a "binary data set". We don't support DynamoDB's set types in docstore.

If we natively (meaning, with the `dynamoattribute` package) encode a `[][]byte` and try to decode it with the docstore codec, I believe we'll currently get an error. We could fix that with an `AsSpecial` method that recognizes this case.

If we docstore-encode a `[][]byte`, it will currently encode as a list of of `[]byte`s. I'm not sure how `dynamodbattribute.Unmarshal` will handle decoding that into a `[][]byte`.  But in any case the docstore codec should have an `EncodeSpecial` method that handles this.

**Comment by shantuo** [comment]
`dynamodb.AttributeValue` also has `NS` (number set) and `SS` (string set). Although the native encoder doesn't encode `[]float64` or `[]string` into these two types, we should make sure we could decode them into the proper types.

**Comment by jba** [comment]
I think we just have to fail on decoding numberset and stringset. I can't think of a safe way to round-trip those.

**Comment by shantuo** [comment]
The current decoder for NS and SS gives the same result as the native one. I think it's ok to not add special case here since otherwise the document struct will have special dynamodb tags and become not portable. Also, I don't think it is necessary to test the decode->encode roundtrip.

I'll make the change to support BS for now.

**Comment by jba** [comment]
> The current decoder for NS and SS gives the same result as the native one.

So we'll decode a number set as a `[]int`, but then re-encode it as a list of ints? That's effectively corrupting the database. Even though no information has been lost, I think there are operations you can only do with sets, like test if they contain a value (see "contains" in https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html). 

Thinking about binary sets, it's really the same problem: we are representing two different database types as one Go type, and that is not good. So hold off on supporting BS.

One way forward is to simply fail on sets. That is the safest choice. 

Another idea: define the types `NumberSet`, `StringSet` and `BinarySet` in `dynamodocstore`. If the encoder encounters these, it can encode them appropriately. When decoding into an `interface{}` (`Decoder.AsInterface`), use these types. For structs, the user would have to define the struct field as one of these types.

The big problem with that idea: the data is no longer portable. If you read a string set from DynamoDB and then try to write it to Firestore, either:
- it will fail, or
- it will succeed and write it as a string array, in which case reading it back and then writing to dynamo will lose information, as above.
I think defining the special types and having them fail on other providers is probably the best compromise. A dynamo user can use docstore without problems, and if they switch to another provider they will discover the non-portability of their data and will have to deal with it manually.

@vangent, thoughts.

**Comment by shantuo** [comment]
Defining new types wouldn't work with the native codec. Another way like I mentioned is to use struct tags, which is how the native encoder uses to encode `[]string` and `[]float` to sets. This is not portable either but they will not fail with other drivers as those are just struct tags.

**Comment by vangent** [comment]
> One way forward is to simply fail on sets. That is the safest choice.

+1

The new types idea sounded OK to me (although I didn't understand @shantuo 's assertion that it wouldn't work with the native codec), and maybe struct tags would work, but either way it seems like something we could add later when we have more information from an actual user.

We should just clearly document in each driver the native types that docstore doesn't support, and maybe suggest the user file an issue if they aren't happy with that.

**Comment by shantuo** [comment]
Discussed offline, we decide to make all three set types (binary, number, string) fail in our decoder, and add `[][]byte` to an `UnsupportedType` case.

**Comment by shantuo** [comment]
Filed #1690 for testing unsupported types.
