### ISSUE TITLE
pubsub: batch size never changes when application doesn't call `Ack`

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#1584]
We use timing info we've gleaned about how long it takes to process messages to figure out how big the `ReceiveBatch` batch size should be, but we only gather the timing info when `Message.Ack` is called. If the application never calls `Ack`, we never updating the timing info and always request batch size = 1.

@jba

**Comment by vangent** [comment]
WDYT @jba ? It's not obvious how to get this timing without `Ack`.

BTW, we never updated the godoc for `Ack` to discuss that maybe you shouldn't call it.

Overall it's making me feel like revisiting the `ackFunc` idea. I still like it for `Nack` though.

Maybe if we rename `Message.Ack` --> `Close`?

**Comment by vangent** [comment]
I think we can estimate batch sizes by timing the interval between calls to `ReceiveBatch` instead of each individual message.

**Comment by jba** [comment]
> I think we can estimate batch sizes by timing the interval between calls to `ReceiveBatch` instead of each individual message.

That was exactly my original implementation. Issac felt it was inaccurate. Our discussion begins at https://github.com/google/go-cloud/issues/691#issuecomment-458712721.

Strongly opposed to renaming Ack to Close.

**Comment by vangent** [comment]
How about timing between calls to `driver.ReceiveBatch` instead of trying to time messages explicitly? So, we'd do something like keep track of how many messages are in the queue when `ReceiveBatch` returns, and the time the call returned, and then right before we make the next call to `ReceiveBatch`, divide the delta in messages by the delta in time; this should do a pretty good job of getting the average message processing time over that period.

I think that works even when we start issuing `ReceiveBatch` calls before the queue is empty. It's less obvious that it works if we need to start issuing `ReceiveBatch` calls in parallel, although it might (and, I'm hoping that we don't have to do that).
