### ISSUE TITLE
internal/context: consider not wrapping sentinel errors like context.Canceled

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#1591]
In `pubsub/benchmark_test.go`:

```
// TODO(rvangent): This is annoying. Maybe retry should return
// context.Canceled instead of wrapping if it never retried?
if cerr, ok := err.(*retry.ContextError); ok && cerr.CtxErr == context.Canceled {
	return nil
}
```

@jba responded:

```
Then wouldn't callers of retry have to check for both kinds of errors?
```

**Comment by jba** [comment]
The reason retry doesn't return `context.Canceled` or `context.DeadlineExceeded` is that they're particularly uninformative when retrying. If you keep getting a retryable error, you'll retry forever or until the context is done. If retry just returned the context error, you'd never know which error caused you to retry forever. That would make it hard to, for example, reclassify supposedly transient errors as effectively permanent.

**Comment by jba** [comment]
The PR linked above is a solution to this problem that uses the new error features. The `xerrors.Is` and (in 1.13) `errors.Is` functions will recognize the `Is` method on an error. I define an `Is` method on the error that retry returns to make it match against the context errors.

**Comment by vangent** [comment]
> If you keep getting a retryable error, you'll retry forever or until the context is done

My proposal was specifically to return the unwrapped `context` error only if no retries were done, which I think avoids the problem you describe.

**Comment by vangent** [comment]
The PR looks fine to me though.
