### ISSUE TITLE
samples: create HTTP quickstart/tutorial

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#1598]
### Is your feature request related to a problem? Please describe.

The current tutorials show a simple CLI (samples/tutorial) and a complex HTTP server (samples/guestbook), but do not show a simple HTTP server.

### Describe the solution you'd like

A tutorial that creates an HTTP server.

**Comment by zombiezen** [comment]
This is a follow-on from #1577.

**Comment by zombiezen** [comment]
I think we should add a guide in the website tutorials to promote discoverability. @eliben, do you want to have a separate issue open for that or should we reopen this one?

**Comment by eliben** [comment]
I'll open a new one
