### ISSUE TITLE
pubsub/azurepubsub: conformance tests don't pass in "autodelete" mode

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#1600]
By "autodelete" mode, I mean creating the Service Bus subscription with `servicebus.SubscriptionWithReceiveAndDelete` and using the `AckFuncForReceiveAndDelete` option set to something non-nil.

The conformance test that fails creates a topic, and two subscriptions for that same topic. It looks to me like using "autodelete" mode means that only one of the subscriptions gets the message. The test expects that both will.

**Comment by vsaroopchand** [comment]
You are correct, the message will be delivered at most once.

**Comment by vangent** [comment]
> You are correct, the message will be delivered at most once.

Hmm, that's unexpected. We are expecting that the "no ack" mode is the same as if the application did an ack.

In this test, a single topic is created, and then two subscriptions to that topic. The test verifies that messages sent to the topic are received by both subscriptions.

It works fine in the normal "ack" mode: 3 messages are sent to the topic, and 6 messages are received, 3 from each topic. Both subscriptions are acking the messages as they receive them.

However, in the "auto ack" mode, only one of the subscriptions gets 3 messages, and the other doesn't get any. Why?

**Comment by vangent** [comment]
@jba FYI

**Comment by jba** [comment]
Everything in [this overview](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-queues-topics-subscriptions#topics-and-subscriptions) suggests that every subscription gets a copy of the message. 

I can't find anything definitive in the docs.

**Comment by vsaroopchand** [comment]
Let me investigate and confirm the behavior.

**Comment by vangent** [comment]
Hi @vsaroopchand , any update on this?

**Comment by vangent** [comment]
Here is where the subscription is created in the test:
https://github.com/google/go-cloud/blob/master/pubsub/azuresb/azuresb_test.go#L115

Here's is the commented-out test that runs conformance tests with autodelete mode enabled:
https://github.com/google/go-cloud/blob/master/pubsub/azuresb/azuresb_test.go#L162

And this is the conformance test that fails if the above is uncommented:
https://github.com/google/go-cloud/blob/master/pubsub/drivertest/drivertest.go#L245

**Comment by vsaroopchand** [comment]
I can confirm the expected behavior is for all subscriptions to receive the message (if listening concurrently). In discussion with the SB team to do additional research into this issue.

**Comment by vangent** [comment]
Thanks Vishal. I also filed https://github.com/Azure/azure-service-bus-go/issues/114.

**Comment by vangent** [comment]
This turns out to be our bug.

https://github.com/google/go-cloud/blob/master/pubsub/azuresb/azuresb_test.go#L103

shortens subscription names that are > 50 characters; this test went past that. The 2 subscriptions that this test creates are made unique using a suffix, which was dropped by the > 50 trim.

**Comment by jba** [comment]
Good catch.

So creating a subscription that already exists does not return an error? Or are we failing to check?

**Comment by vangent** [comment]
Not sure, I will check.
