### ISSUE TITLE
runtimevar: Use `sync.RWMutex` or `atomic.Value` instead of `sync.Mutex` to improve the performance of concurrent reading

### ISSUE THREAD

**Issue by dyxushuai** [google/go-cloud#1615]
Not a Bug!
[L139](https://github.com/google/go-cloud/blob/master/runtimevar/runtimevar.go#L139): mu sync.Mutex
[L281-282](https://github.com/google/go-cloud/blob/master/runtimevar/runtimevar.go#L281-L282): Latest
[L298-299](https://github.com/google/go-cloud/blob/master/runtimevar/runtimevar.go#L298-L299): CheckHealth
Use `sync.Mutex` for concurrent reading may become a performance issue when huge of goroutines work together.
Use `sync.RWMutex` or `atomic.Value` may be good for these scenes.

**Comment by zombiezen** [comment]
@dyxushuai Good observation!

@vangent It does seem that one could reduce contention in steady state with a `RWMutex` for these cases. We would likely want to benchmark/load test before making such a change.

**Comment by vangent** [comment]
I'll take a look.
