### ISSUE TITLE
all: git.apache.org/thrift.git went away. Need to update opencensus.io when a fix is available.

### ISSUE THREAD

**Issue by y0ssar1an** [google/go-cloud#1635]
### The problem
```
go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f https://git.apache.org/thrift.git refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:
	fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Connection refused
```
The `git.apache.org/thrift.git` repo doesn't exist anymore, because the Thrift team moved to GitHub.

Your dependency on it [here](https://github.com/google/go-cloud/blob/6baa0528a468fb11a25ff4b94a32f7a4e3dca709/go.sum#L26,L27) comes from [`opencensus-go`](https://github.com/census-instrumentation/opencensus-go). Please update when they've provided a fix. Thanks!

**Comment by zombiezen** [comment]
(For reference: census-instrumentation/opencensus-go#1077 is the upstream issue.)

@y0ssar1an, can you confirm that error message for me? In a [recent build](https://travis-ci.com/google/go-cloud/jobs/187077349#L678), we are not seeing the same error. The error you're seeing indicates a failure to make a TCP connection to git.apache.org:443, whereas `curl https://git.apache.org/ > /dev/null` works fine from my machine.

**Comment by y0ssar1an** [comment]
Ok, this turned out to be an issue with the internal company network :flushed: I'm able to reach `git.apache.org` from outside the company network, and `go build` is working fine. Sorry for the noise!

**Comment by bos-hieu** [comment]
> ### The problem
> ```
> go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f https://git.apache.org/thrift.git refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:
> 	fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Connection refused
> ```
> 
> The `git.apache.org/thrift.git` repo doesn't exist anymore, because the Thrift team moved to GitHub.
> 
> Your dependency on it [here](https://github.com/google/go-cloud/blob/6baa0528a468fb11a25ff4b94a32f7a4e3dca709/go.sum#L26,L27) comes from [`opencensus-go`](https://github.com/census-instrumentation/opencensus-go). Please update when they've provided a fix. Thanks!

I got this error yesterday. Can anyone help me? Thanks!

**Comment by Rio** [comment]
Seems that that site is down. My "fix" was to switch my builder image from golang:1.12-alpine to golang:1.13-alpine. The new go version uses a proxy by default https://golang.org/doc/go1.13#introduction.

**Comment by weelillad** [comment]
A colleague shared this fix with me: https://github.com/mozilla/sops/issues/443#issuecomment-474209549

> For anyone else using go modules, just add the following into your go.mod:
>
> `replace git.apache.org/thrift.git => github.com/apache/thrift v0.12.0`
>
>see: https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive
