### ISSUE TITLE
secrets: add Keeper.Close method

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#1653]
/cc @shantuo @clausti

### Is your feature request related to a problem? Please describe.

In the future, we may have secret keeper drivers that require resource cleanup or other such behavior. At the moment, there is no hook that a driver can expect to receive to signal such cleanup.

### Describe the solution you'd like

Similar to #1492, I think that the `Keeper` portable type and driver interface should include a `Close` method.

**Comment by eliben** [comment]
We should do this before we declare beta-level API stability
