### ISSUE TITLE
blob: small issues with example code

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#1661]
While reviewing the `blob` API documentation for #1576, I found the following issues:

-  `gcsblob.Example_read` uses `return` in one error check, but `log.Fatal` in all the other error checks: https://github.com/google/go-cloud/blob/6482f3715c170669214c5cf4ba8421c51d772d30/blob/gcsblob/example_test.go#L36-L48
-  `s3blob.Example` shadows the AWS `session` package (`sess` would be a less confusing variable name): https://github.com/google/go-cloud/blob/6482f3715c170669214c5cf4ba8421c51d772d30/blob/s3blob/example_test.go#L31
-  None of URL-opening examples check the `error` return from `blob.OpenBucket`. Example from `s3blob`: https://github.com/google/go-cloud/blob/6482f3715c170669214c5cf4ba8421c51d772d30/blob/s3blob/example_test.go#L52-L59

**Comment by zombiezen** [comment]
The `session`-shadowing problem is also present in `awssnssqs`: https://github.com/google/go-cloud/blob/a247047ee622c794cd160a1785af510f68c9436b/pubsub/awssnssqs/example_test.go#L35

Probably should do a project-global search for this problem pattern.

**Comment by Tazer** [comment]
@zombiezen seems you have fixed all those issues :) 

Thinking if the item should be closed? Was hunting for some stuff to grab but notice this was already done. ✅

**Comment by zombiezen** [comment]
Yes, this is stale now. Thanks for triaging, that helps!

**Comment by eliben** [comment]
@Tazer, check out other issues with the "good first issue" tag
