### ISSUE TITLE
secrets/awskms: NewKeeper docs don't make it clear what strings are acceptable

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#1662]
The current documentation for `awskms.NewKeeper` is as follows:

https://github.com/google/go-cloud/blob/6482f3715c170669214c5cf4ba8421c51d772d30/secrets/awskms/kms.go#L135-L141

However, the link that it points to only shows where to find the information in the AWS console. It does not describe the expected format of the `keyID` string. In particular, it wasn't until I looked at the examples that I discovered that any alias must be prefixed with `alias/` in order to work properly.

I'm not sure whether it's better to link to a page or describe this inline (or both), but the best reference I could find of the expected string formats was on the [`aws kms encrypt` CLI reference](https://docs.aws.amazon.com/cli/latest/reference/kms/encrypt.html):

> To specify a CMK, use its key ID, Amazon Resource Name (ARN), alias name, or alias ARN. When using an alias name, prefix it with "alias/". To specify a CMK in a different AWS account, you must use the key ARN or alias ARN.
>
> For example:
>
> -  Key ID: `1234abcd-12ab-34cd-56ef-1234567890ab`
> -  Key ARN: `arn:aws:kms:us-east-2:111122223333:key/1234abcd-12ab-34cd-56ef-1234567890ab`
> -  Alias name: `alias/ExampleAlias`
> -  Alias ARN: `arn:aws:kms:us-east-2:111122223333:alias/ExampleAlias`

/cc @clausti @shantuo

**Comment by vangent** [comment]
stale.
