### ISSUE TITLE
secrets/localsecrets: improve key input for URLs

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#1664]
/cc @vangent @clausti 

### Is your feature request related to a problem? Please describe.

The current implementation of `localsecrets.URLOpener.OpenKeeperURL` will use `Base64Key` or 
`ByteKey`:

https://github.com/google/go-cloud/blob/6482f3715c170669214c5cf4ba8421c51d772d30/secrets/localsecrets/localsecrets.go#L72-L85

If the user provides secret material of exactly the correct size, then this URL opener works exactly as intended. However, if the secret material is of an incorrect size, then the URL opener will not return an error (as I would expect), but instead silently proceed doing one of two things:

1.  If the decoded argument is longer than 32 bytes, then the bytes after 32 are silently truncated.
2.  If the decoded argument is shorter than 32 bytes, then the value is extended to 32 bytes by adding NUL bytes to the end of the input.

The further issue with the `stringkey` scheme is that it will use the bytes as-is, which will likely be ASCII-clean and thus reduce the entropy of the key by a factor of 2^8 (1 bit per character).

From a usability standpoint, the danger here is that someone will see "secret material" and assume they need to create a "password", which will not be cryptographically strong key material. Since they will not see an error on the wrong length of key material. Quoting the paper [Cryptographic Extraction and Key Derivation: The HKDF Scheme](https://eprint.iacr.org/2010/264):

> We associate the notion of “cryptographically strong” keys with that of pseudorandom keys, namely, indistinguishable by feasible computation from a random uniform string of the same length.

### Describe the solution you'd like

(While this is strictly speaking an enhancement, the implications of improper usage can introduce security issues for the user of `localsecrets` so I am classifying this as a bug.)

I believe the URL opener should only permit base-64 encoded input of the correct size and return errors for anything that doesn't exactly match. Even if the user interprets such an error as requiring a password of 32 characters, that's strictly more entropy than a zero-padded password.

I'd also like to reconsider the `ByteKey` and `Base64Key` functions as they exist now. The silent truncation/zero-extension behavior has the problems I list above and I think they don't provide the right set of anti-affordances to encourage secure usage. At the very least, they should validate the length and return an error if it does not match. An even more accessible design could be to use a key-derivation function to build a cryptographically strong key from a weak password.

### Describe alternatives you've considered

(There may be other solutions than the ones I've thought of here, but I'll list the first few ideas that I considered while reporting this bug.)

Using a key-derivation function in all cases could make insecure usage harder, but at the cost of introducing a performance hit for users that correctly generated a 32-byte random key.

One could imagine addressing this problem only through documentation and extolling the virtues of generating keys correctly, but I feel this likely wouldn't scale: it relies on the user reading the documentation. Such a documentation-only approach also doesn't give the user feedback when they're doing something that is likely a security concern when the library could detect it.

### Additional context

The first few paragraphs in the Introduction section of [Cryptographic Extraction and Key Derivation: The HKDF Scheme](https://eprint.iacr.org/2010/264) provide a fairly decent academic introduction to Key-Derivation Functions and the problems around passwords and key material.

The Wikipedia articles on [Key stretching](https://en.wikipedia.org/wiki/Key_stretching) and [Key Derivation Function](https://en.wikipedia.org/wiki/Key_derivation_function) fill in a few more details, but don't give a very good overview of the problem.

**Comment by clausti** [comment]
This seems like a few issues

1. `ByteKey()` and `Base64Key()` truncation/padding behavior should be removed and those methods should error if not given material of the correct size.
2. `OpenKeeperURL` should only permit base-64 encoded keys/`ByteKey()` should not exist at all?
3. Functionality to increase the cryptographic strength of users' secrete material, either through a method to generate a key and/or to add a key-derivation function to users' supplied material. 

I'll tackle (1) first.

**Comment by eliben** [comment]
@clausti any updates here?
