### ISSUE TITLE
all: consider a big-data query API

### ISSUE THREAD

**Issue by jba** [google/go-cloud#1665]
Something that abstracts:
- [Google BigQuery](https://cloud.google.com/bigquery)
- [Amazon RedShift](https://aws.amazon.com/redshift)
- [Azure Data Lake](https://azure.microsoft.com/en-us/solutions/data-lake)
- [Snowflake](https://www.snowflake.com) data warehouse

**Comment by mytototo** [comment]
Hi there,

Just out of curiosity, why is this marked as unplanned ?
An abstraction layer for warehousing like there is for docstore would be great.

**Comment by eliben** [comment]
@mytototo it's marked unplanned because we don't currently have resources to work on it
