### ISSUE TITLE
secrets: CLI tool that encrypts/decrypts using our provider implementations

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#1670]
@clausti @shantuo, I had this idea while I was writing guides, but I'm not sure whether it's a good one. This might be one for the Unplanned milestone.

### Is your feature request related to a problem? Please describe.

An application operator may need to encrypt data for use in an application later with `secrets.Keeper.Decrypt`. Right now, they'd either have to use the provider-specific API to perform this or write a one-off program that creates a Go CDK secrets keeper and encrypts the information they want.

### Describe the solution you'd like

I could envision a CLI tool like `gocdk-crypt` that would be a command-line version of the `Keeper` API. It would use the URL opener to specify the provider to use. Mocks:

```shell
$ echo "Hello World" | gocdk-crypt -encrypt awskms://alias/my-test-key > cipher.txt
$ gocdk-crypt -decrypt awskms://alias/my-test-key < cipher.txt
Hello World
```

### Describe alternatives you've considered

Another way of solving this could be documentation/how-to guides. Such guides would say that if you're trying to encrypt/decrypt data for provider X, that the equivalent `aws` CLI or `gcloud` CLI invocation is Y. Such a guide could even include snippets that use Terraform data sources like [`google_kms_secret`](https://www.terraform.io/docs/providers/google/d/google_kms_secret.html) or [`aws_kms_secrets`](https://www.terraform.io/docs/providers/aws/d/kms_secrets.html).

(I could be easily convinced that we should only do this as a doc fix, but I wanted to suggest the splashier/more-code idea first.)

**Comment by shantuo** [comment]
I think guides for using equivalent CLI's to do such operations sound sufficient sinc all drivers we have right now have their CLI to do those.

Providing snippets using Terraform seems nice (but not necessary?).

**Comment by eliben** [comment]
@zombiezen do you see this tool being useful in its own right, or just as a sample? As a sample it sounds like a nice addition to our `samples` directory - we don't currently have much in terms of samples (outside test examples) for secrets.

**Comment by zombiezen** [comment]
It's definitely useful as sample code, but I think it might have utility for ops folks trying to set up their cloud resources, especially since the CDK plays some games on certain providers (like Base64 encoding/decoding).

**Comment by vangent** [comment]
I like the idea of having a simple CLI for each of our portable APIs; they will be useful as samples and may also have some utility on their own. We already have `blobdownload` for `blob`, and `gcmsg` for `pubsub`. It should be pretty easy to add similar things for `runtimevar` and `secrets`.

Ideally they would all live near each other, and have similar style as well. E.g., maybe we should rename them to `gocdk-blob` and `gocdk-pubsub`.

**Comment by vangent** [comment]
Done!
