### ISSUE TITLE
all: env vars aren't namespaced

### ISSUE THREAD

**Issue by jba** [google/go-cloud#1674]
I don't think we're being good citizens in our choice of environment variable names:  we're stepping on the global namespace. E.g. `RABBIT_SERVER_URL`, `VAULT_SERVER_URL`. Perhaps these should have a `GOCDK_` prefix.

**Comment by jba** [comment]
@vangent @zombiezen

**Comment by vangent** [comment]
I don't feel that strongly about this. Yes, it would probably be better, but I doubt it will be an issue in practice.
