### ISSUE TITLE
docstore: support wide-column stores?

### ISSUE THREAD

**Issue by jba** [google/go-cloud#1678]
Evaluate whether wide-column stores like Bigtable and Cassandra can act as docstore providers.

Wide-column stores associate keys with a flat set of values, rather than a recursive structure, so mapping one to the other would require work and could impact performance.

Also, Bigtable and Cassandra have two concepts that don't cleanly map to document stores: column families, which control locality; and timestamps, which give column values an additional time dimension.

**Comment by garukun** [comment]
May I also suggest to throw DynamoDB into pile for design considerations. :)

**Comment by eliben** [comment]
@garukun Dynamo is already being worked on -- https://github.com/google/go-cloud/tree/master/internal/docstore/dynamodocstore
