### ISSUE TITLE
pubsub: do ack deadline extension behind the scenes

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#1682]
We could do ack deadline extension behind the scenes (e.g., if we've given a user a message via `Receive` but they haven't yet `Ack` or `Nack` it when the deadline is approaching.

We'd need to know what the deadline is, and probably an option for the maximum extension.

@jba recommends we look at the `cloud.google.com/go/pubsub` client to see how it does this.

**Comment by jba** [comment]
> We'd need to know what the deadline is

Maybe not. IIRC, `cloud.google.com/go/pubsub` assumes the minimum ack deadline of 10 seconds to start. As it learns about the distribution of message processing times, it extends the deadline of incoming messages pretty much immediately to the 99th percentile of processing time.

**Comment by surajbarkale** [comment]
The [documentation is clear on the actual algorithm](https://godoc.org/cloud.google.com/go/pubsub#hdr-Deadlines) used to extend the deadline. We would need to either add `MaxExtension` to `Subscription` for this.
