### ISSUE TITLE
docstore: test unsupported type failing properly by our decoder

### ISSUE THREAD

**Issue by shantuo** [google/go-cloud#1690]

**Comment by jba** [comment]
@shantuo can you explain this better, maybe with a repro?

**Comment by shantuo** [comment]
I was talking about documents with types like dynamo's set types that inserted using the native encoder. When we get them and decode them, we should fail if we do not support them. I don't know whether this is already been done.

**Comment by jba** [comment]
We have `TestDecodeErrorOnUnsupported` in dynamodocstore to check for that.
