### ISSUE TITLE
secrets: verify that Decrypt does not permit using the wrong key

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#1692]
### Is your feature request related to a problem? Please describe.

In the [upcoming secrets how-to guide](https://github.com/google/go-cloud/blob/535dce4559dbb584c8dea26fa3141f218fa4cade/internal/website/content/howto/secrets/crypt.md#decrypting-data), I write that:

> The `Decrypt` method will return an error if the input data did not come from the same secret keeper.

I am actually not sure whether we guarantee this or whether we should guarantee it. It would be useful for an end-user to have this property, as it avoids the scenario where they encrypt data with key A, accidentally decrypt with key B, and potentially obtain garbage data.

### Describe the solution you'd like

We should determine whether our current set of providers (AWS KMS, GCP KMS, Vault, and Local Secrets) all raise errors. If they do (which @clausti and I have a sneaking suspicion of), then we should document that all drivers should do this, and create a conformance test that enforces the property.

**Comment by clausti** [comment]
> The Decrypt method will return an error if the input data did not come from the same secret keeper.

Strictly speaking, this is not true for `localsecrets`. As long as the keeper that was used to encrypt and the keeper that is used to decrypt were constructed with the same secret material, decryption will work. But it doesn't have to be the literal same keeper object.

**Comment by zombiezen** [comment]
Agreed: wording could be more precise (perhaps "equivalent secret keeper" or "secret keeper initialized with equivalent parameters"). But I argue the overall property is a useful one for the end-user to have.

**Comment by zombiezen** [comment]
Hey @shantuo. This blocks #2363, can you help find the answer for me?

**Comment by shantuo** [comment]
AWS does not take a key in the input when doing decryption. I will add tests to verify providers return error on malformed secrets.
