### ISSUE TITLE
docstore/firedocstore: inconsistent behavior of named type

### ISSUE THREAD

**Issue by shantuo** [google/go-cloud#1693]
### Describe the bug

A named type `Binary []byte` encoded by the docstoreEncoder cannot be decoded by the native decoder.

### To Reproduce

In the testCodec code:

```go
type Binary []byte
type BinarySet struct {
	A []Binary
}
b := &BinarySet{
	A: []Binary{{18}, {19}, {20}},
}
check(b, &BinarySet{}, ct.DocstoreEncode, ct.NativeDecode) ---> fail
check(b, &BinarySet{}, ct.NativeEncode, ct.DocstoreDecode)
```

Got error `firestore: cannot set type drivertest.Binary to bytes`

## Expected behavior

Pass

### Version

go version go1.12.1 darwin/amd64

**Comment by jba** [comment]
Good point. But I would describe this as an issue with `cloud.google.com/go/firestore` rather than us.

@jadekler, would you mind if I added this to the firestore client?

**Comment by jadekler** [comment]
@jba Please do!

**Comment by jba** [comment]
This would be a breaking change. Currently
```
type byteSlice []byte
byteSlice{1, 2}
```
encodes to a two-element array value. This change would make it encode to a bytes value. 

@jadekler, the README says that the firestore client is still in beta. Is that correct? I thought it went GA with the Firestore product itself.

In either case, people are probably using it assuming it's GA because the product is GA, so I don't think we should make this change.

**Comment by jadekler** [comment]
Ah yeah, that does seem like not a good idea. Also, we're in the process of making it stable, so definitely not a good time to make breaking changes heh.

Where can I read about these encoders/decoders? Are these go CDK things? Perhaps there's something we can do in that layer to smooth over the issue?

**Comment by jba** [comment]
@shantuo I think it will be consistent with other docstore providers if we leave it as it is, right? It's just not consistent with the native firestore client. We know those sort of inconsistencies happen sometimes; we just have to document them.

Leaving this open until it's documented in the `firedocstore` package doc.

**Comment by shantuo** [comment]
No, I found this not work when I tried to add a test case like above, the dynamodb driver worked while the firestore did not.

**Comment by jba** [comment]
This sort of problem is why we have `UnsupportedTypes`. We can add that test case but have the firestore driver return an enum value for defined types whose underlying type is `[]byte`.

**Comment by jba** [comment]
Closing this: we can't change the native firestore client, so we have to live with this inconsistency.
