### ISSUE TITLE
blob: add support for copying an object

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#1696]

**Comment by vangent** [comment]
Notes: none of the cloud providers have an atomic move. You copy and delete.

* S3 [copy](https://godoc.org/github.com/aws/aws-sdk-go/service/s3#S3.CopyObject)
* GCS [copy](https://godoc.org/cloud.google.com/go/storage#ObjectHandle.CopierFrom)
* Azure [copy](https://godoc.org/github.com/Azure/azure-storage-blob-go/azblob#BlobURL.StartCopyFromURL)

**Comment by Zyqsempai** [comment]
@vangent are you working on it? can I take a part?

**Comment by vangent** [comment]
@Zyqsempai 

Yes, I am working on it. My plan is to do an initial PR with the driver + portable type APIs and the memory/file implementations, and I'm mostly done with that. Then implementing each Cloud provider can be done independently; you could do one or more of those (Azure, S3, GCS). If that sounds interesting to you, I'll cc you on the first PR, and just let me know which of the providers you want.

**Comment by Zyqsempai** [comment]
Yeah, sounds more than interesting, thanks!

**Comment by vangent** [comment]
Great! I cc'd you on the first PR. After that is submitted I plan on extending the `As` tests for `BeforeCopy`. Please update this bug with which provider you'd like to work on first (links for all 3 are above).

**Comment by Zyqsempai** [comment]
I will start with `aws` and then continue with 'gcs'.

**Comment by vangent** [comment]
I'm going to work on GCS now.

**Comment by vangent** [comment]
Wow, GCS was super easy. @Zyqsempai have you started on AWS yet, or shall I go ahead? We'd like to tag a release soon and it'd be good to have `Copy` implemented across the board.

**Comment by Zyqsempai** [comment]
Yep, i will create a PR asap.
