### ISSUE TITLE
pubsub: get rid of the "newBatcher" args to constructors

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#1698]
I don't think we're ever doing anything other than passing `nil` for the default; although I have seen some flakiness in tests due to batch, it hasn't risen to the level of being a problem.

I think it might be simpler to replace the func arg with something like `fixedBatchSize`, which would get passed through to the batcher and enforce that batch size (with 0 being the current default of dynamic batch sizes).

@jba thoughts? Do you remember why we made this an arg?

**Comment by jba** [comment]
To deal with batcher non-determinism. There are potential timing effects (batches transmitted after N ms of idle time). 

I'd be in favor of making it simpler.

**Comment by vangent** [comment]
OK, I'll do this, and add a conformance test with various explicit ack batch sizes.

**Comment by vangent** [comment]
There are some further driver simplifications that this enables, leaving open.
