### ISSUE TITLE
pubsub/awssnssqs: use different URL schemes for topic and subscription

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#1707]
/cc @jba for thoughts

### Is your feature request related to a problem? Please describe.

The topic/publishing side of the `awssnssqs` package uses AWS SNS, and the subscription side uses AWS SQS. However, both types of URLs use the scheme `awssnssqs`. In order to know which service a URL is actually using, you have to consult the documentation and understand it.

### Describe the solution you'd like

To me, it would seem clearer to use `sns` and `sqs` respectively. This would immediately read that one side is connecting to one service or the other.

**Comment by jba** [comment]
Hmm. But it's the same driver. It's not like you can mix an SNS topic with a mempubsub subscription. 

Also, I suspect if you're using this provider you have a basic understanding of the APIs.

OTOH, maybe someday you can create an SNS topic but use a non-SQS subscription?

So I guess I'm agnostic. Will let @vangent decide.

**Comment by vangent** [comment]
I'd be fine with "awssns" and "awssqs"

**Comment by Zyqsempai** [comment]
Will take care of this one.
