### ISSUE TITLE
pubsub: provider package references should include links to their products

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#1711]
### Is your feature request related to a problem? Please describe.

Some providers (like Azure and AWS) have multiple similarly named but distinct products in the messaging space. The reference documentation for the Pub/Sub provider packages (those below `gocloud.dev/pubsub/`) sometimes mention the product name, sometimes not, making it hard for me to know whether it's talking about the same thing that the provider documentation is.

### Describe the solution you'd like

Each provider package documentation comment should include link(s) to the products that Go CDK connects to so as to eliminate the guesswork. (This might be a good idea for other packages as well, but I haven't had as much difficulty for other portable APIs.)

**Comment by marti1125** [comment]
Hi @zombiezen  Could I contribute with this?

**Comment by zombiezen** [comment]
@eliben or @vangent?

**Comment by eliben** [comment]
@marti1125 yes, go ahead and send a PR

**Comment by marti1125** [comment]
Hi @zombiezen and @eliben could you give me an example, how to I could get start, please?
