### ISSUE TITLE
pubsub/awssnssqs: OpenTopic&OpenSubscription require a client instead of a session

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#1713]
### Is your feature request related to a problem? Please describe.

The `OpenTopic` and `OpenSubscription` functions take in `*sns.SNS` and `*sqs.SQS`, respectively. Other AWS providers (see [`s3blob.OpenBucket`](https://godoc.org/gocloud.dev/blob/s3blob#OpenBucket) and [`awsparamstore.NewVariable`](https://godoc.org/gocloud.dev/runtimevar/awsparamstore#NewVariable)) take in a `client.ConfigProvider` (commonly a `*session.Session`). This inconsistency across packages adds cognitive overhead when using mostly AWS services.

### Describe the solution you'd like

`OpenTopic` and `OpenSubscription` should take in a `client.ConfigProvider` and create the `*sns.SNS` and `*sqs.SQS` objects under the hood.

### Describe alternatives you've considered

One could go the other way and make other providers take in their respective client objects. This is somewhat consistent with GCP, but these "client types" in the AWS SDK are largely wrappers around an instantiated configuration. Making the user create these client types is largely boilerplate and doesn't actually introduce meaningful flexibility. Using the configuration seems like the way to go, and is also the lesser delta of breaking changes.

**Comment by Zyqsempai** [comment]
I will take this one.
