### ISSUE TITLE
pubsub/natspubsub: constructor names should be consistent

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#1715]
### Is your feature request related to a problem? Please describe.

The constructors in `natspubsub` are [`CreateTopic`](https://godoc.org/gocloud.dev/pubsub/natspubsub#CreateTopic) and [`CreateSubscription`](https://godoc.org/gocloud.dev/pubsub/natspubsub#CreateSubscription). Constructors in the Go CDK are generally prefixed with `Open`. I am unsure whether the difference in prefix is connoting that topics and subscriptions are being created, or whether this is an oversight.

### Describe the solution you'd like

Either:

a) If `CreateTopic` and/or `CreateSubscription` do mutate server state (i.e. create the objects their names imply on the NATS server), then the godoc reference should be changed to make this more clear. At the moment, they just say "return a Topic" or "return a Subscription".
b) If they do not mutate server state, then these functions should be renamed to `OpenTopic` and `OpenSubscription` for consistency.

**Comment by eliben** [comment]
Some archeology by @vangent turned up:

https://github.com/google/go-cloud/pull/1381#discussion_r259220426

Where the naming was suggested
