### ISSUE TITLE
mysql: We are missing terraform file for azure-mysql

### ISSUE THREAD

**Issue by Zyqsempai** [google/go-cloud#1737]
### Describe the bug

We are missing terraform file for new azure MySQL implementation.

## Expected behavior

There are should be `main.tf` file in azuremysql folder to run the tests.

**Comment by eliben** [comment]
Thanks for the report, @Zyqsempai 
Assigning this to @zombiezen who is going to be back from vacation next week

**Comment by vsaroopchand** [comment]
PR Sent. Please note, you must add our firewall rule in the main.tf file to allow external traffic. By default, only internal traffic is allowed.
See doc for more info: https://docs.microsoft.com/en-us/azure/mysql/concepts-firewall-rules
