### ISSUE TITLE
docstore: put clients in strong consistency mode for testing

### ISSUE THREAD

**Issue by jba** [google/go-cloud#1752]
Our tests write documents, then immediately read them back. This can be flaky for providers that use eventual consistency by default. Where possible, create clients using strong consistency for testing.

This isn't essential, because it only affects tests when we record, and we do that rarely. 

Currently this only applies to dynamo. Firestore is strongly consistent, and we test mongo through a single-process server.

**Comment by vangent** [comment]
FYI -- we have a similar issue for `blob`. We "solve" it there by not cleaning up after tests. For example, if a test creates a bunch of blobs (if they don't already exist) and then tests `List` over them, it creates the blobs but then doesn't delete them; the test may be flaky the first time it is run in `-record` mode, but is stable after that.

**Comment by shantuo** [comment]
We could have the constructors/URL openers taking an option to operate in `strong consistency` mode for the user as well. DynamoDB supports `ConsistentRead`, will look into mongo as well.
