### ISSUE TITLE
all: https://gocloud.dev/ is offline

### ISSUE THREAD

**Issue by mmwtsn** [google/go-cloud#1765]
Requests to https://gocloud.dev/ are currently not resolving for me.

This is causing our package manager to fail.

![Go Cloud](https://user-images.githubusercontent.com/1479130/55642827-943db780-579f-11e9-926a-9c1f5217d5d9.png)

**Comment by vangent** [comment]
The site is up for me. I think that error implies a network problem on your end:
https://www.google.com/search?q=dns_probe_finished_nxdomain

**Comment by mmwtsn** [comment]
Yep. Looks like something is up with my Wi-Fi network. Thank you.
