### ISSUE TITLE
blob: Importing gocloud.dev/blob starts a goroutine

### ISSUE THREAD

**Issue by aarondl** [google/go-cloud#1792]
### Describe the bug

By importing gocloud.dev/blob an unsolicited goroutine starts up in your program.

```
goroutine 8 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc00015d800)
	.../go.opencensus.io/stats/view/worker.go:150 +0xdd
created by go.opencensus.io/stats/view.init.0
	.../go.opencensus.io/stats/view/worker.go:29 +0x57
```

### To Reproduce

* Create a hello world `main.go`
* Import `gocloud.dev/blob`
* Have main wait indefinitely on a nil channel read or something
* Press `ctrl+\` to see the goroutine dump and observe the opencensus worker routine

## Expected behavior

There should be no goroutines running unless explicitly started.

### Version

Doesn't appear to be tied to any one version.

### Additional context

The root cause exists here:
https://github.com/census-instrumentation/opencensus-go/issues/1074

https://github.com/census-instrumentation/opencensus-go/blob/75c0cca22312e51bfd4fafdbe9197ae399e18b38/stats/view/worker.go#L30-L34

**Comment by vangent** [comment]
> There should be no goroutines running unless explicitly started.

Why?

Goroutines in Go are very cheap; it is not unusual for packages or structs to start goroutines as an internal implementation detail. In this case, we are importing some OpenCensus packages that appear to start this goroutine.

**Comment by aarondl** [comment]
@vangent Implicit side effects are basically always a bad thing, it's easy to ask a package to do something like start a goroutine, it's very hard to tell it not to do that (fork is the only option, no?). The more I use Go the more I shy away from import side effects (even driver registration bits).

Why do I want this extra goroutine consuming any resources at all? Especially if I'm not intending to use it? The argument that it's very cheap doesn't really matter, it's more a question of: Why is it consuming resources at all when it has not been asked to? It's also a bit of a slippery slope argument as where do we draw the line? On import should packages be able to scan your hard drive for their config files? Or run otherwise expensive computations?

Call it a philosophical difference. If you're happy that this is happening then by all means it's fine. I wanted to point it out as I view it as bad behavior and wasn't sure if you made any conscious decision around whether or not you want to have this happening in your library. I've pointed it out to the appropriate people and now it's up to yourself and others to decide how it should work. Thanks :)

**Comment by vangent** [comment]
Thanks for the comments, and thanks for using Go CDK!

> Especially if I'm not intending to use it

The goroutine is needed to implement the functionality provided by the package. It's not intended for you to use it explicitly.

I understand your "slippery slope" concern, but I think in Go you should consider "starting a goroutine" closer to the "allocated some memory" end of the slope (which I don't think you would blink an eye at, e.g., package-level vars or consts) than "scanning my hard drive".

In any case, this wasn't a design decision we made explicitly; it's part of our use of OpenCensus. I don't think this concern is a big enough issue for us to revisit that.

**Comment by aarondl** [comment]
> The goroutine is needed to implement the functionality provided by the package. It's not intended for you to use it explicitly.

Surely metrics and tracing is an optional piece of any package which at some point I'd choose to use and only then would require the goroutine. Also goroutines cheap as they are still take processing power away from other goroutines, multi-core arguments etc. etc aside, it depends how busy your program is already. There's a lot of insane-level scale stuff happening in Go at which point these things matter.

Thanks for taking a look. I'll try to get them to pull it out of the OpenCensus library then. Have a good one, and thanks for the great package, blob is especially useful.

**Comment by eliben** [comment]
@aarondl we hear your concerns. As you say, the right place to solve it is the OpenCensus module. We'll keep an eye on https://github.com/census-instrumentation/opencensus-go/issues/1074
