### ISSUE TITLE
internal/testing: check_api_change.sh raises an error if master made a breaking change during test run

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#1802]
As per this comment:

https://github.com/google/go-cloud/blob/4a4b28c6ec7c46a7b4a945e427298862efb65958/internal/testing/check_api_change.sh#L39-L44

The script currently fails in the case where a breaking change has been committed to master since the PR work started. I haven't drilled into whether merging resolves this issue, but I don't think this should be an error case, as this will affect any PRs outstanding after a breaking change commits. (Thundering herd merge.)

Travis CI job with context: https://travis-ci.com/google/go-cloud/jobs/192256983#L1445-L1453

**Comment by vangent** [comment]
I think a merge to `HEAD` should fix it.

Do you have an alternative suggestion?

**Comment by zombiezen** [comment]
Aha, found the underlying issue (and also the low incidence of this false positive occurring): the problem is one of concurrency. The sequence that triggers the failure:

1) Non-breaking PR build starts. Travis automatically created a merge commit as per [their docs](https://docs.travis-ci.com/user/pull-requests/).
2) A breaking PR is submitted to master.
3) `check_api_change.sh` grabs the master branch from the live repo instead of the master branch that was used to create the merge in Step 1.
4) apidiff is now comparing a stale merge of master to a more recent master. This may even trigger false results even if any safe API change was made.

Luckily, the fix is straightforward and makes the test faster: instead of `git clone https://github.com/google/go-cloud`, use `git clone .`.
