### ISSUE TITLE
internal/cmd/gocdk: add help command

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#1810]
Currently, the CLI only surfaces help information if you run `gocdk subcommand --help`. It would be nice to support the common alternative spelling `gocdk help subcommand`. In gg, I implemented this by rewriting the second spelling into the first spelling during subcommand dispatch and allowing the subcommand to render its own help documentation.

**Comment by zombiezen** [comment]
Link to gg source: https://github.com/zombiezen/gg/blob/c2ce6c1b011cd5cdfaf92b1f1fd42df508c0dc3d/cmd/gg/main.go#L263-L271

**Comment by vangent** [comment]
This will be handled in https://github.com/google/go-cloud/issues/2147.
