### ISSUE TITLE
pubsub: consider adding Close/Shutdown methods for drivers

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#1813]
We currently have `Shutdown` at the portable type, but not in the driver interface, for both `Topic` and `Subscription`.

I'm working on Kafka; it's looking like I'm going to need to start a goroutine in `OpenSubscription`. It's not obvious how to clean it up.

* We could add `Shutdown` or `Close` methods to the driver interface and have the portable type call them.

* It could use the `ctx` passed to `OpenSubscription`, but that's a bit subtle IMHO; many users will pass `context.Background()` and leak the goroutine, or pass something else and not realize the context needs to be closed.

* I could make `OpenSubscription` return a `cleanup` function. This seems a bit weird given that it also returns a `pubsub.Subscription` that has a `Shutdown` method.

@jba thoughts?

**Comment by vangent** [comment]
I sent a PR with a variant of option 1 above; drivers may optionally implement `io.Closer` for their topics/subscriptions, and have the `Close` func called during `Shutdown`.

**Comment by jba** [comment]
Might as well just require drivers to have `Close`. It's a trivial burden for those that don't need it.
