### ISSUE TITLE
doc: add website guide for server

### ISSUE THREAD

**Issue by eliben** [google/go-cloud#1819]
With #1598 we now have a minimal sample for using the CDK's `server` in `samples/server`. @zombiezen suggests "we should add a guide in the website tutorials to promote discoverability."

**Comment by zombiezen** [comment]
To be clear, I'm thinking a page like https://gocloud.dev/tutorials/cli-uploader/

**Comment by eliben** [comment]
I believe this has been sufficiently addressed by #2437 for now
