### ISSUE TITLE
pubsub/nats: reconsider ReceiveBatch returning multiple messages

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#1829]
`ReceiveBatch` for `nats` currently returns multiple messages (up to `maxMessages`). These messages are queued in the portable type (`pubsub.Subscription`) before being returned to the user one at a time via `Receive`.

IIUC, the semantics of NATS are that messages are only delivered once; I think this means that any messages that are queued are getting dropped on the floor.

I.e., application is running along, and there happens to be a queue of a few dozen messages. The portable type endeavors to keep this queue non-empty by prefetching messages using `ReceiveBatch`. Whenever the application decides to exit, it will stop calling `Receive` and call `Shutdown`; any messages that were returned from `ReceiveBatch` but not yet passed to the user via `Receive` will never be delivered.

Ideas:
* We could change `ReceiveBatch` to only return a single message. This might help mitigate the problem but won't get rid of it.
* We could try to change `Subscription.Shutdown` to wait until the queue of messages in the portable type is drained (assuming that the caller has separate goroutines calling `Receive`).
* ?

/cc @jba

**Comment by vangent** [comment]
* We could allow drivers to tell the portable type not to prefetch messages, but only to call `ReceiveBatch` as part of `Receive` (and `ReceiveBatch` would always return a single message).

**Comment by vangent** [comment]
Kafka has a similar issue. For Kafka, another option might be to allow the driver to add a hook to `driver.Message` that is called right before the message is returned to the user in `Receive`; that would cause Kafka to mark the message's offset (this works since offsets are in order). I don't think that solution works for NATS because there's no explicit operation to mark a message as received other than receiving it.

**Comment by jba** [comment]
At first glance, I like the idea of disabling prefetch.

I thought Kafka was at-least-once?
