### ISSUE TITLE
docstore/awsdynamodb: pass limit in query RPC

### ISSUE THREAD

**Issue by jba** [google/go-cloud#1830]
The dynamodb query RPC treats its limit parameter as the number of items to process _before_ filtering with the provided filter expression. We want limit to apply to the actual number of items returned to the user.

Currently we track the limit ourselves in the driver iterator, and don't pass a limit to dynamodb. But this could result in a lot of extra work. For example, if the user provides a limit of 1, dynamodb might retrieve 50 items.

I propose that we pass a limit to the RPC. If there are no filters (no additional Where clauses after the key clauses), then we can pass the user-provided limit. Otherwise, we can pass something like double the user limit.

**Comment by vangent** [comment]
> we can pass something like double the user limit

And make more RPCs later if there aren't enough? If the filter is strong, double may not be enough. E.g., what if the filter is on a unique-valued key?

**Comment by jba** [comment]
Yes, that's the tradeoff.
