### ISSUE TITLE
docstore: support multi-field primary keys

### ISSUE THREAD

**Issue by jba** [google/go-cloud#1858]
Currently, docstore assumes that a single field in the document is the unique key. Many document stores work this way, but not all: DynamoDB allows two fields to act as the primary key together (that is, each one individually may not be unique, but the pair is unique). If we want to portably support all document stores, we have to account for this case in the other drivers. 

As an example, consider a collection of high scores for games. The fields are: game name, user name, and score. The primary key is the pair (game name, user name). The collection could use the struct
```
type HighScore struct {
    Game  string
    User  string
    Score int
}
```

The most general way to support this would be for drivers to accept an option that is a function from documents to primary key values. In the above example, it could be
```
func(doc docstore.Document) interface{} {
    hs := doc.(*HighScore)
    return hs.Game + "," + hs.User
}
```
(assuming that no `Game` has a comma).

I propose we support that function. But in doing so we lose the ability for Create to make up a primary key and store it back in the document: it wouldn't know how to construct the key or where to store it. So we should also support a single field name to use as the key, as we do now in most drivers. 

#1856 is the PR that does this for mongodocstore.

**Comment by jba** [comment]
@shantuo @vangent

**Comment by shantuo** [comment]
If we want to keep the unique ID design in the portable API, for dynamo we could have something like
```go
// ParseKey defines how to parse the primaryKey into the partition key and sort
// key, if existing. It returns two interfaces, the first one is the partition
// key, which is required for any dynamo table, the second one is the sort key,
// which is only required when the table defines a field to be the sort key
func ParseKey(primaryKey interface{}) [2]interface{}
```

- For the dev, our API appears true portable as they don't need to know about different nuances between providers, they just know they need one unique primary key for each document.
- For the ops, they will need to design the schema based on the providers and write the `ParseKey` function.
- For us, we parse the key before encoding and separate the `Original` doc with the "artificial" doc we encode under the hood for dynamo. The mongo PR looks good. And we don't need to do anything for firestore.

**Comment by jba** [comment]
We could add `ParseKey`, but I'm not sure how often it would be used. For collections like the `HighScore` one I mention above, you'd still want the separate `Game` and `User` fields so you could query on them.

**Comment by vangent** [comment]
Can you clarify for me the ways in which the portable type uses the assumption that a single field is the unique ID? I understand how a document could violate that, but it's not obvious what the impact on docstore is without any changes.

I like Tuo's idea of trying to handle this via options in the DynamoDB constructor rather than the portable type.

**Comment by jba** [comment]
The portable type uses that assumption in only one place: when Create makes a new unique key for a document that's missing one.

All the options under consideration are driver options, not portable-type options.

**Comment by vangent** [comment]
> The portable type uses that assumption in only one place: when Create makes a new unique key for a document that's missing one.

Then I guess I don't follow how the original suggestion of a `func(doc docstore.Document) interface{}` helps at all, given that it later says "in doing so we lose the ability for Create to make up a primary key and store it back in the document". If that's the only problem we're trying to solve, how does a solution that doesn't solve it help?

Maybe `docstore` also has the requirement of being able to identify a single primary key for a document?

> we lose the ability for Create to make up a primary key

IIRC, SQL doesn't support this either. There are auto-create type unique fields, but if you have a dual-field primary key then you generally need to provide all of the values when creating. That makes sense to me; if you have a combination of fields like the example, the fields likely have real meanings and auto-generated values don't make sense.

**Comment by jba** [comment]
> If that's the only problem we're trying to solve

It's not a problem we're trying to solve, it's a casualty of the solution. The problem we're trying to solve is described in the first paragraph of the first entry of this issue.

> That makes sense to me

Yup, makes sense to me too, which is why I've proceeded to implement this in all drivers.
