### ISSUE TITLE
runtimevar: driver packages use NewVariable instead of OpenVariable

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#1859]
### Is your feature request related to a problem? Please describe.

Our convention for constructing portable types has been to use `OpenFoo` instead of `CreateFoo` or `NewFoo` to avoid the connotation that this is creating a resource. (See #1715 and #158 for prior discussion.)

The `runtimevar` drivers pretty consistently use `NewVariable` as their opening constructor names.

### Describe the solution you'd like

All driver constructors under `runtimevar` except for `constantvar` (which is actually creating a new variable) should substitute `New` for `Open` in their names.

This is a breaking change.

**Comment by vangent** [comment]
`secrets` has the same issue.
