### ISSUE TITLE
all: consider unifying compound ID handling

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#1860]
(This is a write-up of a cross-cutting problem that @vangent and I stumbled across, but with concrete data about affected APIs.)

**EDIT:** The purpose of this issue is to discuss the problem and determine what we want to do about it (even if the answer is "nothing").

/cc @clausti @eliben @jba @shantuo 

### Is your feature request related to a problem? Please describe.

Many cloud providers have resource IDs that are made up of subcomponents in some well-defined syntax. For example, [GCP KMS key IDs](https://cloud.google.com/kms/docs/object-hierarchy#key) take the form `projects/[PROJECT_ID]/locations/[LOCATION]/keyRings/[KEY_RING]/cryptoKeys/[KEY]`. For the purpose of this issue, let's call these _compound IDs_.

There are two broad compound ID usage patterns we have observed:

1)  Applications will keep resources in the same location or project, so the application will build the ID from the subcomponents rather than passing the entire resource ID around.
2)  Applications will pass a verbatim string from configuration down to the API, since this is what was easily copy-pasteable from the cloud console UI.

As of 2019-04-19, compound IDs show up in:

-  The MySQL and PostgreSQL packages. Every database has a collection of fields that build up their instance connection string. For example, Cloud SQL's instance syntax is `myproject:us-central1:myinstance`. The constructors take in parameter structs ([example](https://github.com/google/go-cloud/blob/af156be9f2ca89a3dae18338a4beabf65b7499cc/mysql/cloudmysql/cloudmysql.go#L50-L76)) that separate each field, but it has more than just an instance name.
-  [GCP Pub/Sub constructors](https://github.com/google/go-cloud/blob/af156be9f2ca89a3dae18338a4beabf65b7499cc/pubsub/gcppubsub/gcppubsub.go#L232) take in a project ID and a topic name as two separate strings. In the underlying GCP APIs, these have names like `projects/myproject/topics/mytopic`.
-  The AWS Pub/Sub [publisher](https://github.com/google/go-cloud/blob/af156be9f2ca89a3dae18338a4beabf65b7499cc/pubsub/awssnssqs/awssnssqs.go#L271) takes in an [ARN](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html) as a string and the [subscriber](https://github.com/google/go-cloud/blob/af156be9f2ca89a3dae18338a4beabf65b7499cc/pubsub/awssnssqs/awssnssqs.go#L426) takes in an SQS queue URL (like `https://sqs.us-east-2.amazonaws.com/123456789012/MyQueue`) as a string.
-  `gcpruntimeconfig` has a [`ResourceName` struct](https://github.com/google/go-cloud/blob/af156be9f2ca89a3dae18338a4beabf65b7499cc/runtimevar/gcpruntimeconfig/gcpruntimeconfig.go#L203-L208) that wraps the `projects/[project_id]/configs/[CONFIG_ID]/variables/[VARIABLE_NAME]` resource name in the underlying GCP API.
-  `awskms` accepts [multiple types of KMS key IDs](https://github.com/google/go-cloud/blob/af156be9f2ca89a3dae18338a4beabf65b7499cc/secrets/awskms/kms.go#L141) using a single untyped string.
-  `azurekeyvault` splits apart parts of the API URL into [separate string parameters](https://github.com/google/go-cloud/blob/af156be9f2ca89a3dae18338a4beabf65b7499cc/secrets/azurekeyvault/akv.go#L197) for vault name, key name, and key version.
-  `gcpkms` uses a [single untyped string](https://github.com/google/go-cloud/blob/af156be9f2ca89a3dae18338a4beabf65b7499cc/secrets/gcpkms/kms.go#L132) for the syntax `projects/[PROJECT_ID]/locations/[LOCATION]/keyRings/[KEY_RING]/cryptoKeys/[KEY]`, but includes a [`KeyResourceID` function](https://github.com/google/go-cloud/blob/af156be9f2ca89a3dae18338a4beabf65b7499cc/secrets/gcpkms/kms.go#L139-L144) that can join the parts together.

As you can see, there are a wide variety of ways this problem has been solved throughout the Go CDK, all with varying degress of support for the two use cases above. Further, many of these involve untyped strings, which make usage with Wire difficult.

### Describe the solution you'd like

(I'm not 100% certain of this approach, but I think it addresses the needs stated above.)

Every compound ID should have a named string type like:

```go
package gcpkms

// KeyID is a crypto key resource ID like "projects/[PROJECT_ID]/locations/[LOCATION]/keyRings/[KEY_RING]/cryptoKeys/[KEY]".
type KeyID string

// JoinKeyID builds a key ID from its component parts.
func JoinKeyID(project, location, keyRing, keyName string) KeyID {
  return KeyID("projects/" + project + "/locations/" + keyRing + "/cryptoKeys/" + keyName)
}

// String returns the ID as a string.
func (id KeyID) String() string {
  return string(id)
}

// ProjectID returns the key's project ID or the empty string if the ID could not be parsed.
func (id KeyID) ProjectID() gcp.ProjectID {
  // ...
}

// ... and similarly for Location(), KeyRing(), and KeyName().
```

By using a named type, it also makes it more difficult to pass the wrong type of ID into a function, as well as gives the possibility of such methods. Even if the underlying cloud API doesn't actually use the compound ID directly, the component functions can split the elements back into a form that is usable for the APIs.

### Describe alternatives you've considered

We could use structs everywhere like the ones in MySQL and PostgreSQL, but this makes it more difficult to pass through strings verbatim. If a cloud provider adds a new acceptable ID form (like in AWS KMS), then our inability to parse into a struct hampers verbatim passthrough, whereas such functionality would work largely without a recompile in the typed string approach I outline above.

**EDIT:** Doing nothing may also be an option. We may find this is too much churn for not enough user benefit.

### Additional context

This does not necessarily have to be a breaking change: we could keep the existing functions and add new functions that take the new style, but I haven't thought about this in depth.

**Comment by clausti** [comment]
> // ProjectID returns the key's project ID or the empty string if the ID could not be parsed.
> func (id KeyID) ProjectID() gcp.ProjectID {
>   // ...
> }
> // ... and similarly for Location(), KeyRing(), and KeyName().

Would each of these be re-parsing from the whole string in order to return their specific component?

**Comment by zombiezen** [comment]
Yes, but likely each one could make optimizations. Since such usage would likely be for startup, my intuition is that performance isn't a large concern for these methods, but I could definitely be wrong.

I'm not fully convinced yet that we should address this issue or if so, whether the solution I propose is the right one. I'm opening the issue to start the discussion about what we as a team want to do about this pattern we've observed. Do nothing is a valid option (edited to add it explicitly).

**Comment by clausti** [comment]
My initial thought is that if we are going to create named types (which seems good), we could still have a struct that has fields for the components and also the literal built string. That way, we wouldn't have to re-parse the string any time we'd want to get an attr out of it, and we could fall back to the literal string both on input (like if something was added to the structure of the key before our code caught up) and on output (we don't have an accessor for the subcomponent you want, but we can cough up the whole string)?

**Comment by zombiezen** [comment]
@vangent @eliben Pinging here, we should decide on this before going beta.

(Should we perhaps have a beta-blocker milestone or tag?)

**Comment by eliben** [comment]
> @vangent @eliben Pinging here, we should decide on this before going beta.
> 
> (Should we perhaps have a beta-blocker milestone or tag?)

I think a P1 priority is fine for marking beta blockers right now. We'll want to resolve all P1 issues by then. Ross - assigning to you just to make sure the bug is better tracked, we can reassign once we decide what to do

**Comment by zombiezen** [comment]
Decision from meeting: Untyped string is what we want to use going forward. We would prefer to avoid making breaking changes to do this, but we'll evaluate usage of the current APIs on a case-by-case basis and try to make the situation more consistent. Particularly, we want to keep blob and pubsub APIs unchanged. As we go to make the changes for this issue, we should also be evaluating the URLs in the same packages.

Before closing this issue, we should also amend design.md with the decision here so that future portable APIs remain consistent (i.e. using untyped string).

**Comment by vangent** [comment]
Per discussion with @zombiezen:
* He is going to write up this guidance for `design.md`.
* He is going to review the trickiest cases, `mysql` and `postgres`, starting with `rdspostgres`, and figure out what we want things to look like there (they have relatively complicated `Params` structs, and we do some relatively complicated things to take a URL, parse it into `Params`, and then put it back into another URL -- hopefully this can all get simpler...).
* I am going to start making the more mechanical changes to apply this decision to our existing providers in `blob`, `pubsub`, `secrets`, and `runtimevar`.

**Comment by zombiezen** [comment]
For the SQL providers, I'm thinking the answer is to remove the explicit constructors and only expose the URL openers. I could do this as part of wrapping up #1175. @vangent, does this seem reasonable?

**Comment by vangent** [comment]
I think so, but can you explain in person why an explicit constructor isn't needed anymore? Would it just take a string and so not be distinguishable from the URL opener?

**Comment by zombiezen** [comment]
Quoting my offline reply: "Yes."

**Comment by zombiezen** [comment]
I believe that the remaining work from my end on this issue is captured in #1175, so I'll track there. Unassigning myself from this issue.

@vangent, if the other mechanical changes are completed, I think we can close this issue.
