### ISSUE TITLE
pubsub: clarify/document semantics of Send and SendBatch

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#1863]
Since we batch user messages into `SendBatch` calls, it's not necessarily obvious what the semantics of an error returned from `Send` are.

For example, for a driver that iterates over the batch and sends them one by one, and returns an error for the last one, `n-1` messages were actually sent and 1 message not sent, but all `n` will get an error.

In other cases, retries may cause multiple sends.

We should think about this a bit more and clarify what `SendBatch` should do, what guarantees (if any) the portable type provides, and what differences (if any) there are across drivers.

@jba

**Comment by jba** [comment]
`SendBatch` could return a richer error that describes exactly which sends failed. I think `Send` should report success as accurately as possible.
