### ISSUE TITLE
secrets: add KMIP support

### ISSUE THREAD

**Issue by rolandcrosby** [google/go-cloud#1871]
### Is your feature request related to a problem? Please describe.

I'd like to use a common interface when integrating my product with various key management systems to encrypt and decrypt secrets. The go-cloud secrets interface looks like it will do what I need for the cloud vendors' KMS implementations and Vault. I'm wondering if anyone has considered adding a go-cloud integration with KMS systems supporting the [KMIP](https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=kmip) standard.

### Describe the solution you'd like

I'd like to be able to instantiate a secret keeper using a KMIP server instead of a cloud KMS or Vault server, and then use the regular Encrypt/Decrypt methods with it. Implementing all of the KMIP client functionality doesn't seem necessary - KMIP can do a lot more than just encrypt and decrypt, but most of its functionality appears out of scope for what the secrets package is trying to do.

### Describe alternatives you've considered

The universe of open-source KMIP implementations is small, but there are a few existing libraries I've looked at using directly:

- [gemalto/kmip-go](https://github.com/gemalto/kmip-go)
- [suse/cryptctl](https://github.com/suse/cryptctl)
- [stefanberger/go-kmip](https://github.com/stefanberger/go-kmip)
- [openkmip/libkmip](https://github.com/openkmip/libkmip) (C, not Go)

I'm not sure which of these, if any, is suitable for integration with the go-cloud secrets package, but figured I'd pass them along.

**Comment by vangent** [comment]
Thanks for the idea! We'd need a client library to build on, and based on the popularity of the Go libraries you cited (0-1 Github stars for each, 1-2 contributors), I'd be hesistant to build on any of them.

Our hope is that Go CDK's portable type is your "common interface"... Given that we've covered the big 3 cloud vendors and Vault, are there other specific KMS systems you're interested in?

**Comment by rolandcrosby** [comment]
Thanks for the quick response! That makes sense, I just thought I'd check in case this was already on your feature backlog.

The CDK already covers the majority of KMS services that I've seen customer requests for. Vault is a common request, as are the AWS and Google Cloud services. The other ones I've gotten requests about are proprietary enterprise HSMs and KMS services, which generally appear to use KMIP or PKCS#11.
