### ISSUE TITLE
internal/testing: consolidate list of project modules

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#1883]
### Is your feature request related to a problem? Please describe.

When a new module is added, it must be added to:

-  gocloud.code-workspace (see golang/go#30841)
-  internal/testing/listdeps.sh
-  internal/testing/runchecks.sh

Failure to do so means that tests silently don't run for the module. Especially if we start adding more submodules, this problem is going to get worse.

### Describe the solution you'd like

I would like to have either a consolidated list of the modules or have the scripts automatically detect the go.mod files and declare boundaries there, if feasible.

### Additional context

#1846 is an example of a time that I did forget, #1847 is an example of a time that I almost forgot to update one of the files (runchecks.sh) but not the other (listdeps.sh).

**Comment by eliben** [comment]
I can see us having some single place where all the modules in the repo are listed, and the shell scripts reading from there. Not sure how this applies to the vscode config file though - can it actively read from a separate file? Or would it need to be some sort of codegen (config-gen) solution for that case?

**Comment by zombiezen** [comment]
VSCode would need code-gen, yeah.

**Comment by eliben** [comment]
@zombiezen - I've been thinking about this and I'm going back and forth on the helpfulness of code-gen-ing it vs. once-in-a-rare-while updating the VScode file. Not sure what workflow would be helpful to you, so assigning it to you

**Comment by zombiezen** [comment]
Manual workspace edits are probably fine, as long as we don't change modules too often.

**Comment by zombiezen** [comment]
Closing since I don't think I have anything to contribute here.
