### ISSUE TITLE
blob/s3blob: Attributes.MD5 doesn't match MD5 sum of files

### ISSUE THREAD

**Issue by shatil** [google/go-cloud#1898]
### Describe the bug

`blob.Attributes.MD5` is _not_ the MD5 sum of the object for any object uploaded by using the S3 multipart API.

### To Reproduce

Upload objects that `blob/s3blob.Writer` and compare the `blob.Attributes.MD5` of each. You'll need to replace `BUCKET` in the code below with an S3 bucket's name.

```go
package main

import (
	"context"
	"crypto/md5"
	"fmt"
	"log"

	"gocloud.dev/blob"
	_ "gocloud.dev/blob/s3blob"
)

func check(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

func putObject(ctx context.Context, b *blob.Bucket, key string, value []byte) {
	w, err := b.NewWriter(ctx, key, nil)
	check(err)
	_, err = w.Write(value)
	check(err)
	check(w.Close())
}

func remoteSum(ctx context.Context, b *blob.Bucket, key string) []byte {
	attr, err := b.Attributes(ctx, key)
	check(err)
	return attr.MD5
}

func main() {
	ctx := context.Background()
	b, err := blob.OpenBucket(ctx, "s3://BUCKET")
	check(err)

	small := []byte("This is a small file\n.")
	large := make([]byte, 5<<20) // 5 MiB.

	putObject(ctx, b, "small", small)
	putObject(ctx, b, "large", large)

	fmt.Printf("small local MD5 %x, remote MD5 %x\n", md5.Sum(small), remoteSum(ctx, b, "small"))
	fmt.Printf("large local MD5 %x, remote MD5 %x\n", md5.Sum(large), remoteSum(ctx, b, "large"))
}
```

You'll get something like this:

```
small local MD5 36a158a8d16c9f3d229c1759687c7e6b, remote MD5 36a158a8d16c9f3d229c1759687c7e6b
large local MD5 5f363e0e58a95f06cbe9bbc662c5dfb6, remote MD5 81485c0e873d222199469076b60f30e9
```

## Expected behavior

`blob.Attributes.MD5` should show the MD5 sum of the object, or document why not, and maybe suggest means to calculate `ETag` for a reliable comparison.

### Version

`gocloud.dev v0.12.0`

### Additional context

`blob.Attributes.MD5` is supposed to represent the MD5 sum for an object, and does so for files uploaded in a single part. For such files, the S3 `ETag`, stripped of quotes, is the MD5 sum of a file, e.g., using the `curl` on a public S3 bucket:

```
$ curl -Is https://s3.amazonaws.com/ryft-public-sample-data/AWS-x86-AMI-queries.json | grep ETag
ETag: "53fcff4ed3c74553e378e785e5bd339c"
```

And calculating the MD5 sum on macOS (use `md5sum` instead on Linux):

```
$ curl -s https://s3.amazonaws.com/ryft-public-sample-data/AWS-x86-AMI-queries.json | md5
53fcff4ed3c74553e378e785e5bd339c
```

For objects put to S3 using the multipart API, which is what [AWS SDK for Go's `s3manager`](https://docs.aws.amazon.com/sdk-for-go/api/service/s3/s3manager/) does, objects are uploaded in chunks. Chunk sizes are left to uploader's discretion. The AWS CLI likes to use 8 MiB chunks, meaning files smaller than that are put in single-part upload. `blob.Bucket.Writer` appears to use even smaller chunks than that.

```
$ curl -Is https://s3.amazonaws.com/ryft-public-sample-data/integration_test_dataset_large.json | grep ETag
ETag: "224e9d5312b17939f9f470622d3f529d-24"
```

For multipart uploads, `ETag` is _an_ MD5 sum is separated by a dash from the number of parts in the multipart upload. `blob.Attributes.MD5` presents this MD5 sum as that of the object, but this is incorrect. _This_ particular sum is actually the [MD5 sum of the MD5 sums of each part of the multipart upload](https://stackoverflow.com/questions/12186993/what-is-the-algorithm-to-compute-the-amazon-s3-etag-for-a-file-larger-than-5gb/32664247).

**Comment by vangent** [comment]
Thanks for the report. We were aware of this; this code:
https://github.com/google/go-cloud/blob/master/blob/s3blob/s3blob.go#L540-L564
is supposed to handle it (by leaving the `MD5` field blank for cases where the `ETag` isn't the real MD5.

 In particular, it is supposed to return an empty `MD5` for `ETag` like `"224e9d5312b17939f9f470622d3f529d-24"`, due to the `-24` suffix.

I will investigate.

**Comment by vangent** [comment]
It seems we were not checking the error when hex-decoding the `ETag` via `hex.DecodeString`, on the assumption that it would return `nil` on error. That's not the case; it returns whatever it has been able to decode. I sent a PR to check the error.

This will "fix" this behavior so that the `MD5` field is blank for S3 blobs uploaded in multi-parts, rather that incorrect.

**Comment by shatil** [comment]
Thanks for making quick work of this, @vangent. Can you recommend a way to compare hashes (MD5 or ETag or whatever is available to compare) for multipart uploads?

**Comment by vangent** [comment]
You are welcome!

> Can you recommend a way to compare hashes (MD5 or ETag or whatever is available to compare) for multipart uploads?

* You can use `Size` as a first check.
* If the blobs are the same size, and the provider doesn't give us an MD5, I'm not sure what you can do other than download the file contents.

If you like, and if you want to compare S3 blobs to S3 blobs, you can use `As` to access the underlying S3 types and compare their `ETag`s directly. However, I'm not sure if that even works for multi-part uploaded files; for example, if the chunk-sizes were different then the `ETag`s would be different even though the actual file contents are the same.

Let me know if you figure something out.

**Comment by shatil** [comment]
Thanks for the hint about `Size`! Using that with an existing object's `ETag`, I think you can calculate the part size in a multipart upload, assuming equal-sized parts (except for the last one). Part sizes round to the next multiple of one mebibyte (1048576 bytes), and `ETag` tells us how many parts there are.

```go
// PartSize calculates the part ("chunk") size of an S3 object and whether
// object was uploaded using S3's multipart API.
func PartSize(etag string, size int64) (int64, bool) {
	apart := strings.Split(strings.Trim(etag, `"`), "-")
	if len(apart) == 1 {
		return size, false
	}
	numParts, err := strconv.ParseFloat(apart[1], 64)
	if err != nil {
		log.Printf("couldn't parse number of parts from ETag %q", strings.Join(apart, "-"))
		return size, false
	}
	multiple := float64(1 << 20)
	return int64(math.Ceil(float64(size)/multiple/numParts) * multiple), true
}
```

Knowing the number of parts and the size of each part, we can reliably calculate a local file's `ETag` like this:

```go
// ETag calculates the S3 ETag for a file. Supply partSize = 0 if you're unsure
// what part size was used during a previous multipart upload. The multipart API
// can also be used for files of size smaller than or equal to part size, so
// specify multipart = true for those, or if you're unsure, specify false and
// it'll be deduced from the file size.
func ETag(filename string, partSize int64, multipart bool) string {
	if partSize <= 0 {
		partSize = int64(8 << 20) // 8 MiB is part size for AWS CLI.
	}

	f, err := os.Open(filename)
	if err != nil {
		log.Printf("failed to calculate ETag for %q because: %s", filename, err)
		return ""
	}
	defer f.Close()

	info, err := f.Stat()
	if err != nil {
		log.Printf("failed to stat %q because: %s", filename, err)
	}

	var loaded int64
	var tally []byte

	for loaded < info.Size() {
		h := md5.New()
		n, err := io.CopyN(h, f, partSize)
		if err != nil && err != io.EOF {
			log.Printf("failed to read %q because: %s", filename, err)
			return ""
		}
		loaded += n
		tally = append(tally, h.Sum(nil)...)
	}

	// Multipart doesn't mean there was actually more than one part, just
	// that the S3 multipart API was used.
	if numParts := len(tally) / md5.Size; numParts > 1 || multipart {
		return fmt.Sprintf("%x-%d", md5.Sum(tally), numParts)
	}
	return fmt.Sprintf("%x", tally)
}
```

I tested this against the 5 MiB object I uploaded to S3 in my first post, whose `ETag` is `81485c0e873d222199469076b60f30e9-1` (beats me why it was sent multipart with just the one part). I also tested against `s3://ryft-public-sample-data/integration_test_dataset_large.json`, whose `ETag` is `224e9d5312b17939f9f470622d3f529d-24` in S3.

Here's a working example: https://play.golang.org/p/ywOpwZuNp-h

**Comment by shatil** [comment]
Never mind, that approach is unreliable. E.g., this popular WordPress plugin's video file: https://www.google.com/search?q=webproductlight%2Fofficeloop_low.mp4

Uploaded using AWS CLI or AWS SDK Go's `PutObject`:

```
ETag: "709c29f8e27dd85ffbe8deedb47d5982"
Content-Length: 7523460
```

Uploaded using `blob.s3blob.Writer` (and `s3manager.Uploader` for good measure):

```
ETag: "1c527f8775bc0a88d41752a7593c4801-2"
Content-Length: 7523460
```

My calculation produces `df39d80a88938a11033dd182308d1dc2-2` for `ETag`, which is clearly wrong. Luckily AWS SDK's [`s3manager` documentation does specify a minimum](https://docs.aws.amazon.com/sdk-for-go/api/service/s3/s3manager/#pkg-constants), which is 5 MiB.

**Comment by vangent** [comment]
Do you mind if I ask what you are actually trying to do? It seems like you're trying to use `ETag` to do something but it's not obvious exactly what that is.

* `ETag` is S3-specific, so even if you can get it to work it won't be cross-platform.
* I suspect you can identify 99% of files that are different by just comparing the `Size` of the two files, although it likely depends on the application and what you're storing.
* Perhaps you can compare `Size`, and compare `MD5` if available, and if the sizes are the same and `MD5` is not available, read a few `KB` at a time to compare. If most of your files are different, then this would probably be OK.
* If you are storing the data as well as reading it, you could consider saving an MD5 hash (or any other hash) explicitly in [`Metadata`](https://github.com/google/go-cloud/blob/master/blob/blob.go#L961-L965).

**Comment by shatil** [comment]
My objective was to forestall the upload of files already in the bucket. I'm synching binary and text files (just 10,000 files, but growing) to S3 from EC2, where they're generated every so often. I was using `aws s3 sync` originally, which examines file size and timestamp only, and it was taking too long since timestamps change when files are generated.

> consider saving an MD5 hash (or any other hash) explicitly in Metadata.

In retrospect, this is what I should've done, but I kept digging myself further down this rabbit hole when I had heard "ETag is just MD5!" and saw Go Cloud had that field available. Thanks again, @vangent.
