### ISSUE TITLE
pubsub: add support for amazon kinesis

### ISSUE THREAD

**Issue by h7kanna** [google/go-cloud#1908]
### Is your feature request related to a problem? Please describe.
Add pubsub implementation based on Amazon Kinesis.

### Describe the solution you'd like
I did not check the exact details of the pubsub interface design and if it supports Amazon Kinesis, but If it is possible please add Kinesis support.

### Additional context
I found below Golang packages for Kinesis which may be used for implementation.
Producer : https://github.com/a8m/kinesis-producer
Consumer: https://github.com/vmware/vmware-go-kcl

**Comment by jba** [comment]
That doesn't look like a pubsub system. It looks like a streaming analytics system like Apache Spark or Google Cloud Dataflow.

**Comment by h7kanna** [comment]
Hi, I mean AWS kinesis Data streams

**Comment by eliben** [comment]
@h7kanna we're currently focused on the existing set of providers. We'll be happy to review concrete proposals to add new providers - would you like to take a stab at this?

**Comment by tiny-dancer** [comment]
hey, looking at potentially taking a stab at this.  our proposals/pr's welcomed? asking as the closed state could be interpreted as this will not be entertained for the foreseeable future
