### ISSUE TITLE
docs/howto: provide anchors for sub-sections of how-to docs

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#1941]
For example, https://gocloud.dev/howto/pubsub/subscribe/ has a section about NATS, but there's no way to link directly to it.

**Comment by zombiezen** [comment]
https://gocloud.dev/howto/pubsub/subscribe/#nats does what you need.

The how-to guides will auto-generated heading links, but the `## foo {#bar}` heading syntax sets an explicit anchor of `bar`.

**Comment by vangent** [comment]
The headers have anchors, but no explicit links. I'd like to add the link. Compare [before](https://screenshot.googleplex.com/4LSmUNo91pC) to [after](https://screenshot.googleplex.com/tcJmASQ3HK2).

**Comment by zombiezen** [comment]
Oh I see, you are looking for a UI element that provides that link. I'd like to find a non-JavaScript way of providing that UI element if possible.

**Comment by vangent** [comment]
Feel free to suggest something. This is the best I could find.

**Comment by zombiezen** [comment]
Oops, this is a generation-time hack, I misunderstood. (The blog URL confused me.) I think this is fine, I'll suggest some things on the PR. Thanks Robert!
