### ISSUE TITLE
pubsub/rabbit: TestCancelSendAndReceive seems to be flaky

### ISSUE THREAD

**Issue by eliben** [google/go-cloud#1950]
Example where it failed on Travis: https://travis-ci.com/google/go-cloud/jobs/196471448

@vangent says it failed once when running with `-count 100`

**Comment by eliben** [comment]
I can also reproduce this. Steps:

1. Make sure a local instance of RabbitMQ is running. `./internal/testing/start_local_deps.sh` can help.
2. cd into `pubsub/rabbitpubsub`
3. Run `go test --count=100 -v --run TestCancelSendAndReceive`

**Comment by vangent** [comment]
@jba this test overlaps (at least in name) with `TestConformance/TestCancelSendAndReceive`. Do you think we can just delete it? I spent some time digging into what Rabbit is doing, and it looks like sometimes it shuts down the entire `Connection` instead of just the `Channel`.

**Comment by jba** [comment]
I'm okay with deleting it.
