### ISSUE TITLE
docstore/dynamodocstore: switch to use httpreplay

### ISSUE THREAD

**Issue by eliben** [google/go-cloud#1971]
`docstore/dynamodocstore` is the only remaining user of go-vcr for AWS. I'm trying to port it to use `NewAWSSession2` (which uses httpreplay) but am running into issues, like:

```
    --- FAIL: TestConformance/Query (1.58s)
        setup.go:77: Recording into golden file testdata/TestConformance/Query.replay
        --- FAIL: TestConformance/Query/All (0.08s)
            drivertest.go:904:   []*drivertest.HighScore(Inverse(cmpopts.SortSlices, []*drivertest.HighScore{
                - 	s"Days Gone|mia=99@04/26",
                - 	s"Days Gone|steph=24@04/25",
                  	&{Game: "Praise All Monsters", Player: "andy", Score: 81, Time: s"2019-02-01 00:00:00 +0000 UTC"},
                  	&{Game: "Praise All Monsters", Player: "fran", Score: 33, Time: s"2019-03-19 00:00:00 +0000 UTC"},
                  	... // 6 identical elements
                  }))
          
```

Also there seems to be a cool-off of 10 minutes on running against the AWS dynamo store, otherwise I keep getting `IdempotentParameterMismatchException`

@shantuo can you please port this?

Related to #770

**Comment by jba** [comment]
@shantuo I think to fix the first problem (which I've also seen), we need to clear the collection before the test. (And after too, if you like.)

Also, we can fix the second problem with the new recorder by using time.Now().Unix() to seed https://github.com/google/go-cloud/blob/master/internal/docstore/dynamodocstore/dynamo_test.go#L111, and storing it in the initial state of the recorder.

**Comment by shantuo** [comment]
Is that because we are running the tests in parallel?

**Comment by jba** [comment]
I don't think we are. It's that the mia and steph documents are added before the query test, or that the query test crashes in a previous run before it can delete the collection, so they are still there on the second run.
