### ISSUE TITLE
internal/cmd/gocdk: allow interspersing of positional arguments

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#1991]
The new `gocdk` command uses the Go `flag` standard library package, which notably does not permit any flags after the positional arguments. Concretely, for something like:

```
gocdk init --module-path=github.com/foo/bar baz
```

does not permit:

```
gocdk init baz --module-path=github.com/foo/bar
```

This likely means that we need to use a different flag-parsing library.

**Comment by zombiezen** [comment]
FWIW, I solved this in gg by making a smallish clone of the `flag` package: https://godoc.org/gg-scm.io/pkg/internal/flag

**Comment by vangent** [comment]
github.com/google/subcommands is another possibility.

**Comment by vangent** [comment]
(although actually, I think it uses `flag` internally so it may not solve this)

**Comment by eliben** [comment]
FWIW I'm OK with using featured libraries like viper to build `gocdk` itself. As long as their imports don't seep into generated code users see :-)

**Comment by vangent** [comment]
There's also https://github.com/spf13/pflag.

**Comment by vangent** [comment]
This will be handled in https://github.com/google/go-cloud/issues/2147.
