### ISSUE TITLE
website: hugo seems to keep generating "changing" sitemap.xml files

### ISSUE THREAD

**Issue by eliben** [google/go-cloud#1994]
See https://github.com/google/go-cloud/commit/332c1bde650b09ca2589871809e0ae6 -- we have many commits every day to gh-pages, which essentially reshuffle the `sitemap.xml` file order.

Robert suggests trying a newer Hugo version

Or we could open an issue for Hugo

**Comment by vangent** [comment]
I filed https://github.com/gohugoio/hugo/issues/5934.

**Comment by zombiezen** [comment]
I agree with Robert's assessment here: this seems like an issue with upstream Hugo.

**Comment by eliben** [comment]
The default Hugo `sitemap.xml` template uses:

```
{{ range .Data.pages }}
...
{{ end }}
```

We could create our own template that uses a sorted range? (`range sort`)?

**Comment by eliben** [comment]
#1996 should address this for now (I hope). Will keep a watch on the commits to gh-pages to see if the spurious sitemap updates stop. Leaving open for now to see if this gets fixed and what bep says on the Hugo issue

**Comment by eliben** [comment]
I don't see spurious commits to gh-pages any more, so closing as fixed.
