### ISSUE TITLE
testing: explore options to check local container status before running tests

### ISSUE THREAD

**Issue by shantuo** [google/go-cloud#2005]
We discussed in the vault [PR](https://github.com/google/go-cloud/pull/1983#discussion_r281254551) that we want to get a sync point after localXXX.sh boots a container of a certain server for testing.

There are a few options:
1. Do nothing more, we set a timeout on the constructors and fail if the server is not up after a few seconds.
1. Wait a few seconds after the container starts and check its health.
1. If the previous one is still flaky, write a Go program to do more proper waiting.

**Comment by shantuo** [comment]
For Travis runs, we should detect and run these local tests on Linux only. Currently we skip the tests because the mac builds don't have these containers running, we should remove the `Skip` part.

**Comment by eliben** [comment]
@shantuo I'm raising the priority of this since I'm concerned we're not testing a bunch of code in all scenarios as long as we're skipping by default. There shouldn't be anything blocking this right now, correct me if I'm wrong
