### ISSUE TITLE
pubsub: consider exposing driver Subscription.SendAcks/SendNacks

### ISSUE THREAD

**Issue by Rolinh** [google/go-cloud#2011]
### Is your feature request related to a problem? Please describe.

I am developing an application which collects messages with `Subscription.Receive()`, compresses multiple `Message.Body` into a byte slice and uploads the result to a blob storage service. One of the application's main constraint is that no message can ever be lost (even if the application crashes, force-restarts, etc).
As `Ack()`/`Nack()` are methods of a `Message`, I am forced to keep all messages in memory simply to call `Ack()` once the compressed byte slice has been successfully uploaded to the blob storage service (or `Nack()` if there was an unrecoverable error in the process). Since the application has to collect many messages to create a compressed byte slice, the memory footprint for keeping these messages becomes a problem.

### Describe the solution you'd like

For the use-case described above, the application doesn't need to keep a `Message` once its `Body` has been processed if not just to be able to `Ack()`/`Nack()` the `Message`. Thus, an optimal solution would be to call a method of `Subscription` to acknowledge messages using message acknowledgement IDs.

I noticed that such a method exist in driver's `Subscription` implementations. Indeed, a `driver.Subscription` has variadic methods `SendAcks` and `SendNacks` which take `AckID`s as argument. Such methods would be very useful at `pubsub.Subscription` level as it would allow the user to only keep a `Message`'s `AckID` rather than the full `Message` to be able to ACK/NACK it.

I can't really think of another solution at the moment and would be really happy to hear your opinion about this problem and proposed solution.

### Describe alternatives you've considered

I considered setting a `Message`'s `Body` and `Metadata` to `nil` once they've been used. Although this solution wouldn't require any change in Go cloud, it feels like really hackish and sub-optimal.

**Comment by jba** [comment]
I think setting `Body` and `Metadata` to nil is a perfectly reasonable solution.

**Comment by vangent** [comment]
+1, that seems like a reasonable solution.

**Comment by Rolinh** [comment]
Thank you for your input.
