### ISSUE TITLE
internal/gocdk: add automated tests for launch

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#2013]
I'm sending out the launch command for review, but I haven't found a satisfactory way to test the command. The process is by definition non-hermetic: it is taking a binary and making it available in a different location. HTTP/RPC replay may help a little, but it won't make the application available at the address claimed by the launcher, which is an important property to test.

The local launcher is a little bit better since all we have to communicate with is the local Docker daemon, but that doesn't tell us much other than we correctly issued a `docker run` command.

WDYT @clausti and @vangent? Should we keep these tests manual for now with some test plan, or do you have ideas on how we can test this functionality in an automated way?

**Comment by vangent** [comment]
Can we test the local launcher using HTTP requests to the local port? It seems like we're doing that already to some extent using `waitForHealthy`. I'm doing something similar in the `ptype-add` tests (PR coming as soon as the base one is approved).

I agree that the remote launchers are going to be tough to test. HTTP replay might be good if `-record` works for it.

**Comment by clausti** [comment]
>HTTP/RPC replay may help a little, but it won't make the application available at the address claimed by the launcher, which is an important property to test.

Is it possible to have a test run only in record mode (skip it if you're not recording)? if so, would it be sufficient to do the "is it actually live at the address" testing only every so often? Instead of skipping the test entirely, we could have it check how old the recording is and fail if it's over the threshold?

**Comment by zombiezen** [comment]
> Is it possible to have a test run only in record mode (skip it if you're not recording)?

Yes.

> if so, would it be sufficient to do the "is it actually live at the address" testing only every so often?

Yes, we could skip the check for server liveness when the test is run in replay mode. But replay mode is the default and is run pervasively: when we run `go test ./...`, on Travis, etc.

My observation here is that at that point the test is largely then verifying whether the RPC is made with the correct parameters, which is usually easier to maintain as a unit test. I think that would be my preference, but it does not give as much confidence as an end-to-end test. On the other hand, I think this more limited unit test would make the limited utility of the test more apparent.

> Instead of skipping the test entirely, we could have it check how old the recording is and fail if it's over the threshold?

-1 from me on that idea. The failure mode I see there is that the test would start failing on an unrelated PR and it would block any submissions until the test is fixed.

On a previous team, logs would get regenerated weekly by the build cop, but it was much more automated than our setup. Trying to implement such a plan without having that in place would likely generate a fair amount of toil (noise in recording and flaky backends) with not enough benefit (actual regressions discovered).

**Comment by vangent** [comment]
We should also see if we can add some testing for the `server` package once we have this infrastructure.
