### ISSUE TITLE
pubsub/awssnssqs: add an implementation for Topic that sends directly to SQS

### ISSUE THREAD

**Issue by mremond** [google/go-cloud#2032]
It seems it is not possible to send Messages on subscriptions, only receive messages or send acks.

Maybe I missed something, but it thus does not seem possible to write the publisher part that generate messages received by subscribers.

So, it would be nice to be able to implement both roles with go-cloud.

**Comment by jarlefosen** [comment]
You cannot send messages directly to subscriptions, but you can send to topics.

In pubsub you can have multiple subscribers to a topic. Any message sent to a topic is readable by all subscriptions. In some cases you'd only have one subscription per topic, but there's nothing stopping you from having multiple subscribers.

Here's a document you can read that might be helpful in conceptually understanding the topics/publisher and subscriptions/consumer. https://cloud.google.com/pubsub/architecture

**Comment by mremond** [comment]
ok, thanks for your feedback. The architecture diagram helps clarifying the wording used in the code.

I could not manage to open a topic on an SQS queue, but I will do more tests. It is likely something wrong in my code.

**Comment by mremond** [comment]
Trying to open a topic on an awssqs:// url, leads to the following error message: `open pubsub.Topic: no provider registered for "awssqs" for URL "awssqs://..."; available schemes: awssns`

That's why I assumed topic where SNS only and Subscriptions only working with SQS.

**Comment by jarlefosen** [comment]
Aha, it seems you are trying to open the topic from the `package pubsub`, which is reasonable. However if the package under `pubsub/awssnssqs` is not imported anywhere, it doesn't register its own topic/subscription schemes.
https://github.com/google/go-cloud/blob/master/pubsub/awssnssqs/awssnssqs.go#L119

Can you try calling the `awssnssqs.OpenTopic(...)` instead of `pubsub.OpenTopic(...)`? Then you'd be sure that the package itself has been imported and the schemes are registered.
https://github.com/google/go-cloud/blob/master/pubsub/awssnssqs/awssnssqs.go#L271

**Comment by eliben** [comment]
@mremond check out the how-to guides for using the CDK pubsub package: https://gocloud.dev/howto/pubsub/

**Comment by mremond** [comment]
@jarlefosen When using OpenTopic on awssnssqs, the API is different (for example require the AWS session) and taking an ARN instead of a URL. When sending the message on opened topic opened on the SQS Queue it is failing with "pubsub (code=InvalidArgument): InvalidParameter: Invalid parameter: TopicArn"

Here is a test code: https://gist.github.com/mremond/070cec748bc42871e801ecdbbb97b434

**Comment by vangent** [comment]
> Trying to open a topic on an awssqs:// url, leads to the following error
> message: `open pubsub.Topic: no provider registered for "awssqs" for URL
> "awssqs://..."; available schemes: awssns`

SNS is the AWS service backing a Go CDK `pubsub.Topic`.
SQS is the AWS service backing a Go CDK `pubsub.Subscription`.

So, if you want to open a `Topic` via a URL, for sending messages, you should use `awssns://` as your URL scheme, and call `pubsub.OpenTopic`. If you want to open a `Subscription`, for receiving messages, you should use `awssqs://` as your URL scheme, and call `pubsub.OpenSubscription`.

https://gocloud.dev/howto/pubsub/publish/#sns has an example.

**Comment by mremond** [comment]
Thanks @vangent, but I would like to send a message on SQS, not SNS.
As I understand it, if I want to receive the content in my SQS subscription I need to publish to the queue.
I tried various combinations of transforming the SQS ARN  to see if there was implicitely an SNS id for an SQS queues, but I could not find a working combination.
So, I do not see a way to publish to an SQS queue using SNS API.

**Comment by vangent** [comment]
Oh, I see -- you are right, it is possible to publish directly to an SQS queue, and it is not possible to do that with Go CDK right now.

It was our understanding that the common deployment model is to set up an SNS topic that publishes to an SQS queue:
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-subscribe-queue-sns-topic.html

Does that work for you? If not, we can look into adding a `pubsub.Topic` implementation that publishes directly to SQS.

**Comment by mremond** [comment]
Hi @vangent, thanks for the feedback.

Going through that doc, it feels that you can indeed subscribe a queue to an SNS topic, but it feels like a bridging or migration option. Earlier in that doc, you have the SQS send for message, that seems to be the primary option: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-send-message.html

And in my case, I cannot use that workaround, as I am using a FIFO queue and the documentation about Subscribing queues to topics states: "Amazon SNS isn't currently compatible with FIFO queues.".

So, I guess, yes, having an option to directly send to SQS seems needed at some point. It may not be easy to add such option while maintaining an API that works with all other providers.

**Comment by vangent** [comment]
Looking at the [SQS API](https://docs.aws.amazon.com/sdk-for-go/api/service/sqs/), it shouldn't be too hard to add a `Topic` implementation for it.

I'll update the title of this issue to reflect that it's requesting a new feature, a `Topic` implementation for SQS.

Thanks for the discussion!
