### ISSUE TITLE
internal/website: visible horizontal scrollbar regardless of window width

### ISSUE THREAD

**Issue by eliben** [google/go-cloud#2033]
On desktop Chrome and Firefox, gocloud.dev has a horizonal scrollbar no matter what width I set the window to.

LMK if you can't see it locally and I'll try to provide more concrete reproduction instructions.

**Comment by zombiezen** [comment]
From debugging, the issue appears to be with scrollbar width subtracting from the `<html>` element width, but then the `.PageLayout` element is exceeding that width. I'll dig in deeper to find out how to account for that.
