### ISSUE TITLE
internal/cmd/gocdk: create processContext logger

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#2038]
There's a variety of places that require synchronous access to writing to stderr/logs. I'm currently using the standard library `log.Logger`, but we likely need to integrate non-log-entry data like raw stdout/stderr from subprocesses in `serve`.

**Comment by zombiezen** [comment]
The requirements for this as I see them:

- It would be ideal to have method(s) on `processContext` that log a message.
- It is desirable to log information to either stdout or stderr. Generally, the guideline is that output that another process may want to parse (e.g. request logs or a URL endpoint for a running server) should be sent to stdout. stderr should be reserved for output that is informational but the format may change.
- For similar reasons, our tests should be able to read stdout after the command has completed.
- We must support concurrent writes to either stdout or stderr, even in an unstructured stream. For example, when running `gocdk serve`, the CLI process and the (up to) two server subprocesses may be trying to write to either stderr or stdout concurrently with each other. I believe it to be acceptable in such cases to interleave lines, but partial lines being interleaved would not be okay.

**Comment by clausti** [comment]
@zombiezen, in your [comment](https://github.com/google/go-cloud/pull/2169#issuecomment-497049381) on @vangent's PR, in response to his comment that "Maybe we should add functions to ProcessContext for Log and Printf and use those everywhere?", you said 

> I'd like to see us address the larger problem rather than trying to optimize individual parts

but I'm not sure I understand if you're saying Robert's suggestion does that or doesn't do that... it didn't seem to me like the suggestion to consolidate logging onto `ProcessContext` says anything one way or the other about latter bullet points on this issue?

**Comment by zombiezen** [comment]
My comment about addressing larger problem was aimed at PR #2169, not the particular statement. I don't see the PR moving us toward any of the bullets above, since it's just one more call site we have to migrate anyway. That was my intent.

I agree with Robert that we should consolidate logging onto `processContext` (that's bullet 1). I think any such effort should also address the other bullets, too.

**Comment by vangent** [comment]
@zombiezen 	how do you see `Logger` fitting in with `stdout` vs `stderr`? Currently we use `Logger` in a bunch of places to insert a timestamp and `gocdk: ` timestamp. That doesn't sound useful for what you've described as `stdout` since it makes the output harder to process. I'm not sure it adds much value for `stderr` either...?
