### ISSUE TITLE
docstore: require opt-in for expensive queries

### ISSUE THREAD

**Issue by jba** [google/go-cloud#2051]
This is a refinement of #1769.

Right now, all providers try to execute all queries. That may result in a table scan or partial query with client-side filtering. (By the latter, I mean handing some filters to the service while doing the rest on the client.)

We return some information about these expensive operations in the query plan, but we need more. (We don't report client-side filtering.)

Also, users are unlikely to look at the plan. So instead, if a query would be expensive, we will return an error and require the user to set an option to enable it. The error text will describe the option.

We'll start with the simple collection options `AllowScans` and `AllowClientFiltering`, but we can fine-tune these to apply only to specific queries. Alternatively, we can put the options on the Query type: `coll.Query().AllowScan()....`.

**Comment by jba** [comment]
#2063 adds an `AllowScans` option to dynamo. The error message for a table scan tells the user to set it. We should actually do better, and suggest an index that will avoid a scan.

**Comment by shantuo** [comment]
And the user would likely know when they should use these options through the some kind of logging, like mentioned in #2004

**Comment by jba** [comment]
They'll know to use these options because the query returns an error. I don't think logging improves on that.

**Comment by vangent** [comment]
> They'll know to use these options because the query returns an error

But that will only happen once (i.e., once they opt in to `AllowScans`, they are opted in for all queries).

Maybe the option should be to allow scans on a specified set of tables?

**Comment by jba** [comment]
> specified set of tables

You pass `Options` on each call to `OpenCollection`, that is, for each table. So the options are already at table granularity.

**Comment by vangent** [comment]
Yes, you are right, sorry. I guess there is not really a good way to 

I still think logging all queries/slow queries (via an option) is a good idea, but that's #2004.

**Comment by jba** [comment]
This is done.
