### ISSUE TITLE
docstore: support query sort order

### ISSUE THREAD

**Issue by jba** [google/go-cloud#2052]
We'd like to support arbitrary sorting of results in queries, like SQL's `ORDER BY` clause. Unfortunately, providers put limitations on sort order:

- MongoDB allows the user to specify arbitrary fields for sorting, both ascending and descending. If no sort order is specified, the ordering is undefined.
  - If an index on the sort fields exists, the query will succeed. 
  - Otherwise, if the result set is less than 32M, the MongoDB server will sort in memory.
     - If there is a limit of _k_, the server will keep only the top _k_ values in memory, and will sort these if they don't exceed 32M.
  - Otherwise, the query returns an error.
- Firestore sorts by document ID if no ordering is specified. Multiple sort fields can be provided,
but it is an error if the first sort field differs from that of the first non-equality query filter. For example, `Query().Where("Score", ">", 100).OrderBy("Player")` is invalid.
- DynamoDB requires that a query specify a table or index with a sort key. It always sorts results by that sort key. There is no way to provide multiple sort keys.

Here is one design that will restrict queries enough to make them portable, provided the appropriate indexes exist:
- A query can have at most one OrderBy clause. (This accommodates DynamoDB.)
- If it has none, the sort order is undefined.
- The field in the OrderBy clause must appear in a Where clause. (With this, we can accommodate Firestore's restriction: we can reorder the Where clauses so the sort field is first.)
- If an index is needed to handle the OrderBy clause and none is provided, the query returns an error describing the needed index.

Other ideas:
- Try to be clever like MongoDB, and sort in memory for small results. I think this is a misfeature: it means query problems are unlikely to show up in testing, and will start hitting in production at unpredictable times.
- Allow more generality (e.g. multiple OrderBy clauses), and fail on providers that can't support it. If we do decide to support this, it should be opt-in so users know they are writing non-portable code.

**Comment by jba** [comment]
@shantuo @vangent @eliben

**Comment by vangent** [comment]
The proposal SGTM.

**Comment by jba** [comment]
This is done, with one caveat: there is no way in DynamoDB to satisfy even the restricted requirements listed above, because scans have no defined sort order. Instead, we built an escape hatch into the driver so the user can handle these queries however they like (for example, reading all the data into memory and sorting).
