### ISSUE TITLE
all: consider making it easier to wrap/compose portable types

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#2053]
#909 is an example of feature request where we want to "wrap" an existing portable type and add some functionality. In that case, the request is to make a `blob.Bucket` that targets a bucket subfolder by adding a prefix to every key (and removing the prefix from returned keys). Other examples might be something like encrypting all data passed to a type and decrypting returned data, adding logging decorators, a `Bucket` that writes to 2 underlying buckets, etc.

Today, this is hard to do because of the concrete portable type. Possibilities include:

1. A user could create their own interface for the parts of the portable type they use, and use that interface everwhere in their code. They can then wrap that interface. For example, `MyBucket` is implemented by `blob.Bucket`, but also by a new type that wraps a `blob.Bucket`. This would add a fair amount of complexity to the user's codebase, and doesn't allow Go CDK to provide a solution, but will work for single user use cases.

2. Go CDK could implement specific wrappers in the portable type itself (e.g, add a `SetPrefix` function to `blob.Bucket`. This is relatively easy to use and to do, but requires Go CDK to implement all wrappers, and adds complexity to the portable type.

3. A user could try to implement the driver interface (e.g., `driver.Bucket`) using an instance of the portable type. This is difficult because the APIs are not the same, and the user would need to reverse things that the portable type is doing before passing them to the driver, which may not even be possible in some cases (e.g., `pubsub/driver.Subscription` has `SendAcks`, but acks aren't exposed in the portable type at all). In composed cases, they might also end up with the multiple layers of the portable type, which is not desirable (e.g., a `pubsub.Topic` based on a `driver.Topic` that is implemented in terms of a `pubsub.Topic` would have 2 layers of batching...).

4. A user could create a new concrete type, e.g. `PrefixedBucket` that wraps `blob.Bucket`. This does not compose well, nor does it work well with `URLOpeners`, and doesn't allow them to use the two types interchangeably.

5. A user could wrap an existing implementation of the driver interface. E.g., implement `driver.Bucket` given an existing `driver.Bucket`. This is pretty natural, although it requires the user to look at the driver interface. Today, this is easy to do inside the Go CDK codebase, but impossible from outside, as the Driver type for a portable type isn't exposed.

If this is something that our users request, 5 above seems like the way to go. We'd have to add a way for a user to get access to the Driver type underlying a portable type (possibly destroying the portable type in the process, to avoid multiple portable types sharing the same driver).

For the example of a `blob.Bucket` that writes to two actual buckets, the process would look something like this:

```
b1, _ := blob.OpenBucket("gcs://mygcsbucket")
b2, _ := blob.OpenBucket("s3://mys3bucket")
b12 := NewDualBucket(b1, b2)
// b1 and b2 are no longer usable; b12 writes to both.

...

func NewDualBucket(b1, b2 *blob.Bucket) *blob.Bucket {
  driver1 := b1.Driver() // b1 is no longer usable after this
  driver2 := b2.Driver() // same for b2
  return blob.New(&dualDriver{driver1, driver2})
}

// type dualDriver implements blob.driver.Bucket using the two drivers.
```

We generally don't want users to use the Driver type, so this is a pointy stick that we've avoided giving them up to now.

For #909, we're going to implement `NewPrefixedBucket` by wrapping the driver, but since we're implementing it inside Go CDK, we can do it without adding any new functions like `bucket.Driver()`.

@zombiezen

**Comment by eliben** [comment]
I agree that we shouldn't encourage (5) in the near-to-mid term, especially given our plans for driver stability vs. user-facing API stability. It seems like we could implement the most commonly needed wrappers as prefixes on our own, so the cases in which the user will need this are going to be rare and (1) should be reasonable.

This is something we should reconsider when the driver APIs will have been empirically stable for some time.

**Comment by jba** [comment]
+1 for (1) (letting the user do it).
