### ISSUE TITLE
server: consider adding OpenCensus TraceID to a response header

### ISSUE THREAD

**Issue by shouichi** [google/go-cloud#2055]
### Is your feature request related to a problem? Please describe.

It would be nice if trace id is returned from server via response header. For example app engine returns it via `x-cloud-trace-context` header.

### Describe the solution you'd like

Write to response header just after starting a span. Around here:

https://github.com/google/go-cloud/blob/1e22a7facf5308a9745c28a92c11fa6818301eb8/server/server.go#L148

### Describe alternatives you've considered

None.

### Additional context

If the suggested solution is fine, I can send a PR with test.

**Comment by vangent** [comment]
I believe you can do this yourself in the `http.Handler` that you pass to `server.New`.

Something like this:

```
import "go.opencensus.io/trace"

...

func (h handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
  span := trace.FromContext(r.Context()) 
  if span != nil {
    traceID := span.SpanContext().TraceID
    w.Header().Set("x-cloud-trace-context", traceID) // or whatever header you want
  }
  ...
}
```

@zombiezen @jba any thoughts on whether we should do this by default?

**Comment by shouichi** [comment]
Yes, that's what we do right now. It would be convenient if setting trace header is handled by go-cloud out of the box. It's not very strange to set the trace header because tracing is always enabled.

**Comment by zombiezen** [comment]
@shouichi My understanding is that `X-Cloud-Trace-Context` is primarily a request header, I don't see official docs for using it as a response header.

@rakyll Are you aware of this behavior? Is this something that most OpenCensus-enabled servers should do?

**Comment by shouichi** [comment]
> My understanding is that `X-Cloud-Trace-Context` is primarily a request header, I don't see official docs for using it as a response header.

You're right. https://cloud.google.com/appengine/docs/standard/go/reference/request-response-headers

However, I tried on an app engine app and got the following response with trace header.

```
❯ curl -I https://gubernator.k8s.io/
HTTP/2 405 
allow: GET
content-type: text/html; charset=UTF-8
x-cloud-trace-context: 6f0c7ec26bcdc3b9b6738c78fca24369
content-length: 188
date: Wed, 15 May 2019 00:29:16 GMT
server: Google Frontend
```

**Comment by vangent** [comment]
Out of curiosity, what do you do with such a response header?

Since it's not obvious that this is of general interest/utility, and there is a way to get the behavior that you want (described [here](https://github.com/google/go-cloud/issues/2055#issuecomment-491886561)), I am inclined to leave this open but assign it to the `Unplanned` milestone. If lots of people express interest in it, we can reconsider whether to do it.

**Comment by shouichi** [comment]
Primary use case in my mind is for bug reports. When a client receives an error, it can report a bug with the received trace id.

**Comment by rakyll** [comment]
AppEngine's behavior is due to the fact it uses a different span model than OC. We don't encourage this model anymore.

@shouichi As soon as the client knows about the trace context of the outgoing request, you can still report a bug associated with the trace context.

**Comment by shouichi** [comment]
In some cases, not all clients send requests with trace context. But I understand the situation, feel free to close this issue. Thank you!
