### ISSUE TITLE
sqlhealth: checker shutdown after successful ping to db

### ISSUE THREAD

**Issue by shouichi** [google/go-cloud#2056]
### Describe the bug

sqlhealth.Checker shutdown (or returns its for loop) after successful ping.

### To Reproduce

1. Start checker.
1. See successful ping once.
1. Checker never pings again.

It returns after successful ping.

https://github.com/google/go-cloud/blob/1e22a7facf5308a9745c28a92c11fa6818301eb8/health/sqlhealth/sqlhealth.go#L57

## Expected behavior

Checker periodically pings database.

In addition, checker's wait time never decreases. Honestly I don't really sure the expected behavior. It would be great if it is clearly documented.

Edited:

Also, Checker.CheckHealth does not check `Checker.healthy` when running.

https://github.com/google/go-cloud/blob/1e22a7facf5308a9745c28a92c11fa6818301eb8/health/sqlhealth/sqlhealth.go#L92

### Version

v0.13.0

### Additional context

None.

**Comment by vangent** [comment]
The docstring does say:

```
// New starts a new asynchronous ping of the SQL database. Pings will be sent
// until one succeeds or Stop is called, whichever comes first.
``

so that does describe what the code is doing. And since it stops after a successful ping, `CheckHealth` looks consistent with that.

@zombiezen can you explain why `sqlhealth.Checker` doesn't keep pinging after a single successful ping? Maybe the docstring could be updated to explain.

**Comment by zombiezen** [comment]
Load balancers typically don't stop sending traffic to an already healthy backend, so keeping the health check to a single healthy ping seems fine in the general case. Otherwise, the server is always sending extra ping traffic to the database server.

@shouichi Can you elaborate more on why you want the health checks to continue?

**Comment by shouichi** [comment]
Oh, I misunderstood the responsibility of checker. I thought checker's responsibility was to check the database connection continuously while server's running. However it seems that the responsibility is to just wait for the database connection to become ready.

Thanks!
