### ISSUE TITLE
tests: add a script with tests that should be run before every release

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#2060]
We have a number of tests that are skipped on Travis because they require interaction with a real Cloud provider. They are runnable manual/locally, sometimes requiring a Terraform file to be run first.

We should create a script that bundles these up, and update our release documentation to indicate that whoever is doing the release should run this script as part of the process to make sure it passes.

Some of the SQL tests fall in this bucket, as does `pubsub/azuresb`.

**Comment by eliben** [comment]
It will be useful to have this before the upcoming release. @vangent assigning to you since you did the last few releases

**Comment by vangent** [comment]
This is done, although a bunch of the tests aren't passing, marked with TODOs. I filed issues for them as well.
