### ISSUE TITLE
internal/gocdk: make `biome.json` a dot file

### ISSUE THREAD

**Issue by clausti** [google/go-cloud#2080]
`biome.json` should be a dot file. All other commands that read from `biome.json` will need to be updated.

**Comment by vangent** [comment]
SGTM if the CLI supports reading/writing configuration that's stored there.

**Comment by zombiezen** [comment]
+1 to idea with Robert's caveat.

**Comment by clausti** [comment]
Sounds good, updated #2081 to make the file name change imperative instead of ??.

**Comment by zombiezen** [comment]
Hm, should we keep this issue open until we've updated the other commands that read/write biome.json?

**Comment by clausti** [comment]
Oh, um.. should we?

**Comment by clausti** [comment]
Ok this issue is now a directive to change the file name instead of "consider".

**Comment by zombiezen** [comment]
This is mutually exclusive with #2326.
