### ISSUE TITLE
internal/gocdk: edit launcher selection with cli command instead of editing file

### ISSUE THREAD

**Issue by clausti** [google/go-cloud#2081]
`biome.json` contains settings that control the behavior of the cli with respect to a particular biome.

These settings should be editable through cli actions instead of the user needing to edit the file. With this change, the file name should be changed to `.biome.json`, see: https://github.com/google/go-cloud/issues/2080.

**Comment by clausti** [comment]
This functionality should be a verb on the `gocdk biome` subcommand, see: https://github.com/google/go-cloud/issues/2082

**Comment by zombiezen** [comment]
This is mutually exclusive with #2326.
