### ISSUE TITLE
internal/cmd/gocdk: dockerfile should use latest version of Go

### ISSUE THREAD

**Issue by clausti** [google/go-cloud#2084]
Observed: 
The `Dockerfile` created in `init` is using Go 1.11

Expected: 
The `Dockerfile` created in `init` should use the most recent release of Go, presently 1.12

**Comment by zombiezen** [comment]
Note: Dockerfile created by init actually contains nothing. My local version of #2099 that I demoed contained 1.11, but this will be fixed when #2099 lands.
