### ISSUE TITLE
server: get hello world working on GAE Standard

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#210]
While `*Server.ListenAndServe` works fine for generic compute environments, it does not work in cases where an alternate listening mechanism is needed, like on Google App Engine Standard, which requires calling `appengine.Main` in place of `http.ListenAndServe`.

To fix this, `*server.Server` should be expanded to include a hook that takes in the wrapped `http.Handler` that `*server.Server` creates as well as the listening address, and then runs the server.  This would also be useful for #57, because in GCP contexts this would be the correct place to attach startup hooks like Cloud Profiler.

**Comment by ijt** [comment]
I got in touch with the maintainer of `go-app-builder` and he does not intend to fix this.

So it looks like apps will have to include a special case in `func main` in order to run on App Engine, at least for now.

**Comment by ijt** [comment]
Reopening after offline discussion with @zombiezen, and retitling to reflect the real goal.

**Comment by ijt** [comment]
The new `go111` runtime now allows using plain old `http.ListenAndServe` so that may mean we'll be able to have a Go Cloud hello world on App Engine with no additional work.

**Comment by vangent** [comment]
Yup, it works.
https://github.com/vangent/go-cloud/tree/appengine/samples/appengine

Not sure this is worth committing since it's such a trivial sample, but it does work.

**Comment by ijt** [comment]
Adding this example would make it clear that this is expected to work, and give users a helpful starting point. I'm in favor of adding it.
