### ISSUE TITLE
pubsub: cost too many CPU

### ISSUE THREAD

**Issue by chaserchen** [google/go-cloud#2103]
When I started my subscriber service, My computer's CPU usage is close to 100%.

I foud this code(https://github.com/google/go-cloud/blob/master/pubsub/pubsub.go#L583) will create goroutine continuously.

I don't think need to create goroutine in this case, And can reduce CPU consumption.

**Comment by vangent** [comment]
Re-opening to follow up on this [PR comment](https://github.com/google/go-cloud/pull/1731#issuecomment-492667163), which points at the 50ms poll loop in the RabbitMQ driver.

**Comment by vangent** [comment]
Hi @chaserchen !

I take it you are using the RabbitMQ implementation of `pubsub.Subscription`?

Are you sure that your CPU resources are being used by this loop? Running a goroutine briefly to check for messages every 50ms should be quite cheap. Some things you could try to verify:

-- Profile your application (https://golang.org/pkg/runtime/pprof/, https://blog.golang.org/profiling-go-programs) and see where the CPU is being used.
-- Use [`gohack`](https://github.com/rogpeppe/gohack) to get a local copy of `gocloud.dev` and try changing the [`maxTime`](https://github.com/google/go-cloud/pull/1731/files#diff-b0e8a1fd7a821fc1ff012c48b12e1e49R566) to something longer, e.g., `500`, and see if that changes anything.

**Comment by vangent** [comment]
Please do be clear about which `pubsub.Subscription` implementation you are using, and include some code snippets for how you use the `Subscription`. Thanks!

**Comment by chaserchen** [comment]
I using RabbitMQ implementation of pubsub.Subscription.
I use this simple example, You can try and watch the CPU usage.

```go
package main

import (
	"context"
	"fmt"

	"github.com/streadway/amqp"
	"gocloud.dev/pubsub/rabbitpubsub"
)

func main() {
	conn, _ := amqp.Dial("amqp://guest:guest@localhost:5672/dos-test")
	subscription := rabbitpubsub.OpenSubscription(conn, "park-permit-event.01", nil)

	ctx := context.Background()
 	for {
		msg, err := subscription.Receive(ctx)
		if err != nil {
			fmt.Println(err)
			break
		}
                fmt.Println(msg.Body)
		msg.Ack()
	}
}
```

**Comment by chaserchen** [comment]
The CPU profile flame svg is: https://github.com/chaserchen/pichub/blob/master/profile-50ms.svg

After change maxTime to 500ms, the CPU consumption is significantly reduced, and the CPU profile flame svg is: https://github.com/chaserchen/pichub/blob/master/profile-500ms.svg
