### ISSUE TITLE
testing: helper tool to summarize test results

### ISSUE THREAD

**Issue by eliben** [google/go-cloud#2110]
Followup on #2039 to track the final state we'd like to be in.

The default `go test` doesn't report how many tests were skipped, and we had some issues before with tests being skipped when they shouldn't have been. Therefore, we'd like to have a helper tool that will summarize test results.

Instead of running `go test` in our modules, we'll run a script which will invoke `go test -json` piped into a program that:

1. Incrementally reads stdin to produce similar output to `go test` - we want to see progress, which test executes, how long it took, outputs from tests, etc.
2. At the end, produces a summary specifying how many tests ran, skipped, passed, failed

**Comment by eliben** [comment]
@jba assigning to you, since you mentioned in #2039 you want to keep working on it. I can do that too, if you're overloaded with other stuff.

**Comment by jba** [comment]
I'll do it after I'm done preparing tomorrow's talk.

**Comment by vangent** [comment]
This is done and working nicely.
