### ISSUE TITLE
tests: runchecks should do more in the loop over modules

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#2117]
Currently it does a bunch of stuff for the root module, and then loops over additional modules as an afterthought.

When we have more sub-modules, we'll want to do things like get coverage for them, etc.

It will be cleaner to have a single loop over modules, where we do all the things, and then some additional things that only apply to the top-level (not module specific).

**Comment by eliben** [comment]
Also related: #2111

**Comment by vangent** [comment]
Blocked by #2111.
