### ISSUE TITLE
blob/all: Create New Bucket

### ISSUE THREAD

**Issue by zanes2016** [google/go-cloud#2128]
Is there a way to create a new bucket (specifically interested in GCS) on a cloud provider? I see that blob.NewBucket exists, but then states that it should not be used. I'm a little confused about this.

**Comment by vangent** [comment]
No, there is not. 

We have purposely tried to stay away from the provisioning space; we are focused on developers using resources, not operators provisioning them. There's some discussion here:
https://github.com/google/go-cloud/blob/master/internal/docs/design.md#developers-and-operators

There are plenty of other toolkits (e.g., Terraform) for provisioning resources.

`blob.NewBucket` isn't creating a new Bucket resource, it's creating a new `*blob.Bucket` struct for connecting to an existing resource, given a `blob.Driver`. It's not intended for use outside of driver implementations; we tried to make that clear in the godoc ("NewBucket is intended for use by provider implementations").

If somebody were writing an application that dynamically created buckets and used them, that might be a reason for us to add a new API for that, but we're very hesitant to get into that space.

Hope that helps clarify.
