### ISSUE TITLE
internal/cmd/gocdk: re-tag and publish image to GCR as part of Cloud Run launch

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#2130]
### Is your feature request related to a problem? Please describe.

The Cloud Run launcher takes in a Docker image reference as input and it [must be accessible to the Cloud Run service](https://cloud.google.com/run/docs/deploying#images). The two ways to do this are either by having an image in Google Container Registry (GCR) or on a public Docker registry like Docker Hub (but only allowed when running Cloud Run in Kubernetes Engine).

In order to push a local Docker image to GCR, the Docker image needs to be [tagged with one of the `gcr.io/` prefixes](https://cloud.google.com/container-registry/docs/pushing-and-pulling#tag_the_local_image_with_the_registry_name). The Dockerfile we generate in init deliberately uses a vendor-neutral tag, and the Docker image may be used in several different contexts, so it would be nice to avoid polluting the biome-independent Docker image with biome-dependent Docker tags.

### Describe the solution you'd like

When the Cloud Run launcher runs, the Docker image passed to Cloud Run should be the first of:

1. If the launch specifier contains an `image_name` argument, that will be used. `gocdk launch` should return an error if the `image_name` does not start with one of the `gcr.io/` prefixes.
2. If the image name provided to `gocdk launch` starts with one of the `gcr.io/` prefixes, then it will be used directly.
2. Otherwise, `gcr.io/PROJECT_ID/` will be prepended to the image name given, where `PROJECT_ID` is the project given in the launch specifier `project_id` parameter.

When executing the launch, if the image reference given to `gocdk launch` does not have the same name as the one chosen above, then `gocdk launch` will re-tag the image given to `gocdk launch` with the desired `gcr.io/`-based image name on the local Docker daemon, then push the image from the local Docker daemon to GCR. This assumes the user has already [configured `gcloud` as a Docker credentials helper](https://cloud.google.com/container-registry/docs/advanced-authentication).

### Describe alternatives you've considered

As mentioned above, we could kludge around this by making the Dockerfile magic comment include a gcr.io prefix, but I'd rather avoid that to keep the user's application image free of vendor prefixes. (e.g. in the case where they want to launch on multiple clouds).

### Additional context

This is a follow-up to [#2106](https://github.com/google/go-cloud/pull/2106#discussion_r284441333).

**Comment by clausti** [comment]
This sounds good to me.
