### ISSUE TITLE
docstore: limit ongoing RPC's when necessary

### ISSUE THREAD

**Issue by shantuo** [google/go-cloud#2133]
When running benchmarks against the DynamoDB backend, I got errors like:
```
at XXX: RequestError: send request failed
        caused by: Post https://dynamodb.us-east-2.amazonaws.com/: dial tcp: lookup dynamodb.us-east-2.amazonaws.com: no such host;
```

I think this is because we have too many open request when doing the plenty of unordered actions. I'm running on macOS, which has a relative small default file descriptor limit so this is relatively easy to trigger.

**Comment by jba** [comment]
Are we really dialing a TCP connection for every RPC? Is there a way to keep connections alive for a while?
