### ISSUE TITLE
prerelease: Terraform scripts for various GCP tests fail with Error 403

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#2138]
Running https://github.com/google/go-cloud/blob/master/internal/testing/prereleasechecks.sh, I was unable to get the Terraform scripts for `mysql/cloudmysql`, `postgres/cloudpostgres`, `tests/gcp` to work; they all failed with `"Error 403: The caller does not have permission, forbidden".`

**Comment by vangent** [comment]
Marking this as P1 at least to triage; since we can't run the tests, we don't know if things are actually working.

**Comment by zombiezen** [comment]
Triage results: project name was used instead of project ID. I believe this should fix the issue: spot-checked that this fixed the Terraform setup for `mysql/cloudmysql`.
