### ISSUE TITLE
docstore/mongodocstore: use Find for unordered gets

### ISSUE THREAD

**Issue by shantuo** [google/go-cloud#2143]
Benchmark numbers for 50-get actions:
```
BenchmarkConformance/BenchmarkActionListGet-8           200	  10493466 ns/op
```

I experimented with using `Find` and an `$in` filter, the number is:
```
BenchmarkConformance/BenchmarkActionListGet-8          2000        565110 ns/op
```

The performance boosted from ~10 ms to ~0.5 ms, plus we don't need to manage plenty of single get requests.

There are some problems I still need to figure out:
1. Find takes an option with field paths selections, which means if the user wants different field paths, one Find results cannot fulfill that request.
   - We can split into groups by requested field paths. I suspect the user would likely to write those gets in a loop and the field paths would be the same. So this approach doesn't look that bad than what it appears to be.
   - We can request all field paths and decode later. If we go with the previous assumption, this would be wasting the effort.
   - We can simply give up and fall back to use single gets when we found those gets are not towards the same set of field paths.
1. The find will return a cursor and we need to match the documents with the order the user requests.
   - We can create a list with indices of the actions sorted by the IDs and pass the same order option into Find, then map the order to the original action list.

cc @jba  @vangent

**Comment by jba** [comment]
Nice!

I'd go with 1a (split into groups by field path). Like you said, most of the time there would be one.

For 2, I'd just create a map from id to document, then as you read each result, get the document from the map and decode into it.
