### ISSUE TITLE
all: create GitHub contribution linter

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#216]
It would be useful to have a GitHub bot that enforces/auto-suggests some of the non-code things in CONTRIBUTING.md. In particular:

- [ ] Issue title format
- [ ] PR title format
- [ ] Commit message format (one line summary, "Fixes" on last line of description)
- [ ] License headers in new files
- [ ] Branches are in a fork, not on the main repository

This can use the [checks API](https://developer.github.com/changes/2018-05-07-new-checks-api-public-beta/) to present the information as well as some limited support for auto-fixing, like the license headers.

**Comment by zombiezen** [comment]
I'm going to set up the authentication and deployment parts of this, which aren't blocked on go-github.

**Comment by tbpg** [comment]
google/go-github#913 is fixed/merged.

**Comment by zombiezen** [comment]
For this issue, I am planning to create a minimal event worker server that will remove the "In Progress" label from any closed issues. I will open issues for the other desired checks.
