### ISSUE TITLE
gcp: provide another way to pass credentials when use URLOpener

### ISSUE THREAD

**Issue by felipeweb** [google/go-cloud#2160]
Some apps receive the credentials in bytes and need to create a file and set `GOOGLE_APPLICATION_CREDENTIALS`.

I'd like to see another way to pass credentials when I'm using URLOpener

**Comment by felipeweb** [comment]
One solution that I can see is to add one more query param to pass them.

Is that solution good enough to start?

**Comment by vangent** [comment]
Hi @felipeweb,

Why can't you set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable directly, as described here?
https://cloud.google.com/docs/authentication/getting-started#setting_the_environment_variable

It sounds like you are proposing a new query param, what would the query param value be?

**Comment by felipeweb** [comment]
I am thinking in a new param `credentials_path` following the same principals of `private_key_path`

**Comment by felipeweb** [comment]
@vangent  I can't set `GOOGLE_APPLICATION_CREDENTIALS` my company have some restriction about this environment variable usage in non containerized applications

**Comment by vangent** [comment]
Can you put the credentials file where `FindDefaultCredentials` is looking for it?
https://godoc.org/golang.org/x/oauth2/google#FindDefaultCredentials

(probably `$HOME/.config/gcloud/application_default_credentials.json`)

@zombiezen thoughts on adding `credentials_path`? IIRC, we originally had it and removed it for some reason.

**Comment by vangent** [comment]
We could add a function `DefaultCredentialsFromURL` to the `gcp` package, which would look for a `credentials_file` query parameter and load creds from there if found, defaulting to the existing `DefaultCredentials`, and then update all of the `URLOpener`s for GCP to call the new function. A wrinkle is that we'd have to make sure that the `URLOpener`s don't error out for an "unknown query parameter"; maybe add a `func UsedQueryParam(p string) bool` or some such to `gcp`...?

**Comment by zombiezen** [comment]
We opted not to add a `credentials_file` parameter initially because the Application Default Credentials scheme is fairly well-established in GCP land and we want to prefer passing such credential information in environment variables. The private key file is only there for signing URLs, but a case could be made that that should be passed via environment variable, too.

The concession we made is that it is always possible to construct a `URLOpener` that uses custom credentials, and the explicitness is desirable in these cases. Otherwise, we end up having to create API surface for every combination of provider-specific options for credentials.

**Comment by zombiezen** [comment]
Hey @felipeweb! Sounds like you figured out something that worked for you.. I am curious about something you said before:

> I can't set `GOOGLE_APPLICATION_CREDENTIALS` my company have some restriction about this environment variable usage in non containerized applications

Can you give any more details about this restriction? If this is a common restriction, we should probably think about how we should address it.

**Comment by felipeweb** [comment]
@zombiezen  An agent running on all our vms use this variable, so in non containerized apps we can't use this variable
