### ISSUE TITLE
all: add Packet support

### ISSUE THREAD

**Issue by vielmetti** [google/go-cloud#219]
Similar to #76 (add Azure support), add support for Packet.

The relevant existing library is https://github.com/packethost/packngo the `packngo` library for the Packet API in Go.

**Comment by zombiezen** [comment]
Thanks for your interest in Go Cloud! We don't have the bandwidth to support Packet right now, but see the [README](https://github.com/google/go-cloud/blob/master/README.md#project-status) for information about how you can contribute an implementation of the Go Cloud interfaces for Packet.
