### ISSUE TITLE
internal/cmd/gocdk: `biome add` flag for specifying launcher

### ISSUE THREAD

**Issue by clausti** [google/go-cloud#2217]
The `biome add` command should have a flag allowing the user to specify a launcher.

**Comment by clausti** [comment]
I think the design doc says this should be an optional flag and default to `local`, but we could make it required instead? I don't know if silently defaulting to local is actually the most desired behavior @zombiezen @vangent

**Comment by zombiezen** [comment]
Prompting the user interactively when no flags are given seems correct for this command to me. Adding a biome is relatively infrequent and the question set is different depending on the answer to the initial question, thus suggesting a more interactive "wizard" experience.
