### ISSUE TITLE
internal/gocdk: automate moving terraform state file to cloud

### ISSUE THREAD

**Issue by clausti** [google/go-cloud#2218]
If multiple developers are working on the same codebase and deploying to the same non-local biome, they also need to share a terraform state file to avoid provisioning problems/duplication/clobbering. `gocdk` could prompt the user to do this when they first `biome add` with a cloud launcher.

**Comment by zombiezen** [comment]
Doc links for the future taker of this bug: the command should use [Remote State](https://www.terraform.io/docs/state/remote.html) and configure a [backend](https://www.terraform.io/docs/backends/index.html).
