### ISSUE TITLE
internal/gocdk: make it possible to use gocdk without using Terraform

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#2236]
I.e., imagine a user that already has resources provisioned in the Cloud, so they don't need us to do it for them. They still want to be able to run their application locally (`gocdk serve`), possibly against local resources or possibly against Cloud-based ones (configured via URL). They still want to be able to have multiple biomes and to launch their application.

At least we'll need to:
* Add a flag that causes `gocdk` to read from an arbitrary JSON file instead of from outputs.tf (for things like launcher parameters, environment variables for the application, etc.).
* Make sure that there's a way to disable the `terraform` commands that we normally run (e.g., `terraform apply`).

**Comment by zombiezen** [comment]
We decided not to do this because it would potentially be introducing multiple configuration languages, which is more confusing. We should add an FAQ entry for this at some point.
