### ISSUE TITLE
all: add Joyent Triton support

### ISSUE THREAD

**Issue by SamWhited** [google/go-cloud#224]
Please consider adding support for [Joyent Triton] ([Go SDK])

[Joyent Triton]: https://www.joyent.com/
[Go SDK]: https://godoc.org/github.com/joyent/triton-go

**Comment by zombiezen** [comment]
Thanks for your interest in Go Cloud! We don't have the bandwidth to support Joyent Triton right now, but see the [README](https://github.com/google/go-cloud/blob/master/README.md#project-status) for information about how you can contribute an implementation of the Go Cloud interfaces for Joyent Triton.
