### ISSUE TITLE
all: change copyright to "contributors" 

### ISSUE THREAD

**Issue by SamWhited** [google/go-cloud#225]
Please consider changing the copyright from "Copyright Google LLC" to "Copyright The Go Authors" (or the "go cloud authors" or similar) like the Go core project and subrepos. This more broad shared copyright with an authors/contributors file is one of the reasons I am comfortable contributing to Go and I would like to see future Go projects continue to use it.

Thank you.

**Comment by zombiezen** [comment]
Understood. We were following [the Google Open Source policy](https://opensource.google.com/docs/releasing/contributions/#copyright) for the initial release. Now that we have external contributors, we will add an [AUTHORS file](https://opensource.google.com/docs/releasing/authors/), but we want to ensure that we do it in a way that's compatible with the overall Go project. Stay tuned.

**Comment by zombiezen** [comment]
Copyright has been updated to "The Go Cloud Authors". This will be enforced by the check in #318; exact design is under review at #321.
