### ISSUE TITLE
internal/gocdk: add k8s launcher

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#2258]
### Is your feature request related to a problem? Please describe.

Users that have an on-premise Kubernetes (k8s) cluster or a hybrid/multi-cloud environment (like that set up by the [GKE on-prem](https://cloud.google.com/gke-on-prem/) aspect of [Anthos](https://cloud.google.com/anthos/)) may want to use the `gocdk` CLI to launch their applications into their cluster.

### Background

`gocdk` launchers can be thought of as a process that takes in:

- A reference to a Docker image (like `myproject:latest`) present in the local Docker daemon
- The set of environment variables that must be set when running the container
- Launcher-specific parameters in the format of a JSON object. `gocdk biome add` will prompt the user to fill in any required fields.

A launcher is responsible for pushing the Docker container to a registry as appropriate and then making any calls needed to the launch target's control plane to run the server with the environment variables given.

### Describe the solution you'd like

In keeping with the CLI's design philosophy, a solution to this would produce a "reasonable default" [deployment spec](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/) with a minimum of prompts from the CLI to the user. A common scenario is one where the person wanting to deploy a job to a k8s cluster is not the same person who set up the k8s cluster. The `gocdk` CLI should assume a minimum of knowledge.

The hurdles I see are as follows:

- Private registry location
- Which scaling parameters to expose and how to expose them
- Whether to use `k8s.io/client-go` or `kubectl`
- How to [authenticate to k8s](https://kubernetes.io/docs/reference/access-authn-authz/authentication/)

While I think this could be achieved, it would require a serious amount of effort to keep it up to the user experience bar we've set for the other launcher implementations.

#### Private Registry Location

For the Cloud Run launcher, we know ahead of time that the only place the Docker images is Google Container Registry (`gcr.io`). For an arbitrary k8s cluster, we don't know where to place images. We likely don't want to have them be public, so this implies using a private registry, but we do not know a priori what this setting is going to be. Thus, we probably need to prompt the user.

Further reading: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

#### Scaling Parameters to Expose

The selling point of k8s is being able to set scaling parameters and have k8s manage the orchestration to machines for you. While for simple cases, 1 replica may suffice, the user will quickly want to start using the sort of controls that k8s gives them and this presents a problem: do we wrap these constructs ourselves or present them wholesale to the user? Presumably this would be part of the launch specifier, but then we would be asking users to use HCL to generate a deployment spec, where the common language is YAML.

I suspect that the answer to this will end up being that `gocdk add biome` would create a reasonable default k8s deployment YAML file in the biome and that the launch specifier would somehow read in parts of that to use.

Further reading: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/ and https://github.com/ashald/terraform-provider-yaml

#### Whether to use `k8s.io/client-go` or `kubectl`

This is a relatively minor point, but another concern is how we want to make calls to the k8s control plane, whether in-process or shelling out to `kubectl`. I see the tradeoff to be that if we use the client library, we're on the hook to push new versions of `gocdk` when there's a new k8s, but if we shell out to `kubectl`, it's one more dependency that the user has to install to be productive.

#### How to authenticate to k8s

Related to the previous points, we also need to be correctly authenticated to the k8s apiserver in order to deploy the target. We will not know how to do that a priori, and must rely on the user to provide the correct credentials, without much guidance we can give if they get it wrong.

Further reading: https://kubernetes.io/docs/reference/access-authn-authz/authentication/

**Comment by vangent** [comment]
> * A reference to a Docker image (like `myproject:latest`) present in the local Docker daemon
> * The set of environment variables that must be set when running the container
> * Launcher-specific parameters in the format of a JSON object. `gocdk biome add` will prompt the user to fill in any required fields.

Is the last one necessary? Or, at least, is it necessary that the set of parameters is complete? The launcher can encapsulate whatever parameters it needs to set, and if it's easy to configure launchers, then the user can configure distinct launchers for each biome.

This is why I'm pushing for the "exec" module of integration for launchers instead of a Go interface, similar to what we've seen for how IDEs integrate with tools. If the user can configure a launcher by providing a path to something to exec, and we pass the Docker image reference and the set of environment variables (mechanism TBD), then they can do everything else. For example, a biome could be configured to launch using a custom shell script that pushes the docker image to a private repo, configures whatever scaling parameters they want, and pushes using `kubectl` via whatever authentication method they have on their machine. Go CDK just execs that shell script with the docker image and the env.

Whether we do this for all launchers, or just as an integration point for custom launchers is a separate question.

**Comment by zombiezen** [comment]
> Is the last one necessary? Or, at least, is it necessary that the set of parameters is complete?

It is not necessary that the set of parameters is complete; it is expected that launchers will gather credentials and other service-specific global settings from other sources. I do think it's important that settings specific to launches in that biome are encapsulated in the biome.

> The launcher can encapsulate whatever parameters it needs to set, and if it's easy to configure launchers, then the user can configure distinct launchers for each biome.

I don't understand this.

> This is why I'm pushing for the "exec" module of integration for launchers instead of a Go interface, similar to what we've seen for how IDEs integrate with tools. If the user can configure a launcher by providing a path to something to exec, and we pass the Docker image reference and the set of environment variables (mechanism TBD), then they can do everything else. For example, a biome could be configured to launch using a custom shell script that pushes the docker image to a private repo, configures whatever scaling parameters they want, and pushes using `kubectl` via whatever authentication method they have on their machine. Go CDK just execs that shell script with the docker image and the env.
> 
> Whether we do this for all launchers, or just as an integration point for custom launchers is a separate question.

I think I'm going a step beyond to [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy): "Expect the output of every program to become the input to another, as yet unknown, program." I think we've already established a project structure that allows someone to create a custom launcher by reading the same data we're reading. In the long run, I think that is more flexible and can permit launches in more automation than placing the `gocdk` CLI as a bottleneck for arranging the input to be passed in.

**Comment by vangent** [comment]
Let's chat in person, I'm not sure we are understanding each other well.
