### ISSUE TITLE
sample/tutorial: gcsblob.NewBucket func does not exist

### ISSUE THREAD

**Issue by jnhk** [google/go-cloud#227]
When following sample/tutorial:
```go
// GCP auth section
return gcsblob.NewBucket(ctx, bucket, c)

// AWS auth section
return s3blob.NewBucket(ctx, s, bucket)   
```
I found that `gcsblob.NewBucket` function does not exist. This should be changed to `gcsblob.OpenBucket` instead.

[Edit] From my observation,  a call to `OpenBucket` in AWS will attempt to create a bucket if it doesn't exist, whereas a call to `OpenBucket` to a non-existent bucket in GCP would result in `Error 404: Not Found`. So it seems to me that the "ideal" `NewBucket` has not been implemented yet.

**Comment by zombiezen** [comment]
Thanks for the find! And yes, `OpenBucket` should not be creating a bucket. Can you file a separate issue for that incorrect behavior?
