### ISSUE TITLE
all: Add Scaleway support

### ISSUE THREAD

**Issue by remyleone** [google/go-cloud#228]
Similar to #219 #76 

https://github.com/nicolai86/scaleway-sdk

**Comment by zombiezen** [comment]
Thanks for your interest in Go Cloud! We don't have the bandwidth to support Scaleway right now, but see the [README](https://github.com/google/go-cloud/blob/master/README.md#project-status) for information about how you can contribute an implementation of the Go Cloud interfaces for Scaleway.

**Comment by displague** [comment]
@zombiezen Are there plans to abstract more of the cloud provider interface than buckets and databases? As in, something more akin to [Fog](https://fog.io/) or [LibCloud](https://libcloud.apache.org/)?

**Comment by vangent** [comment]
Scaleway is S3-compatible, so the s3blob driver should work.
