### ISSUE TITLE
docstore/firedocstore: convert non-string name field to string if possible

### ISSUE THREAD

**Issue by shantuo** [google/go-cloud#2297]
### Is your feature request related to a problem? Please describe.

The Firestore driver returns an error when the name field is not a string, while other drivers don't have that requirement.

### Describe the solution you'd like

Convert the name field to a string is possible, otherwise return an InvalidArgument error.

**Comment by jba** [comment]
You can do this by providing a namefunc. I will clarify that in the doc.
