### ISSUE TITLE
gcp: project id may be empty

### ISSUE THREAD

**Issue by broady** [google/go-cloud#2298]
I was just doing some code reading, one correctness issue:

https://github.com/google/go-cloud/blob/ad670b9f06d5fb56a2fcf62a729b02e7083c841e/gcp/gcp.go#L86-L92

ProjectID may be empty, even if Credentials is non-nil:

https://github.com/golang/oauth2/blob/0f29369cfe4552d0e4bcddc57cc75f4d7e672a33/google/default.go#L24-L25

In practice, this happens when 3-legged OAuth credentials are used. For example, via the `gcloud auth application-default` command set.

**Comment by zombiezen** [comment]
Quite true, but the intent for this function is to be used in simple(-ish) Wire injection scenarios where the user is specifying that the project ID comes from the credentials. If they want a more sophisticated behavior (e.g. taking from a flag), then they shouldn't use this function.

In practice, I think this function will be less relevant now based on the decision made in #1860: most IDs coming from flags should include the project ID as part of the string passed to the constructor.

**Comment by zombiezen** [comment]
Closing this out since I haven't heard anything back.

**Comment by broady** [comment]
+1 to #1860.
