### ISSUE TITLE
firedocstore: constructor should take a single resource string

### ISSUE THREAD

**Issue by jba** [google/go-cloud#2312]
According to https://github.com/google/go-cloud/blob/master/internal/docs/design.md#compound-ids, constructors should take a single string denoting the resource.

The actual Google Cloud Firestore resource string would be `projects/$PROJECT/databases/(default)/documents/$COLLECTION`. If I understand the design doc right, the `OpenCollection` function would take this string, and we could provide a helper function (named what?) that would take a project ID and collection and return this string. So one would write
```
firedocstore.OpenCollection(client, firedocstore.ResourceString(projectID, collPath), ...)
```
which seems like quite a mouthful.

Alternatively, `OpenCollection` could accept the string `$PROJECT/$COLLECTION`. That seems more reasonable, but I don't know if it satisfies the design rule.

**Comment by jba** [comment]
@zombiezen @vangent

**Comment by vangent** [comment]
Yes, `OpenCollection` should take `projects/$PROJECT/databases/(default)/documents/$COLLECTION` and we should provide a helper to construct that from the pieces (isn't `default` dynamic too?).

The `URLOpener` should also have that string in it, e.g., `firedocstore://projects/$PROJECT/databases/(default)/documents/$COLLECTION`.

**Comment by jba** [comment]
`(default)` is hardcoded. There is only one database per project, for now at least.

`gcppubsub.Open{Topic,Subscription}` don't do this, by the way. They should be changed before we go beta.

I don't see any functions anywhere that build a full resource string from components. Do we have a naming convention? If not, any suggestions? `CollectionPath`, maybe?

I noticed the pubsub URLs accept abbreviations with just project/topic or project/subscription. Should docstore URLs do the same?

**Comment by vangent** [comment]
> `gcppubsub.Open{Topic,Subscription}` don't do this, by the way. They should be changed before we go beta.

Ah, but they do! https://godoc.org/gocloud.dev/pubsub/gcppubsub#OpenSubscriptionByPath.

We left the previous constructors as-is to avoid breaking backwards compatibility.

> I don't see any functions anywhere that build a full resource string from components. Do we have a naming convention? If not, any suggestions? `CollectionPath`, maybe?

https://godoc.org/gocloud.dev/secrets/gcpkms#KeyResourceID
https://godoc.org/gocloud.dev/runtimevar/gcpruntimeconfig#VariableKey

> I noticed the pubsub URLs accept abbreviations with just project/topic or project/subscription. Should docstore URLs do the same?

I don't think so; those abbreviations are there for backwards compatibility.

**Comment by jba** [comment]
> We left the previous constructors as-is to avoid breaking backwards compatibility.

We're not even beta yet. We shouldn't be that worried about being compatible.
