### ISSUE TITLE
docstore: try to support atomic writes or transactions

### ISSUE THREAD

**Issue by jba** [google/go-cloud#2333]
Docstore providers differ widely on how they support transactions:

- [Firestore](https://cloud.google.com/firestore/docs/manage-data/transactions): all reads must happen before all writes.
- MongoDB:  Full transactions as of v4.0, nothing prior to that.
- DynamoDB: up to 10 atomic reads, or up to 10 atomic writes. There is a [Java library](https://aws.amazon.com/blogs/aws/dynamodb-transaction-library/) for transactions, but the [design](https://github.com/awslabs/dynamodb-transactions/blob/master/DESIGN.md) shows that it requires cooperation from others to avoid reading uncommitted writes.
- CouchDB: no support.

We should think about whether we want to provide some non-portable support. For example:
- Transactions with gets before writes (MongoDB 4.0, Firestore)
- Atomic writes, limited to 10 (MongoDB 4.0, Firestore, DynamoDB)

**Comment by shantuo** [comment]
> Atomic writes, limited to 10 (MongoDB 4.0, Firestore, DynamoDB)

Sounds reasonable, but neither DocumentDB nor Cosmos DB is compatible with MongoDB 4.0 yet.
