### ISSUE TITLE
internal/gocdk: reconsider the apply/launch/deploy command structure

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#2336]
* It's hard to remember the difference between `launch` and `deploy` (`deploy` does `build`, then `apply`, then `launch`).
* Should they be subcommands of `gocdk biome`?
* Maybe instead of multiple commands, it should be one command with flag(s)? E.g., `gocdk deploy --nobuild` or `gocdk deploy --launchonly`).

**Comment by zombiezen** [comment]
A rough sketch that @clausti, @vangent, and I whiteboarded this command set:

```
gocdk build
gocdk biome apply BIOME
gocdk deploy --image=<image_ref> [--apply=false] BIOME
```
