### ISSUE TITLE
mysql/postgres: reconsider package names

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#2357]
E.g., maybe `cloudsql` should be `gcpcloudsql`.

https://github.com/google/go-cloud/blob/master/internal/docs/design.md#package-naming-conventions

**Comment by zombiezen** [comment]
I think the GCP Cloud databases are the only ones that need changing. I'm thinking `cloudmysql` should be `gcpmysql` (the product name isn't too strong here). I'll make this change once the dust clears from #1175.

**Comment by polinasok** [comment]
According to https://cloud.google.com/sql/docs/, it is Google Cloud SQL for MySQL and Google Cloud SQL for PostgreSQL, so if we want to keep them as separate APIs, it makes sense to go with Ross' suggestion and use gcpmysql and gcppostgresql.

I would also suggest change rds to aws for consistency.
Amazon RDS for MySQL (https://aws.amazon.com/rds/mysql/) => awsmysql
Amazon RDS for PostgreSQL (https://aws.amazon.com/rds/postgresql/) => awspostresql

**Comment by zombiezen** [comment]
From meeting this morning: the decision is to make both the s/cloud/gcp/ and s/rds/aws/ changes for the SQL packages.
