### ISSUE TITLE
internal/gocdk: consider renaming "provision" command

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#2360]
Maybe "resource" would be better? "provision add" is two verbs, and the command doesn't actually provision, it just sets up Terraform files that will provision later.

**Comment by vangent** [comment]
@zombiezen @clausti 

Are you OK with renaming `provision` to `resource`?

**Comment by clausti** [comment]
Is the proposal to replace `provision add` with `resource add` or just `resource`?

**Comment by vangent** [comment]
the former. so, `resource list` would be another command.

**Comment by clausti** [comment]
Yeah, then I'm in favor of s/provision/resource.

**Comment by zombiezen** [comment]
+1
