### ISSUE TITLE
internal/website: add how-to guide for runtimevar

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#2365]
Follow-on from #1576.

The `runtimevar` package is missing a how-to guide. The guide should walk the user through:

- Opening a runtime variable on various providers
- Encoding/decoding concerns
- Watching for changes synchronously
- Fetching the latest value from a variable

As per @vangent's request, this is marked as P1/beta-blocking.

**Comment by zombiezen** [comment]
Also: it's important for all guides, but especially for `runtimevar`, to explain what the purpose of the package is (i.e. reading dynamic configuration data). How-to guides should be framed in terms of solving a user's problem, not in terms of the solution we have.

**Comment by eliben** [comment]
Fixed by #2384
