### ISSUE TITLE
all: highlight URL openers over constructors in package descriptions

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#2387]
Thanks @polinasok for the find!

Current documentation for the portable API packages (e.g. https://godoc.org/gocloud.dev/blob) start with a recommendation like:

> use its exported function(s) to create a *Bucket; do not use the NewBucket function in this package.

and then further down:

> Alternatively, you can construct a *Bucket via a URL and OpenBucket. See https://gocloud.dev/concepts/urls/ for more information.

New users should use URL openers, which is what we are recommending in our how-to guides. To fix this issue, we should rewrite the package documentation introductions to either:

a) Highlight the URL openers and deemphasize the constructors, or
b) Just point to the how-to guides, which already do this.

**Comment by eliben** [comment]
:+1: 

Just ran into this with docstore. https://godoc.org/gocloud.dev/docstore starts by saying:

> Your application should import one of these provider-specific subpackages and use its exported functions to create a *Collection; do not use the NewCollection function in this package.

Which is most definitely *not* what we should be recommending to users to try initially. Reducing duplication with the how-to would also be good
