### ISSUE TITLE
internal/website/content/howto: s/ctor/constructor/ in anchor links

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#2388]
> If `vault-ctor` is the fragment link, I have the tiniest of nits, which is that `-constructor` would be both clearer and easier to remember for all of them, and there's not really any reason not to?

_Originally posted by @clausti in https://github.com/google/go-cloud/pull/2386_

Would need to update across all current how-to guides and potentially references in code. Bonus points if the existing anchors are preserved because [cool URIs don't change](https://www.w3.org/Provider/Style/URI).

**Comment by clausti** [comment]
I made the comment because they looked like new additions in that PR. If it's more work than that it doesn't matter that much.

**Comment by eliben** [comment]
Yeah I noticed this in other how-tos too. Since "ctor" is a fairly common abbreviation in languages that have constructors (like C++), I'd vote to leave it as-is. There's merit in keeping URLs short too :-)

**Comment by clausti** [comment]
@eliben, it being common in languages like C++ means its usage isn't off-putting to people who have experience in such languages, but it might be to people who've never encountered it.  Like I said originally and above, it's a small detail and not a big thing, but it is an instance us signaling who we think our docs are "for".
