### ISSUE TITLE
blob: support walking through paths

### ISSUE THREAD

**Issue by dhowden** [google/go-cloud#241]
Currently there is no way to read through paths in a blob store (i.e. to iterate over all paths in a bucket or under a particular path, equivalent to `filepath.Walk` in the std lib).   This is maybe stretching the idea of a "blob store" and so might sit better somewhere else, but S3 and GCS have methods which implement this, and the functionality is very useful.

Are there plans to implement this in go-cloud?

Context: we have a storage-abstraction library which we're now planning to migrate to go-cloud instead of maintaining our own bridges to different platforms (https://github.com/sajari/storage/pull/5).  Our library also implements path-walking which we have found very useful, but as yet there is no equivalent for go-cloud that we can see :) (https://github.com/sajari/storage/blob/master/walk.go).

**Comment by zombiezen** [comment]
Curious, what sort of guarantees do you need from visiting the blobs? The reason that `Bucket` currently doesn't support a "list" operation is that there's quite a bit of variance between cloud providers on what they offer (consistency, etc.).  From what we've seen, most devs who need this type of functionality build a secondary index in a more strongly consistent datastore.

**Comment by dhowden** [comment]
We typically use this functionality to perform idempotent operations on each object in a bucket (tools/background-processes that aggregating information, perform transformation etc...), so an eventual-consistency guarantee has been sufficient for us. 

If implemented, the relevant API methods should include info detailing that the call is based on an (potentially) eventually-consistent data source, which is unfortunate. Understandable if this is a deal-breaker for inclusion.

**Comment by buchanae** [comment]
We also have a [storage library](https://github.com/ohsu-comp-bio/funnel/tree/master/storage) which we'd like to see shared/normalized/eliminated by a larger community. Ours has stat and list.

Eventual consistency is acceptable for us. It seems better to have the lowest common denominator than to have nothing.

Side note, the term "walk" might not fit object/blob storage where directories are not a first class concept.

**Comment by JohnEmhoff** [comment]
We have a similar need -- our data is effectively write-once, read-many, where attributes of an object are stored in a key with a prefix of the owning object's key. Eventual consistency would be fine for us.

**Comment by smaxwellstewart** [comment]
+1

**Comment by zombiezen** [comment]
Summarizing some offline discussion with @ijt, @neild, and others: if/when we do this, we should probably give the operation a name like `InconsistentList` (even for backends that support strong consistency) so that it clearly communicates expectations.

**Comment by vangent** [comment]
- S3 has [ListObjects](https://godoc.org/github.com/aws/aws-sdk-go/service/s3#S3.ListObjects)
  - Takes a Prefix, MaxKeys (int64, page size), and Marker (string, starting point).
  - There's a helper for iterating through pages of results via [ListObjectsPages](https://godoc.org/github.com/aws/aws-sdk-go/service/s3#S3.ListObjectsPages)
- S3 also has [ListObjectsV2](https://godoc.org/github.com/aws/aws-sdk-go/service/s3#S3.ListObjectsV2) which looks pretty similar.
- GCS has [Objects](https://godoc.org/cloud.google.com/go/storage#BucketHandle.Objects)
  - Takes a prefix.
  - Returns an iterator, which returns a [PageInfo](https://godoc.org/google.golang.org/api/iterator#PageInfo) you can use for pagination.
- Azure has [ListBlobs](https://godoc.org/github.com/Azure/azure-sdk-for-go/storage#Container.ListBlobs)
  - Takes Prefix, Marker, MaxResults.
- For all three, you can specify a Delimiter in the request, which does some kind of pretend-it's-a-directory thing that I don't understand yet.

**Comment by zombiezen** [comment]
The delimiter allows you to treat the key space semi-hierarchically. For example, if you had the following blobs:

- `foo`
- `bar`
- `baz/quux`
- `baz/fido`

And you did a list with empty prefix with the slash delimiter, you would get back `foo`, `bar`, and `baz/` (the API makes some indication that `baz/` is a dummy entry).

**Comment by vangent** [comment]
This is done except for exposing `As` for `List`, and except for `Delimiter` support, tracked separately in #541 and #542.
