### ISSUE TITLE
docstore/memdocstore: MaxOutstandingActionRPCs makes no sense for memdocstore

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#2411]
https://godoc.org/gocloud.dev/docstore/memdocstore#Options

**Comment by jba** [comment]
The name may be wrong, but why does it make no sense?

**Comment by vangent** [comment]
Because `memdocstore` doesn't make any RPCs?

**Comment by jba** [comment]
(I knew I'd written this down somewhere!)

So change the name.

**Comment by vangent** [comment]
I ended just changing the name to drop `RPCs` as jba@ suggested.
