### ISSUE TITLE
docstore: provide a way to serialize revisions

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#2414]
Currently `RevisionField` must be of type `interface{}`.

Imagine a use case where I'm writing a web app to allow users to edit a document. I read the document, display a form with the current values of the fields, and do a `Replace` operation when the form is POSTed.

Today, I think the only two ways to achieve that are:
1. Keep an in-memory map of `key` -> `interface{}` for revisions; this requires sticky sessions of some kind.
2. Re-fetch the document as part of the POST action, and just always clobber the document, basically ignoring revisions.

If `RevisionField` were a string, or at least serializable in some way, it could be stashed in a hidden form field.

For `blob`, we had a similar issue for `PageToken`; different providers used different types. We represented that as a `[]byte`, and made each provider serialize/unserialize as needed. For `blob`, the page token wasn't exposed to the end user though.

**Comment by jba** [comment]
If we actually made the revision field a `string` or `[]byte`, then every operation would have to pay the cost of encoding/decoding it, and (worse) a user couldn't get the real value to use with an escape hatch.

Two alternatives:
1. Make it of type `docstore.Revision`.
    - Its `Value` method returns the original value, for use with escape hatches.
    - Its `String` method returns a `string`.
    - That string can be parsed back into a `Revision` with `Collection.ParseRevision`. 

2. Keep it as `interface{}`, but add `Collection.RevisionToString` and `Collection.RevisionFromString` methods.

The second is simpler, but the first uses the type system better. In particular, there is no way for the user to create a `Revision`, so the user can't mistakenly (or deliberately) pass a bad one into the package.

**Comment by jba** [comment]
We'll do the second.
