### ISSUE TITLE
docstore: provide better error message when Get fieldpaths have wrong case

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#2415]
I have a struct with a field `Key`.

When I do a `Get` and pass it `xxxx` as a field path, I get a good error message, something like: `no field matching xxxx`.

When I do the same with `key`, I get:
`cannot set type string to <nil>`

Why the difference?

**Comment by shantuo** [comment]
I think this is intended and follows the Go rules, like in `encoding/json`. Our godoc says "Match looks for an exact match first, then falls back to a case-insensitive comparison", in the second case, it got a match, you got the error because of the type mismatch.

**Comment by vangent** [comment]
What type mismatch?

**Comment by shantuo** [comment]
It looks like the `key` is a string type but it got a `nil`? Can I see your example? It might be a bug in somewhere else in the decoder.

**Comment by vangent** [comment]
Try adding this to `memdocstore/mem_test.go`:

```
type MyDoc struct {
        Key string
        Value string
        DocstoreRevision interface{}
}

func TestWrongKey(t *testing.T) {
        ctx := context.Background()

        coll, err := OpenCollection("Key", nil)
        if err != nil {
                t.Fatal(err)
        }
        defer coll.Close()

        doc := MyDoc{Key: "foo", Value: "testvalue"}
        if err := coll.Create(ctx, &doc); err != nil {
                t.Fatal(err)
        }

        getdoc := MyDoc{Key: "foo"}
        if err := coll.Get(ctx, &getdoc, "Value"); err != nil {
                t.Fatal(err)
        }
        if getdoc.Value != "testvalue" {
                t.Errorf("got %v want %v", getdoc.Value, "testvalue")
        }

        err = coll.Get(ctx, &getdoc, "BadKey")
        t.Log(err)

        err = coll.Get(ctx, &getdoc, "value")
        t.Log(err)
}
```

and then run with `-v`. I get:

```
--- PASS: TestWrongKey (0.00s)
    mem_test.go:86: no field matching "BadKey" in memdocstore.MyDoc (code=InvalidArgument)                                                           
    mem_test.go:89: cannot set type string to <nil> (code=InvalidArgument)
```

The first error looks fine.
The second error is weird. It's not obvious where the `nil` is coming from, it's the same document that worked above.

**Comment by shantuo** [comment]
The driver's decoder find the match but the memdocstore doesn't do the same.

**Comment by shantuo** [comment]
Actually, I was wrong. I think the second one should also be an error, we could improve the error message.

**Comment by jba** [comment]
@shantuo can you explain why the error happens in the second `Get` above?

**Comment by shantuo** [comment]
Because the driver decoder considers the `value` as a match to `Value`, and then passes to the mem decoder, which [doesn't return an error](https://github.com/google/go-cloud/blob/master/docstore/memdocstore/mem.go#L367) when looking up the path `value` in the document but cannot find. The error we get here is because it tries to [decode](https://github.com/google/go-cloud/blob/master/docstore/memdocstore/codec.go#L114) a `nil` into a string.

I think the behavior should be changed to that `Match` only matches exact case since the other providers won't match for wrong cases anyways.

**Comment by jba** [comment]
OK, I see.

The problems with matching field names exactly are:
- It doesn't match `encoding/json`'s behavior. We can't really advertise that users can just use their structs that have `json` struct tags without modification. In fact, we probably shouldn't allow `json` tags at all.
- It might cause problems for our MongoDB driver, which has casing issues of its own. See https://github.com/google/go-cloud/blob/master/docstore/mongodocstore/mongo.go#L103. I haven't thought carefully about what would happen if we went to exact matching, or if we could fix it.

We should also explore the other direction: what would it take to make each of our drivers support decoding case-insensitive field names?

**Comment by shantuo** [comment]
The providers won't do a case-insensitive matching for those projections, in this case they will not return anything for `value`.

**Comment by jba** [comment]
OK, let's go with exact match, except for mongo when `Options.LowercaseFields` is true. Wherever we talk about supporting `json` tags, we should make it clear that our decoding behavior differs from `encoding/json`.

I noticed that Firestore doesn't give an error if you ask for fields that don't exist. So I think we have to have that behavior for all providers, and we should document and test it.
