### ISSUE TITLE
docstore/memdocstore: revision field doesn't seem to work

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#2417]
Maybe I'm missing something. It's unclear to me if this is an issue with `memdocstore` or all providers.

I have a struct like this:

```
type MyDocument struct {
        Key              string
        Value string
        DocstoreRevision interface{}
}
```

1. I open a collection with the URL `mem://mycollection/Key`.
2. I create a new document by calling `Create`.
3. I `Get` the document by key; the `%v` of the `DocstoreRevision` field says "1".
4. I `Replace` the document by creating a new `MyDocument`:

```
doc := MyDocument{Key: key, Value: "newvalue"}
if err := collection.Replace(req.Context(), &doc); err != nil {
  ...
}
```

I was expecting this to fail because I didn't set the `DocstoreRevision` field, but it happily succeeded.

**Comment by shantuo** [comment]
I think this is allowed because we 1) couldn't tell whether there is a revision for the document at all and 2) we didn't enforce using the revision logic. If we are going with the new design as discussed in #2308 , we should be able to check for missing revision field.

**Comment by jba** [comment]
The rule up to now has been to check the revision field if a revision is present. In this case the revision field is nil, hence not present.

We could insist that if the argument to Replace has a revision _field_, then it must have a _revision_. But what about Put? You can use Put to create a new document, so we can't insist that the revision be present.

I think I'm okay with the stronger rule for Replace. My main concern is whether there is a use case for "blind Replace," where you know the document exists but you don't care what its revision is. I guess we can implement the stronger rule and see if a blind-Replace use case comes up.

There's still the question of what happens with structs that have no revision field. Maybe it's reasonable that you can't use Replace with those structs at all.

**Comment by jba** [comment]
And what about Delete? You certainly want blind Deletes. You often know that something should be removed regardless of its current revision.

Maybe it's better for consistency if we keep the behavior of Replace, so it matches Put and Delete.

**Comment by vangent** [comment]
RE "blind replace": do the providers support that? Do they default to revision checking, or no revision checking?

**Comment by jba** [comment]
Most providers don't even know what a revision is. We do it for them. So they allow blind everything. 

The exception is CouchDB, which requires the revision for both [Replace](http://docs.couchdb.org/en/stable/api/document/common.html#put--db-docid):

>  When updating an existing document, the current document revision must be included in the document...

and [Delete](http://docs.couchdb.org/en/stable/api/document/common.html#delete--db-docid):

> You must supply the current (latest) revision...

I don't think we want to hold our semantics hostage to that, though. But we do need to allow it, so maybe the docs should say "some providers may require a revision."
