### ISSUE TITLE
docstore/memdocstore: use the current time as a revision field

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#2419]
It's a number, and for the first document it starts at 1, which led me to interpret it (visually) as the revision number of the document. But it looks like it's actually a collection-wide counter, not a per-document counter.

Probably a timestamp or something would be less misleading.

**Comment by jba** [comment]
It's an implementation detail. You're not supposed to interpret it.

**Comment by jba** [comment]
I guess if it really bothers you, it would be easy enough to change this to a time, though it would require a check to avoid re-using the same time.

**Comment by jba** [comment]
Good starter issue. Requires familiarity with the [time package](https://godoc.org/time), especially monotonic time.

**Comment by vangent** [comment]
Or just start with a random number?

**Comment by eliben** [comment]
> Or just start with a random number?

It's not clear what the problem we're trying to solve here is. Is it that revision is a monotonically increasing integer starting with 1? If it started with 2029190 that would be less confusing? Monotonic timestamp is fine, as long as it never wraps around
