### ISSUE TITLE
docstore: move tests to conformance tests, or document why they are provider-specific

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#2422]
E.g., `memdocstore` has tests called `TestUpdateEncodesValues` and `TestUpdateAtomic`. These sound like they should be conformance tests for all providers, not `memdocstore` specific. If I'm wrong, they should explain why they are provider-specific.

**Comment by jba** [comment]
For `TestUpdateEncodesValues`, I'm not sure that every driver will blind-decode an int to an int64, so I don't know how general that test is.

For `TestUpdateAtomic`, note that the doc for update says "It is undefined whether updating a sub-field of a non-map field will succeed.". This test assumes it will not succeed. I suppose we could add a boolean function to the harness so we can run this test only on drivers where it fails.

**Comment by polinasok** [comment]
memtest still has 4 tests: `TestUpdateEncodesValues`, `TestUpdateAtomic`, `TestSortDocs`, `TestSaveAndLoad`. Tuo will continue with `TestUpdateEncodesValues`, and I will take on the other 3, moving them to conformance test or adding comments if they cannot/should not be moved.

**Comment by shantuo** [comment]
There are dynamo-specific tests around query plans and I will add comments to them.

**Comment by jba** [comment]
@polinasok Tuo and I already had conversations about those tests. I think they were on a PR.

The atomic one is hard to move because it depends on undefined behavior (that _is_ defined for memdocstore).

SaveAndLoad tests a feature specific to memdocstore.
