### ISSUE TITLE
samples/guestbook: requires 9 CPUs, GCP free account only provides for 8 CPUs...

### ISSUE THREAD

**Issue by kjothen** [google/go-cloud#244]
Hi - could the sample be modified to run within the free account constraints?

europe-west2

* google_container_cluster.guestbook: googleapi: Error 403: 
	(1) Insufficient regional quota to satisfy request for resource: "IN_USE_ADDRESSES". The request requires '9.0' and is short '1.0'. The regional quota is '8.0' with '8.0' available.
	(2) Insufficient regional quota to satisfy request for resource: "CPUS". The request requires '9.0' and is short '1.0'. The regional quota is '8.0' with '8.0' available., forbiddenool, automatically filled out bug template!

**Comment by ijt** [comment]
Sure, I'll give it a shot.

**Comment by ijt** [comment]
I poked at it a bit but kept getting confusing errors from terraform, so I guess I'm too unfamiliar with terraform to be of much help with this right now. Maybe @shantuo or someone else?

**Comment by shantuo** [comment]
The guestbook app should be available for free account user. It requires 3 CPUs and 1 address. One possible situation is that you have some old instances and addresses that's not deleted. For example, one may create a GKE cluster with services and then only delete the cluster. The address may become unassociated with any cluster but still exist. Could you try to remove these resources or try from another project?

**Comment by kjothen** [comment]
I shutdown my existing projects and created a new project. Everything works. I did have to get the vgo package and install clang for the deploy.sh script to run. Thanks for investigating and clarifying the resource requirements.
