### ISSUE TITLE
docstore: Query for nil FieldPath value

### ISSUE THREAD

**Issue by Inuart** [google/go-cloud#2450]
We are trying to query for documents that don't have a specific field in them.

I expected this to be written like `coll.Query().Where("deleteTime", "=", nil).Get(ctx, "_id")` but `nil` seems to be an invalid value.

Alternatively, querying for a `"=" time.Time{}` or `"<=" time.Time{}` doesn't provide any results.

Is this currently possible?

**Comment by jba** [comment]
It's not currently supported, but it's a reasonable feature request. We have to make sure we can do it portably first. We'll look into it.

**Comment by shantuo** [comment]
Only MongoDB has the ability to do such queries. If we are going to support it, it will be a table scan for firestore and dynamodb.

You could either:
1. Create another field like `isDeleted`.
2. Use `Colleciton.As` to directly use MongoDB's collection if you're using MongoDB.

**Comment by Inuart** [comment]
Table scan you mean filtered on the client?

**Comment by shantuo** [comment]
Yes, unfortunately, both firestore and dynamodb's queries are based on an index, and it is not possible to index on a field that is NOT in the document.

**Comment by jba** [comment]
Another way to make it portable would be to store the field with every document, using a special "missing" value for documents that normally wouldn't have the field at all.
