### ISSUE TITLE
docstore/mongodocstore: lowercaseFields should be more portable

### ISSUE THREAD

**Issue by shantuo** [google/go-cloud#2456]
We have a `lowercaseFields` in `mongodocstore`'s construct options. It converts all the field names to lower cases to match the official go mongo library (https://godoc.org/go.mongodb.org/mongo-driver/mongo)

However it loses some portability on the portable API level, for example, if we have a struct like:
```go
type Foo struct {
    ID string
    N int
    S string
}
```

and we want to read a document into `Foo` with a set of field paths, 
normally we'd do:
```go
collection.Get(ctx, dsc, "N", "S")
```

but in the lowercase mode we'd write:
```go
collection.Get(ctx, dsc, "n", "s")
```

I think we should always do the first case and convert that only when writing to the db. This might result in double encoding I don't know, we'll need to figure out how not to distinguish this case too much.

The second problem, which is a side effect, is that it also convert the keys for map types, which is different than what the mongo Go client does. I think this one is a bug.

cc @jba

**Comment by jba** [comment]
I agree that using the uppercase names in the portable API should work even in lowercase mode.

> The second problem, which is a side effect, is that it also convert the keys for map types, which is different than what the mongo Go client does. I think this one is a bug.

Can you give a specific example?

**Comment by shantuo** [comment]
If you do
```go
dc, _ := newCollection(db.Collection("lowercase-fields"), "id", nil, &Options{LowercaseFields: true})
coll := docstore.NewCollection(dc)
coll.Put(ctx, map[string]interface{}{"id": 1, "Num": 2})
```

It results in the db as:
```
> db.getCollection("lowercase-fields").find()
{ "_id" : NumberLong(1), "num" : NumberLong(2), "docstorerevision" : "06a0c2d0-4791-48c7-a597-dadfd3dd5377" }
```

**Comment by jba** [comment]
What happens if you do the same with the official Go mongo driver?

**Comment by shantuo** [comment]
The official Go mongo driver doesn't lower map keys.
