### ISSUE TITLE
internal/gocdk: go.mod installed by gocdk needs to be updated as part of the release process

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#2466]
@eliben 

Our release process involves updates all `go.mod` files for modules in our repo to use `replace` directives for `gocloud.dev` with relative paths during development, and then removing them and updating the `requires` for `gocloud.dev` to the release we're about to tag.

We need to do something similar for the [`go.mod`](https://github.com/google/go-cloud/blob/master/internal/cmd/gocdk/internal/static/_assets/init/go.mod) file built into the `gocdk` CLI. Currently I have been manually updating the `requires` line to point to specific commits as breaking changes are made, but that's not sustainable or reliable.

Two complications:

1. I'm not sure what we could use as a `replace` path, because we don't know where the user will run `gocdk` to instantiate their project.

2. `go generate` has to be run in `internal/cmd/gocdk` after updating that `go.mod` file, as it is compiled into the binary.

For now, we can do this manually as part of the release process.

**Comment by eliben** [comment]
It's not clear what we can do about this. Presumably for future users this should point to the latest released version of the Go CDK, which shouldn't be hard to build into the release instructions? We won't want it to point to specific commits anyway

**Comment by zombiezen** [comment]
The next steps for this issue is to automate this process. The difficult part is to find out what `replace` directive should go in the go.mod file.
