### ISSUE TITLE
internal/website: reconsider blob how-to section "Prefixed Buckets"

### ISSUE THREAD

**Issue by polinasok** [google/go-cloud#2510]
https://gocloud.dev/howto/blob/open-bucket/#prefix
Comment from @vangent: "I think we can drop this section and just leave it in the godoc. Thoughts?"
Originally posted in https://github.com/google/go-cloud/pull/2495/commits/ff6e56cbd16bd7788cbb6886ee1aadbe46aabde4_

**Comment by vangent** [comment]
IMHO this is a relatively unusual use case and doesn't warrant a whole section in the "How To". It should either be 

a) reduced to a sentence or less (e.g., something like "You can also wrap a *blob.Bucket to always operate on a subfolder of the bucket using blob.PrefixedBucket." where `blob.PrefixedBucket` there is a link to the godoc.

or 

b) removed entirely (and just in godoc)
