### ISSUE TITLE
internal/gocdk/tests: update record/replay tests to use internal/testing/cmdtest

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#2516]
@jba have you already started with this? I'd like to get it in soon since I'd like to add some tests that require `stdin`. If you haven't, or if you have something that requires a lot of work or merging to get done, please assign back to me and I can do it.

**Comment by jba** [comment]
I have it. I was waiting for the dust to settle on the others, but that may not be until after I get back from vacation (Wednesday), so I'll make the PR for this today.

**Comment by jba** [comment]
Fixed by #2524.
