### ISSUE TITLE
blob/s3blob: OpenBucket creates S3 bucket?

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#252]
From @jhnk in #227:

> From my observation, a call to OpenBucket in AWS will attempt to create a bucket if it doesn't exist, whereas a call to OpenBucket to a non-existent bucket in GCP would result in Error 404: Not Found. So it seems to me that the "ideal" NewBucket has not been implemented yet.

I have not verified this behavior myself, but keeping this issue open to make sure that we follow up.

**Comment by shantuo** [comment]
S3 client library doesn't have OpenBucket, it has an explicit [CreateBucket](https://godoc.org/github.com/aws/aws-sdk-go/service/s3#S3.CreateBucket) which creates a bucket. When you give a non-existent bucket name to uploader it will not create that bucket.

**Comment by zombiezen** [comment]
@shantuo Can we close this out?
