### ISSUE TITLE
internal/gocdk: add a demo for SQL

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#2535]

**Comment by zombiezen** [comment]
@vangent, it would helpful to expand on this issue.

**Comment by vangent** [comment]
The idea is to add a simple demo similar to the existing ones for `blob`, `pubsub`, etc., that uses a Go CDK URL for `mysql` and/or `postgres` and demonstrates some simple functionality. The demo would probably need to install a simple schema and run on top of that.

**Comment by vangent** [comment]
Plays nice with #2536.
