### ISSUE TITLE
internal/gocdk: add provisioning for SQL resources

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#2536]

**Comment by zombiezen** [comment]
@vangent, you should add more detail to this issue.

**Comment by vangent** [comment]
`gocdk resource add postgres/awspostgres`  or `gocdk resource add mysql/gcpmysql` for example. Similar to other `resource add` commands, they would add Terraform files to the project to provision the appropriate database with the appropriate provider, and output a Go CDK URL to connect to it. Plays nice with #2535.
