### ISSUE TITLE
internal/gocdk: use project name instead of "gocdk" in random name

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#2546]
### Is your feature request related to a problem? Please describe.

The Terraform local `gocdk_random_name` added automatically into the biome uses "gocdk" as a prefix, which does not help in identifying the purpose of a particular resource in the cloud console without other context.

### Describe the solution you'd like

The generated local should use the project's name (the base name of the module root) as the prefix instead of the generic "gocdk".

**Comment by vangent** [comment]
Related: #2561.
