### ISSUE TITLE
all: bash scripts won't run without bash, e.g., in Windows PowerShell

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#257]
We want the samples to run anywhere Go runs.

Bash scripts won't run without additional fiddling within the Windows PowerShell:
https://stackoverflow.com/questions/1098786/run-bash-script-from-windows-powershell

I suggest we convert the locally used scripts to Go so they run everywhere Go Cloud does.

```
$ find . -name \*.sh
./tests/gcp/test.sh
./internal/testing/checkpr.sh
./samples/guestbook/gcp/deploy.sh
./samples/guestbook/gcp/provision-db.sh
./samples/guestbook/localdb.sh
./samples/guestbook/aws/provision-db.sh
```
It may be fine to skip converting checkpr.sh since it is mostly intended to be run from Travis CI, but it would also be inconsistent and possibly set an unportable precedent. Our best bet may be to keep it simple and only use Go for scripting within this project.

Downsides mentioned by @zombiezen:
1. Go is more verbose for this sort of scripting than bash, although I would counter that it may be more readable, especially for gophers
2. go run doesn't return the error code returned by the script. This is technically true, but go run does at least exit zero or non-zero according to the exit code of the script, and that is probably fine for most uses.

**Comment by zombiezen** [comment]
We also need to consider interaction with Terraform here: does Terraform always run `go run` for every invocation, etc.

**Comment by ijt** [comment]
@zombiezen, yes I believe Terraform will have to use `go run` for this.

**Comment by enocom** [comment]
I'm in favor of this idea.

There will be some gotcha's with this work, but converting scripts to Go makes more of the code accessible to a Go developer while making the scripts more readable. Those are good things.

If we don't like the result, reverting back to bash isn't too hard either.

**Comment by ijt** [comment]
I'm a bit stuck on this bit:

~/src/github.com/google/go-cloud/tests/aws$ time go run test.go $gcpid ~/.ssh/id_rsa.pub

tests/aws/test: 2018/08/15 17:35:20 region not provided, default to us-west-1
tests/aws/test: 2018/08/15 17:35:20 Building test app...
tests/aws/test: 2018/08/15 17:35:20 Provisioning AWS resources...
tests/aws/test: 2018/08/15 17:35:20 run([terraform init -input=false .])
tests/aws/test: 2018/08/15 17:35:21 run([terraform apply -auto-approve -input=false -var app_binary=/tmp/go-cloud-aws-test990066980/app -var gcp_project=aws-this-account-is-1525908917 .])

Error: Error applying plan:

1 error(s) occurred:

* aws_instance.app: timeout - last error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

**Comment by ijt** [comment]
I got to a different error by doing this:
```
issactrotts@issactrotts2:~/src/github.com/google/go-cloud/tests/aws$ ssh-add ~/.ssh/id_rsa
```
Now it fails like this:
```
2018/08/15 20:20:22 startApp:cannot get key from file: ssh: no key found
exit status 1
FAIL    github.com/google/go-cloud/tests/aws/app        0.075s
tests/aws/test: 2018/08/15 20:20:22 Tearing down AWS resources...
tests/aws/test: 2018/08/15 20:22:31 running [vgo test -v -args --gcp-project aws-this-account-is-1525908917 --aws-region us-west-1 --host-ip 52.53.162.242 --key-path /home/issactrotts/.ssh/id_rsa.pub]: exit status 1
```

**Comment by ijt** [comment]
I tweaked the error message in `tests/aws/app/app_test.go` to show the ssh key path and it reported this:
```
2018/08/15 20:36:03 startApp: cannot get key from file /home/issactrotts/.ssh/id_rsa.pub: ssh: no key found
```

**Comment by ijt** [comment]
Now I'm trying again to get `tests/gcp/test.go` to work. Here's what happened:

```
~/src/github.com/google/go-cloud/tests/gcp$ go run test.go gocloud-212523
tests/gcp/test: 2018/08/15 21:50:04 Provisioning GCP resources...
tests/gcp/test: 2018/08/15 21:52:31 Making sure vgo image is built...
tests/gcp/test: 2018/08/15 21:52:33 Building app binary with vgo...
WARNING: This command group is deprecated. Please use `gcloud builds`
instead.
WARNING: This command is deprecated. Please use `gcloud builds submit`
instead.
Creating temporary tarball archive of 386 file(s) totalling 2.1 MiB before compression.
Some files were not included in the source upload.

Check the gcloud log [/home/issactrotts/.config/gcloud/logs/2018.08.15/21.52.34.054539.log] to see which files and the contents of the
default gcloudignore file used (see `$ gcloud topic gcloudignore` to learn
more).

Uploading tarball of [../..] to [gs://gocloud-212523_cloudbuild/source/1534395154.12-695b80e304664ec981ca2512ecdd71c0.tgz]
Created [https://cloudbuild.googleapis.com/v1/projects/gocloud-212523/builds/dfec118a-34cf-4608-a22d-289098696cd7].
Logs are available at [https://console.cloud.google.com/gcr/builds/dfec118a-34cf-4608-a22d-289098696cd7?project=1044323297833].
ERROR: (gcloud.container.builds.submit) Name expected [
          table(
            id,
            createTime.date('%Y-%m-%dT%H:%M:%S%Oz', undefined='-'),
            duration(start=startTime,end=finishTime,precision=0,calendar=false,undefined="  -").slice(2:).join(""):label=DURATION,
            build_source(undefined="-"):label=SOURCE,
            build_images(undefined="-"):label=IMAGES,
            status
          )
         *HERE* 'value(id)'].
tests/gcp/test: 2018/08/15 21:52:40 Tearing down GCP resources...
tests/gcp/test: 2018/08/15 21:54:43 running [gcloud --quiet --project gocloud-212523 container builds submit --async --format='value(id)' --config app/cloudbuild.yaml --substitutions _IMAGE_NAME=gcr.io/gocloud-212523/gcp-test,_VGO_IMAGE_NAME=gcr.io/gocloud-212523/vgo ../..]: exit status 1
exit status 1
```
