### ISSUE TITLE
all: please consider add a random prefix like "spm" to all the last part of the import path.

### ISSUE THREAD

**Issue by bronze1man** [google/go-cloud#258]
When you have a very large project, you will get a lot of packages with the same last part of the name:
## packages named "driver":
* "database/sql/driver"
* "github.com/google/go-cloud/blob/driver"
* "github.com/google/go-cloud/runtimevar/driver"

## Or packages named "aws":
* "github.com/aws/aws-sdk-go/aws"
* "github.com/google/go-cloud/aws"

The problem is that:
* When you need import them in the same file, you must alias them.
* The ide intellij idea will popup a window to ask you to choose to import which packages even if you only import one of them.
* The same package name will decrease the readability of the code.

So I suggest add a simple random prefix like "spm" to the last part of the import path will avoid conflict.

**Comment by zombiezen** [comment]
As per the [guidance on Go package names](https://blog.golang.org/package-names), we try to avoid same package names when they are likely to collide. One package is unlikely to implement multiple drivers, so I think that one is fine.

The `aws` case is a bit more subtle: the two packages usually aren't imported together, as the Go Cloud package is imported to provide values, whereas the AWS one is usually used in consumers of these types. I would rather that we pick a more meaningful name for this package than adding a prefix for the sake of it.
