### ISSUE TITLE
internal/gatherexamples: make comment signifiers more clear & explicit

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#2582]
From discussions with @polinasok on https://github.com/google/go-cloud/pull/2534:

* `// Ignore unused variables in example:` actually drops everything under it, so that could be more explicit.
* Since the comments are visible in godoc, all of them should probably explain that (e.g., "Hide variable set up in gocloud.dev examples" or maybe a prefix like "Auto directive" or "gatherexamples directive" or "gatherexamples rewrite").

Maybe a more general purpose
`// Start omit in gocloud.dev examples` to ``End omit in gocloud.dev examples`?

**Comment by vangent** [comment]
Also consider trimming trailing whitespace lines.

**Comment by zombiezen** [comment]
(I know I'm lurking; feel free to ignore.) One other thing to consider: these comments will show up in the gddo example rendering, which is why I intentionally made them human-readable. I think explicit markers have merit, but make sure they don't communicate something confusing to the gddo reader.
