### ISSUE TITLE
docstore: all checks for keys should be checking for empty value

### ISSUE THREAD

**Issue by shantuo** [google/go-cloud#2589]
It currently checks for `nil` only, for example
```go
doc := map[string]interface{}{"key": ""}
```
should be treated as missing key as well.

We currently only does empty value check in firestore since it requires string type for name field, we should do this in the portable API ideally.

**Comment by jba** [comment]
We should also document that you can't use zero-valued keys.

I'm a little concerned that we can't support an empty key in a map. It's possible that someone needs that. But I think it's probably better that we start by returning an error, and see if anyone complains.
