### ISSUE TITLE
docstore/mongodocstore: add support for querying slice values

### ISSUE THREAD

**Issue by Inuart** [google/go-cloud#2606]
We are trying to do geospatial queries with docstore.

In mongo there's a `$geoWithin` feature that is optimised for this cases, but (as far as I know) coordinates need to be stored as an array in the document. So our collection stores coordinates in this manner.

Currently there is no way to select a single list element on a FieldPath, so queries like `Where("position.coordinates[0]", ">=", longitude` are not working.

A part from fetching all documents and discarding the unsuitable ones afterwards, what would an available workaround look like?

**Comment by jba** [comment]
Of course, there's always the escape hatch of using `Collection.As` to get at the mongo client directly. That is your best bet today.

We should consider adding the '[N]' syntax to our field paths. I'm not sure if all providers support it, though.

**Comment by vangent** [comment]
Another alternative might be to denormalize the coordinate(s) you need to query to another field in the document (assuming that it's a small subset). E.g., store `position.coordinates[0]` as `position.longitude` and query on that.
