### ISSUE TITLE
docstore: Query.Update should retry on revision check failure

### ISSUE THREAD

**Issue by jba** [google/go-cloud#2611]
Split off from #2458 

Non-mongo implementations of Query.Update should retry documents that fail a revision check. 

For example, say the call
```
Query().Where("Score", ">", 100).Update(ctx, docstore.Mods{"Score", 100})
```
returns 100 documents. During the update of those documents, three fail because their revisions have changed. The driver should retry those three.

That involves either repeating the query (narrowed, preferably, to the keys of the failed documents), or retrieving the documents by key and evaluating the filters on the client.

We also need to consider what happens if a document is deleted between the time it is retrieved and updated.

**Comment by shantuo** [comment]
The current API is hidden by #2637 , add them back when this is done.
