### ISSUE TITLE
internal/cmd/gocdk: init should create a go.sum file

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#2618]
### Describe the bug

`gocdk init` does not create a go.sum file when first creating the project. This causes problems when running `gocdk build`, because the Dockerfile expects the file to exists.

### To Reproduce

1. `gocdk init foo`
2. `cd foo`
3. `gocdk build` (this will crash)

### Expected behavior

Build works, but perhaps not verifiable. (I think an empty go.sum would likely be fine.)

### Version

master (1d5466654942d3ec020d239e97666bc5fe60acaa)

**Comment by vangent** [comment]
Should `gocdk build` run a `go build` first?

**Comment by zombiezen** [comment]
The smallest possible fix would be to have `gocdk init` generate an empty go.sum file. `gocdk build` could run `go list ./...` at the module root, which I think would cause the dependencies to fetched and recorded.

**Comment by vangent** [comment]
What's the down side of just running `go build` as part of `gocdk build`? IIUC, it would create the `go.sum` file (so `gocdk init` wouldn't have to change), and it also helps identify compile errors much more quickly. E.g.,:

1. Create a project from scratch (`gocdk init foo && cd foo`)
2. `touch go.sum` (to work around this bug)
3. Edit `main.go` to introduce a compile error
4. `time gocdk build`

-->

```
# foo
./main.go:17:2: undefined: xhttp
The command '/bin/sh -c go build -o foo' returned a non-zero code: 2
Error: gocdk build: docker build: exit status 2
user	0m1.407s
```

vs

1. Create a project from scratch (`gocdk init foo && cd foo`)
2. Edit `main.go` to introduce a compile error
3. `time go build`

-->
 
```
# foo
./main.go:17:2: undefined: xhttp
user	0m0.621s
```

(and `go.sum` now exists).

**Comment by zombiezen** [comment]
The `go build` would waste time in the successful compile case, since its compile and link work (other than the go.sum changes) would be thrown away. The Docker build will issue another `go build` anyway, and while @clausti and I brainstormed a few ways to reuse results, neither of us were convinced that we could do so in a way that would a) work in cloud build scenarios or b) affect the reproducibility of the build.

That said, you could likely get at the same compile errors more quickly. by running the type-checker (i.e. `go/packages`) on the module's packages. I believe that would be faster than compiling and linking the code and get at the faster edit-compile fail-fix cycle you want.

**Comment by vangent** [comment]
I'll send a PR to run `go build`, since I think it achieves two birds with one stone: creating a valid `go.sum` file per this issue, and giving compile-time feedback more quickly. I'll leave a TODO to consider using `go/packages` for the latter, but IMHO there's not a huge advantage at this point (`go build` is quite fast).
