### ISSUE TITLE
all: cache/ cache/redis cache/memorystore cache/elasticache

### ISSUE THREAD

**Issue by andrioid** [google/go-cloud#2623]
### Is your feature request related to a problem? Please describe.

I woud love a cache abstraction to handle connecting to redis or memcache services.

### Describe the solution you'd like

/cache
/cache/memorystore
/cache/elasticache
/cache/redis
/cache/inmemory

The ability to read/write bytes and set when it should expire.

### Describe alternatives you've considered

I can use a Redis or Memcache client directly

**Comment by vangent** [comment]
What do you think of https://github.com/philippgille/gokv ?

**Comment by andrioid** [comment]
Looks like a good way to store k/v data. Also, wow on how many implementations there are already.

I'd still like a cache. Something that has get/set/remove, but also TTL so that I'm not storing stuff that I don't need to store.

Maybe gokv can be extended to use TTL for keys in Redis. But that might not fit their use-case.

I hope I'm not alone in thinking that caching could use a good abstraction.

I should probably just use the Redis client libraries. Almost everyone is using their protocol anyway.

**Comment by vangent** [comment]
I agree it seems a key/value store with TTL is a reasonable area for abstraction; thanks for the suggestion!

We've also considered other kinds of key/value stores, less structured than `docstore` but more performant than `blob`; think timeseries data, Cassandra, Bigtable, etc.

Given that none of the `gokv` implementations are really Cloud services, I'm not sure it's a great fit for a Go CDK portable API. But, if there's significant demand for it we will consider it.

**Comment by andrioid** [comment]
I'd just like to add that I like the [Redis API on TTL](https://redis.io/commands/ttl).

So you can use Redis like a k/v without worrying about TTL. But adding a `Expire(i uint)` would tell the backend to set a TTL or return an error if the operation isn't supported.

That way this feature could co-exist with a generic cloud key/value store.

**Comment by qaisjp** [comment]
There's also https://github.com/abronan/valkeyrie
