### ISSUE TITLE
blob: add support for querying via SQL

### ISSUE THREAD

**Issue by joeblew99** [google/go-cloud#2626]
Amazon s3 select allows users to query S3 using SQL.
Minio also matches this functionality.
Not sure about google storgage if it has Select also.

This allows devs to use SQL to query data inside an S3 Store. Very useful.

They also both fire an event when data in the Store changes that you can subscribe to.
Minio supports many of the PubSubs engines that go-cloud also supports.

So i am raising this as a question for feature assessement

**Comment by vangent** [comment]
I split this into two separate issues; see #2627 for notifications.

**Comment by vangent** [comment]
If you can open a `db.SQL` connection to make queries, then that seems portable already. At a brief check, that doesn't seem possible for S3; instead, it's a specific API call for in the S3 library.

I don't see anything similar for GCS or Azure Blob storage, so I don't think this is possible to support portably.

If you want this functionality from S3, you can use [`As`](https://gocloud.dev/concepts/as/) to get the underlying S3 type and make the appropriate API call.

**Comment by vangent** [comment]
I'll leave this feature request open; if there's a lot of demand, we can investigate further.
