### ISSUE TITLE
pubsub: support for delayed message delivery

### ISSUE THREAD

**Issue by Place1** [google/go-cloud#2636]
Cloud pubsubs support delayed message delivery, it's a really handy feature and would be useful in go-cloud.

**Comment by vangent** [comment]
Out of curiosity, why is it useful?

Do the major Cloud providers support it? (Google Cloud Pub/Sub, AWS SNS, AWS SQS, Azure ServiceBus, we also have NATS and Kafka support).

**Comment by Place1** [comment]
Ok so from researching a little more not all systems support the feature, so i'll just close this issue, but it's useful for scheduling jobs that need to run in the future. Features like "email a reminder to this user in a weeks time" can be implemented by publishing a message scheduled to be delivered next week.

**Comment by npomfret** [comment]
+1
