### ISSUE TITLE
all: excessive dependencies

### ISSUE THREAD

**Issue by gmosx** [google/go-cloud#2646]
First of all, thank you for this amazing project <3

One issue I have with `gocloud` are the excessive dependencies. Even if I just use small part of the offered functionality (e.g. just `gocloud.dev/server`) I still get's tens of 'random' dependencies that slow down my build and some times even trigger unresolved-dependency errors.

Is there a way to ameliorate the problem?

**Comment by vangent** [comment]
Hi @gmosx --

In `v0.15.0` we did improve this by splitting out some high-dependency and separable components into separate modules (e.g., `runtimevar/etcd`). We've kept the "big 3" Cloud providers in the main `gocloud.dev` module though.

Note that the dependencies are not necessarily compiled/included in your binary if you are not using them. They are still listed in the `go.mod` file though. To speed that up and make it more reliable, consider using a module proxy (`GOPROXY=https://proxy.golang.org`). Hope that helps!

**Comment by gmosx** [comment]
Hey @vangent, thanks for the tips, good to hear that things are improving.

I will try the GOPROXY solution when go 1.13 is released.

**Comment by sagikazarmark** [comment]
I wonder if it would make sense to factor out cloud providers as well and "register" them, similarly to how sql drivers work.

**Comment by vangent** [comment]
We did consider factoring each cloud provider out as well, but ended up deciding not to do that. Hopefully the proxy helps your download speeds.
