### ISSUE TITLE
docstore/memdocstore: Misleading URL example in the howto

### ISSUE THREAD

**Issue by szabba** [google/go-cloud#2652]
### Describe the bug

The example URL on the [howto page](https://gocloud.dev/howto/docstore/#mem) is `mem://userID`. This gives the impression that URL should be just `mem://myKeyFieldName`. However using that URL causes an error message like:
```
open collection mem://userID: invalid key name "" (must be non-empty and have no slashes)
```

From going over the `memdocstore` package code it looks like the URL should be something like `mem://users/userID`.

### To Reproduce

```go
package main

import (
	"context"
	"log"

	"gocloud.dev/docstore"
	_ "gocloud.dev/docstore/memdocstore"
)

func main() {
	ctx := context.Background()
	_, err := docstore.OpenCollection(ctx, "mem://userID")
	if err != nil {
		log.Print(err)
	}
}
```

## Expected behavior

I was surprised to see the URL from the docs not working.

### Version

0.16.0

### Additional context

If there's anything missing here, please ask. I will try to provide additional details.

**Comment by vangent** [comment]
Thanks for reporting, looks like the how-to got out of date.
