### ISSUE TITLE
blob/gcsblob: Make GoogleAccessID and PrivateKey optional

### ISSUE THREAD

**Issue by andrioid** [google/go-cloud#2653]
### Is your feature request related to a problem? Please describe.

I'm creating a microservice on cloud-run and recently ran into the 32MB response limit. So I thought, I'll just use the SignedURL functionality and redirect to it.

But I can't seem to access the private-key anywhere on cloud-run. The credentials seem to be fetched from the metadata service

I came across this issue on the Go SDK: https://github.com/googleapis/google-cloud-go/issues/1130

It feels like a really weird abstraction, that I need to tell OpenBucket about encryption keys when everything else is automatically detected.

The developer experience is *otherwise* excellent.

### Describe the solution you'd like

`bucket.SignedURL()` should work out-of-the-box on GCP in my opinion without further configuration.

### Describe alternatives you've considered

I've tried:

- Sending service-account.json file as an ENV var
- Retrieving the private-key from ENV
- Retrieving the private-key from known location.

I haven't tried hard-coding the credentials or shipping them through Git or Docker

**Comment by vangent** [comment]
If you can figure out how to sign things on Cloud Run (seems like there are some hints on the issue you referenced, you can provide a function to [`Options.SignBytes`](https://godoc.org/gocloud.dev/blob/gcsblob#Options). For example, on `appengine` there is an existing `SignBytes` function provided; see the [example](https://godoc.org/cloud.google.com/go/storage#SignedURLOptions). I'm not sure if there's such a thing yet for Cloud Run, but I'd suggest following the issue you linked to.

I'll leave this open in case there turns out to be a function we could call internally to do it automatically.

**Comment by andrioid** [comment]
Thanks for the tip. Maybe my motivation for opening this wasn't clear.

I thought it was a good idea to track the other issue in terms of developer-experience. So when they can do it automatically, we could too.

I think it's a terrible shame that a package such as this, that works perfectly out of the box without any extra IAM configuration fails on signing public-urls.

**Comment by wmark** [comment]
@vangent Would you entertain a PR that'll use the auto-generated *credentials v1* API in absence of any `SignBytes` function? I'm thinking along the lines of this, first guessing the an accessID like so (the user is already able to overwrite it) to get a default value:
```diff
--- a/blob/gcsblob/gcsblob.go
+++ b/blob/gcsblob/gcsblob.go
@@ -114,7 +114,10 @@ func (o *lazyCredsOpener) OpenBucketURL(ctx context.Context, u *url.URL) (*blob.
                        o.err = err
                        return
                }
-               o.opener = &URLOpener{Client: client}
+               o.opener = &URLOpener{
+                       Client:  client,
+                       Options: Options{GoogleAccessID: creds.ProjectID + "@appspot.gserviceaccount.com"},
+               }
```

… Followed by a `sync.Once` with a `credentials.NewIamCredentialsClient(bgctx)` called in `SignURL` (not shown), to play out like this:
```diff
@@ -597,8 +612,24 @@ func (b *bucket) Delete(ctx context.Context, key string) error {
        return obj.Delete(ctx)
 }

+// defaultSignBytes will construct a SignBytes function for SignedURL.
+func (b *bucket) defaultSignBytes(ctx context.Context, googleAccessID string) func([]byte) ([]byte, error) {
+       return func(p []byte) ([]byte, error) {
+       …
+       }
+}
+
 func (b *bucket) SignedURL(ctx context.Context, key string, dopts *driver.SignedURLOptions) (string, error) {
-       if b.opts.GoogleAccessID == "" || (b.opts.PrivateKey == nil && b.opts.SignBytes == nil) {
+       if b.opts.GoogleAccessID == "" {
                return "", errors.New("to use SignedURL, you must call OpenBucket with a valid Options.GoogleAccessID and exa
        }
        key = escapeKey(key)
@@ -610,6 +641,9 @@ func (b *bucket) SignedURL(ctx context.Context, key string, dopts *driver.Signed
                PrivateKey:     b.opts.PrivateKey,
                SignBytes:      b.opts.SignBytes,
        }
+       if b.opts.PrivateKey == nil && b.opts.SignBytes == nil {
+               opts.SignBytes = b.defaultSignBytes(ctx, opts.GoogleAccessID)
+       }
        return storage.SignedURL(b.name, key, opts)
 }
```

**Comment by wmark** [comment]
See also googleapis/google-cloud-go#1495.

**Comment by vangent** [comment]
I think so, can you send a PR?
