### ISSUE TITLE
docstore/memdocstore: encoding in saveFile failing

### ISSUE THREAD

**Issue by Tylerflick** [google/go-cloud#2664]
Memdocstore fails to save to a file because of a gob encoding failure.

### Describe the bug

When closing an instance of memdocstore with a populated doc, gob returns the following error:
> gob: type not registered for interface: map[string]interface {}

The error is returned from mem.go when it calls into the gob package:
``` go
// saveDocs saves m to filename if filename is not empty.
func saveDocs(filename string, m mapOfDocs) error {
	if filename == "" {
		return nil
	}
	f, err := os.Create(filename)
	if err != nil {
		return err
	}
	if err := gob.NewEncoder(f).Encode(m); err != nil {
		_ = f.Close()
		return err
	}
	return f.Close()
}
```

### To Reproduce
The following snippet produces the problem:
``` go
func TestSaveToFile(t *testing.T) {
	const url = "mem://docstore/DocId?filename=out.foo"
	ctx := context.Background()
	coll, err := docstore.OpenCollection(ctx, url)
	if err != nil {
		t.Fail()
	}
	defer coll.Close()
	actionList := coll.Actions()
	actionList.Create(map[string]interface{}{
		"DocId":            "k712",
		"PublicationYears": []int{1967, 1973},
	})
	if err := actionList.Do(ctx); err != nil {
		t.Fail()
	}
}
```
In the example I used map[string]interface but structs have the same problem

## Expected behavior

The document encodes correctly and is saved to the file

### Version

Which version(s) of the Go Cloud modules are you seeing the bug with?
v0.16.0

**Comment by vangent** [comment]
```
func TestSaveToFile(t *testing.T) {
	const url = "mem://docstore/DocId?filename=out.foo"
	ctx := context.Background()
	coll, err := docstore.OpenCollection(ctx, url)
	if err != nil {
		t.Fatal(err)
	}
	defer func() {
		if err := coll.Close(); err != nil {
			t.Error(err)
		}
	}()
	actionList := coll.Actions()
	actionList.Create(map[string]interface{}{
		"DocId":            "k712",
		"PublicationYears": []int{1967, 1973},
	})
	if err := actionList.Do(ctx); err != nil {
		t.Fail()
	}
}
```

worked better to reproduce this; the original passed for me the first time and then failed the second time with `EOF`. This is because the original error is in the save phase, which happens during `Close`, and the original test doesn't check the error returned from `Close`. So, `out.foo` is created but stays empty, and the second run fails trying to read it.

**Comment by vangent** [comment]
I believe you'll need to register your interface types for gob encoding:
https://stackoverflow.com/questions/21934730/gob-type-not-registered-for-interface-mapstringinterface
