### ISSUE TITLE
all: add an API for service mesh / registry

### ISSUE THREAD

**Issue by mytototo** [google/go-cloud#2673]
When working with micro-services we often need to add them in the service mesh / registry, such as Consul or Kubernetes.

I think about an API that automatically adds a service when adding a health check to a `server` options, or something similar.

For inspiration, the [micro/go-micro](https://github.com/micro/go-micro) does that with the `registry` package.

What do you think ?

**Comment by eliben** [comment]
This is out of scope for the CDK project. If frameworks like go-micro provide it -- great! The libraries are orthogonal. You can use a framework for your microservice and CDK to access cloud services
