### ISSUE TITLE
blob: Add an API to compose objects

### ISSUE THREAD

**Issue by dwbuiten** [google/go-cloud#2674]
### Is your feature request related to a problem? Please describe.

This now, there is no way to use gocloud to to compose a set of objects in a bucket, and it would be nice if it could.

### Describe the solution you'd like

A simple API could be like:

```Go
keysToBeComposed := []string{"key1, "key2"}
err := bucket.Compose(keyName, keysToBeComposed) // or `keysToBeComposed...`
if err != nil {
    return err
}
```

### Describe alternatives you've considered

Right now I am forced to use the (IMO very un-Go-like, and very verbose) GCS `storage` package if I want to compose anything.

### Additional context

I'm aware this functionality does not exist on e.g. S3, so I don't know if it's feasible to add it; I don't know if you guys require functionality to be present on all blob types for a feature to be considered. Feel free to close this request if it's a hard requirement.

**Comment by vangent** [comment]
> require functionality to be present on all blob types for a feature to be considered

I wouldn't say it's a hard requirement, but it's a guideline. I don't think it exists for Azure either. We could implement composition for all providers by reading + appending, but that's relatively easy to do with the existing API so it would end up just being a performance improvement for GCS only.

For now, you can use `As` to get at the underlying GCS type and use the GCS APIs.

I'll leave this issue open, but `Unplanned`, in case the other providers add such functionality in a way that makes it reasonable to make a portable version.

**Comment by dwbuiten** [comment]
Yeah, I expected as much - seams reasonable. Just thought I'd pitch the idea :).

I'm using `As` and the strorage API, but it's a little awkard (a `blob.Bucket` returns a `storage.Client` rather than a `storage.BucketHandler` for some reason), but otherwise servicable.

Thanks for the response!
