### ISSUE TITLE
blob/azureblob: Support for User Delegation Keys

### ISSUE THREAD

**Issue by seiffert** [google/go-cloud#2681]
### Is your feature request related to a problem? Please describe.

The problem we're trying to solve is that we need to generate pre-signed URLs for storage accounts without using storage access keys. Storage access keys cannot be scoped to specific containers or blobs within an account and are long-lived.

To generate pre-signed URLs (SAS in the context of Azure), one currently needs to provide a `*azblob.SharedKeyCredential` in the options when opening a bucket.

### Describe the solution you'd like

Instead of the `*azblob.SharedKeyCredential`, I would like to be able to pass in a `azblob.StorageAccountCredential` which is an interface implemented by `azblob.SharedKeyCredential` and `azblob.UserDelegationCredential` in [`github.com/Azure/azure-storage-blob-go`](github.com/Azure/azure-storage-blob-go) since [this PR](https://github.com/Azure/azure-storage-blob-go/pull/131) which is part of the module since v0.7.0. The `azblob.UserDelegationCredential` could then be obtained using Azure AD OAuth tokens and would eliminate the need for storage access keys.

### Describe alternatives you've considered

We experimented with using storage access keys, but that doesn't align well with our permission model at the moment. An alternative would be to generate pre-signed URLs using the Azure SDK directly which would be bad for portability and increase code complexity.

**Comment by praneetloke** [comment]
@seiffert I opened #3007 for a way to refresh the user delegation key (UDK). I would love it if you have some insight into it. There doesn't seem to be a lot of "talk" around acquiring user delegation key via OAuth2 client credentials (via an AAD app or SP) and using that effectively with this SDK in a long-running service.
