### ISSUE TITLE
docstore: driver ErrorCode() method returns ErrorCode from the internal gcerr package

### ISSUE THREAD

**Issue by sbulman** [google/go-cloud#2692]
The docstore driver.Collection interface ErrorCode method returns the gcerr.ErrorCode type which is an internal type. This prevents implementations of the interface to be defined externally.

In my particular case, I was looking to implement an implementation that uses mocks to allow simple unit testing of components that use go cloud types. In general, this also prevents external implementations using in house document store implementations or a more general plugin architecture external to this code repository.

Are there any plans to support this, or advice on how to write unit tests when using go cloud storage types.

**Comment by vangent** [comment]
Our intent is that users use a local implementation for testing; e.g., `memdocstore` for docstore. This should result in easier and better tests than using a mocked driver, as the mapping of concrete type to driver is sometimes non-trivial.

If you really want to write your own driver implementations, you can clone the repo. There's no plan to make it easy to do so externally, for a variety of reasons including that it would require a high level of stability for driver interfaces, and that it is unclear how to enforce that driver implementations conform to the requirements.

**Comment by sbulman** [comment]
Thanks for the response @vangent . Would you consider using the gcerrors package in the docstore driver interface rather than the internal gcerr package. This would enable the ability to implement a driver (in a clone) that uses mocks. I don't believe this is possible if the mocks have to expose internal package types.

**Comment by vangent** [comment]
Sorry, don't think so. In a cloned repo you can do whatever you want, but I strongly recommend against mocking driver interfaces; the mapping between your application code and what driver interfaces are called should be considered an implementation detail. In other words, your tests may break anytime something internal changes. Use a stub `memdocstore` instead.
