### ISSUE TITLE
pubsub: Ordered queues instead of topics

### ISSUE THREAD

**Issue by shousper** [google/go-cloud#2693]
### Is your feature request related to a problem? Please describe.

We hit a limitation when processing messages from an AWS SQS FIFO queue with message grouping.

A single batch can contain messages for multiple groups and if a message for one group has a failure there is no way to reject/nack all the messages from that group for the batch. The `Subscription` interface only speaks in messages, not batches.

This meant we were unable to use the `pubsub` package without resorting to limiting batch sizes to 1 message.

### Describe the solution you'd like

Given the description of the `pubsub` package only really mentions "interact[ing] with publish/subscribe systems" maybe a `queue` package for interacting with message queuing systems is more appropriate? The difference being that messages would be persisted, maybe delivered in sequence and/or via streams. This might also apply to `nats-streaming`, `kafka` and others.

### Describe alternatives you've considered

Alternatively, some additional options or interface methods for greater control of how messages are consumed would help but on the surface that feels like it edges towards a mixing of responsibilities.

### Additional context

[This issue](https://github.com/google/go-cloud/issues/1559) might be loosely related in that it talks about "streaming" topics and queues.

EDIT: grammar, formatting.

**Comment by vangent** [comment]
Sorry, I am not very familiar with message grouping in AWS SQS.

Why is it important to reject/nack all the messages in a batch from a group? Are messages for that same group in the next batch for some reason OK to process?

How did you use limit `pubsub` to batch size=1 anyway? I didn't think we exposed that ability at all, as you noted the entire interface is streaming messages, batching is an internal implementation detail.

`pubsub` can be used with both queuing and non-queuing systems, there is a discussion [here](https://godoc.org/gocloud.dev/pubsub#hdr-At_most_once_and_At_least_once_Delivery).

We spent a long time considering the simplest interface for `pubsub`, and it would be a major change to expose batching; we are unlikely to make that change.

**Comment by shousper** [comment]
No worries @vangent 🙂 

I'd say these sections of the docs are most relevant

- https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html#FIFO-queues-understanding-logic
- https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/using-messagegroupid-property.html

> Why is it important to reject/nack all the messages in a batch from a group? Are messages for that same group in the next batch for some reason OK to process?

Because SQS uses its visibility marker to determine if a message is in-flight or not. If any message for a group is in-flight no messages for that group will be returned to any consumer. When you fetch a batch of messages and a message for a group fails you need to make sure all remaining messages for that group, in that batch are rejected as well so they can be retried in order.

Once a new batch is received you can try and process the messages again for that group but there is no way to know when the first batch finishes and the next batch commences.

> How did you use limit `pubsub` to batch size=1 anyway?

Sorry, we didn't & can't. I think my statement was unclear. That'd involve forking or requesting those options to be exposed -- not desirable.

> `pubsub` can be used with both queuing and non-queuing systems

This is true, but it doesn't talk about ordered messaging. Thus my question of if this is something for a different package & interface(s) or if you would want to extend `pubsub` to support systems that provide ordered messaging.

> We spent a long time considering the simplest interface for pubsub, and it would be a major change to expose batching; we are unlikely to make that change.

I understand and agree. The focus here is message grouping and how it is handled with an ordered queue. If support could be added without changing interfaces or exposing batching I think that'd be perfect.

The closest I can imagine is adding "group" awareness to the batcher via subscription options that mean it could determine the group for a message. Then another option to tell the batcher that the messages are ordered so it could handle the rejection of remaining messages for a group if there is a failure. Feels super SQS-specific to me though, haha.

**Comment by vangent** [comment]
Can you use `As` to access the `sqs.Message` and determine the group from there?
https://godoc.org/gocloud.dev/pubsub/awssnssqs#hdr-As

Otherwise, I agree that this seems heavily SQS specific and is unlikely to be supportable in the Go CDK portable API.

**Comment by shousper** [comment]
> Can you use `As` to access the `sqs.Message` and determine the group from there?

No need, the `MessageGroupId` is a standard attribute that is populated into the `Metadata` of `pubsub.Message`. This doesn't help though, because even if we store the failing group ID in local memory and reject subsequent messages for that group we have no way of knowing when to stop rejecting them.

> Otherwise, I agree that this seems heavily SQS specific and is unlikely to be supportable in the Go CDK portable API.

I thought so too.. then I looked at [GCP PubSub - Ordering messages](https://cloud.google.com/pubsub/docs/ordering) [NATS Streaming - Durable messages](https://nats-io.github.io/docs/nats_streaming/channels/subscriptions/durable.html) and [Apache Kafka - Consumer Offset Tracking](https://kafka.apache.org/documentation/#impl_offsettracking).

They don't all solve the ordered-messaging problem, but they all have features to help facilitate it. The same might be true for group processing, idk.

**Comment by dan-compton** [comment]
To be fair, AWS SQS FIFO only solves for ordering in the case where there is a single synchronous consumer and single synchronous producer.
