### ISSUE TITLE
telemetry/all: APIs

### ISSUE THREAD

**Issue by joesonw** [google/go-cloud#2698]
### Is your feature request related to a problem? Please describe.

I understand that go-cloud is to minimize the pains for transferring among different clouds/local environment. 

I couldn't help to notice that there has not been a package for telemetry yet. Which can be a huge deal for those migrating from traditional deployments to cloud, where logging, metrics and tracing are already integrated.

### Describe the solution you'd like

<table>
    <thead>
        <tr>
            <th>Environment</th>
            <th>Sub-package</th>
            <th>Solution</th>
        </tr>
    </thead>
    <tbody>
       
        <tr>
            <td rowspan=3>GCS</td>
            <td>Logging</td>
            <td>Stackdriver Logging</td>
        </tr>
        <tr>
            <td>Metrics</td>
            <td>Stackdriver Monitoring</td>
        </tr>
        <tr>
            <td>Tracing</td>
            <td>Stackdriver Trace</td>
        </tr>
        
        <tr>
            <td rowspan=3>AWS</td>
            <td>Logging</td>
            <td>Cloud Watch</td>
        </tr>
        <tr>
            <td>Metrics</td>
            <td>Cloud Watch</td>
        </tr>
        <tr>
            <td>Tracing</td>
            <td>X-ray</td>
        </tr>
        
        <tr>
            <td rowspan=3>Local</td>
            <td>Logging</td>
            <td>Fluentd, Logstash, Elasticsearch (direct), etc.</td>
        </tr>
        <tr>
            <td>Metrics</td>
            <td>Prometheus, InfluxDB, etc.</td>
        </tr>
        <tr>
            <td>Tracing</td>
            <td>OpenTracing</td>
        </tr>
    </tbody>
</table>

### Describe alternatives you've considered

`server` package implemented partial of telemetry functionalities.

**Comment by vangent** [comment]
We did consider this, but OpenCensus is already strongly in this space. The `server` package uses it.
