### ISSUE TITLE
blob/driver: provide a conformance test suite for implementations

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#270]
For each API, a cloud provider implements a Driver interface in order to support that API for their cloud. For each Driver type, we should create a testcase that takes a Driver as input, and runs it through its paces. If the Driver passes the tests, then we guarantee it will work with the go-cloud API implementation.

**Comment by zombiezen** [comment]
I think `blob` is the one that probably makes the most sense for now, but feel free to open up issues for the other ones.

**Comment by vangent** [comment]
I think this is tightly related to #286 and #128 so I'm grabbing it.

**Comment by vangent** [comment]
Fixed in #311.
