### ISSUE TITLE
blob/gcsblob: SignedURL without OpenBucket

### ISSUE THREAD

**Issue by inigohu** [google/go-cloud#2706]
This is more a questions than a feature request.
How can I sign a URL without open/close a bucket?

> GCW is more of a pain, you have to provide SignedURLOptions which include things like a private key you have to download, or a custom signing function. I think this will need to be passed in to the OpenBucket constructor.

https://github.com/google/go-cloud/issues/404#issuecomment-428786270
I think it shouldn't be mandatory to make `OpenBucket` to sign a URL. 

Looking at the [documentation](https://cloud.google.com/storage/docs/access-control/signing-urls-with-helpers#storage-signed-url-object-go), there is no need to create `gcp.HTTPClient` for example

**Comment by vangent** [comment]
> How can I sign a URL without open/close a bucket?

Sorry, you can't; `SignedURL` is a function of `Bucket` so you have to create one. While it is true that the underlying GCS library can create a signed URL without a client, that's not true across all providers.
