### ISSUE TITLE
blob/azureblob: blob azure storage doesn't work in v0.18.0

### ISSUE THREAD

**Issue by spacycoder** [google/go-cloud#2708]
### Describe the bug

Unable to do operations on blob azure storage in v0.18.0 of gocloud.
The example under uses ```Exists()```, but it fails on other operations too.

### To Reproduce
```
package main

import (
	"context"
	"log"

	"gocloud.dev/blob"
	_ "gocloud.dev/blob/azureblob"
)

func main() {
	bucket, err := blob.OpenBucket(context.Background(), "azblob://asdf")
	if err != nil {
		log.Fatal(err)
	}
	defer bucket.Close()

	exists, err := bucket.Exists(context.Background(), "foo.txt")
	if err != nil {
		log.Fatal(err)
	}

	log.Println(exists)
}
```

## Expected behavior

The example above should return a boolean indicating the existance of "foo.txt". Instead it returns the following error: 
    
    2019/11/19 13:09:16 blob (key "test.jpg") (code=Unknown): -> github.com/Azure/azure-pipeline-go/pipeline.NewError, C:/Users/<user>/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/error.go:154
    HTTP request failed

    Head https://<accountname>.blob.core.windows.net/asdf/test.jpg?timeout=61: proxyconnect tcp: dial tcp 10.64.2.21:0: connectex: The requested address is not valid in its context.
    exit status 1

### Version
Bug happens in v0.18.0, works fine in v0.17.0.

**Comment by vangent** [comment]
Hmm. It is working for me locally.

The URL in that error looks like your account name is being set to "<accountname>".

If you're using the URL opener (`blob.OpenBucket`), the account name is read from the environment variable `AZURE_STORAGE_ACCOUNT` (per https://gocloud.dev/howto/blob/#azure). Can you check that environment variable?

https://github.com/google/go-cloud/pull/2683 is the only change in `azureblob` between `v0.17.0` and `v0.18.0` that I can see, but I don't see anything obvious there that might cause this.

**Comment by spacycoder** [comment]
Have double checked and the environment variables are being set. 

Did some more testing and v0.18.0 seems to work if i connect my laptop to a mobile hotspot. 
So it probably has something to do with our corporate network.
But it works fine when using v0.17.0 so i don't understand why it shouldn't work with v0.18.0 too.

Also tried using https://github.com/Azure/azure-storage-blob-go and i get the same error there.

**Comment by vangent** [comment]
It looks like this may have been a change in #2683 due to our upgrade in azure libs:

github.com/Azure/azure-pipeline-go v0.1.9 -> v0.2.1
github.com/Azure/azure-storage-blob-go v0.6.0 -> v0.8.0

I suggest following up with those libraries to learn more about what changed.
