### ISSUE TITLE
docstore/awsdynamodb: Secondary indexes for dynamodb

### ISSUE THREAD

**Issue by Tanax** [google/go-cloud#2709]
I'm sorry if this has been posted or addressed before. I tried searching but didn't find anything.

Basically, I think it would be pretty awesome if secondary indexes is supported, either LSI or GSI.
Is this in the current roadmap?

Thanks!

**Comment by vangent** [comment]
Does #1832 answer your question? IIUC, we use `DescribeTable` to get all of the indices on a table, and try to use them to construct an efficient query. We fall back to a full table scan.

**Comment by Tanax** [comment]
@vangent Does that apply even if you use a single Get() on the collection rather than the Query() as you mentioned? Or is Query() the way to use secondary indexes? :) And how does it know which index to use?

If I have an index for fields "FieldAB" and I try to get a document 
```
var myDoc = MyDoc{ FieldAB: "SomeValue" }
err := collection.Get(ctx, &myDoc)
```

This would use that index?
Thanks Robert!

**Comment by shantuo** [comment]
When using `Get`, `Only the key fields of doc are used`, in the case of AWS, it could be the partition key and/or sort key of the table. Only `Query` tries to look for other index.

**Comment by Tanax** [comment]
@shantuo Ah, I see! I did not know that. Thank you for clarifying that!
