### ISSUE TITLE
blob/s3blob: fails to copy large file >5GB

### ISSUE THREAD

**Issue by Qinusty** [google/go-cloud#2711]
### Describe the bug

When attempting to perform a Copy() operation on a blob in an S3 bucket which is larger than the maximum size of 5GB for a single copy operation (see https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html), the following error message is displayed.

```
The specified copy source is larger than the maximum allowable size for a copy source: 5368709120
```

### To Reproduce

Place a large file (>5GB) into a bucket and attempt to Copy() it.

## Expected behavior

The object should copy without issue, regardless of size.

### Version

commit: a68836e8e108ad55d26e8e2d21579028090c8aa5

**Comment by vangent** [comment]
I am not sure what Go CDK can do about this, as it is a backend restriction from AWS.

**Comment by vangent** [comment]
From #2790, "...S3 has CopyObject, but it can only be used for objects <5MiB. For larger objects you need to use CreateMultiPartUpload & UploadPartCopy and code to do so automatically is not yet merged to the AWS Go SDK."

**Comment by segevfiner** [comment]
You need to use something like this: https://github.com/aws/aws-sdk-go/pull/2653 (Sadly a PR that has been lingering for a long time)
