### ISSUE TITLE
blob/azureblob: `*blob.Bucket.Exists(...)` returns nil when container (bucket) does not exist

### ISSUE THREAD

**Issue by guschtilt** [google/go-cloud#2712]
### Describe the bug
I have a fresh (`err==nil`) open bucket created with `b, err = azureblob.OpenBucket(...)` and an arbitrary `containerName` param that does not exist. Then I do the first active request to the bucket `ok, err = b.Exists(ctx, "key")`. I would expect `err != nil` with some sort of "ContainerNotFound" error (like it is for example with a S3 bucket), instead I get `err==nil`. When I do another bucket request, in my case `attr, err := b.Attributes(ctx, "key")` I suddenly get such an error ("===== RESPONSE ERROR (ServiceCode=ContainerNotFound) =====...").

### To Reproduce
1. Create a bucket using https://godoc.org/gocloud.dev/blob/azureblob#OpenBucket specifying a `containerName` that does not exist in your Azure storage account
2. Call https://godoc.org/gocloud.dev/blob#Bucket.Exists on that bucket, specifying an arbitrary `key`
3. Call https://godoc.org/gocloud.dev/blob#Bucket.Attributes on that bucket, specifying an arbitrary `key` 

## Expected behavior
In step 2 I would expect the same error I get in step 3

### Version

- gocloud.dev: v0.18.0 
- github.com/Azure/azure-storage-blob-go: v0.8.0

**Comment by guschtilt** [comment]
I think the problem is that you use the same gcerror code ("NotFound") for both the cases, 1. key/blob in bucket does not exist, and 2. the bucket itself does not exist, while `*blob.Bucket.Exists(...)` depends on what `*blob.Bucket.Attributes(...)` returns. I believe the solution would be to add another gcerror to differentiate the two "NotFound" cases.

**Comment by vangent** [comment]
I think you may be misunderstanding the `Exists` API. It returns a `(bool, error)`, and the `bool` is telling you whether the object exists. The `error` is only non-nil if there was some other kind of error.

Can you try calling `exists, err := b.Exists(ctx, "key")` and check `exists`? In the example you gave, it should be `false`. If you do it with a real container + key, it should be `true`. You'll only get an error if there's some other kind of error (e.g., bad creds, network down, etc.).

**Comment by bensussman** [comment]
I understand @vangent 's response, but it just means that `gocloud.dev` is missing a fundamental feature: how do you detect if the *bucket itself* exists? Right now using `Exists()` won't work, so instead what we do is:

```
func canAccessBucket(ctx context.Context, bucket *blob.Bucket) bool {
	iter := bucket.List(&blob.ListOptions{Delimiter: "/"})
	_, err := iter.Next(ctx)
	if err != nil && !errors.Is(err, io.EOF) {
		return false
	}
	return true
}
```

This extra sucks because for `azure` the error returned from `iter.Next()` has no error code, and takes 60s to time out before erroring:

```
blob (code=Unknown): -> github.com/Azure/azure-pipeline-go/pipeline.NewError, <path>/vendor/github.com/Azure/azure-pipeline-go/pipeline/error.go:154
HTTP request failed

Get "https://totallyfakestorageaccountname.blob.core.windows.net/totallyfakeblobcontainername?comp=list&delimiter=%2F&maxresults=1000&prefix=ben%2Frun_outputs%2F17%2F&restype=container&timeout=61": dial tcp: lookup spellbennolocal.blob.core.windows.net on 127.0.0.11:53: no such host
```

**Comment by vangent** [comment]
Can you file a new feature request for that? Note that it may not make sense for all drivers (e.g., for `memblob` there is no concept of a bucket "existing").

Please also mention the azure thing there, or file a separate bug for that, not sure why it has to time out (unclear if this is something we can fix or not though).

**Comment by bensussman** [comment]
@vangent Thanks for the prompt reply!! I created a feature request for `blob`: `bucket.IsAccessible()` AND I created a bug report for `Non-existant storage containers don't error until timeout after 60s`. Let me know what else i can do to help.

Thanks!
