### ISSUE TITLE
blob/fileblob: Attributes for directory does not behave the same as other providers

### ISSUE THREAD

**Issue by shidel-dev** [google/go-cloud#2714]
### Describe the bug
When using  fileblob, and calling `bucket.Attributes(ctx, "path/to/folder")`, it responds successfully, and sets a ContentType of `application/octet-stream`, this is due to the fact that a directory does not have a .attrs file https://github.com/google/go-cloud/blob/master/blob/fileblob/attrs.go#L60. Cloud providers, and the memory provider will return an error in this case, as a directory is not a concept in those domains.

### To Reproduce
call `bucket.Attributes(ctx, "path/to/folder")` and observe the output

## Expected behavior
It to return a not found error

### Version
latest master

**Comment by vangent** [comment]
Thanks for identifying this, I'll take a look.
