### ISSUE TITLE
blob/azureblob: Add support for specifying different Azure cloud environments (Government, China, Germany) to default URLOpener

### ISSUE THREAD

**Issue by Strife96** [google/go-cloud#2716]
### Is your feature request related to a problem? Please describe.

Currently the azureblob package reads the Azure Storage Account name and a key or SAS token from the environment variables. However, it always attempts to open the URL as "<account_name>.blob.core.windows.net". Furthermore, this hardcoded URL is embedded in the non-exported openBucket function, which generates the azureblob.bucket that implements all of the driver functions. As a result, it doesn't seem possible to write my own URLOpener implementation to do this without rewriting a very large portion of the package, including the underlying bucket and driver implementations. 

### Describe the solution you'd like

I would like to be able to specify an Azure cloud environment such as "public", "usgovernment", "german", etc either as an environment variable or somewhere in the azblob:// URL. The blob opener would then attempt to access the account at the Azure storage endpoint for that environment, rather than the standard public endpoint. For example, "usgovernment" would target "<account_name>.blob.core.usgovcloudapi.net". 

### Describe alternatives you've considered

If it is too difficult or intrusive to write this functionality into the package itself, it would be nice if the target URL were somehow exposed for developers to modify or extend it. 

Alternatively, if the azureblob bucket structure were exposed, it would be much easier to write a URLOpener that targets a different URL and then instantiates the bucket with the new ServiceURL.

**Comment by vangent** [comment]
Is there a standard environment variable for this? Similar to `AZURE_STORAGE_KEY`.

**Comment by Strife96** [comment]
There doesn't appear to be any standard blessed by Microsoft. Their az CLI tool relies on "az cloud set" and Powershell uses "Connect-AzAccount -EnvironmentName". Most of their other tools use their own configuration methods or redirect to a browser login. I can't find any Microsoft tools that even specify an environment variable for this purpose. Sadly, third party tools are also not standardized. For example, Ansible uses the variable AZURE_CLOUD_ENVIRONMENT while Terraform uses ARM_ENVIRONMENT. 

I understand it's less desirable to generate non-standard environment variables, but if this functionality is still being considered, it seems sensible enough to use AZURE_CLOUD_ENVIRONMENT. The name is descriptive and unlikely to collide with other technologies using that variable for any different purpose. It could hold values such as "AzureCloud", "AzureUSGovernment", "AzureChinaCloud", etc. which are the same for Azure's SDK and CLI tools, as well as Ansible's current use of the variable.

**Comment by vangent** [comment]
Sounds good. Would you care to send a PR for this? It should be relatively straightforward to add a field to `Options` for this, fill in in the `URLOpener`, and use it in `openBucket` (defaulting to `windows.net`).

I'm not sure how `AzureCUSGovernment` (or whatever) is mapped to a domain, maybe there's a function for that in the Azure library...? Or the environment variable could just be the domain to use.

**Comment by Strife96** [comment]
Sure, I'll fork and send the PR as soon as I'm confident the addition works and is well tested. I'm fairly certain the only difference between environments is a different "blob.core.<env>" domain. I'll make sure the default behavior in absence of AZURE_CLOUD_ENVIRONMENT remains the same and targets "blob.core.windows.net".
