### ISSUE TITLE
docs: split README.md documentation into distinct user journeys

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#272]
The README should include sections for specific user journeys, and describe:
* What Go Cloud provides for that user
* What they should do to get started

Possible user journeys include:
* I'm a developer that just wants to contribute.
* I've got an existing Go application {on AWS, on GCP, other cloud, not-on-cloud}.
* I'm going to write a new Go application.
* I've got an existing non-Go application.
* I want to extend support for an API to a new cloud provider.
* I want to add a new API.

**Comment by vangent** [comment]
@cassandraoid FYI

**Comment by ZVampirEM77** [comment]
@vangent How about add a "doc" directory? We can put all documents into it, including what you suggest  above.

**Comment by vangent** [comment]
Sure, sounds like a good idea.

**Comment by zombiezen** [comment]
Yes, I expect that this should be published using GitHub pages + Hugo or some such solution.

**Comment by vangent** [comment]
Most of what I thought should be done here is already done, or was a bad idea. `internal/design` has some docs in addition to the `README`.
