### ISSUE TITLE
all: Ambigous import

### ISSUE THREAD

**Issue by bep** [google/go-cloud#2722]
After updating Hugo go `gocloud.dev v0.18.0`, every `go mod` (e.g. `go mod tidy`) fails with:

```bash
github.com/gohugoio/hugo/deploy imports
	gocloud.dev/blob/azureblob imports
	github.com/Azure/azure-storage-blob-go/azblob tested by
	github.com/Azure/azure-storage-blob-go/azblob.test imports
	github.com/Azure/go-autorest/autorest/adal imports
	github.com/Azure/go-autorest/tracing: ambiguous import: found github.com/Azure/go-autorest/tracing in multiple modules:
	github.com/Azure/go-autorest v12.0.0+incompatible (/Users/bep/go/pkg/mod/github.com/!azure/go-autorest@v12.0.0+incompatible/tracing)
	github.com/Azure/go-autorest/tracing v0.1.0 (/Users/bep/go/pkg/mod/github.com/!azure/go-autorest/tracing@v0.1.0)
```

I'm on:

```
go version go1.13.4 darwin/amd64
```

**Comment by eliben** [comment]
For reference, this seems like a known issue with `Azure/go-autorest` [https://github.com/Azure/go-autorest/issues/414]

We may need to bump to a newer version of that module in our go.mod

**Comment by bep** [comment]
Note that this happened when I was doing a `go get -u ./...` on the project, which I have now found out is a terrible idea.

Doing:

```
go get -u gocloud.dev
```

As in, do one per udpated module, the above error goes away (it seems)

**Comment by eliben** [comment]
@bep do you believe there's anything for go-cloud to do here?

**Comment by bep** [comment]
I'm closing it. The thing is, I don't know. I do suspect that `go get -u ...` is doing odd stuff, but that is a bigger issue than this one ... And belongs on the Go tracker.

**Comment by jayschwa** [comment]
I am getting a similar error for `Azure/go-autorest` via `gocloud.dev`. I am trying to upgrade from `gocloud.dev` v0.17.0 to v0.19.0. I believe this issue could be reopened as a TODO for `gocloud.dev` to set its dependency versions to ones that work if/when they exist.

```
$ go mod tidy
spell/utils/storage imports
	gocloud.dev/blob/gcsblob tested by
	gocloud.dev/blob/gcsblob.test imports
	gocloud.dev/internal/testing/setup imports
	github.com/Azure/azure-storage-blob-go/azblob tested by
	github.com/Azure/azure-storage-blob-go/azblob.test imports
	github.com/Azure/go-autorest/autorest/adal: ambiguous import: found package github.com/Azure/go-autorest/autorest/adal in multiple modules:
	github.com/Azure/go-autorest v12.0.0+incompatible (/home/jayschwa/go/pkg/mod/github.com/!azure/go-autorest@v12.0.0+incompatible/autorest/adal)
	github.com/Azure/go-autorest/autorest/adal v0.8.2 (/home/jayschwa/go/pkg/mod/github.com/!azure/go-autorest/autorest/adal@v0.8.2)
```

**Comment by jhendrixMSFT** [comment]
I believe this is due to an incomplete go.mod file for azblob.

https://github.com/Azure/azure-storage-blob-go/issues/173

I've opened a PR to add the missing dependencies.  Once the fix has been merged and a new module version tagged you'll want to update to this version.
