### ISSUE TITLE
blob: Provide an api for getting URl for public objects

### ISSUE THREAD

**Issue by tamalsaha** [google/go-cloud#2727]
### Is your feature request related to a problem? Please describe.

I am uploading public files to buckets using blob api. I would like to get the https url (not signed url) for the object from api call.

**Comment by wmark** [comment]
I've a use-case for this, too. Currently my thinking is:
1. `Exists` will get a key's Attributes. In case of GCS you then can read its [ACL](https://godoc.org/cloud.google.com/go/storage#ObjectAttrs.ACL:~:text=object.-,ACL) slice.  
Absent any directory you'd probably call this.
2. With a directory, list, or index, you can store and retrieve “public,” have prior knowledge.  

Which makes this feature a matter of maintaining `maps: bucket → URL prefix string`.

**Comment by evankanderson** [comment]
Any thoughts on what this API would look like?

Would a patch be welcome? Would it likely be an extension of the [`blob.BucketURLOpener`](https://pkg.go.dev/gocloud.dev/blob#BucketURLOpener) interface?
