### ISSUE TITLE
wire: consider splitting "wire" into a separate repository

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#273]
"wire" is relatively complex, and only tangentially related to Go Cloud. It may also be useful for dependency injection use cases that are not using Go Cloud. We should consider splitting it into a separate repository to make that clear.

Related: the documentation in Go Cloud should make it more clear what wire's role is. E.g., I'd suggest that we have a simple example app that doesn't use wire, and a more complex one with multiple dependencies that does wire, and shows in comments what the code would have looked like without it.

**Comment by challenger14** [comment]
go get

**Comment by enocom** [comment]
I agree splitting Wire out of Go Cloud would help to clarify the purpose of Go Cloud, especially on a package level. Presently, Go Cloud includes packages (e.g., `aws` and `gcp`) whose purpose is to organize Wire provider sets. Having these concerns elsewhere would focus Go Cloud on the generic types.

**Comment by vangent** [comment]
Marking as a dupe of #513.
