### ISSUE TITLE
/server/requestlog: add http.Request to Entry struct 

### ISSUE THREAD

**Issue by gilcrest** [google/go-cloud#2734]
# Is your feature request related to a problem? Please describe.

Currently, the Entry struct has the RequestURL field, which stores the entire http.URL string. I would like to easily log only certain pieces of the URL (e.g. path, etc.). 

### Describe the solution you'd like

Is it possible to just add the request URL to the Entry struct so we can easily access and log whichever field from the URL we like or pull out the individual elements of the url and expose them as separate fields?

### Describe alternatives you've considered

I've thought through other ways of doing this, and it's of course possible outside of this interface, but I'm trying to stick within the parameters of go-cloud whenever possible.

### Additional context

I'd also like to log the request body in some cases, but I can imagine that's a bridge too far. I can have a separate handler to do that...

**Comment by vangent** [comment]
Can you just parse the URL?

**Comment by gilcrest** [comment]
Yeah, I certainly can do that. I was just thinking that in your ServeHTTP method, you're doing a lot of super helpful things to pluck out the important bits from the http.Request struct, but the actual http.Request is gated from logging as a result. It would be nice if the whole http.Request struct was added to your Entry struct so I can log the body, determine the scheme, log headers, etc. Right now, I have to parse the URL back into a URL and then pull out the bits I want, when it was already in that form to begin with... and I can't log headers or the body. 

I dunno, it's fairly trivial I guess, I can workaround it. For what it's worth - I'm really enjoying go-cloud and I think you're doing a great job on it, so thanks!

Dan

**Comment by vangent** [comment]
@zombiezen any feedback on this? I'm not super familiar with the `server` code.

Thanks for the positive feedback Dan!

**Comment by gilcrest** [comment]
Hi @zombiezen and @vangent - I linked a PR with this issue. Let me know what you think.

Thanks again!

Dan

**Comment by zombiezen** [comment]
I'll leave comments on the PR.

**Comment by gilcrest** [comment]
Closing, will try to find another way.
