### ISSUE TITLE
Cut 0.19 release

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#2738]
There's been quite a few [new features since v0.18.0](https://github.com/google/go-cloud/compare/v0.18.0...d78048728fab8ef4d7ee07b0cbd68ba44d6b81de). @vangent or @eliben, would you mind cutting a new release?

Independently, I'm curious whether it might be appropriate to mark this project as 1.0, since it seems like the expectation is largely that changes submitted do not break existing API.

**Comment by vangent** [comment]
I'll get to this sometime soon.
