### ISSUE TITLE
secrets: add support for GCP Secrets Manager

### ISSUE THREAD

**Issue by gaahrdner** [google/go-cloud#2742]
### Is your feature request related to a problem? Please describe.

With the recent release of [Secrets Manager](https://cloud.google.com/secret-manager/docs) it seems to make sense to support that in addition to KMS.

### Describe the solution you'd like

Secrets Manager is supported.

### Describe alternatives you've considered

Using KMS.

**Comment by vangent** [comment]
The `secrets` package supports encryption and decryption. If I understand correctly, Secrets Manager just lets you store/retrieve keys/secrets, but you do the encryption/decryption on your own.

https://cloud.google.com/secret-manager/docs/overview discusses the difference.

Concretely, GCP Cloud KMS has a Decrypt API that `gcpkms` calls; same for AWS KMS. Secrets Manager has no such API.
