### ISSUE TITLE
google fraud?

### ISSUE THREAD

**Issue by rbucker** [google/go-cloud#2743]
I cannot determine if go-cloud is google. The README points to gocloud.systems and that is not google. yet the content suggests that it is. this is sketchy

**Comment by eliben** [comment]
The README is fairly explicit:

"If you are looking for the website of GoCloud Systems, **which is unrelated to the Go CDK**, visit https://gocloud.systems."

The Go CDK is a project started by some Google engineers, but it's an OSS project accepting contributions

**Comment by rbucker** [comment]
It's still misleading at best. Thanks for the clarification.
