### ISSUE TITLE
pubsub: support embedded NATS

### ISSUE THREAD

**Issue by mytototo** [google/go-cloud#2744]
Hi,

As you might know NATS is written in Go, and allows server creation from a Go application. This way, we can benefit NATS pub / sub system directly from Go applications without running a dedicated NATS server.

In my opinion this removes an interesting pain point due to deployment and make pub / sub really easy.

Support embedded NATS in Go applications is something planned?

Thank you.

**Comment by vangent** [comment]
IIUC, embedded NATS should work fine with Go CDK. You just connect to localhost:<port> instead of a remote server.
