### ISSUE TITLE
blob: Support customer-supplied encryption key 

### ISSUE THREAD

**Issue by wader** [google/go-cloud#2746]
Im trying to figure out how use customer-supplied encryption key with go-cloud. In my case I would like end up using GCS customer-supplied encryption keys https://cloud.google.com/storage/docs/encryption/customer-supplied-keys

Maybe i'm missing something?

**Comment by vangent** [comment]
Can you find the documentation for how to use customer-supplied encryption keys via the GCS blob API?

If it's an `HTTPClient`  change, then you can do it directly before passing it to the [GCS constructor](https://gocloud.dev/howto/blob/#gcs-ctor). If it's a change later on (e.g., when writing), then you'll have to use `[As](https://gocloud.dev/concepts/as/)` (probably `BeforeWrite`).

**Comment by wader** [comment]
Thanks, that should work. I think it's `CustomerKeySHA256` in 
 https://pkg.go.dev/cloud.google.com/go/storage?tab=doc#ObjectAttrs that I want to set before read/write then.

**Comment by vangent** [comment]
Great!

**Comment by wader** [comment]
This seems to be what I was looking for:

```go
blobWriter, err := bucket.NewWriter(ctx, "test", &blob.WriterOptions{
	BeforeWrite: func(asFunc func(interface{}) bool) error {
		var o **storage.ObjectHandle
		if !asFunc(&o) {
			// handle error...
		}

		*o = (**o).Key([]byte{0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7})

		return nil
	},
})

blobReader, err := bucket.NewReader(ctx, "test", &blob.ReaderOptions{
	BeforeRead: func(asFunc func(interface{}) bool) error {
		var o **storage.ObjectHandle
		if !asFunc(&o) {
			// handle error...
		}

		*o = (**o).Key([]byte{0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7})

		return nil
	},
})
```
