### ISSUE TITLE
mysql/cloudsql: native password authentication not enabled

### ISSUE THREAD

**Issue by evescorp** [google/go-cloud#275]
#### What did you do?
I want to use the go-cloud library to connect to a database in a GCP MySQL instance so I followed the example in https://github.com/google/go-cloud/blob/master/mysql/cloudmysql/example_test.go filling the proper values for my project in GCP and the database credentials.

#### What did you expect to see?
I expect it to successfully connect to the selected database in Google Cloud SQL.

#### What did you see instead?
The connection failed with the error message "driver.go:120: could not use requested auth plugin 'mysql_native_password': this user requires mysql native password authentication."
Then I did a little research and found this issue [https://github.com/go-sql-driver/mysql/pull/644](url). It turns out the go-mysql-driver team added a new function to create database configuration named NewConfig in which it sets some default values included 'AllowNativePasswords: true'. 
It would be great if you reflect that change in cloudmysql.go. For me the workaround was to add the line "cfg.AllowNativePasswords = true":

	cfg := &mysqll.Config{
		Net:    dialerName,
		Addr:   params.ProjectID + ":" + params.Region + ":" + params.Instance,
		User:   params.User,
		Passwd: params.Password,
		DBName: params.Database,
	}
	cfg.AllowNativePasswords = true

#### System details

```
Docker container using image golang:1.10.3

$ go version
go1.10.3 linux/amd64

$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build065283112=/tmp/go-build -gno-record-gcc-switches"

$ uname -sr
Linux 4.4.111+
```

**Comment by Londonclog** [comment]
Your help fixing these issues would be appreciated. Thank you.

**Comment by vangent** [comment]
@ijt , I think you still need to merge your change over from your fork.
