### ISSUE TITLE
docstore/all: nil *time.Time references can't be stored

### ISSUE THREAD

**Issue by phroggyy** [google/go-cloud#2754]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 darwin/amd64
</pre>

### Describe the bug

When using a *time.Time field, there is currently no way to store a nil value.

_This is halfway between a bug and a feature, but I will describe the bug aspect here._

### To Reproduce

```golang
import (
	"context"
	"time"

	"gocloud.dev/docstore/memdocstore"
)

type Thing struct {
	DeletedAt *time.Time `docstore:"deleted_at"`
}

func main() {
	coll, err := memdocstore.OpenCollection("id")
	doc := &Thing{}
	coll.Put(context.Background(), doc)
}
```

output:
```
panic: value method time.Time.MarshalBinary called using nil *Time pointer
```

## Expected behavior

The record is stored with `deleted_at: nil` (or whatever is the null value representation for the datastore)

### Version

v0.18.0

### Additional context

This happens because of a combination of things:

1. `EncodeSpecial` in every `codec.go` consider `time.Time` a special type but not `*time.Time`
2. This causes `EncodeSpecial` to return `false, nil`, which pushes us to this line in `docstore/driver/codec.go`: `if v.Type().Implements(binaryMarshalerType)`
3. Because the `time.Time` methods are included in the `*time.Time` method set, and because `time.Time` implements `encoding.BinaryMarshaler`, this returns true
4. Since it is the struct literal, rather than the pointer implementing the interface, the call to `v.Interface().(encoding.BinaryMarshaler).MarshalBinary()` fails, as we try to call `MarshalBinary` on the pointer

## Solutions

* The most obvious solution to me is to consider both `time.Time` and `*time.Time` special types, and treat them both as times. However, this does not solve the case for other structs whose literal implements a marshaler interface, but the pointer is passed
* we could do an explicit nil check after checking for special encoding
* we could check `if !v.IsValid() || !v.IsZero()` instead of just `IsValid`. The downside here is that intentional zero values would become nil, which may not be desirable

**Comment by vangent** [comment]
Why are you using a `*time.Time`? I've only seen people use `time.Time`, with the zero time indicating it's not set.

The Godoc supports that view: https://golang.org/pkg/time/#Time

```
Programs using times should typically store and pass them as values, not pointers.
That is, time variables and struct fields should be of type time.Time, not *time.Time.
```

**Comment by phroggyy** [comment]
I would like to store the value nil to represent the zero value – I don't think it should be assumed that **any** reader of that data necessarily understands the zero-value is non-existent, whereas nil/null clearly does indicate that. For now though, I just set the type to `interface{}` on the struct, and then type assert to `time.Time`. If that is the recommended way – should we document it?

**Comment by vangent** [comment]
Sure, that will work. I don't think we need to document it, as the recommended way is to follow the godoc for time.Time.
