### ISSUE TITLE
gocloud.dev/docstore/gcpfirestore: error while decoding DocstoreRevision

### ISSUE THREAD

**Issue by vkonstantin** [google/go-cloud#2755]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
<pre>
Yes
gocloud.dev v0.19.0
</pre>

### Describe the bug:
Error: "<b>error: docstore (code=Unknown): while decoding: cannot set seconds: ...</b>"
happens in module gocloud.dev/docstore on call Collection.Get() after Collection.Put() for "firestore://..." resources

### To Reproduce:
go.mod
<pre>
module test.test/test
go 1.13
require gocloud.dev v0.19.0
</pre>

main.go

<pre>
package main

import (
	"context"
	"log"

	"gocloud.dev/docstore"

	_ "gocloud.dev/docstore/gcpfirestore"
	_ "gocloud.dev/docstore/memdocstore"
)

type Doc struct {
	DocstoreRevision interface{}
	ID               string `docstore:"id"`
}

func main() {
	log.Println("firestore:")
	firestoreUrl := "firestore://....<url to your document>"
	run(firestoreUrl)

	log.Println("mem:")
	memUrl := "mem://test/id"
	run(memUrl)
}

func run(url string) {
	ctx := context.Background()
	collection, err := docstore.OpenCollection(ctx, url)
	if err != nil {
		log.Panic(err)
	}
	defer collection.Close()

	doc := &Doc{}
	err = collection.Create(ctx, doc)
	log.Printf("Create: DocstoreRevision:%v, error: %v", doc.DocstoreRevision, err)

	err = collection.Get(ctx, doc)
	log.Printf("Get before Put: DocstoreRevision:%v, error: %v", doc.DocstoreRevision, err)

	err = collection.Put(ctx, doc)
	log.Printf("Put: DocstoreRevision:%v, error: %v", doc.DocstoreRevision, err)

	err = collection.Get(ctx, doc)
	log.Printf("Get after Put: DocstoreRevision:%v, error: %v", doc.DocstoreRevision, err)
}

</pre>

output:
<pre>
firestore:
Create: DocstoreRevision:seconds:1582813070 nanos:847138000 , error: nil
Get before Put: DocstoreRevision:seconds:1582813070 nanos:847138000 , error: nil
Put: DocstoreRevision:seconds:1582813071 nanos:659748000 , error: nil
Get after Put: DocstoreRevision:seconds:1582813071 nanos:659748000 , <br/><b>error: docstore (code=Unknown): while decoding: cannot set seconds:1582813071 nanos:659748000 </b>

mem:
Create: DocstoreRevision:1, error: nil
Get before Put: DocstoreRevision:1, error: nil
Put: DocstoreRevision:2, error: nil
Get after Put: DocstoreRevision:2, error: nil
</pre>

### Expected behavior
No error. 

"memdocstore" doesn't have this problem

**Comment by vangent** [comment]
When you are retrieving a document using `Get`, you should start with an empty document (except the key field(s) needed to specify the document.

If you change the last `Get` in your sample code to:

```
        doc = &Doc{ID: doc.ID}
	err = collection.Get(ctx, doc)
	log.Printf("Get after Put: DocstoreRevision:%v, error: %v", doc.DocstoreRevision, err
```

it should work.

The issue is that as written, your second `Get` is attempting to overwrite all of the fields, including the revision field; `gcpfirestore` uses a `proto Timestamp` struct for the revision which apparently doesn't allow that.

**Comment by vkonstantin** [comment]
But in this way, I should change my code depending on which link I will get "firestore://" or "men://" which is inconvenient.
I think that problem not in proto.Timestamp but in decoder when it tries to decode DocstoreRevision when it is a pointer on a struct. Because if I change "DocstoreRevision *proto.Timestamp" to "DocstoreRevision proto.Timestamp" it works fine. Take a look:

**Comment by vkonstantin** [comment]
package main

import (
	"context"
	"log"

	tspb "github.com/golang/protobuf/ptypes/timestamp"
	"gocloud.dev/docstore"
	_ "gocloud.dev/docstore/gcpfirestore"
	_ "gocloud.dev/docstore/memdocstore"
)

type Doc struct {
	DocstoreRevision interface{}
	ID               string `docstore:"id"`
}

func main() {
	log.Println("firestore:")
	firestoreUrl := "firestore://......."
	run(firestoreUrl)

	log.Println("mem:")
	memUrl := "mem://test/id"
	run(memUrl)
}

func run(url string) {
	ctx := context.Background()
	collection, err := docstore.OpenCollection(ctx, url)
	if err != nil {
		log.Panic(err)
	}
	defer collection.Close()

	doc := &Doc{}
	err = collection.Create(ctx, doc)
	log.Printf("Create: DocstoreRevision:%v, error: %v", doc.DocstoreRevision, err)

	err = collection.Get(ctx, doc)
	log.Printf("Get before Put: DocstoreRevision:%v, error: %v", doc.DocstoreRevision, err)

	err = collection.Put(ctx, doc)
	log.Printf("Put: DocstoreRevision:%v, error: %v", doc.DocstoreRevision, err)

	log.Printf("Type of DocstoreRevision before: %T, value: %v", doc.DocstoreRevision, doc.DocstoreRevision)
	doc = changeDocstoreRevision(doc)
	log.Printf("Type of DocstoreRevision after: %T, value: %v", doc.DocstoreRevision, doc.DocstoreRevision)

	err = collection.Get(ctx, doc)
	log.Printf("Get after Put: DocstoreRevision:%v, error: %v", doc.DocstoreRevision, err)
}

func changeDocstoreRevision(d *Doc) *Doc {
	if d.DocstoreRevision != nil {
		if t, ok := d.DocstoreRevision.(*tspb.Timestamp); ok {
			d.DocstoreRevision = *t
		}
	}
	return d
}

**Comment by vkonstantin** [comment]
2020/03/04 14:16:32 firestore:
2020/03/04 14:16:33 Create: DocstoreRevision:seconds:1583320593 nanos:35065000 , error: <nil>
2020/03/04 14:16:33 Get before Put: DocstoreRevision:seconds:1583320593 nanos:35065000 , error: <nil>
2020/03/04 14:16:34 Put: DocstoreRevision:seconds:1583320594 nanos:110919000 , error: <nil>
2020/03/04 14:16:34 Type of DocstoreRevision before: *timestamp.Timestamp, value: seconds:1583320594 nanos:110919000 
2020/03/04 14:16:34 Type of DocstoreRevision after: timestamp.Timestamp, value: {1583320594 110919000 {} [] 0}
2020/03/04 14:16:34 Get after Put: DocstoreRevision:seconds:1583320594 nanos:110919000 , error: <nil>

**Comment by vangent** [comment]
> I should change my code depending on which link I will get "firestore://" or "men://"

No, you should change your code so that you do `Get` using an empty doc (other than the key field(s)). That will work with both and is the right way to do it.


@jba any comment on `*proto.Timestamp` vs `proto.Timestamp`?
