### ISSUE TITLE
all: replay tests have diffs even if interactions haven't changed

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#276]
The HTTP/gRPC replay tests currently don't scrub transient attributes like date or request ID, which makes diffs noisy.  This makes it difficult for a reviewer to see whether an interaction has actually changed or whether it's just normal noise.

**Comment by vangent** [comment]
We've decided that this not feasible, for reasons described in the design.md file changes in https://github.com/google/go-cloud/pull/297.
