### ISSUE TITLE
blob/memblob: Reader truncates length instead giving error

### ISSUE THREAD

**Issue by wader** [google/go-cloud#2762]
### Describe the bug

If memblob reader is given a length longer than the blob it will truncate the response instead of giving an error like other blob drivers lite gcsblob.

### To Reproduce

```go
package main

import (
	"bytes"
	"context"
	"io"
	"log"

	"gocloud.dev/blob"
	_ "gocloud.dev/blob/memblob"
)

func main() {
	bucket, err := blob.OpenBucket(context.Background(), "mem:")
	bucket.WriteAll(context.Background(), "test", []byte{1}, nil)
	br, err := bucket.NewRangeReader(context.Background(), "test", 0, 2, nil)
	buf := &bytes.Buffer{}
	io.Copy(buf, br)

	log.Printf("buf: %#+v\n", buf)
	log.Printf("err: %#+v\n", err)
}
```

## Expected behavior

Expected some kind of range error similar to gcsblob. memblob seems to currently truncate https://github.com/google/go-cloud/blob/master/blob/memblob/memblob.go#L238

### Version

v0.19.0

**Comment by vangent** [comment]
This behavior seems OK given the documentation for `io.Reader`:

https://golang.org/pkg/io/#Reader


"It may return the (non-nil) error from the same call or return the error (and n == 0) from a subsequent call."

**Comment by wader** [comment]
Ok thanks. So to implement for example HTTP range request that should support validation of ranges on top of this API you have to either check the Size attribute or be careful about read error and number of bytes read?

**Comment by vangent** [comment]
Basically, just follow the advice on `io.Reader` -- make sure you process any bytes that come along with an error return value, and stop reading once you get an `EOF`.

**Comment by wader** [comment]
Ok! thanks again
