### ISSUE TITLE
blob: Provide api for setting metadata

### ISSUE THREAD

**Issue by dArignac** [google/go-cloud#2763]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

Please provide an API for setting meta data for a file, analogous to https://godoc.org/github.com/Azure/azure-storage-blob-go/azblob#BlobURL.SetMetadata, but implemented for the bucket API. Currently one can only set the metadata when uploading a file.

### Describe alternatives you've considered

Using the vendor specific approach, but that needs conditions in the functional code that should be in this lib IMHO.

### Additional context

No.

**Comment by vangent** [comment]
Sadly, this is not possible because AWS doesn't support it:
https://github.com/aws/aws-sdk-go/issues/2833

**Comment by dArignac** [comment]
Just wondering if this could be achieved with the S3 tagging feature? I mean it is not really meta data, but at the end it is additional key/value pairs attached to an object (it's available in the AWS Go SDK).

https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObjectTagging.html
https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObjectTagging.html

**Comment by vangent** [comment]
Possibly it could be, but given that we're using S3's Metadata for reading and at creation time already, it would be difficult to change that.

**Comment by dArignac** [comment]
Ok, understood. Thanks for the feedback!
