### ISSUE TITLE
blob: provide a mechanism for retries on bucket writes/reads

### ISSUE THREAD

**Issue by jaxxstorm** [google/go-cloud#2765]
### Is your feature request related to a problem? Please describe.

When writing objects bo buckets like we do with Pulumi's state backend, lots of requests could be rate limited. GCloud implements a quota system, and if the usage library reaches that quota system, Gcloud returns a HTTP 429 response code.

It's possible that we wrap any calls and implement the retry/backoff at the implementation level, but there seems to be precedent for doing this in the `go-cloud` library, as evidenced by the retry package https://github.com/google/go-cloud/blob/master/internal/retry/retry.go

### Describe the solution you'd like

Ideally, I'd like to be able to implement a blob writer with a retries, perhaps as an option to the [writer options](https://godoc.org/gocloud.dev/blob#WriterOptions)? 

### Describe alternatives you've considered

As mentioned before, it would be possible to do this at the implementation level, but having it available on all buckets would be preferable for situations that aren't necessarily HTTP issues, for example if there's timeout due to network issues etc/.

**Comment by vangent** [comment]
Most provider implementations (e.g., `gcsblob`) will retry internally if it is appropriate. The exact behavior is provider-specific. For example, GCS says:

"All of the methods of this package use exponential backoff to retry calls that fail with certain errors, as described in https://cloud.google.com/storage/docs/exponential-backoff. Retrying continues indefinitely unless the controlling context is canceled or the client is closed. See context.WithTimeout and context.WithCancel."

(from https://pkg.go.dev/cloud.google.com/go/storage?tab=doc#pkg-overview)

When you says "GCloud", do you mean GCS or something else? 

I don't think we want to add another layer of retries in the concrete type.

**Comment by vangent** [comment]
(the internal `retry` package is used by `pubsub`, which has different semantics than `blob`)

**Comment by jaxxstorm** [comment]
@vangent thanks for the reply - can you link me to the logic that does the backoffs? I couldn't track it down earlier.

Yes, sorry I did mean GCS, not GCloud.

**Comment by vangent** [comment]
It's in the GCS code. An example is:
https://github.com/googleapis/google-cloud-go/blob/storage/v1.6.0/storage/storage.go#L656
