### ISSUE TITLE
Move `gocloud.dev/pubsub/internal/batcher` out of internal

### ISSUE THREAD

**Issue by tonyhb** [google/go-cloud#2771]
`gocloud.dev/pubsub/internal/batcher` can only be imported by `gocloud.dev/pubsub/`.  I'm making a new Redis driver using gocloud.dev so that we can migrate easily to Google Pubsub.  

However, I'm unable to set batcher opts for at-most-once delivery in the way that the nats package does - because batcher is internal.

Is this _truly_ meant to be private if people can bring their own drivers?

**Comment by vangent** [comment]
Yea, we intend for people to be able to write their own drivers in separate repos, but I don't think it has happened so it might be a bumpy road.

Could you fork the `gocloud` repo and add your driver local to your fork?

If not, I can make `batcher` public.

**Comment by tonyhb** [comment]
Ah thank you for the heads up!  Yes, I can probably do that if we need to customize batching :)

Will know after testing [using](https://github.com/alicebob/miniredis) [these](https://github.com/elliotchance/redismock).  Appreciate it.

**Comment by vangent** [comment]
Please reopen if needed.

**Comment by ajwerner** [comment]
I am also implementing a custom driver and would like to be able to set NumHandlers to greater than 1. Obviously this is just a performance consideration and can fork in the short term but for it to be useful it would be nice not to depend on a fork. Thanks.
