### ISSUE TITLE
blob/s3blob: Write() / Read() allocate way too much

### ISSUE THREAD

**Issue by richardartoul** [google/go-cloud#2774]
# Describe the bug

Despite #2757  calls to Write() and Read() still allocate way too much due to emitting metrics for each individual function call.

### To Reproduce

Have a read-heavy workload that involves reading a lot of data out of S3 and your applications allocations will be completely dominated by these two functions (which should be streaming and zero alloc)

## Expected behavior

Each call to Read() should not trigger an allocation.

### Version

Latest

### Additional context

The only solution I can think of is to keep track of the number of bytes written/read and then only emit them once when the stream is closed. I can make that change if that is acceptable.

**Comment by vangent** [comment]
SGTM

**Comment by richardartoul** [comment]
@vangent This should do it: #2775
