### ISSUE TITLE
errors: constructing errors with codes is not possible for external implementers

### ISSUE THREAD

**Issue by ajwerner** [google/go-cloud#2779]
I've been building an external implementation of pubsub and have not been able to get the tests to
pass because I can't construct the appropriate errors. 

The package to construct the errors is https://godoc.org/gocloud.dev/internal/gcerr

Relates to #2778

**Comment by vangent** [comment]
My plan is:

* Add a `gcerrors.CodedError` interface that will allow external implementers to return coded errors. Your driver implementation will need to return an error type that implements `Error` as well as `gcerrors.CodedError`.

* The docstore driver interface currently returns the internal `gcerr` error code type, as noted in #2803. This is a bug and I'll fix it by updating it to return the public `gcerrors` ErrorCode type instead.

**Comment by vangent** [comment]
@ajwerner can you clarify the problem? You don't need to construct `internal/gcerr` errors, your driver can return any error it wants. The methods in the driver interface just return `error`, not `internal/gcerr`.  The only requirement is that your driver also implement `ErrorCode` (e.g., https://github.com/google/go-cloud/blob/master/pubsub/driver/driver.go#L109) and return the appropriate `gcerrors.ErrorCode` for the error. You could return `gcerrors.Unknown` every time if you wanted (although that wouldn't make for a good user experience for your driver).

The `docstore` driver interface expects drivers to return `gcerr.ErrorCode`, which is a bug.
