### ISSUE TITLE
blob: Add support for cross bucket copy

### ISSUE THREAD

**Issue by segevfiner** [google/go-cloud#2790]
### Is your feature request related to a problem? Please describe.

I need to copy objects between different buckets, sometimes across different accounts & regions.

### Describe the solution you'd like

Add a method that can copy objects across buckets to the blob abstraction in the library. This should be optimized to use cloud specific functions to do the copy directly instead of downloading and uploading the objects again where possible.

### Describe alternatives you've considered

Implement this operation myself, abstracting it for different cloud object stores. Which is what this library aims to do.

### Additional context

Some cloud object stores require some attention when using their copy API. For example, S3 has `CopyObject`, but it can only be used for objects <5MiB. For larger objects you need to use `CreateMultiPartUpload` & `UploadPartCopy` and code to do so automatically is not yet merged to the AWS Go SDK.

**Comment by vangent** [comment]
There was a previous discussion of this on #1766. IIRC, it was not easy because not all providers support it.

**Comment by segevfiner** [comment]
Yeah. It would need a fallback.
