### ISSUE TITLE
travis: only run affected tests on PR checks

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#28]
It would be nice to have PR Travis builds only run the tests for any affected packages for the files touched, then leave the master branch build to run all tests.  The benefit would be to decrease the presubmit latency, since running less tests also means less dependencies to download.  I'm not sure if this has been done before, but it seems like all the information is there in the Go tool and Travis to do subsetting like this.

/cc @cflewis

**Comment by vangent** [comment]
Obsolete.
