### ISSUE TITLE
all: test against Go 1.11

### ISSUE THREAD

**Issue by shantuo** [google/go-cloud#280]
Also we should update our documentation on anything different.

**Comment by shantuo** [comment]
`go test` works with `GO111MODULE=off`. If we turn on the module, it will break the wire tests since it generates and builds Go packages in a temporary directory without a `go.mod` file. We could generate a `go.mod` file for the testdata.

**Comment by zombiezen** [comment]
Hopefully #78 does not affect anything.

**Comment by vangent** [comment]
FYI, I think that golangci-lint (which is used by Travis) doesn't yet support Go 1.11 yet.

**Comment by shantuo** [comment]
Do you mean it won't work under Go 1.11?

**Comment by vangent** [comment]
Yes.
