### ISSUE TITLE
docstore: better integration with protobuf

### ISSUE THREAD

**Issue by eqinox76** [google/go-cloud#2801]
### Is your feature request related to a problem? Please describe.

I am using the go cdk to persist structs generated by the protoc-gen-go plugin `github.com/golang/protobuf v1.4.2`. But i am getting complains from go vet.

Lets take proto.Job as a example. To use it with the go cdk docstore i need a Id and DocstoreRevision field. To not have the maintenance issue of copying over fields i am using composition:
```golang
type jobWithId struct {
	proto.Job
	Id               string
	DocstoreRevision interface{}
}
```
As an example the persist code looks like:
```golang
entry := jobWithId{Job: *job, Id: id}
err := s.jobColl.Put(ctx, &entry)
```

The problem is that `go vet` complains about a copied `sync.Mutex`:
```
literal copies lock value from *job: proto.Job contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex
```
The protobuf generated structs contain private fields which in turn contain a `sync.Mutex` (protoimpl.MessageState.MessageInfo.initMu). This has been changed from the earlier XXX_ fields as can be seen [here](https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.20.0#v1.20-generated-code)

The complain itself is correct even if it does not apply to this situation. But i can not think of a sensible way to fix it. 

### Describe the solution you'd like

I don't see a clear solution. Adding another docstore interface which takes the Id and DocstoreRevision may work but muddies the interface.

### Describe alternatives you've considered

Copying over the public fields manually will make each change to the protobuf specification brittle.

**Comment by vangent** [comment]
What if your `jobWithId` has a `*proto.Job` field instead of embedding?

**Comment by eqinox76** [comment]
Sounds good! So i will write some code to reformat the existing document.

Thank you
