### ISSUE TITLE
blob/s3blob: S3 Server Side Encryption with KMS

### ISSUE THREAD

**Issue by alexplischke** [google/go-cloud#2802]
### Is your feature request related to a problem? Please describe.

I need my files encrypted (server side) as I send them over to the S3 bucket (see https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/s3-example-server-side-encryption-with-kms.html).
I don't seem to be able to find a (documented) way to do this with the current API provided by s3blob.

### Describe the solution you'd like

Ability to specify the server side encryption setting and key on a per file upload request basis and/or when opening the bucket.

**Comment by vangent** [comment]
You will have to use `As` on `BeforeWrite` to do that.

https://gocloud.dev/concepts/as/

https://godoc.org/gocloud.dev/blob/s3blob#hdr-As

https://docs.aws.amazon.com/sdk-for-go/api/service/s3/s3manager/#UploadInput

https://github.com/google/go-cloud/blob/master/blob/example_test.go#L319

**Comment by alexplischke** [comment]
Thank you! 👍
