### ISSUE TITLE
docstore: begins_with for query

### ISSUE THREAD

**Issue by Tanax** [google/go-cloud#2804]
Is this supported right now?

This is quite vital for single table designs to be able to query for documents based on hash key and a partial sort key (begins_with). I know it is supported for dynamodb but not sure about the other docstores.

I had a look at the source code and as far as I could see, there was no specific operator for this supported for the Where() method of a query. Is this supported indirectly (for instance by passing a partial sort key value to the "=" operator) or is this in the pipeline?

Thank you!

**Comment by vangent** [comment]
You should be able to query `begins_with` using `>=` and `<`. For example, `begins_with "aaa"` == `>= aaa AND < aab'.

**Comment by Tanax** [comment]
Thank you, that sounds great that it's supported!
A bit curious though how this would actually work in practice.

Let's say I have a cart table:
hk   | sk                  | other attributes
abc | Product_def | Milk | $1
abc | Product_ghi | Coffee | $5
abc | Summary     | $6

How would I fetch all products for cart "abc"?
`>= "Product" AND < XX` ?

**Comment by vangent** [comment]
Why not `hk == "abc"`? Is each row a separate `Document`? What's the Key?

**Comment by Tanax** [comment]
@vangent If I do `hk == "abc"` I will get all rows, regardless of the subtype. 

Each row is a separate document, yes. That's the point of a single table design, to have a single table for your entity as well as the entity's relational data and it's solved by the sort key. 

To get a single unique row/document, you'd need (in this fictional scenario) both the cart ID (abc) as well as the type of cart information you want (Product/Summary/etc) and if it's a product, a product ID (def). That would in this case fetch me the row containing the milk. 

But to get all products in a specific cart, you want to utilize the begins_with functionality to say that I want the cart ID (sk) == "abc" and the type of information (sk) == begins_with("Product_").

**Comment by vangent** [comment]
`hk == "abc" AND sk >= "Product" AND sk < "Producu"` should get everything starting with "Product".
