### ISSUE TITLE
blob/gcsblob: deprecate Options.{PrivateKey,SignBytes}

### ISSUE THREAD

**Issue by wmark** [google/go-cloud#2815]
With upcoming v0.20 of this CDK a `Options.MakeSignBytes(Context…)` gets introduced that can be used to express both, signing by `Options.PrivateKey` and `Options.SignBytes()`.

1. We arrive at a reduced complexity.
2. We enable a later *private key* rotation and other security best-practices.
3. `PrivateKey` is a wrapper to `SignBytes` [anyway](https://github.com/googleapis/google-cloud-go/blob/v0.57.0/storage/storage.go#L639-L654).

For the legacy `PrivateKey` we can provide a `MakeSignBytes` until they arrive at a better solution, then drop it altogether.

With `gocloud.dev/blob/gcsblob` now shipping with defaults for signing, setting a signer will be rather rare outside on-premise installations. A depreciation will shift the responsibility from legacy code to this module, eliminating a possible future blocker.

**Comment by vangent** [comment]
We'd prefer not to break backwards compatibility, but we can mark them deprecated via comment.

**Comment by wmark** [comment]
Sure. Could be extracted into a `MakeSignBytes` at a later point.
