### ISSUE TITLE
all: github.com/Azure/go-autorest/autorest/adal ambiguous import after update to v0.20.0

### ISSUE THREAD

**Issue by felipeweb** [google/go-cloud#2819]
### Describe the bug
       gocloud.dev/blob/azureblob imports
        github.com/Azure/azure-storage-blob-go/azblob tested by
        github.com/Azure/azure-storage-blob-go/azblob.test imports
        github.com/Azure/go-autorest/autorest/adal: ambiguous import: found package github.com/Azure/go-autorest/autorest/adal in multiple modules:
        github.com/Azure/go-autorest v12.0.0+incompatible (/home/felipeweb/go/pkg/mod/github.com/!azure/go-autorest@v12.0.0+incompatible/autorest/adal)
        github.com/Azure/go-autorest/autorest/adal v0.8.3 (/home/felipeweb/go/pkg/mod/github.com/!azure/go-autorest/autorest/adal@v0.8.3)

### To Reproduce

- Update to 0.20.0 in an existent module and then go mod tidy

**Comment by vangent** [comment]
This has been reported before. It's an Azure issue, not Go CDK.

https://github.com/Azure/go-autorest/issues/414

#2722 
#1990
#2798

**Comment by miquella** [comment]
I'm hoping that Azure/go-autorest#528 will provide resolution to this issue (once upgrade versions of the submodules are released).
