### ISSUE TITLE
blob/fileblob: No results returned for List with a bucket rooted at /

### ISSUE THREAD

**Issue by alex** [google/go-cloud#2820]
### Describe the bug

When a `fileblob` bucket is rooted at `/`, `List` seems to never return any results

### To Reproduce

```go
package main

import (
	"context"
	"fmt"
	"io"

	"gocloud.dev/blob"
	"gocloud.dev/blob/fileblob"
)

func main() {
	bucket, err := fileblob.OpenBucket("/", nil)
	if err != nil {
		panic(err)
	}
	it := bucket.List(&blob.ListOptions{Prefix: "tmp/"})
	for {
		obj, err := it.Next(context.TODO())
		if err == io.EOF {
			break
		} else if err != nil {
			panic(err)
		}
		fmt.Println(obj.Key)
	}
}
```

## Expected behavior

This prints out a bunch of files I have in `/tmp`

### Version

`v0.20.0`

### Additional context

If I have a bucket at `/` and use `Prefix: ""` then the results that get printed out have keys like `tc/shells` which makes me think it's accidentally stripping a character too many off the front.

**Comment by alex** [comment]
The bug appears to be here: https://github.com/google/go-cloud/blob/53d4ff30c6afa5480a8bdfae236d4a2c9a300028/blob/fileblob/fileblob.go#L324-L325

This strips off too much.

**Comment by alex** [comment]
A diff like:

```diff
diff --git a/blob/fileblob/fileblob.go b/blob/fileblob/fileblob.go
index a21f1338..f596823d 100644
--- a/blob/fileblob/fileblob.go
+++ b/blob/fileblob/fileblob.go
@@ -322,7 +322,11 @@ func (b *bucket) ListPaged(ctx context.Context, opts *driver.ListOptions) (*driv
                        return nil
                }
                // Strip the <b.dir> prefix from path; +1 is to include the separator.
-               path = path[len(b.dir)+1:]
+               prefixLen := len(b.dir)
+               if b.dir != "/" {
+                       prefixLen++
+               }
+               path = path[prefixLen:]
                // Unescape the path to get the key.
                key := unescapeKey(path)
                // Skip all directories. If opts.Delimiter is set, we'll create
```

appears to resolve this, but I'm not fully confident this is correct

**Comment by vangent** [comment]
`List` is returning keys that should work with the`Bucket`. It sounds like you are expecting the key to be a full file path like `/tmp/foo.txt`, but they are not. If you root a `Bucket` at `/`, and then read key `tmp/foo.txt`, I believe it will read `/tmp/foo.txt`. So, the expected key returned from `List` is `tmp/foo.txt`.

If you want to list files under `/tmp`, why don't you root the Bucket there?

What does get printed out if you root the bucket at `/` with no `Prefix`? Anything in `/tmp`?

**Comment by alex** [comment]
Please run the code I included, you'll see that it returns _nothing_, not that the results have a different prefix than what I expect :-)
