### ISSUE TITLE
LocalSecrets: OpenKeeperUrl error

### ISSUE THREAD

**Issue by migone** [google/go-cloud#2826]
Hi,
using local secrets I got a few errors using a base64 string as URL.
Following specification the URL generated is correct in size and Base64 URL econded.
When I got the error the message details tell me that I'got wrong characters in URL string.
I double checked several times with different keys the presence of invalid characters, but I'm pretty sure there are ok.
Digging into the code I found that the method OpenKeeperURL internally do a request to the method Base64Key(u.Host).
The Base64Key method, unfortunately use base64.StdEncoding.DecodeString(base64str) instead of base64.URLEncoding.DecodeString thus giving the invalid character error.
By changing to base64.URLEncoding.DecodeString everything works as expected.

These are some keys to reproduce the error:
s5f96GgqMQKSycAd6wLqvUftkY-IhkTvAA8s1qJdtLI=
UKcmEoZW7nKl0uPHr8yV__KJm0ANhiFz8PzDN-gYWq8=

Characters - and _ are correct for base64 URL encoded strings and they work in place of + and / which will be invalid for URL.

Could anybody return to me if I'm correct and FIX it or tell me how to submit the fix?
Thanks bye!
Davide Migone

**Comment by moidurrahaman15** [comment]
> Hi,
> using local secrets I got a few errors using a base64 string as URL.
> Following specification the URL generated is correct in size and Base64 URL econded.
> When I got the error the message details tell me that I'got wrong characters in URL string.
> I double checked several times with different keys the presence of invalid characters, but I'm pretty sure there are ok.
> Digging into the code I found that the method OpenKeeperURL internally do a request to the method Base64Key(u.Host).
> The Base64Key method, unfortunately use base64.StdEncoding.DecodeString(base64str) instead of base64.URLEncoding.DecodeString thus giving the invalid character error.
> By changing to base64.URLEncoding.DecodeString everything works as expected.
> 
> These are some keys to reproduce the error:
> s5f96GgqMQKSycAd6wLqvUftkY-IhkTvAA8s1qJdtLI=
> UKcmEoZW7nKl0uPHr8yV__KJm0ANhiFz8PzDN-gYWq8=
> 
> Characters - and _ are correct for base64 URL encoded strings and they work in place of + and / which will be invalid for URL.
> 
> Could anybody return to me if I'm correct and FIX it or tell me how to submit the fix?
> Thanks bye!
> Davide Migone

**Comment by vangent** [comment]
Thanks for the report, I sent a PR to fix it.
