### ISSUE TITLE
docstore: array contains query

### ISSUE THREAD

**Issue by eqinox76** [google/go-cloud#2828]
### Is your feature request related to a problem? Please describe.

I have a n:m relation between documents in two collections A, B. I would like to retrieve all documents from collection B which relate to one specific document in A. With the supported filter options i am not able to do such a query.

### Describe the solution you'd like

It seems all supported databases support a array contains search. This way i could store a list of ids in each document in B and query easily for them.

### Describe alternatives you've considered

* Create a third collection where the relations are stored in minimal documents {A: "123", B: "DEF"}. Hard to keep in sync.
* Request every document and filter locally. Wasteful when i cannot reduce the result set.
* Keeping a local cache of the relation. Will need notification and invalidation between processes.

### Additional context
Here are the links to the supported array contains queries
[mongodb](https://docs.mongodb.com/manual/tutorial/query-arrays/#query-an-array-for-an-element)
[firestore](https://firebase.google.com/docs/firestore/query-data/queries#array_membership)
[dynamodb](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Condition.html)
[cosmosdb](https://docs.microsoft.com/de-de/azure/cosmos-db/sql-query-array-contains)

**Comment by vangent** [comment]
@jba any comment on this?

**Comment by ybourgery** [comment]
Any progress on this feature?

**Comment by coryschwartz** [comment]
+1 for this feature. It seems like all the underlying databases (except for memdatastore) support queries like this.

The docstore query api on go-cloud is surprisingly limited. 
Since this isn't supported at this time, it seems we have to As() to the specific clients and maybe rely on our own adapter for queries like this.

**Comment by vangent** [comment]
Fixed!
