### ISSUE TITLE
all: add K-V stores

### ISSUE THREAD

**Issue by beriberikix** [google/go-cloud#2829]
### Is your feature request related to a problem? Please describe.

K-V databases are most commonly used as caching servers as well as instances that need minimal state (local, profile image, etc.) There are many specific databases that are optimized caching, but it is also common to wrap other database types (relational/document) to provide a simple K-V api.

### Describe the solution you'd like

[gokv](https://github.com/philippgille/gokv) is a library I'm currently using that has similar goals to `go-cloud` with an impressive [number of implementations](https://github.com/philippgille/gokv#implementations). The common API that wraps any database and turns them into a K-V is _nice_. However, it doesn't seem to be inline with the model here and I could understand if that wasn't supported. Also the support of purely open-source DBs that are not cloud hosted could also be not included. However, the local in-memory & embedded impl would be a nice-to-have.

### Describe alternatives you've considered

Wrap `gokv`?

**Comment by vangent** [comment]
This is similar to #2623. TL;DR, we didn't see a great opportunity here for wrapping Cloud services. There are lots of open source ones. We're unlikely to take this on. Why not just use `gokv` directly?

**Comment by beriberikix** [comment]
Ah, I missed the duplicate, sorry about that!

>  Why not just use gokv directly?
Largely for API consistency and unnecessary complexity. I'm embedding `gokv` (and probably `go-cloud`) into a library. I could easily hide the package differences from users by including both but would prefer not too. Also in my use case I don't need the breadth of databases in `gokv`. 

A lesser reason would be that development has appeared to slow down by the author, but that could be summer/current state of the global pandemic.

In any case, I *will* be using `gokv` for now!
