### ISSUE TITLE
mysql: Common code to retrieve the connection options from URL

### ISSUE THREAD

**Issue by g8rswimmer** [google/go-cloud#2830]
From the Issue #2745 and #2824, there is a pattern where the mysql connection urls are not having the options decoded. I looked at the aws code, and it appears that the url options would not be decoded there as well.

Since the options in the mysql config would be common among the connections, it might be beneficial to have a common method to parse them from the url. 

The code in the gcpmysql could be used as a reference. https://github.com/google/go-cloud/blob/master/mysql/gcpmysql/gcpmysql.go#L121

**Comment by vangent** [comment]
I think this was done by #2855
