### ISSUE TITLE
The golang.org/x/mod package/dependency  triggers Git "invalid version" error in v0.20.0 release.

### ISSUE THREAD

**Issue by thisisaaronland** [google/go-cloud#2833]
### Describe the bug

The golang.org/x/mod package/dependency  triggers Git "invalid version" error.

### To Reproduce

Add "require gocloud.dev v0.20.0" to `go.mod` which yields the following error when trying to build code:

```
go: found gocloud.dev/blob in gocloud.dev v0.20.0
go: gocloud.dev@v0.20.0 requires
	cloud.google.com/go@v0.58.0 requires
	cloud.google.com/go/datastore@v1.1.0 requires
	golang.org/x/exp@v0.0.0-20200207192155-f17229e696bd requires
	golang.org/x/mod@v0.1.1-0.20191105210325-c90efee705ee: invalid version: git fetch --unshallow -f origin in /home/centos/go/pkg/mod/cache/vcs/13df7481b5cc3358460b717a6142fe8dbaae7652e5d05689849f419ffd40ac12: exit status 128:
	fatal: git fetch-pack: expected shallow list
```
Steps to reproduce the behavior.

### Version

v0.20.0

If I downgrade to v0.19.0 the problem goes away.

### Additional context

n/a

**Comment by vangent** [comment]
This looks like it might be related to https://github.com/golang/go/issues/38373, can you take a look? Which OS and `go` and `git` versions are you using?

**Comment by thisisaaronland** [comment]
I will check the version of Git, shortly. I am using Go 1.14.4.
