### ISSUE TITLE
blob: Stream uploads directly via io.Reader

### ISSUE THREAD

**Issue by stanhu** [google/go-cloud#2835]
### Is your feature request related to a problem? Please describe.

Right now it appears that the `blob` package only provides a `Writer` interface to write a byte slice to the blob (https://godoc.org/gocloud.dev/blob#Writer.Write). This requires the data be stored or buffered somewhere beforehand sending.

### Describe the solution you'd like

In many cases, it would be much nicer to stream the data to the blob storage. AWS and S3 do this via HTTP chunked transfers, while Azure blob already uses the `PutBlock` API to do this. 

It would be nice to be able to use `io.PipeReader` instead as the input. For example, both S3 and Azure blob storage already use a pipe in the `Write` method.

1. S3: https://github.com/google/go-cloud/blob/7818961b5c9a112f7e092d3a2d8479cbca80d187/blob/s3blob/s3blob.go#L239-L241
1. Azure: https://github.com/google/go-cloud/blob/7818961b5c9a112f7e092d3a2d8479cbca80d187/blob/azureblob/azureblob.go#L851-L853

Perhaps we can introduce `blob.PipeWriter` as another option for transfers.

### Describe alternatives you've considered

Right now the only alternative here is to use the SDKs to do this.

**Comment by vangent** [comment]
> This requires the data be stored or buffered somewhere beforehand sending.

Can you clarify what you mean by that? You can write to a `blob.Writer` in small chunks, there's no requirement that it's buffered.

For example, if you have a PipeReader from somewhere (with some other system writing to the PipeWriter) you can start a goroutine that reads from the PipeReader and writes directly to the `blob.Writer`.

Maybe a code snippet of what you're trying to do would help; I don't see an obvious use case with Pipes that couldn't work with `blob.Writer` plus a simple wrapper.

**Comment by stanhu** [comment]
Thanks, I think you're right. I think I was confused because most of the SDKs abstract this out and use `io.Reader` as the input, and I thought Go Cloud would be a drop-in replacement for how I was doing things before. For example, I was calling Azure the `UploadStreamToBlockBlob` directly in https://github.com/Azure/azure-storage-blob-go/blob/48358e1de5110852097ebbc11c53581d64d47300/azblob/highlevel.go#L380, but Go Cloud is presenting a lower-level interface than I was expecting.

I think I can work with that, though. Would it make sense to present an `Upload(io.Reader)` interface?

**Comment by vangent** [comment]
There is already a `blob.WriteAll` shortcut for the simplest case of writing a byte array.

And Go has lots of wrappers/etc. for io. For example, if you have an `io.Reader` and want to read from it and upload the contents, you can create the `blob.Writer` and then use https://golang.org/pkg/io/#Copy.

**Comment by stanhu** [comment]
Thanks. I'll just work with this.
