### ISSUE TITLE
blob/s3blob: Expose the uploader concurrency option for S3 uploads

### ISSUE THREAD

**Issue by timuralp** [google/go-cloud#2836]
### Is your feature request related to a problem? Please describe.

The default AWS Go SDK Uploader concurrency setting is for 5 parallel requests (https://docs.aws.amazon.com/sdk-for-go/api/service/s3/s3manager/#pkg-constants). I would like to be able to change this value. Unfortunately, I don't see a way to reach the S3 Uploader and cannot mutate its state or affect its options at instantiation time.

### Describe the solution you'd like

Expose a configuration option when calling `blob.NewWriter` to set the number of parts to be uploaded in parallel.

### Describe alternatives you've considered

Not sure what other alternatives there might be to solve this. Open to ideas!

**Comment by vangent** [comment]
I sent a PR to expose the `*s3manager.Uploader` via `WriterOptions.BeforeWrite`.

https://gocloud.dev/concepts/as/
https://godoc.org/gocloud.dev/blob#example-WriterOptions
