### ISSUE TITLE
server/requestlog: request logging unconditionally consumes entire body

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#2848]
Offending lines:

https://github.com/google/go-cloud/blob/012388aa3abfa3b3114d1ff9cb0f0c3d0ff4385c/server/requestlog/requestlog.go#L84-L88

For servers that take in large requests, especially those that rely on HTTP 100 Continue to bail early, this can cause a request to be stalled for much longer than necessary to reject a request.

**Comment by vangent** [comment]
SGTM. A minor alternative change would be to drop #3 by always using the # of bytes read by the handler (as in #2) if it ready any. This seems easier to document/understand to me, and it's not like "try to read some more" makes it more accurate.
