### ISSUE TITLE
pubsub: Receive decay stops when messages stop

### ISSUE THREAD

**Issue by chrisivens** [google/go-cloud#2849]
### Describe the bug

The decay mechanism is reliant on a relatively continuous throughput of messages. If working on a finite queue length or one that only has messages occasionally, the decay mechanism skips the calculation and maintains the last batch size set by calling `Subscription.updateBatchSize()`

### To Reproduce

Produce a large number of events and then stop production (we used SQS). The consumer will scale up `runningBatchSize` in `Subscription` to `pubsub.maxBatchSize` but will not decay once the last message has been processed.

## Expected behaviour

Decay to occur when the messages received from the source with each call to receive messages that returns zero results.

### Version

0.20.0

### Additional context

This `if` statement in `Subscription.Receive` circumvents the decay mechanism when there are no messages to process and the `s.throughputStart` will be set to zero after the last message has been collected.

```
if s.throughputStart.IsZero() {
    // No throughput measurement; don't update s.runningBatchSize.
} else {
    // ...
}
```

Although this adds more calculation rather than short-circuiting it, it will decay if this replaces the `if` statement.

```
// if s.q and s.throughputStart are zero values, continue to decay the s.runningBatchSize
elapsed := 0 * time.Second
if !s.throughputStart.IsZero() {
	// Update s.runningBatchSize based on throughput since our last time here,
	// as measured by the ratio of the number of messages returned to elapsed
	// time when there were messages available in the queue.
	if s.throughputEnd.IsZero() {
		s.throughputEnd = now
	}
	elapsed = s.throughputEnd.Sub(s.throughputStart)
}
if elapsed == 0 {
	// Avoid divide-by-zero.
	elapsed = 1 * time.Millisecond
}
```

**Comment by vangent** [comment]
Thanks for the detailed report!

Can you clarify what the actual behavioral problem is? I get that the batch size is not decaying, but why is that bad? If the application behavior is something like:
* a bunch of messages are available
* the messages are processed quickly (and batch size increases)
* no more messages are available (batch size stays high)
* a bunch of messages are available again, and we get a large number of them due to the high batch size

that seems like it's working as intended to me. The batch size is primarily a measurement of how fast messages are processed, and that likely doesn't change when there are no messages available.

**Comment by chrisivens** [comment]
Thanks for looking in to this @vangent, hopefully I can give you enough reason now. The best thing perhaps would be to give you our scenario.

Firstly, this issue came about as we stress-tested our services in the staging environment prior to initial release so there was no traffic other than us but this always would be the case in a staging environment.

As mentioned, we use SQS for our event queue. We use 10 goroutines per k8s pod and on our staging environment, we were only scaling to 5 pods max. So, once this scaled up after running many requests, we were seeing too many requests with empty receives and a large cpu usage as a result.

<img width="1164" alt="Screenshot 2020-09-01 at 19 34 51" src="https://user-images.githubusercontent.com/401928/92076326-48d37280-edb2-11ea-8b4f-564d4f1bf20d.png">

As you can see from this screenshot, we're staying at ~16k empty receives whereas we should only be running at ~500 for the time windows shown. The drop in the graph is when pods were killed.

This extra cpu load caused our pods to scale up to max and never scale down even though there are no messages and this in turn means more cost, especially when we move to production. Perhaps the batch size isn't the main culprit here and the awssnssqs driver is where the focus should be but I haven't looked at it from that angle myself yet.

**Comment by vangent** [comment]
I see, that makes sense. So it's not the batch size that's a problem per se, it's the frequency of calls to AWS.

What's the unit for those graphs? Per minute, per second?

* Here is where we decide whether or not to make another call to `ReceiveBatch`: https://github.com/google/go-cloud/blob/master/pubsub/pubsub.go#L542.
* Note that it does depend on `runningBatchSize`, but that if the queue is currently empty we will always call it (as batch size can't be negative). This is intended to "prefetch" messages by calling `ReceiveBatch` before we run out of messages, but in your scenario we've already run out.
* Thus, if there are no messages the `pubsub` portable type will repeatedly call the driver's `ReceiveBatch` in this scenario; it's up to the driver to slow it down if necessary (some drivers don't poll, so they don't need to).
* The AWS driver sleeps 250ms after receiving an empty batch: https://github.com/google/go-cloud/blob/master/pubsub/awssnssqs/awssnssqs.go#L709.
* Based on this, we should only be making a call to AWS every (250ms + RPC duration), so at most 4/second per gortoutine.
* However, AWS only supports fetching 10 messages at a time (!) (https://github.com/google/go-cloud/blob/master/pubsub/awssnssqs/awssnssqs.go#L112).
* So, we are actually making (`runningBatchSize`/10) RPCs every 250ms or so. The maximum batch size is 3000, so up to a 300x increase....

Decaying the batch size as you suggest would improve this. I will take a look.

Another possibility is to configure long-polling for AWS by setting `WaitTimeSeconds` to something non-zero. This would make each RPC wait for up to that long before returning an empty response. https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-short-and-long-polling.html#sqs-long-polling.

Probably both.

Side note: I wouldn't expect the CPU rate during these times to be high; sleeping 250ms, making an RPCs, waiting for a response, and processing the empty response shouldn't take much time.

**Comment by chrisivens** [comment]
I think our cpu is registering as high because we run the pods very lean. We may want to increase the reserved cpu or profile our handler code to make sure we're as efficient as we can be within reason.

**Comment by vangent** [comment]
https://github.com/google/go-cloud/pull/2853
  should have addressed this.

I have a second PR to expose the WaitTime in the AWS-specific `SubscriberOptions`, so you may want to try configuring that to a non-zero value if you want to reduce polling.

**Comment by chrisivens** [comment]
Thanks. I'll give it a good test run tomorrow. Much appreciated.
