### ISSUE TITLE
pubsub/rabbit: Allow parameters

### ISSUE THREAD

**Issue by mytototo** [google/go-cloud#2857]
### Is your feature request related to a problem? Please describe.

When working with `pubsub` packages we can pass parameters to the URL. For what I have seen and tried, it looks like it is not implemented for RabbitMQ. Why?

I would like to pass `x-single-active-consumer` parameter, as described here: https://www.rabbitmq.com/consumers.html#single-active-consumer

### Describe the solution you'd like

Be able to set parameter like for the other `pubsub` packages.

Example:

```go
OpenTopic(ctx,  "rabbit://topic?x-single-active-consumer=true")
```

**Comment by vangent** [comment]
Per-driver package parameters have to be explicitly supported. We just haven't done so for RabbitMQ. Can you send a PR?
