### ISSUE TITLE
blob:azureblob allow http protocol

### ISSUE THREAD

**Issue by MetalBlueberry** [google/go-cloud#2864]
On line 332 in azureblob.go. the blobURL is hardcoded to be build based on accountName and storageDomain. For my use case, I'm trying to connect to [Azurite blob storage emulator](https://github.com/Azure/Azurite) over http just for testing purposes but it is impossible due to the https restriction. 

I would like to be able to connect to Azurite over http using go-cloud

I've also tried to use a self-signed certificate over https, but for some reason I cannot manage to connect. I do not exactly what is going on.

**Comment by vangent** [comment]
Hmm, Line 332 in azureblob.go (https://github.com/google/go-cloud/blob/master/blob/azureblob/azureblob.go#L332) doesn't seem relevant to your question. Maybe you are looking at a previous version?

IIRC, someone added explicit support for the emulator, see https://github.com/google/go-cloud/pull/2817.

Protocol (http vs https) can be set:
https://github.com/google/go-cloud/blob/master/blob/azureblob/azureblob.go#L114

Also see:
https://github.com/google/go-cloud/blob/master/blob/azureblob/azureblob_test.go#L420
https://github.com/google/go-cloud/blob/master/blob/azureblob/azureblob.go#L386

**Comment by MetalBlueberry** [comment]
I'm using latest version v0.20.0 and you are right, this change has not been released yet. What is the plan for the next release?

Thank you for you detailed answer and sorry for not checking the code base before opening the issue.

**Comment by vangent** [comment]
No explicit plan for the next release; sometime in the next couple of months. You can always grab the latest version using pseudo-versions: https://golang.org/cmd/go/#hdr-Pseudo_versions.
