### ISSUE TITLE
blob/azureblob: Support for querying credentials from the Instance Metadata Service

### ISSUE THREAD

**Issue by JulesDT** [google/go-cloud#2870]
### Is your feature request related to a problem? Please describe.

The current azureblob package does not seem to allow to directly query the Instance Metadata Service to get credentials and relies on [environment variables](https://github.com/google/go-cloud/blob/master/blob/azureblob/azureblob.go#L26-L28).

### Describe the solution you'd like

If environment variables are not provided I would expect the azureblob to tentatively query the Instance Metadata Service to get credentials to be used to query the Azure Blob Storage service.

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by vangent** [comment]
Can you point to some documentation for the Instance Metadata Service and how it is supposed to be use? I'm kind of flying blind on this review.

**Comment by chrismellard** [comment]
@vangent Here's the high level docs from Azure - https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview

In essence though if the workload is running within an MSI enabled context then acquisition of a Service principal token occurs via the MSI infrastructure implicitly and not via explicit client credentials secret/id

**Comment by Segflow** [comment]
Shouldn't this feature be available for the other services as well? e.g: the pub/sub

**Comment by pfleidi** [comment]
@vangent I found this page here a good introduction: https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-managed-identities-work-vm

In a nutshell: If managed identities are configured correctly, there is a metadata service available to an Azure VM that lets applications fetch oAuth tokens without the need for secrets to be configured.

[Here](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/tutorial-linux-vm-access-storage)'s an example for such a request:

```bash
curl 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fstorage.azure.com%2F' -H Metadata:true
```
