### ISSUE TITLE
pubsub: SQS backoff

### ISSUE THREAD

**Issue by chrisivens** [google/go-cloud#2871]
I realise this is a can of worms that I'm opening here but in essence, I'd like to be able to run an exponential backoff for messages that are received out of order on our systems which will eventually pass.

This certainly has ramifications if used wrongly such as with a fifo queue, it could hold up message processing for example. We've implemented something locally which uses a separate standard queue when working with a fifo queue. This is our design decision though.

We've found that if we have a message which is Nack'd which sets the message visibility timeout to 0, the message can be read dozens of times a second and it really needn't be. It can even cause the connection to be killed by AWS.

The current driver and interface only has the message ID's available to run the batch Nack so it doesn't have any context with which to run a backoff.

**Comment by vangent** [comment]
Can you just delay the nack?

I don't think (but I'm not sure) that "nack and don't retry for <delay>" is an operation that is supported by the providers. Do you know?

**Comment by chrisivens** [comment]
On SQS, the Nack method requeues the message with a visibility timeout of 0. This is probably quite important for a FIFO queue because messages would otherwise back-up behind that message until it was next read in order to enforce the message ordering.

For a standard queue, you would use the visibility timeout to delay the message becoming available to the consumers once more. Given that the Subscription interface defines this `SendNacks(ctx context.Context, ackIDs []AckID) error` there is currently not enough context within the awssnssqs implementation to allow any delay to the message (except perhaps a pre-defined delay which would be something at least) as it just has the message IDs.

**Comment by vangent** [comment]
OK. I'm not sure what we can do here. Can your application just delay sending the Nack? I.e., in your processing routine, start a goroutine that sleeps for the backoff and then calls `m.Nack()`. It costs you a goroutine, but that is probably fine.

**Comment by chrisivens** [comment]
I think I'll close this issue for now but if I manage to figure out a neat way to provide backoff for sqs - either by a decorator to the handler or modifying the driver - I'll open a new ticket. Our solution is working for now on one project but our other teams use pubsub with different handler setup which is why something more universal would be beneficial.

**Comment by vangent** [comment]
See https://github.com/google/go-cloud/issues/3193; this came up again. I'm going to add a mode where `Nack` does nothing; the message will be retried, but after its normal `VisibilityTimeout` (defaults to 30s but is configurable).
