### ISSUE TITLE
pubsub: expose Shutdown error type 

### ISSUE THREAD

**Issue by adamdecaf** [google/go-cloud#2878]
### Is your feature request related to a problem? Please describe.

Currently when a Topic or Subscription is shutdown a reader receives a `FailedPrecondition` error back which they have to inspect the string to understand the underlying error. 

### Describe the solution you'd like

[`errTopicShutdown` is already used internally](https://github.com/google/go-cloud/blob/v0.20.0/pubsub/pubsub.go#L251) to describe the specific "shutdown" error, but it's not exposed for callers to use. 

### Describe alternatives you've considered

Currently callers can use `strings.Contains(..)` to inspect the error, but that is brittle as future changes may break such logic.

### Additional context

Example: https://github.com/moov-io/paygate/pull/622

**Comment by vangent** [comment]
You can get the error code using https://pkg.go.dev/gocloud.dev@v0.20.0/gcerrors#Code. It's safe to assumed that `FailedPrecondition` implies shutdown.
