### ISSUE TITLE
blob: Support passing conditional request headers, receiving caching headers like ETag, and propogating 304 Not Modified

### ISSUE THREAD

**Issue by segevfiner** [google/go-cloud#2881]
### Is your feature request related to a problem? Please describe.
Some blob provider (At least AWS) support conditional requests by way of `Last-Modified`/`If-Modified-Since` and/or `ETag`/`If-None-Match`, being able to pass those along and propagating a 304 Not Modified is important for performance reasons.

### Describe the solution you'd like
Support passing along conditional request headers to `bucket.NewReader`, add additional needed headers in the returned `Reader` like `ETag`, and allow knowing when a `304 Not Modified` is returned (By way of a specific error, or by a Reader that expects you to checks for it and fails if you read it?).

The Reader doesn't expose all `Attributes` ATM which some blob providers do return anyhow on the request to fetch a blob.

### Describe alternatives you've considered
Not using the library when I want to support this scenarios. Trying to do a per cloud implementation in `BeforeRead` which is probably not possible as I don't have access to all needed headers from the library and I don't know how it would handle 304 Not Modified

### Additional context
This could lead to an implementation of a `blob.ServeBlob` functions that acts similarly to `http.ServeContent` but works to support range requests, caching, propagating headers, etc. for serving blobs in web servers.

**Comment by vangent** [comment]
Please try using the `As` functions / `BeforeXXX` callbacks for this kind of provider-specific behavior, that is what they are intended to be used for. I'm not sure what you mean by "I don't have access to all needed headers from the library".

**Comment by segevfiner** [comment]
I think I can handle inputs using `Before*`, but is there a way to get access to, for example, the `ETag` header?

But regardless, it's interesting to see if some of this behavior is common enough among the various providers that it deserves an abstraction, or worth it for this package to provide an implementation of this itself that does the best it can for each provider.

Otherwise I will end up writing an implementation of this for each provider myself as a function atop this package, but there is a problem in figuring out what driver/provider is used from a `Bucket` so I can choose the right one.

**Comment by vangent** [comment]
I believe you can get access to the headers using `As` on the `Reader` (https://pkg.go.dev/gocloud.dev@v0.20.0/blob/s3blob#hdr-As) to get the `s3.GetObjectOutput` (https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#GetObjectOutput). There's an example here: https://github.com/google/go-cloud/blob/v0.20.0/blob/s3blob/s3blob_test.go#L179.

**Comment by vangent** [comment]
> some of this behavior is common enough among the various providers that it deserves an abstraction

Which behavior? Headers like `ETag` are provider-specific. I don't think conditional requests like "If Modified Since" are portable across all providers either.

**Comment by segevfiner** [comment]
> I believe you can get access to the headers using As on the Reader (https://pkg.go.dev/gocloud.dev@v0.20.0/blob/s3blob#hdr-As) to get the s3.GetObjectOutput (https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#GetObjectOutput). There's an example here: https://github.com/google/go-cloud/blob/v0.20.0/blob/s3blob/s3blob_test.go#L179.

Thanks! I will try playing around with that.

> Which behavior? Headers like ETag are provider-specific. I don't think conditional requests like "If Modified Since" are portable across all providers either.

They might be. The value of the `ETag` header is opaque and provider specific, but its use is standard, same as with other such headers. They are part of the HTTP spec, not some provider extension, so it's possible that it is something they all implemented to some degree or another, with the HTTP protocol, clients & servers already making concession for how to handle the varying support for them depending on server capabilities, etc.

It's a very common for them to be used as targets for HTTP static sites, and I think they are all served using HTTP, but with different request formats. Which is where the need for such support from them arises.

**Comment by vangent** [comment]
If you think that ETag is common across all providers and is useful to be exposed, please file a separate bug for that and we can consider adding it to https://pkg.go.dev/gocloud.dev@v0.20.0/blob#Attributes. I don't recall if we looked at it in detail before. Links to each provider's use of it would be helpful as well.

I am pretty sure that we looked at "conditional" reads and didn't see a clean way to support them in a provider-agnostic way.

**Comment by segevfiner** [comment]
Alright. I'll check this out later and report back.

**Comment by segevfiner** [comment]
| Provider           | `ETag` | `Date` | `Last-Modified` | `If-Match`/`If-None-Match` | `If-Modified-Since`/`If-Unmodified-Since` | Docs                                                                                                                                  |
| ------------------ | ------ | ------ | --------------- | -------------------------- | ----------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------- |
| AWS S3             | Yes    | Yes    | Yes             | Yes                        | Yes                                       | https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html                                                                    |
| GCP GCS            | Yes    | Yes    | ?               | Yes                        | ? (XML API only?)                         | https://cloud.google.com/storage/docs/generations-preconditions#_JSONAPI https://cloud.google.com/storage/docs/json_api/v1/parameters |
| Azure Blob Storage | Yes       | Yes       | Yes                | Yes                           | Yes                                          | https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob https://docs.microsoft.com/en-us/rest/api/storageservices/specifying-conditional-headers-for-blob-service-operations |

Note: I think GCS might have omitted specfying `If-Match`/`If-None-Match` in the Go client, altough
the docs specify it's supported, likely just an omission in the client library.

@vangent If you still want me to open a separate issue for any part of what I requested in this one, do say so.

**Comment by vangent** [comment]
* Adding `ETag` and `Date` to `Attributes` seems fine, please file a separate feature request.
* We already have `ModTime` (https://pkg.go.dev/gocloud.dev@v0.20.0/blob#Attributes)
* If-Match/If-Modified-Since are less obvious that they are portable given the lack of support for GCS in the Go library.

**Comment by segevfiner** [comment]
The documentation states that at least `If-Match`/`If-None-Match`nare supported. But it is indeed something that needs to be checked. It's possible it was just forgotten in the library and they will accept a pull request to add it. They do expose the `ETag` after all, and it is really only used for that.

**Comment by vangent** [comment]
Where? I only see `Conditions` which support conditions based on integers for `Generation` and `Metageneration`. The XML/JSON APIs support `If-Match`/`If-Modified-Since`, but I don't think the Go library does. I agree that if that gets added that we could do this portably.

**Comment by segevfiner** [comment]
> Where? I only see Conditions which support conditions based on integers for Generation and Metageneration. The XML/JSON APIs support If-Match/If-Modified-Since, but I don't think the Go library does. I agree that if that gets added that we could do this portably.

Nowhere currently in that client. I'm saying it needs to be added. Me or someone else needs to open an issue and/or PR against that library. It uses the JSON API underneath AFAIK. (The XML one is a partial emulation of S3 that doesn't support some stuff like multi-part uploads).

Opened https://github.com/google/go-cloud/issues/2887 as requested

**Comment by vangent** [comment]
OK. I'm going to close this bug, feel free to open a new bug about the conditional fields once GCS supports it in the Go client.
