### ISSUE TITLE
blob: Consider a convienet way to figure out the driver/provider type of a Bucket

### ISSUE THREAD

**Issue by segevfiner** [google/go-cloud#2882]
### Is your feature request related to a problem? Please describe.
Due to differing details and limitations of the current API, it is sometimes needed to write code to handle specific drivers/providers specially, the current `Bucket` struct doesn't provide a way to know which type of driver/provider is serving it short of trying to cast to some driver/provider specific type by way of `As`, but that doesn't apply to `fileblob` which doesn't support any such type.

### Describe the solution you'd like
Add a function, e.g. `DriverType()` (Naming bike shed whoooo) to `Bucket` that allows to figure out the type of underlying driver.

### Describe alternatives you've considered
Figure it out by parsing the URL that we are passing to `OpenBucket`, not convenient, and not generic when receiving an arbitrary `Bucket`.

**Comment by vangent** [comment]
Sorry, we are not likely to do this; the type of the driver is not exposed by design. Use `As` (https://gocloud.dev/concepts/as/) for provider-specific code. You are of course free to keep track of what kind of bucket your application creates separately (although I know that this is likely inconvenient).

Can you give an example where knowing that the driver is `fileblob` specifically would allow you to do something fileblob-specific even though `fileblob` doesn't expose any internals via `As`?

**Comment by segevfiner** [comment]
Wanting to use a different key scheme when using `fileblob` to make up for filesystem directory size limits and performance limitations (Gave up on that due to the lack of this, and just used the same scheme with extra directories in both cases).

A utility to handle caching headers and others that are not exposed in the current API where I need to tell which driver, I'm working against to know which code to use.

**Comment by vangent** [comment]
> just used the same scheme with extra directories in both cases
Sounds good, that is probably the right answer in cases like this when you are trying to write provider-agnostic code. There will be other situations where you may have to target the least-common-denominator across providers, although we've tried to mask that as much as possible.

> utility to handle caching headers
You should be able to use `Reader.As` to get these from providers that have them. `fileblob` does not have caching headers, so your code will have to handle that case.

In general, `gocloud` is strongly encouraging you *not* to write code like `if driver == "foo" else`. In cases where you need provider-specific functionality, access it directly via `As`.

We could conceivably expose some `os` types for `As` for `fileblob` if that would be helpful.

**Comment by segevfiner** [comment]
Should be helpful as that would allow such code to detect the fileblob case by trying to cast to an appropriate type that it can handle, which as you said, is preferred from a condition on the driver type itself.

**Comment by vangent** [comment]
OK, filed https://github.com/google/go-cloud/issues/2885.
