### ISSUE TITLE
blob: Add ETag and Date to Attributes

### ISSUE THREAD

**Issue by segevfiner** [google/go-cloud#2887]
### Is your feature request related to a problem? Please describe.
I'm trying to implement support for conditional requests/caching using `blob`. It requires passing in and returning various HTTP headers.

### Describe the solution you'd like
As one part of this, `ETag` and `Date` can be added to `Attributes`.

See https://github.com/google/go-cloud/issues/2881#issuecomment-729888206

### Describe alternatives you've considered
Having to retrieve them in a provider dependent way.

### Additional context
See https://github.com/google/go-cloud/issues/2881

**Comment by vangent** [comment]
`Date` (which I assume means "CreateTime") does not appear to be portable. At least, S3 and `os.File` do not provide it.

**Comment by vangent** [comment]
I will make it so that `CreateTime` is set to `ModTime` if not available.

**Comment by segevfiner** [comment]
`Date` is the current server time as far as I remember actually, used to correct for clock skew in `Last-Modified`, `Expires`, `Cache-Control: max-age`, etc.

So for fileblob it will just be `time.Now()`

Check the RFC: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.18

**Comment by segevfiner** [comment]
Creations times can probably still be useful for some things of course. But are you sure you don't want to set them to the zero time when not available?

By the way, did you know that creation times are available on Windows via `os.FileInfo.Sys` which is a `syscall.Win32FileAttributeData` on Windows in a `CreationTime` field; and on new enough Linux on some file systems via the Linux specific [`statx`](https://man7.org/linux/man-pages/man2/statx.2.html) in the`stx_btime` field (Accessible in Go via [unix.Statx](https://godoc.org/golang.org/x/sys/unix#Statx)).

**Comment by vangent** [comment]
I didn't see any `Date` exposed on any of the providers.

I'll leave this as `CreationDate`, but I think the suggestion to use the zero time instead of `LastModTime` is good.

Yea, I did notice that there are OS-specific ways of getting `CreateTime` was not motivated to walk that road :-). Thanks for the pointers.
