### ISSUE TITLE
runtimevar: add drivers for AWS Secrets Manager and GCP Secret Manager

### ISSUE THREAD

**Issue by THE108** [google/go-cloud#2907]
AWS Secrets Manager ([https://aws.amazon.com/secrets-manager](https://aws.amazon.com/secrets-manager)) and GCP Secret Manager ([https://cloud.google.com/secret-manager](https://cloud.google.com/secret-manager)) seem to be better alternatives for storing secrets than using config services like AWS SSM Parameter Store / GCP Cloud Runtime Configurator + KMS.

### Describe the solution you'd like

Available runtimevar drivers for AWS Secrets Manager and GCP Secret Manager.

### Describe alternatives you've considered

AWS SSM Parameter Store / GCP Cloud Runtime Configurator + KMS.

**Comment by THE108** [comment]
P.S. I can help with a PR.

**Comment by vangent** [comment]
PRs for this are welcome. Hopefully a new driver is fairly straightforward by copying one of the existing ones. We will likely have to work together because we'll need to record test files with our test projects (GCP and AWS). Let me know what support you need.

**Comment by THE108** [comment]
@vangent 

I've submitted a [PR for AWS Secrets Manager](https://github.com/google/go-cloud/pull/2909). Tests obviously fail due to missing `.replay` files so I'll need some help to generate them.

**Comment by vangent** [comment]
Thanks for the contribution! Are you planning on sending a PR for GCP Secret Manager as well?

**Comment by THE108** [comment]
> Thanks for the contribution! Are you planning on sending a PR for GCP Secret Manager as well?

Yes, I'll submit a separate PR probably next week.

**Comment by THE108** [comment]
@vangent 

Could you point me out to the documentation repo so I can a relevant section for AWS Secrets Manager?

**Comment by vangent** [comment]
@THE108 it's the same repo, for example you probably want to edit:
https://github.com/google/go-cloud/tree/master/internal/website/content/howto/runtimevar

**Comment by THE108** [comment]
@vangent 

I created a [PR](https://github.com/google/go-cloud/pull/2938) for GCP Secret Manager.
