### ISSUE TITLE
runtimevar/etcdvar: etcd has all sorts of go.mod problems

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#2914]
https://github.com/etcd-io/etcd/issues/12124
https://github.com/etcd-io/etcd/issues/11931
https://github.com/etcd-io/etcd/issues/11749

This means we can't update etcd or a bunch of other unrelated modules (like cloud.google.com).

Plan is to drop support for etcd going forward until these are fixed. Users can continue using the current tagged version of go-cloud.

**Comment by saheljalal** [comment]
All the indicated issues appear closed now. Could we evaluate if support will be added back here?
