### ISSUE TITLE
sql/mysql protocol in connectionstring parsed wrong 0.21.0 regression

### ISSUE THREAD

**Issue by eqinox76** [google/go-cloud#2923]
### Describe the bug
Hey all,
we are using a connection string like `mysql://user:password@tcp(dbtest-01)/database` to connect to a mysql instance. 
Up until 0.21.0 this worked fine but now it fails with `no such host`.
### To Reproduce
```golang
db, err := mysql.Open(ctx, "mysql://user:password@tcp(dbtest-01)/database")
if err != nil {
	log.Fatalf("open db failed: %s", err)
}
rows, err := db.Query("show variables like 'max_allowed_packet'")
if err != nil {
	log.Fatal(err)
}
```
Since 0.21.0 the query fails with:
```
dial tcp: lookup tcp(dbtest-01): no such host
```
Using `mysql://user:password@dbtest-01/database` without protocol works fine.
At version 0.20.0 using the connection string without the protocol returned the error:
```
default addr for network 'dbtest-01' unknown
```

## Expected behavior
Working sql.DB* instance.

### Version
gocloud.dev v0.21.0
$ go version
go version go1.15.6 linux/amd64

### Additional context
I guess the regression was caused by #2855 .
It interacts with the way the go-sql-driver formats the connection string. https://github.com/go-sql-driver/mysql#dsn-data-source-name.

I am not sure if we use the connection string in a special way or if this may impact other users.

**Comment by vangent** [comment]
@alexsn FYI

**Comment by alexsn** [comment]
@eqinox76, using the following url format will resolve your issue: `mysql://user:password@dbtest-01/database`.
@vangent, do we want to support this format? If so I'll send a PR a bit later.

**Comment by vangent** [comment]
Yes, I think we should support it, both for backwards compatibility and because it's listed in https://github.com/go-sql-driver/mysql#dsn-data-source-name. Ideally we could use a parser provided in that package to avoid reimplementing it. Thanks in advance for the PR!

**Comment by eqinox76** [comment]
Thank you!
