### ISSUE TITLE
blob/azureblob: Using a SAS token no longer works

### ISSUE THREAD

**Issue by stanhu** [google/go-cloud#2933]
## Describe the bug

Before https://github.com/google/go-cloud/pull/2873, setting the environment variable `AZURE_STORAGE_SAS_TOKEN` would work fine because the default behavior was to open the bucket via the environment: https://github.com/google/go-cloud/pull/2873/files#diff-9ee8a1ad2dadc385fec784185cfeacacb8796a02b4da3b576dfe5e3a9346d753L154-R169

Now, an account key MUST be provided for that to work, but that defeats the purpose of the SAS token in the first place.
 
### To Reproduce

Attempt to download or upload a blob with `AZURE_STORAGE_SAS_TOKEN` and `AZURE_STORAGE_ACCOUNT`. Azure will attempt to access the file publicly:

```
FATAL: blob (key "myblob") (code=Unknown): write error: -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /Users/stanhu/.gvm/pkgsets/go1.15.3/global/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.11.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=PublicAccessNotPermitted) =====
Description=Public access is not permitted on this storage account.
```

## Expected behavior

The upload works.

### Version

v0.21.0

### Additional context

I think the fix here should be to tweak that `if` statement to look at `sasToken`.

**Comment by vangent** [comment]
@chrismellard

**Comment by stanhu** [comment]
I cleaned my module cache, but I'm seeing this:

```
verifying github.com/Azure/azure-storage-blob-go@v0.12.0: checksum mismatch
	downloaded: h1:LEu0WO1uxAkeJFuNTZR+xxUpIoRUwOXgA2ipS798Ycc=
	go.sum:     h1:7bFXA1QB+lOK2/ASWHhp6/vnxjaeeZq6t8w1Jyp0Iaw=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
```

**Comment by vangent** [comment]
The module cache thing appears to be Azure's fault; they moved a tag.
https://github.com/Azure/azure-storage-blob-go/issues/236#issuecomment-747063565

**Comment by chrismellard** [comment]
I'll take a look later on today around pushing a fix for this.

**Comment by stanhu** [comment]
I submitted a fix in https://github.com/google/go-cloud/pull/2934.

**Comment by chrismellard** [comment]
Or not :) Too slow

**Comment by vangent** [comment]
@chrismellard thanks! A review of #2934 would be great though.

**Comment by stanhu** [comment]
I submitted https://github.com/google/go-cloud/pull/2935 to pin the version to the pseudo-version, so I'll need to update #2934 accordingly.
