### ISSUE TITLE
pubsub/all: flush messages without closing the topic

### ISSUE THREAD

**Issue by Segflow** [google/go-cloud#2945]
### Is your feature request related to a problem? Please describe.

Right now, the portable type *Topic offers the methods `Shutdown` which flushes all pending messages and closes the topic, making it impossible for a user to flushes messages without closing the topic -- During tests for example. 

The only way to do this right now, is to Shutdown the topic, reopen it again and repeat. 

### Describe the solution you'd like

Portable type should expose a Flush() method

**Comment by vangent** [comment]
Thanks for the request!

a) `Topic.Send` is blocking -- it does not return until the message is sent. Why do you need `Flush`?
     (`Topic.Shutdown` ensures that any existing calls to `Send` return before `Shutdown` returns).
b) Anyway, sending messages from the `Topic` does not provide any guarantees that they are available on the `Subscription`, so how does `Flush` help?

**Comment by Segflow** [comment]
Aha! I had to ready the code more closely to understand that.
