### ISSUE TITLE
0.22 release

### ISSUE THREAD

**Issue by Segflow** [google/go-cloud#2949]
### Is your feature request related to a problem? Please describe.

In 0.21 pubsub/azuresb is broken. A .Receive() call panics. This was fixed here https://github.com/google/go-cloud/pull/2931

We are using it in production and we had to reference a specific commit to work around that. A 0.22 release that includes that fix would be much appreciated.

**Comment by vangent** [comment]
Ack.

I would like to get #2944 in, and maybe #2926; waiting on reviews.

@Segflow if you have a good way of testing out #2944, I'd appreciate it. The tests are passing so I'm fairly confident but real-life testing would be great.

**Comment by Segflow** [comment]
Will try to test it next week in our dev environment

**Comment by vangent** [comment]
Done.
