### ISSUE TITLE
blob/azureblob: Storage URL is always prefixed with account name

### ISSUE THREAD

**Issue by marwan-at-work** [google/go-cloud#2959]
### Describe the bug

I was to configure Azure CDN for my blob storage container using [these guides](https://docs.microsoft.com/en-us/azure/cdn/cdn-create-a-storage-account-with-cdn)

The Azure CDN gives you a URL that you can ping directly which will proxy back to the storage account without the client having to care or know about it. 

The StorageDomain option seemed like the right place to configure the CDN URL. However, it always ends up being prefixed with the AccountName which is unfortunately not correct: https://github.com/google/go-cloud/blob/d1f7069afcebb8169000b4f61d1f095eafd46268/blob/azureblob/azureblob.go#L477

### To Reproduce

Create an Azure CDN for a blob account and use this library to access it. 

### Version

v0.21.0

### Additional Context

It's worth noting the underlying storage client also has an issue detailed here: https://github.com/Azure/azure-storage-blob-go/issues/255

**Comment by vangent** [comment]
What does the URL look like?

**Comment by marwan-at-work** [comment]
@vangent :wave: 

The CDN URL looks something like this: 

* https://mycdnname.azureedge.net

Which points to the storage account of this URL: 

* https://myaccountname.blob.core.windows.net


Of course, if I match the CDN name to the AccountName, then things would work...but that eventually breaks when you have multiple CDNs pointing to the same storage account. 

What do you think of adding a new option next to `StorageDomain` called `CDN` so that we maintain backwards compatibility with the  current behavior while allowing for CDNs to be configured? Of course any other suggestion that solves the issue sounds great.

**Comment by vangent** [comment]
Sounds good, sent a PR.
