### ISSUE TITLE
secrets/all: Add support for creating asymmetric keys

### ISSUE THREAD

**Issue by priyawadhwa** [google/go-cloud#2972]
I was wondering if there were any plans to add support for creating asymmetric keys for the various KMS providers? I want to be able to create a key, encrypt and decrypt information all within this library. Thank you!

**Comment by vangent** [comment]
No, we don't plan on adding support for creating keys. That's more of a provisioning/operator role; see https://github.com/google/go-cloud/blob/master/internal/docs/design.md#developers-and-operators.
