### ISSUE TITLE
blob/gcsblob: gcloud auth login does not set ADC

### ISSUE THREAD

**Issue by prateekj117** [google/go-cloud#2973]
### Describe the bug
Docs [here](https://gocloud.dev/howto/blob/#gcs) say that `gocloud.dev/blob` should pick up `gcloud auth login` creds, but that is not the case.

On digging a little deeper into the code, I noticed that gocloud internally uses `golang.org/x/oauth2/google` for authentication to GCP, which searches for `Application Default Credentials (ADC)`. As expected `gcloud auth application-default login` worked. This was a breaking [change](https://cloud.google.com/sdk/docs/release-notes#breaking_changes_119) in gcloud version 128.

### To Reproduce
- Login using `gcloud auth login`
- Use OpenBucket method on GCP Storage which would use Default Credentials.
- See the error.

## Expected behavior
Documentation should be updated with the correct command `gcloud auth application-default login`. 

### Version
gocloud.dev v0.20.0

### Additional context
Would like to work on this issue.

**Comment by vangent** [comment]
Thanks for noticing this. Happy to accept a PR, let us know if you need help.
