### ISSUE TITLE
secrets/awskms: bump version of aws-sdk-go from v1.36.1 to v1.37.x

### ISSUE THREAD

**Issue by noliran** [google/go-cloud#2974]
### Is your feature request related to a problem? Please describe.

AWS's Go SDK version v1.37.0 added support for AWS SSO-based credentials (https://github.com/aws/aws-sdk-go/pull/3755).
Not having this prevents from downstream dependencies of go-cloud (like pulumi) from using awskms:/// in environments where AWS SSO-based credentials are used.

### Describe the solution you'd like

Bump version of aws-sdk-go from v1.36.1 to v1.37.0 (or newer)

### Describe alternatives you've considered

A potential workaround is to use a tool like `yawsso` to "manufacture" non-SSO based credentials (as found in ~/.aws/credentials), but these are short-lived and prone to expiration.

### Additional context

Happy to contribute a PR with the version bump - but I'm not certain what kind of testing would need to be done other than bumping the version.

**Comment by vangent** [comment]
I sent a PR.
