### ISSUE TITLE
docstore/mongodocstore: error update with increment modifier only

### ISSUE THREAD

**Issue by sahalazain** [google/go-cloud#2979]
### Describe the bug

When update document with single increment modifier triggering mongodb error `Modifiers operate on fields but we found type null instead. For example: {$mod: {\u003cfield\u003e: ...}} not {$set: null} (code=Unknown)`

### To Reproduce

```
col.Update(ctx, doc, docstore.Mods{docstore.FieldPath("count"):   docstore.Increment(1)})
```

## Expected behavior

Should not error at all

### Version

gocloud.dev/docstore/mongodocstore v0.22.0

### Additional context

Currently the workaround is by including set id on modifier
```
mods := docstore.Mods{
	docstore.FieldPath("count"):   docstore.Increment(1),
	docstore.FieldPath("_id"): id,
}

col.Update(ctx, doc, mods)
```

I think the problem is in the mongo driver code on function `newUpdateDoc`

```
updateDoc["$set"] = sets
if len(unsets) > 0 {
  updateDoc["$unset"] = unsets
}
if len(incs) > 0 {
  updateDoc["$inc"] = incs
}
```

I think it should check the length of sets as the others 
```
if len(sets) > 0 {
  updateDoc["$set"] = sets
}
```

**Comment by vangent** [comment]
I can't reproduce this old bug. If it's still relevant, can you include a more complete reproduction?
