### ISSUE TITLE
blob/azblob: Permissions error when using SAS Token

### ISSUE THREAD

**Issue by stack72** [google/go-cloud#2982]
Since upgrading to go-cloud v0.22.0, we have started receiving permissions errors when using SAS Tokens and azblobs. The error is as follows:

```
error: saving update info: blob (key ".pulumi/stacks/dev.json -> .pulumi/history/dev/dev-1617188138003597000.checkpoint.json") (code=Unknown): -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.13.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthorizationPermissionMismatch) =====
Description=This request is not authorized to perform this operation using this permission.
RequestId:5ead053e-501e-007f-031c-261d34000000
Time:2021-03-31T10:55:38.2878720Z, Details:
   Code: AuthorizationPermissionMismatch
   PUT https://stack72testing.blob.core.windows.net/statestore/.pulumi/history/dev/dev-1617188138003597000.checkpoint.json?se=2021-03-31t18%3A48%3A01z&sig=REDACTED&sp=rw&spr=https&sr=c&st=2021-03-31t10%3A48%3A01z&sv=2020-02-10&timeout=61
   User-Agent: [go-cloud/blob/0.1.0 Azure-Storage/0.13 (go1.16.2; darwin)]
   X-Ms-Client-Request-Id: [ca9eef4c-da54-4e82-4871-c5e37fbdc99c]
   X-Ms-Copy-Source: [https://stack72testing.blob.core.windows.net/statestore/.pulumi/stacks/dev.json?se=2021-03-31t18%3A48%3A01z&sig=REDACTED&sp=rw&spr=https&sr=c&st=2021-03-31t10%3A48%3A01z&sv=2020-02-10]
   X-Ms-Tags: []
   X-Ms-Version: [2019-12-12]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation using this permission.
   Content-Length: [279]
   Content-Type: [application/xml]
   Date: [Wed, 31 Mar 2021 10:55:37 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [ca9eef4c-da54-4e82-4871-c5e37fbdc99c]
   X-Ms-Error-Code: [AuthorizationPermissionMismatch]
   X-Ms-Request-Id: [5ead053e-501e-007f-031c-261d34000000]
   X-Ms-Version: [2019-12-12]
```

This worked perfectly prior to v0.22.0. When switching from a SAS Token to a Storage Access Key, everything works as expected. I understand that the `403` is actually coming from the `github.com/Azure/azure-storage-blob-go` library but it feels like there is either something breaking in that library or something that we are missing in the docs about how to handle this situation now

Thanks 

Paul

**Comment by vangent** [comment]
How are you specifying the SAS token? (i.e., using the constructor? a URL? etc.).

If this is a regression, can you help figure out which commit broke it? I only see 2 between Dec 9 (v0.21.0) and Feb 5 (v0.22.0):
https://github.com/google/go-cloud/commits/master/blob/azureblob

**Comment by stack72** [comment]
Hi @vangent 

Setting the SAS Token via an Env Var as per the docs https://gocloud.dev/howto/blob/#azure 

I can try and build my binary with each of the commits and let you know how it goes

P.

**Comment by vangent** [comment]
> I can try and build my binary with each of the commits and let you know how it goes

Thanks, that will help. If it's the commit that is just updating our Azure storage library version, you'll probably have to follow up with them. If it's one of the commits in our code, it's a regression we can fix.

**Comment by leezen** [comment]
@vangent Not sure this is helpful, but I simply can't get `Copy` to work via the SDK with SAS tokens.

with `AZURE_STORAGE_ACCOUNT` and `AZURE_STORAGE_SAS_TOKEN` set, then run the following:

```go
package main

import (
	"context"
	"fmt"

	"gocloud.dev/blob"
	_ "gocloud.dev/blob/azureblob"
)

func main() {
	ctx := context.Background()
	bucket, err := blob.OpenBucket(ctx, "azblob://state")
	if err != nil {
		fmt.Printf("%s", err)
	}
	defer bucket.Close()

	err = bucket.Copy(ctx, ".pulumi/dst.json", ".pulumi/stacks/footest.json", nil)
	if err != nil {
		fmt.Printf("%s", err)
	}
}
```

results in:

```
===== RESPONSE ERROR (ServiceCode=AuthorizationPermissionMismatch) =====
Description=This request is not authorized to perform this operation using this permission.
RequestId:dc120964-f01e-0013-2473-32cc5e000000
Time:2021-04-16T03:49:35.2183190Z, Details: 
   Code: AuthorizationPermissionMismatch
   PUT https://leezenstatebackend.blob.core.windows.net/state/.pulumi/dst.json?se=2021-04-16t10%3A50%3A02z&sig=REDACTED&ske=2021-04-16t10%3A50%3A02z&skoid=4abf74a6-b744-43be-8ef2-e2bc53c429de&sks=b&skt=2021-04-16t02%3A50%3A02z&sktid=706143bc-e1d4-4593-aee2-c9dc60ab9be7&skv=2020-02-10&sp=racwdl&spr=https&sr=c&st=2021-04-16t02%3A50%3A02z&sv=2020-02-10&timeout=61
   User-Agent: [go-cloud/blob/0.1.0 Azure-Storage/0.12 (go1.16.2; darwin)]
   X-Ms-Client-Request-Id: [d9eaa086-311e-464f-69b9-adc172962af7]
   X-Ms-Copy-Source: [https://leezenstatebackend.blob.core.windows.net/state/.pulumi/stacks/footest.json?se=2021-04-16t10%3A50%3A02z&sig=REDACTED&ske=2021-04-16t10%3A50%3A02z&skoid=4abf74a6-b744-43be-8ef2-e2bc53c429de&sks=b&skt=2021-04-16t02%3A50%3A02z&sktid=706143bc-e1d4-4593-aee2-c9dc60ab9be7&skv=2020-02-10&sp=racwdl&spr=https&sr=c&st=2021-04-16t02%3A50%3A02z&sv=2020-02-10]
   X-Ms-Tags: []
   X-Ms-Version: [2019-12-12]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation using this permission.
   Content-Length: [279]
   Content-Type: [application/xml]
   Date: [Fri, 16 Apr 2021 03:49:35 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [d9eaa086-311e-464f-69b9-adc172962af7]
   X-Ms-Error-Code: [AuthorizationPermissionMismatch]
   X-Ms-Request-Id: [dc120964-f01e-0013-2473-32cc5e000000]
   X-Ms-Version: [2019-12-12]
```

This is true both with `v0.22.0` and previous commits (even going back to `v0.20.1-0.20201119163756-34afe72a0fb3`). 

On the other hand, the following succeeds in the same terminal:
`az storage copy -s https://leezenstatebackend.blob.core.windows.net/state/.pulumi/stacks/footest.json\?$AZURE_STORAGE_SAS_TOKEN -d https://leezenstatebackend.blob.core.windows.net/state/.pulumi/dst.json\?$AZURE_STORAGE_SAS_TOKEN`

```
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Azcopy command: ['/Users/leezen/bin/azcopy', 'copy', 'https://leezenstatebackend.blob.core.windows.net/state/.pulumi/stacks/footest.json?sv=2020-02-10&ss=bfqt&srt=sco&sp=rwdlacupx&se=2021-04-16T12:11:26Z&st=2021-04-16T04:11:26Z&spr=https&sig=REDACTED', 'https://leezenstatebackend.blob.core.windows.net/state/.pulumi/dst.json?sv=2020-02-10&ss=bfqt&srt=sco&sp=rwdlacupx&se=2021-04-16T12:11:26Z&st=2021-04-16T04:11:26Z&spr=https&sig=REDACTED']
INFO: Scanning...
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support
INFO: azcopy: A newer version 10.10.0 is available to download


Job 5544bb79-fab9-5840-55ac-a07049603e4c has started
Log file is located at: /Users/leezen/.azcopy/5544bb79-fab9-5840-55ac-a07049603e4c.log

0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total, 


Job 5544bb79-fab9-5840-55ac-a07049603e4c summary
Elapsed Time (Minutes): 0.0334
Number of File Transfers: 1
Number of Folder Property Transfers: 0
Total Number of Transfers: 1
Number of Transfers Completed: 1
Number of Transfers Failed: 0
Number of Transfers Skipped: 0
TotalBytesTransferred: 873
Final Job Status: Completed
```

I would expect these to behave more or less the same?

**Comment by vangent** [comment]
The URL (`https://leezenstatebackend.blob.core.windows.net/state/.pulumi/dst.json`) looks basically correct.

I have no info on what "az copy" does differently, sorry.

Can you check the permissions for the token? Maybe there's something missing there.
https://github.com/Azure/azure-storage-azcopy/issues/790 looks similar (old, but has some suggestions, and points to
https://azure.microsoft.com/it-it/blog/azure-storage-support-for-azure-ad-based-access-control-now-generally-available/).

Does this work with Go CDK `v0.21.0` as the initial report describes? If so, there are only 2 commits that might have caused the regression, please trying using those commits explicitly to see which one it is.

My best guess is that this is a regression in the `azblob` library that we picked up, and that you should report the bug to them. It's also possible they've already fixed it and you can explicitly update your go.mod file to pick up a later version with the fix.

`Copy` definitely works in Go CDK, here is the test log (and I just re-ran it):
https://github.com/google/go-cloud/blob/master/blob/azureblob/testdata/TestConformance/TestCopy/Works.replay

**Comment by leezen** [comment]
@vangent My minimal repro doesn't work with `v0.21.0` either. The problem with v0.21.0 is that it broke support for using SAS tokens per https://github.com/google/go-cloud/pull/2934. If I go back to v0.20.0 it works.

I think it's `8141b1f10adf4bfec5fd23b004cc9df6543741d0` -- when I use that commit, it doesn't work. Going to the commit before that (`07c60c44656243bb1c6e3d4bd4df758fc0aacc4a`) works, so as you suspected, it's from the SDK upgrade (just not going to 0.12.0, but going to 0.11.0)

Not related, but worth mentioning is that there is something odd about the permissions for a token (see details). That being said, I'm fairly sure I've eliminated that as an issue considering that `az copy` works?
<details>
When I create a SAS token at the container-level with full `racwdl` permissions via a user delegation key (the user has Storage Blob Data Owner and Storage Blob Delegator), the following request fails:
```
❯ curl https://leezentesting.blob.core.windows.net/pulumi-state/.pulumi/test.json\?comp\=properties\&restype\=account\&$AZURE_STORAGE_SAS_TOKEN
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.
RequestId:c607a5cd-101e-0037-35e1-327f37000000
Time:2021-04-16T16:58:49.4905026Z</Message></Error>%       
```

When I do the same using a SAS token created from the account key, the request succeeds. Using the successful SAS token with `az storage copy` works as expected.
</details>

**Comment by leezen** [comment]
I dug into this more and it appears to be because the implementation of `Copy` tries to set empty tags, which the SAS token likely won't have since the token isn't generated for a specific blob but for the account/container.

**Comment by leezen** [comment]
I've submitted https://github.com/google/go-cloud/pull/2988 which I've verified fixes the repro case I have in https://github.com/google/go-cloud/issues/2982#issuecomment-820898914

**Comment by vangent** [comment]
Thanks @leezen ! I cloned your PR because the change requires updating some golden files.
