### ISSUE TITLE
docstore/mongodocstore: Support for Mongo specific features

### ISSUE THREAD

**Issue by prateekj117** [google/go-cloud#2985]
### Is your feature request related to a problem? Please describe.
I might be missing something here, but AFAIK, `gocloud.dev` pkg does not support features like Indexes in MongoDB and doing complex queries using the Aggregation Pipeline in MongoDB.  

### Describe the solution you'd like
It would be great if `gocloud` would have support for these things. Would also like to know if they are planned for future releases, or if these things are not a priority right now.

**Comment by vangent** [comment]
`gocloud` provides commonly used, vendor-neutral generic APIs that you can deploy across cloud providers. It is not intended to include vendor-specific functionality.

That said, I believe that at least some queries generated by `mongodocstore` should use indices, although there's nothing specific in our code about that.

**Comment by prateekj117** [comment]
@vangent Ok. Sounds good. Thanks for the clarification !!!
