### ISSUE TITLE
gcppubsub: return message id of the published message

### ISSUE THREAD

**Issue by sahejsingh** [google/go-cloud#2986]
### Is your feature request related to a problem? Please describe.

Unable to log the message id of the just published gcp pubsub message

### Describe the solution you'd like

The problem is here: https://github.com/google/go-cloud/blob/master/pubsub/gcppubsub/gcppubsub.go#L324
The library does not let clients access `PublishResponse`.

### Describe alternatives you've considered

Alternative is to use google's library directly.

### Additional context

None.

**Comment by vangent** [comment]
Yes, it seems like we could have an `AfterSend` hook in addition to `BeforeSend`.
