### ISSUE TITLE
blob/tests: Refactor tests to not doing any Bucket provisioning, and take all inputs as constants

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#299]
As a first step toward making --record tests runnable by everyone, let's make tests use constants for their inputs (e.g., bucket name), replacing any existing flags, and update tests to not use anything other than the constants.

Tests should not create/destroy buckets either, do that manually for now.

So, the process for running AWS blob tests in --record would be:
1. Manually provision a bucket.
2. Update the constant(s) in s3blob_test.go to use your bucket name.
3. Run the tests.

There will be a separate follow-on bug for using Terraform to automate the provisioning.

**Comment by shantuo** [comment]
I'd suggest we can keep a long-live bucket for now and make its name a const. At least for AWS this should be fine since the bucket is not associated with a specific "project".

**Comment by vangent** [comment]
Yea, that's what we have for AWS right now. It is probably a good idea to have a shared GCP project for Go-Cloud members to use to limit churn. For example, if you're just adding a new testcase, you could run "go test --record --run <new test>" and only check in the new record file(s), instead of having to update all of the record files because the const changed.

**Comment by vangent** [comment]
Fixed in #311.
