### ISSUE TITLE
secrets/hashivault: Adding support for VAULT_ADDR and VAULT_TOKEN

### ISSUE THREAD

**Issue by stack72** [google/go-cloud#2990]
Hi,

would you be interested in accepting a PR that adds support for the 2 env vars above?

In order to not break existing users, I think the workflow should be:

check VAULT_SERVER_URL and if there then use it
if not exists, check VAULT_ADDR
else error as per https://github.com/google/go-cloud/blob/master/secrets/hashivault/vault.go#L88

then for the token, check VAULT_SERVER_TOKEN then VAULT_TOKEN and default to it not being there as per https://github.com/google/go-cloud/blob/master/secrets/hashivault/vault.go#L92

Thanks

Paul

**Comment by vangent** [comment]
Are these new env variables just aliases for the existing ones? If so, why would we need this?

**Comment by stack72** [comment]
The ones I linked are the official env vars suggested to be used when interacting with vault and seem to be the variables people set for things like terraform provider, cli etc

https://www.vaultproject.io/docs/commands#environment-variables

**Comment by vangent** [comment]
Ah, that makes sense then. Sure, a PR SGTM.

**Comment by stack72** [comment]
Awesome - as I said, I'll make sure to preserve the existing behaviour and then fallback to these new env vars - that way you can deprecate at a later time
