### ISSUE TITLE
secrets/azurekeyvault: Add support for private clouds (Azure Stack Hub)

### ISSUE THREAD

**Issue by sebtelko** [google/go-cloud#2995]
I'd like to open a discussion of how we can support Azure Stack Hub in the azurekeyvault package.
### Is your feature request related to a problem? Please describe.

This regexp prevents private clouds like Azure Stack Hub from using the azurekeyvault package:
https://github.com/google/go-cloud/blob/5f19477156214406d87ddea6e8ff967e7bf1dd46/secrets/azurekeyvault/akv.go#L211

### Describe the solution you'd like

I'd like this regexp relaxed such that a private cloud vault on the form `vault.region.external.com` can be used.

### Describe alternatives you've considered

Alternatively allow adding specific custom URIs that should be allow listed.

**Comment by vangent** [comment]
Is changing the regex the only required change?

**Comment by vangent** [comment]
Can you send a PR? Or at least give some examples of what it should match.

**Comment by sebtelko** [comment]
The problem is that the `region01.external.com` can't be known by the go-cloud package ahead of time.

An example that would work is:
```go
 keyIDRE = regexp.MustCompile(`^(https://.+\.vault\.(?:.*)/)keys/(.+)$`)
```

It just removes all the hardcoded domains and allows anything. I don't really see a problem with this though, the regexp groups are still captured correctly. We could restrict it a bit more but it might be better to just create a more helpful error message.

If that seems ok, I can make a pull request and add some tests that verify that the old behavior is retained for the URIs mentioned in the current regexp.

**Comment by sebtelko** [comment]
@vangent I've sent a PR. I opted for a little more restrictive regexp than `.*` and went with `[a-z\d-.]+` instead. That should match any characters allowed in that part of the key id.
