### ISSUE TITLE
blob: permission denied error when signing url running on GKE with workload identity

### ISSUE THREAD

**Issue by bkondakor** [google/go-cloud#2996]
### Describe the bug

My application is running on GKE with an SA that has `storage.Admin` access to my bucket. 
It can list and read files from the bucket with no problem, but when I try to create a signed url it throws a permission denied error:

```
error: blob (key "resource/7bd4b118-8ab4-48c2-9187-f66247de28ba") (code=Unknown):
     gocloud.dev/blob.(*Bucket).SignedURL
         /go/pkg/mod/gocloud.dev@v0.22.0/blob/blob.go:1071
   - rpc error: code = PermissionDenied desc = The caller does not have permission
```

### To Reproduce

Create bucket:
```
func getBucket(bucketName string) *blob.Bucket {
	ctx := context.Background()

	b, err := blob.OpenBucket(ctx, bucketName)

	if err != nil {
		log.Panicf("Failed to setup bucket: %s", err)
	}

	return b
}
```

Sign url:

`url, err := s.bucket.SignedURL(context.Background(), id, nil)`

## Expected behavior

Create signed url

### Version

	cloud.google.com/go v0.81.0
	cloud.google.com/go/storage v1.15.0 // indirect

**Comment by vangent** [comment]
Yes, that's what I meant by driver.

IIRC, on GKE you may be able to use a MakeSignBytes function to get it to work through IAM:

* https://github.com/google/go-cloud/blob/master/blob/gcsblob/gcsblob.go#L24
* https://github.com/google/go-cloud/blob/master/blob/gcsblob/gcsblob.go#L180

I think if you use the URL opener (e.g., https://github.com/google/go-cloud/blob/master/blob/gcsblob/example_test.go#L65), it might do that by default. If that doesn't work, then you do need to specify the private key, as described in https://pkg.go.dev/cloud.google.com/go/storage#SignedURLOptions; that's a requirement from GCS, not Go CDK.

**Comment by bkondakor** [comment]
Using `gcsblob` directly with a privatekey solved this issue for me, but are you planing to make it work through the URL opener? Or is it not possible? Right now it doesn't set the credentials correctly for url signing on GKE through blob.OpenBucket.

**Comment by vangent** [comment]
The URL opener supports a `private_key_path` parameter:
https://github.com/google/go-cloud/blob/master/blob/gcsblob/gcsblob.go#L207

**Comment by bkondakor** [comment]
Oh, I missed that. Thanks!
