### ISSUE TITLE
pubsub/gcppubsub: Allow configuration of batch size

### ISSUE THREAD

**Issue by davidsbond** [google/go-cloud#3003]
### Is your feature request related to a problem? Please describe.

The current gcppubsub driver does not have a way of configuring the amount of messages pulled at once, it's 1000 by default. With long running processing of messages, a single subscriber can sit with all the messages, while other subscribers may have waits between receiving messages.

### Describe the solution you'd like

Add the ability to configure the batch size for the gcppubsub driver. Seems that the `SubscriptionOptions` type is currently empty, and it could be added there and used to populate the `recvBatchOpts` parameter, which is always passed as `nil` in `OpenSubscription`.

### Describe alternatives you've considered

Only alternative is to reimplement the driver locally or fork the repo to add support for this.

**Comment by vangent** [comment]
`pubsub` actually does a dynamic computation to compute the batch size. It will start at `1`. See here:
https://github.com/google/go-cloud/blob/master/pubsub/pubsub.go#L421

`1000` is the configured maximum batch size for `gcppubsub`, but it should not be the case that you have multiple subscribers with imbalanced message load for an extended period. (There is a ramp-up time, so if you have lots of messages and a new subscriber, it will take a while to ramp up to requesting large batches).

Are you actually seeing the problem you're describing here? IIUC, the PR you sent would just restrict the maximum batch size, and I'm not sure that adds much value here. (The minimum batch size will still be 1).

**Comment by davidsbond** [comment]
Hey @vangent, thanks for taking a look. I'm a big fan of this package by the way!

I'm working on a piece to move some code coupled directly with GCP pub sub over to using gocloud. The original setup set the pubsub client to at most handle 1 message at a time with no extra concurrency or batching. 

We have subscribers performing potentially long jobs off the back of events sent via PubSub, and found with ordering keys enabled we were starting to build up a backlog where previously did not have one. 

Behind the scenes we assumed that one subscriber may have claimed many of the messages (up to that 1000), due to the batching and size of the backlog.

We see that with 8 instances working on a single subscription, some subscribers have long periods (5-20) minutes where they do not get given any events to process, which seemed odd as the number of unacked messages implies there'd be something for it to pick up.

We were also not able to use the "view messages" functionality in the GCP console, as pulling would always return nothing, which we thought lined up with the idea that one of the instances on the subscription had claimed all the outstanding messages.

Since our jobs can take minutes to run, we assumed the backlog was likely caused by not being able to explicitly limit how many messages each consumer of a subscription will deal with at one time

**Comment by davidsbond** [comment]
We also saw that the number of unacked messages would build up over time, then suddenly a very large batch would be asked several hours after the constant uptick of unacked messages. Which we thought lined up with our assumptions also

**Comment by vangent** [comment]
I think you can already configure this at the `pubsub` level.

The constructor `NewSubscription` (https://github.com/google/go-cloud/blob/master/pubsub/pubsub.go#L761) takes a `*batcher.Options` (https://github.com/google/go-cloud/blob/master/pubsub/batcher/batcher.go#L83), which allows you to configure the parallelism, minimum and maximum batch sizes.

**Comment by vangent** [comment]
Wait, hang on, that is used by drivers not by end users. Looking more...
