### ISSUE TITLE
blob/azureblob: add a way to use CLI auth

### ISSUE THREAD

**Issue by lukehoban** [google/go-cloud#3012]
As requested in https://github.com/pulumi/pulumi/issues/7251, it would be helpful to support `AZURE_STORAGE_AUTH_VIA_CLI` so that blob storage could be authenticated via CLI auth, similar to the existing `AZURE_KEYVAULT_AUTH_VIA_CLI` that was added in https://github.com/google/go-cloud/issues/2462.

**Comment by vangent** [comment]
I'd be happy to review a PR for this. The PR for the referenced issue #2462 should be a good starting point.

**Comment by vangent** [comment]
I believe that #3156 will fix this, as it supports using https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#DefaultAzureCredential, which should support CLI auth.

**Comment by vangent** [comment]
Fixed by #3156.
