### ISSUE TITLE
secrets: Provide API to sign digests

### ISSUE THREAD

**Issue by maguro** [google/go-cloud#3016]
It would be handy to be able to sign and verify digests.  Not sure if this would go into `secrets`.  I'm thinking that there's enough here to warrant a new `signatures` package.

**Comment by maguro** [comment]
fyi, I've started to flesh out what would go into this on my fork.

**Comment by vangent** [comment]
This sounds like a bigger feature change than we're going to accept here, but we're happy to link to your fork if you add it there.
https://github.com/google/go-cloud#project-status
