### ISSUE TITLE
pubsub: mempubsub: log if message sent to topic with no subscribers

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#3022]
### Describe the bug

The mempubsub fake does not support these operations in this order:

1. opening a topic
2. sending to it
3. opening a subscription to the topic
4. receiving from the subscription

### To Reproduce

Add this test to `mem_test.go`:

```go
func TestOpenTopicSendOpenSubscriptionReceive(t *testing.T) {
	ctx := context.Background()
	url := "mem://mytopic"
	topic, err := pubsub.OpenTopic(ctx, url)
	if err != nil {
		t.Fatalf("opening topic: %v", err)
	}
	msg := fmt.Sprintf("random: %d", rand.Int())
	topic.Send(ctx, &pubsub.Message{Body: []byte(msg)})
	sub, err := pubsub.OpenSubscription(ctx, url)
	if err != nil {
		t.Fatalf("opening subscription: %v", err)
	}
	timedCtx, cancel := context.WithTimeout(ctx, 3*time.Second)
	m, err := sub.Receive(timedCtx)
	if err != nil {
		t.Fatalf("receiving message: %v", err)
	}
	cancel()
	if string(m.Body) != msg {
		t.Errorf("received msg is %q, want %q", string(m.Body), msg)
	}
}
```

## Expected behavior

I expected the test to pass. Currently it fails by the context timing out while waiting to receive.

### Version

442d53e

**Comment by ijt** [comment]
I'd be happy to try my hand at writing a fix for this. Just want to first make sure we're in agreement that this is a problem.

**Comment by vangent** [comment]
I don't think this is a problem. I don't think that `mempubsub` is the only service for which subscribers only get messages that were sent after they subscribed. Certainly there's nothing in the API semantics that imply otherwise....

**Comment by jba** [comment]
I agree with Robert. If a pubsub service had to deliver already-sent messages to new subscribers, that would imply that it has to save them indefinitely. I think if you want that property then you want a data-streaming tool like Kafka, rather than pubsub messaging.

**Comment by ijt** [comment]
That's fair. Closing this.

**Comment by teja635** [comment]
I ran into this issue as well. It might be helpful to add an error message.

**Comment by jba** [comment]
We appreciate that there is a lot of interest in this. I've been bit by this non-bug too. But it can't be an error. If it was an error to subscribe to a topic to which messages had already been sent, then you'd never be able to join any topic that had been around for a while!

I can imagine that mempubsub (and only mempubsub) could write a log message describing the situation. Then at least during testing the developer would have some notice of the issue. Does that work for you all?

**Comment by ijt** [comment]
That might work. Alternatively, mempubsub could complain if you publish to a topic that doesn't yet have any subscribers.
