### ISSUE TITLE
mysql/postgres: Add an In-Memory SQL Store

### ISSUE THREAD

**Issue by amitsaha** [google/go-cloud#3023]
### Is your feature request related to a problem? Please describe.

A key problem involved with using the mysql/postgres packages (and just `database/sql` in general) is that of unit testing. And there's a few ways to do that, ranging from unit testing to more of a functional (local)/integration testing (non-local). It's true that the latter is what gives us the most confidence in our tests. However, it also involves a setup cost - one time initial setup cost, on-going maintenance and eventual give up to just user some version of a test database running non-locally. 

### Describe the solution you'd like

What if we could provide a SQL compliant in-memory data store as part go-cloud? Then, we wouldn't need to implement mock interfaces, and we also would be testing our code with "real" SQL database before moving onto the more stringent/production-similar integration testing. Essentially, the SQL equivalent of the [fileblob](https://pkg.go.dev/gocloud.dev/blob/fileblob) package or [memdocstore](https://pkg.go.dev/gocloud.dev@v0.23.0/docstore/memdocstore).

### Describe alternatives you've considered

- Mocks (For e.g. using https://pkg.go.dev/github.com/DATA-DOG/go-sqlmock)
- In-memory "real" DB solutions - such as tidb-lite for MySQL (https://github.com/WangXiangUSTC/tidb-lite)
- Container based functional/integration style testing

**Comment by vangent** [comment]
Please just use one of the existing in-memory database solutions. There are plenty, including free/open source ones:
https://en.wikipedia.org/wiki/List_of_in-memory_databases
