### ISSUE TITLE
gcsblob: Size() and Read() don't work correctly for a 0-length read

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#303]
After a 0-length read, Size() should be available. For GCS, it is not.

  r, _ := b.NewRangeReader(ctx, key, 0, 0)

Expected: r.Size() should be correct.
Actual: r.Size() is always 0.

In addition, doing a Read on r fails with "bad CRC on read: got 0".
We should document the expected behavior of Read for a Reader created with length=0.
-- Should always return error?
-- Should always succeed and read 0 bytes?

**Comment by shantuo** [comment]
We rely on GCP Go client library for GCS implementation and this may be a bug on the client library. Does it return an error on `b.NewRangeReader(ctx, key, 0, 0)`. I saw you didn't check it.

In our documentation we state "If length is 0, it will read only the metadata." which means `Size` should work in this case. If there is a bug at the underlying API we should add a fix on our end to ensure this.

**Comment by vangent** [comment]
No, there's no error for NewRangeReader, just 0 for Size, and error if you to try actually Read from it.

**Comment by vangent** [comment]
I've traced it into the GCS implementation. I can see the HEAD request going out, and the response coming back with a "Content-Length" header, but the *http.Response object has a ContentLength set to 0. The GCS code looks like it's doing the right thing, but the http library is not (?!?).

Looks a lot like https://golang.org/issue/4126, but that was fixed about 5 years ago.

**Comment by vangent** [comment]
Another update: a standalone Go program seems to do the right thing when making the HTTP HEAD request. I believe it must be affected by the use of TLS or something else about the underlying Transport. For the standalone program, the server is returning HTTP 2.0, whereas with the GCS library, it returns 1.1. Still investigating....

**Comment by vangent** [comment]
I've tracked this down to a bug in "github.com/dnaeon/go-vcr/recorder". It intercepts the HTTP response from the server, and always sets the body.ContentLength to the length of the body it received.

Filed https://github.com/dnaeon/go-vcr/issues/30.
