### ISSUE TITLE
postgres: change packages to use pgx instead of pq

### ISSUE THREAD

**Issue by jessie-hernandez-vi** [google/go-cloud#3036]
The postgres/awspostgres and postgres/gcppostgres packages internally use the "pq" driver. From the pq project's README at https://github.com/lib/pq#status:

> This package is effectively in maintenance mode and is not actively developed. Small patches and features are only rarely reviewed and merged. We recommend using pgx which is actively maintained.

Additionally, the pq library is very limited when it comes to using advanced features of PostgreSQL, such as binding arrays and working with JSONB types.

These packages should switch to using pgx, which is actively maintained and has advanced support for PostgreSQL.

**Comment by vangent** [comment]
Thanks for the suggestion.

Is it a backwards-compatible change? In particular, it looks like we use
https://godoc.org/github.com/lib/pq#hdr-Connection_String_Parameters

are those the same for pgx?

If yes, it seems like it should be pretty simple, would you care to send a PR?
If not, more care/design is needed.

**Comment by ushu** [comment]
pgx does not use database/sql internally but provides a compatibility layer (github.com/jackc/pgx/v4/stdlib) which allows registration of the driver and support for standard options, querying etc.
Then at any type you can cast the connection driver back to a pgx instance and call all the fancy methods.

**Comment by vangent** [comment]
Sorry, to be more clear I meant "is it a backwards compatible change for Go CDK?" I.e., if we make this change, is it opaque for our existing users?

**Comment by fulviodenza** [comment]
@vangent It seems like pgx open method requires more paramenters since pq requires only the context (https://github.com/lib/pq/blob/756b4d73db86a374aecc8bb20f134f8c4dc81a49/conn.go#L294) for the open function while pgx support function (https://github.com/jackc/pgx/blob/a413de981978e4100d5736af7aaa2b392511612f/conn.go#L350) does not require context but specific variables. I think this could not be opaque for the users. Correct me if I'm wrong or made any mistakes.

**Comment by vangent** [comment]
OK, it doesn't sound like we can make this change in a backwards-compatible way. We would have to add new packages/drivers. That seems like a reasonable idea, but we're preferring to keep Go CDK fairly stable at this point and not add new drivers. If you'd like to add one in a fork, please let us know and we'll add a link to it.
