### ISSUE TITLE
blob/gcsblob: ContentType "form-data; name=foo" is not supported

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#304]
If you try to Write to a blob with ContentType set to "form-data; name=foo", it fails with:

googleapi: Error 400: Media type 'form-data; name=foo' is not supported. Valid media types: [*/*], badContent

This works for AWS.

Fix for GCS, or figure out how to document/deal with deltas in what ContentTypes are supported.

**Comment by shantuo** [comment]
"form-data; name=foo" is the correct format for MIME type, but is not a "valid" one. The underlying service decides whether they want to take that. We only check for the format not the content. I think this one is similar to the naming difference between providers. Each of them may be slightly different and we cannot guarantee on that. I think what we can do is add related documentation, or links to the implementation, not the high level API. I agree we should discuss on the next planning how we want to better notify users to be careful of implementation differences.

**Comment by vangent** [comment]
Agree that we need to come up with an overall strategy for how to deal with provider differences. Some options include:

1. Enforce the most restrictive constraints in the API. This results in true portability, but less flexibility.
2. Don't do anything, and just document places where we are allowing anything through the API, but know that different providers have different rules.
3. Same as #2, but try to document all of the differences.
4. Same as #1, but just warn or provide some other way of letting the API user know that if they switch to a different provider implementation, the behavior may change.

**Comment by vangent** [comment]
Issue #315 is about the overall strategy; once we choose one we can apply it to ContentType validation.

**Comment by vangent** [comment]
Data validation for specific fields can still vary by provider (e.g., maximum length, format like this bug, etc.). I did a bunch of work to use escaping for specific characters, so that should be fairly portable.

We decided that the added complexity in the proposal for how to handle this (from #315) did not justify implementing it.

I think we should just leave this bug open for now, `Unplanned`.
