### ISSUE TITLE
blob/fileblob: Windows OpenBucket() call failing

### ISSUE THREAD

**Issue by amitsaha** [google/go-cloud#3070]
### Describe the bug

I am facing issues with coming up with the right `file:///` URL on Windows. As per the source code [documentation](https://github.com/google/go-cloud/blob/master/blob/fileblob/fileblob.go#L113), the following should work:
```file:///C:/myPath```

### To Reproduce

Run the test:

```
package main

import (
	"fmt"
	"log"
	"net/url"
	"path/filepath"
	"strings"
	"testing"

	"gocloud.dev/blob/fileblob"
)

func setupTestBucket(filesDir string) error {
	u, err := url.Parse(fmt.Sprintf("file:///%s", filesDir))
	if err != nil {
		return err
	}
	opts := fileblob.Options{
		URLSigner: fileblob.NewURLSignerHMAC(
			u,
			[]byte("super secret"),
		),
		CreateDir: true,
	}
	filesDir = strings.Replace(filesDir, "\\", "/", -1)	
	_, err = fileblob.OpenBucket("file:///"+filesDir, &opts)
	if err != nil {
		return err
	}
	return nil
}

func TestFileUploadTest(t *testing.T) {

	filesBucket := filepath.Join(t.TempDir(), "files-bucket")
	err := setupTestBucket(filesBucket)
	if err != nil {
		t.Fatal(err)
	}

}
```

When you run the test, you will see:

```
2021/10/09 12:33:30 C:/Users/amits/AppData/Local/Temp/TestFileUploadTest1184106158/001/files-bucket
--- FAIL: TestFileUploadTest (0.00s)
    c:\Users\amits\gocloud-fileblob-issue\bug_test.go:40: CreateFile c:\Users\amits\gocloud-fileblob-issue\file:\C:\Users\amits\AppData\Local\Temp\TestFileUploadTest1184106158\001\files-bucket: The filename, directory name, or volume label syntax is incorrect.
```

## Expected behavior

Expected the bucket to  be created successfully

### Version

`v0.24.0`

### Additional context

I am successful in creating the bucket when I omit the file URL scheme.

**Comment by vangent** [comment]
Methinks you are confusing `fileblob.OpenBucket` with the URL opener exposed in `blob`.

For `fileblob.OpenBucket` (https://pkg.go.dev/gocloud.dev/blob/fileblob#OpenBucket), you just pass the path, no "file:///" prefix.

For `blob.OpenBucket (https://pkg.go.dev/gocloud.dev/blob#OpenBucket), you pass a URL like the one in your sample code.

See the examples, https://pkg.go.dev/gocloud.dev@v0.24.0/blob/fileblob#example-OpenBucket vs https://pkg.go.dev/gocloud.dev@v0.24.0/blob/fileblob#example-package-OpenBucketFromURL.

If you know you are going to use `fileblob`, it's probably simpler to use the `fileblob.OpenBucket` opener. The advantage of the URL opener is that you can have the URL in a configuration file (for example), and the code itself doesn't need any knowledge at all of what kind of bucket is in use.

Hope that helps.

**Comment by amitsaha** [comment]
> Methinks you are confusing fileblob.OpenBucket with the URL opener exposed in blob.

You are absolutely right. I did confuse that. Thank you.
