### ISSUE TITLE
blob/fileblob: wrong ListPage result for certain pageSizes if a blob includes "-/"

### ISSUE THREAD

**Issue by websbg** [google/go-cloud#3089]
go version go1.16 linux/amd64
tested with v0.24.0 and master

**used file structure:**
		"testFile1",
		"t/t/t",
		"t-/t.",
		//"t0/t.", // instead of "t-/t." works well
		"dir1/testFile1dir1",
		"dir2/testFile1dir2",
		"d",

**Expected result with Prefix "" and Delimiter "/":**
d
dir1/
dir2/
t/
t-/
testFile1

**Unexpected result with pageSize 5 (2x t/):**
d
dir1/
dir2/
t/
t-/
t/
testFile1

**Unexpected result with pageSize 1/2/4 (missing t-/):**
d
dir1/
dir2/
t/
testFile1

The test is available on github: https://github.com/websbg/go_test_blob.git

**Comment by vangent** [comment]
Thanks for the detailed report!
