### ISSUE TITLE
docstore/mongodocstore: time.Time fields with pointers are not stored as ISODate

### ISSUE THREAD

**Issue by alexplischke** [google/go-cloud#3098]
### Describe the bug

Given a struct with a *time.Time field
```
StartTime *time.Time `docstore: "startTime,omitempty"`
```
will result in a DB entry like so:
```
starTime: BinData(0, 'AQAAAA7ZtDC/DsguAP//')
```

### To Reproduce

Simply create a struct with a *time.Time field and try to persist to mongo.

## Expected behavior

If the time.Time field is not a pointer
```
startTime time.Time `docstore: "startTime"`
```
the entry in the DB is actually:
```
startTime: ISODate('2022-03-04T16:54:54.150Z')
```

I'd expect
```
StartTime *time.Time `docstore: "startTime,omitempty"`
```
to result in an entry in the DB to be 
```
startTime: ISODate('2022-03-04T16:54:54.150Z')
```
as well.

Effectively, I'd expect there to be no difference for how time.Time is stored, whether it's a pointer (when it's not nil) or not.

The underlying mongo driver [says this](https://pkg.go.dev/go.mongodb.org/mongo-driver/bson#hdr-Structs):
> 4. A pointer field is marshalled as the underlying type if the pointer is non-nil. If the pointer is nil, it is
marshalled as a BSON null value.

### Version

v0.24.0

**Comment by vangent** [comment]
See #2754 -- this is not easy to fix, the recommendation is to follow the Go recommendation to use `time.Time`, not `*time.Time` (https://pkg.go.dev/time#Time).
