### ISSUE TITLE
mempubsub: Export Topic and Subscription for testing

### ISSUE THREAD

**Issue by phumberdroz** [google/go-cloud#3120]
### Feature Request

An easy way to test against gocloud pubsub would be appreciated. Using mempubsub we have a simple implementation that makes it already easy to plug something in that just "works".

### Describe the solution you'd like

Make it easy for me to test against mempubsub. For example testing against the absence of a message currently requires me to receive them and then timeout. Which makes it cumbersome in my opinion and does not make it very smooth if you have 100s of test cases. 

### Describe alternatives you've considered

none

### Additional context

I am not sure if mempubsub is supposed to be used for testing even? Maybe it dedicated "test" package improve the situation as well.

**Comment by vangent** [comment]
The intent of the Go CDK is that the API for the different providers is the same; we're not going to provide a special API for `mempubsub` that lets you peek into the internals. This is a feature! You can run your tests against `memsubsub`, and then run the same tests against a real provider.

If your test wants to verify that a message wasn't sent, maybe you could check for that explicitly (instead of implicitly via trying to receive it)? You're not testing Go CDK, you're testing your own code, right?

**Comment by phumberdroz** [comment]
Yes I am testing my own code. 

I thought this could be achieved via the `As` function of pubsub that expose internals of others like the Kafka implementation.
 
https://github.com/google/go-cloud/blob/master/pubsub/mempubsub/mem.go#L39 

https://github.com/google/go-cloud/blob/master/pubsub/mempubsub/mem.go#L361 if Subscription would be exported and Msgs be public it would help my particular case very well. At least that is my current thinking.

Maybe I am also mistaken in how I want to test my own code and I will review again my approach.

**Comment by phumberdroz** [comment]
If I would write a Merge Request for this would it be accepted @vangent ? :)

**Comment by vangent** [comment]
No, I don't think so. The intent for `As` is to give access to provider-specific features that aren't accessible via the Go CDK APIs. `mempubsub` doesn't have any provider-specific features.

You may want to reconsider how you are thinking about testing; peeking into the internals of another component's implementation seems like a sign that you're approaching it wrong. If you want to verify that a message is being sent, or not sent, you should be able to test that by instrumenting your own code where you send the message. Or, do what you suggested at the beginning and do a `Receive` with a short timeout; if you have a helper for that it shouldn't be cumbersome.
