### ISSUE TITLE
postgres: Support IAM auth for GCP

### ISSUE THREAD

**Issue by aebrahim** [google/go-cloud#3121]
### Is your feature request related to a problem? Please describe.

The cloudsql-proxy supports using [IAM database auth](https://cloud.google.com/sql/docs/postgres/iam-logins) but this package does not. This also means that packages that rely on this, such as the postgresql terraform module, must copy passwords around, as in the [example](https://registry.terraform.io/providers/cyrilgdn/postgresql/latest/docs#gcp).

### Describe the solution you'd like

I should be able to pass in an enable_iam_login parameter, and have it passed through to cloudsql-proxy. I really would love to be able to use that with the terraform postgresql package which relies on this.

### Describe alternatives you've considered

Otherwise, we have to keep throwing SQL password strings around, which is annoying and less secure. Alternately, switch to AWS, where this is [supported](https://github.com/cyrilgdn/terraform-provider-postgresql/pull/134).

### Additional context

I believe this can be implemented by doing the following (based on a cursory review of the code):

1. Add an iam auth option to `go-cloud/gcp/cloudsql/cloudsql.go`, and use that to set `EnableIAMLogin: true,` in `certs.RemoteOpts{}`
2. Add a url parameter for iam auth, and read it in from `lazyCredsOpener.OpenPostgresURL` (in `gcppostgres/gcppostgres.go`)
3. Filter out the url parameter from the previous step in `URLOpener.OpenPostgresURL` (in `gcppostgres/gcppostgres.go`) when doing parameter validation.

**Comment by vangent** [comment]
Any chance you could send a PR?

**Comment by aebrahim** [comment]
If the strategy looks good to you, will do!

**Comment by aebrahim** [comment]
@vangent I wrote #3122 - upon further reflection,  I didn't think a flag to enable/disable in the proxy made as much sense as having it always enabled - I believe the control of this feature makes the most sense in the database configuration, not the proxy.

**Comment by vangent** [comment]
I'm rolling back this change and reopening this due to the problem reported in #3164.

**Comment by vangent** [comment]
@aebrahim please feel free to try again.
