### ISSUE TITLE
secrets/localsecrets: secrets: "base64key" doesn't accept base64 keys that include "/" character 

### ISSUE THREAD

**Issue by shibukawa** [google/go-cloud#3123]
### Describe the bug

``base64key://`` schema ignores path part (after "slash")

### To Reproduce

This code is randomly failed.

```go
package main

import (
	"context"
	"encoding/base64"
	"fmt"

	"gocloud.dev/secrets"
	"gocloud.dev/secrets/localsecrets"
)

func main() {
	secretBytes, err := localsecrets.NewRandomKey()
	if err != nil {
		panic(err)
	}
	key := string(base64.StdEncoding.EncodeToString(secretBytes[:]))
	fmt.Println(key)
	secretKey := "base64key://" + base64.StdEncoding.EncodeToString(secretBytes[:])

	_, err = secrets.OpenKeeper(context.Background(), secretKey)
	fmt.Println(err)
}
```

```
open keeper base64key://moE/ITHHLA48xQT33fC8TYIexn/vLXuWtKDkRafSN98=: failed to get key: illegal base64 data at input byte 0
```

## Expected behavior

https://github.com/google/go-cloud/blob/452381bb74ab35ec65f6e50261f2e61f35b81149/secrets/localsecrets/localsecrets.go#L74

If the url contains path parameter, it should use it.

To use current implementation, we should avoid keys that contains "/", but the available key bit space should be smaller than 32bit and weaker than expected.

current implementation:

```go
sk, err = Base64Key(u.Host)
```

expected behavior:

```go
if u.Path != "" {
  sk, err = Base64Key(u.Host + "/" + u.Path)
} else {
  sk, err = Base64Key(u.Host)
}
```

### Version

v0.25.0

**Comment by shibukawa** [comment]
In addition to `/`, `+` causes same issue too.

**Comment by vangent** [comment]
Use `base64.URLEncoding`, not `base64.StdEncoding`. I'm sending a PR to remove the StdEncoding function in the package and clarify the documentation.

**Comment by shibukawa** [comment]
Thank you. I confirmed `base64.URLEncoding` works perfectly.
