### ISSUE TITLE
blob/[all] should support `MaxConcurrency` in addition to `PartSize`

### ISSUE THREAD

**Issue by richardartoul** [google/go-cloud#3127]
### Is your feature request related to a problem? Please describe.
We have several services that do a large number of concurrent uploads of files in several different clouds. The `PartSize` option is very useful for controlling allocation rates and memory usage, especially when I have an idea how large a file is going to be ahead of time. However, in addition to part size, all the cloud providers have some kind of configuration knob for concurrency. This value usually has a major impact on memory usage of the underlying libraries. As a result of this, I've started accumulating a lot of stuff like this in my application code:

```golang
if scheme == "s3" {
    var uploader *s3manager.Uploader 
    if asFunc(&uploader) {
        uploader.Concurrency = opts.Concurrency
    }
} else if scheme == "azblob" {
    var uploader *azblob.UploadStreamToBlockBlobOptions
    if asFunc(&uploader) {
        uploader.MaxBuffers = opts.Concurrency
    }
}
```

I think the `Concurrency` option is as important (if not more important) than the `PartSize` option as to warrant its own dedicated field in `*blobclient.WriterOptions` so that users can set appropriate values once and have reasonable behavior across all cloud environments.

As a point of reference, before I added the custom logic for Azure, some of my workloads were spending ~40-50% of *all* their CPU cycles just allocating buffers for uploads and after the change this dropped to < 5%. 

### Describe the solution you'd like
I'd like a field called `Concurrency` or something similar added to `*blobclient.WriterOptions` so that it can be used in cloud-specific implementation such as the s3blob and azblob to set fields like `upload.Concurrency` and `uploader.MaxBuffers` respectively.

### Describe alternatives you've considered

I cant think of any alternatives except for every user to maintain custom code using the `As` convention

### Additional context

![Screen Shot 2022-04-25 at 3 11 23 PM](https://user-images.githubusercontent.com/9171254/165174843-308e4275-bf0e-48f0-8412-7224c52ad757.png)

**Comment by vangent** [comment]
We generally only try to add things that apply to all of the major providers. I don't see any similar setting for GCS...?

**Comment by richardartoul** [comment]
You're right it looks like GCS always uses a default concurrency of 1. I still think this is a worthwhile change though.

**Comment by richardartoul** [comment]
Thank you for implementing this!
