### ISSUE TITLE
blob/gcsblob: add support for ReadAll of fsouza/fake-gcs-server

### ISSUE THREAD

**Issue by somen440** [google/go-cloud#3128]
As one of the many options, I would like to use gcsblob with the gcs emulator running at hand.

Specifically, here.
https://github.com/fsouza/fake-gcs-server

When used, WriteAll and List work as intended. But it doesn't work for ReadAll.

---

When there is a directory like the following

```
❯ tree
...
...
└── mock
    └── gcs
        └── sample-bucket
            └── hoge
...
...
❯ cat mock/gcs/sample-bucket/hoge 
hoge%      
```

Start docker as follows

```
docker run --rm --name fake-gcs-server -p 4443:4443 -v ${PWD}/mock/gcs:/data fsouza/fake-gcs-server -scheme http
```

Then, you can get the placed file as an object.

```
❯ curl -sL http://127.0.0.1:4443/storage/v1/b/sample-bucket/o/hoge | jq
{
  "kind": "storage#object",
  "name": "hoge",
  "id": "sample-bucket/hoge",
  "bucket": "sample-bucket",
  "size": "4",
  "crc32c": "BuYpEQ==",
  "md5Hash": "6nA+eqHv2gBk6qUH2eirfg==",
  "timeCreated": "2022-04-28T09:42:53.817208Z",
  "timeDeleted": "0001-01-01T00:00:00Z",
  "updated": "2022-04-28T09:42:53.817234Z",
  "generation": "0"
}
```

To do this in your code, set the following environment variables:

```
STORAGE_EMULATOR_HOST=127.0.0.1:4443
```

At this time, I expect the following test code to succeed.

```
func TestGcsSample(t *testing.T) {
	t.Parallel()

	ctx := context.Background()
	b, err := blob.OpenBucket(ctx, "gs://sample-bucket")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		_ = b.Close()
	})

	got, err := b.ReadAll(ctx, "hoge")
	if err != nil {
		t.Fatal(err)
	}
	if df := cmp.Diff(got, "hoge"); df != "" {
		t.Errorf("diff=%s", df)
	}
}
```

However, in reality, the following error is returned.

```
blob (key "hoge") (code=NotFound): storage: object doesn't exist
```

Looking at the emulator log, it was as follows.

```
time="2022-04-28T10:01:42Z" level=info msg="172.17.0.1 - - [28/Apr/2022:10:01:42 +0000] \"GET /sample-bucket/hoge HTTP/1.1\" 404 10"
```

This is synonymous with a request like

```
❯ curl -sL http://127.0.0.1:4443/sample-bucket/hoge  
Not Found
```

This is likely to be just my misconfiguration. But I couldn't read it 😢 
I would like advice on this

**Comment by vangent** [comment]
* What does the `GET` request in the emulator log for your successful `curl` look like?
* https://github.com/google/go-cloud/blob/master/blob/gcsblob/gcsblob.go#L298 should set the endpoint when using the emulator. It looks like it has `/storage/v1` in it; your URLs with that emulator have an additional `/b`, I'm not sure where that's coming from.

Maybe try prepending the bucket name with "b/"? E.g., `blob.OpenBucket(ctx, "gs://sample-bucket")`.

Or, try modifying the GoCDK code at the line above to include the extra `/b` and see if that helps.

**Comment by somen440** [comment]
success log

```
time="2022-04-30T23:45:14Z" level=info msg="172.17.0.1 - - [30/Apr/2022:23:45:14 +0000] \"GET /storage/v1/b/sample-bucket/o/hoge HTTP/1.1\" 200 296"
```

About `API GET /b/BUCKET/o/OBJECT` was here.
https://cloud.google.com/storage/docs/json_api/v1#objects

When I tried the test below, I got the same error here as well.

```go
func TestStorage(t *testing.T) {
	t.Parallel()

	client, err := storage.NewClient(context.TODO(), option.WithEndpoint("http://127.0.0.1:4443/storage/v1/"))
	if err != nil {
		t.Fatal(err)
	}
	r, err := client.Bucket("sample-bucket").Object("hoge").NewReader(context.TODO())
	if err != nil {
		t.Fatal(err)
	}
	defer r.Close()
	got, err := io.ReadAll(r)
	if err != nil {
		t.Fatal(err)
	}
	if df := cmp.Diff(string(got), "a"); df != "" {
		t.Errorf("diff=%s", df)
	}
}
```

We will continue to investigate, but this seems to be an emulator (configuration?) Issue rather than a go-cloud issue.
Thank you for your reply!

**Comment by somen440** [comment]
@vangent 
The cause has been found.
fsouza/fake-gcs-server does not have a public URL by default.

It was necessary to specify the public-host option for it to take effect. After selecting `-public-host` , I confirmed that this test passed. I apologize to you for a fuss over. There is no problem with closing this.
