### ISSUE TITLE
all: include common CLI along with go-cloud

### ISSUE THREAD

**Issue by suryarashmitha** [google/go-cloud#313]
Similar to abstracting cloud specific SDK's this CLI should abstract aws, gcloud, az.

**Comment by zombiezen** [comment]
This isn't something we're looking at right now, but it's possible for someone to build a CLI around the library primitives in Go Cloud. That would be really interesting and it would be cool to see.

**Comment by vangent** [comment]
We do have sample CLIs for each portable type (see `samples/`). I don't think we're going to do more than that.
