### ISSUE TITLE
pubsub/rabbitpubsub: move from `streadway/amqp` to `rabbitmq/amqp091-go`

### ISSUE THREAD

**Issue by Juneezee** [google/go-cloud#3132]
### Is your feature request related to a problem? Please describe.

The [github.com/streadway/amqp](https://github.com/streadway/amqp) module is no longer actively maintained. The author recommends migrating to [github.com/rabbitmq/amqp091-go](https://github.com/rabbitmq/amqp091-go) that is maintained by the RabbitMQ core team.

### Describe the solution you'd like

Replace the `github.com/streadway/amqp` package with `github.com/rabbitmq/amqp091-go`.

**Comment by vangent** [comment]
Thanks for the heads up. Thankfully it looks like a pure fork at least at this point so should be easy to switch.
