### ISSUE TITLE
Support for environment variables?

### ISSUE THREAD

**Issue by markdboyd** [google/go-cloud#3136]
### Describe the solution you'd like

I **think** I would like to load a runtime variable from an environment variable. From what I can tell, this implementation does not exist. `constantvar` seems to only support loading raw values. 

But I'm not sure if it makes sense to write an implementation of `runtimevar` for environment variables. Environment variables can change at runtime, so maybe? But I may be misunderstanding the intended or correct use of this package

### Describe alternatives you've considered

I could just get my value directly from `os.Getenv` and skip using `runtimevar`, but that would change [the internals of the `ossf/allstar` tool that I'm using](https://github.com/ossf/allstar/blob/main/pkg/ghclients/ghclients.go#L100).

I've also considered trying to use the `constantvar` adapter but since my variable is a private key with multiple lines, I'm not sure if this can/does work without logic to compact the value to a single line when setting the environment variable and expand the value to multiple lines when reading it.

**Comment by vangent** [comment]
> since my variable is a private key with multiple lines, I'm not sure if this can/does work without logic to compact the value to a single line when setting the environment variable and expand the value to multiple lines when reading it

Would that be any different for a `runtimevar` that supports reading the environment variable directly?

Do you actually expect your environment variable to change at runtime?

**Comment by markdboyd** [comment]
> Would that be any different for a runtimevar that supports reading the environment variable directly?

No, I guess that would be the expected behavior for a runtimevar that supports reading the environment variable

> Do you actually expect your environment variable to change at runtime?

No, I suppose not. So it seems like the best approach for me is to adapt my app code to just read the environment variable and not use the runtimevar package, unless you disagree.

If you agree then I guess this issue can be closed.

**Comment by markdboyd** [comment]
I guess I will say that a runtimevar plugin for environment variables would be a nice general purpose utility, just like the one for constantvar. If you think there is value in it, I can take a shot at implementing it, but if you don't see the value that's totally fine too.

**Comment by vangent** [comment]
I don't think that a changing environmental variable is common. So, the primary use case is a `runtimevar` that supports a value that came from an environment variable. I think `constantvar` plus a single line of code for `os.Getenv` seems to handle that fine.
