### ISSUE TITLE
blob: add origin and content-encoding to SignedURLOptions

### ISSUE THREAD

**Issue by iangudger** [google/go-cloud#3139]
GCS supports limiting signed URLs to a specific origin and setting a content-encoding for the signed URL. I am trying to convert an application to use blob, but it uses both of these features.

**Comment by vangent** [comment]
Sadly, I don't think that functionality isn't supported by the other providers, so you will have to use `As` functionality to do it if you need it (use `SignedURLOptions.BeforeSign`).
