### ISSUE TITLE
gcsblob: reader.ModTime() returns zero but the API returns it

### ISSUE THREAD

**Issue by evanj** [google/go-cloud#314]
The reader.modTime field is never updated: https://github.com/google/go-cloud/blob/master/blob/gcsblob/gcsblob.go#L54. This is sort of okay, since the [documentation for `ModTime()`](https://godoc.org/github.com/google/go-cloud/blob#Reader.ModTime) states: "This is optional and will be time.Time zero value if unknown" . However, the underlying HTTP response includes the modification time in the `Last-Modified` header. Unfortunately, `cloud.google.com/go/storage` does not parse it. Perhaps that library should do so, or at least this library should explicitly call [ObjectHandle.Attrs()](https://godoc.org/cloud.google.com/go/storage#ObjectHandle.Attrs) if NewRangeReader length == 0, so it is possible to get the modification time in some way.

My use case: I am synchronizing files from one source to another, and it can be useful to check the modification time to determine if something is likely to need to be copied. This works fine for s3 but not for GCS.

**Comment by shantuo** [comment]
We chose not to call `ObjectHandle.Attrs` to save the network request as the `Last-Modified` is returned from the HTTP response, instead, we'd like to fix the Go client library of GCS to fix this. We filed https://github.com/GoogleCloudPlatform/google-cloud-go/issues/1091 to track.

**Comment by evanj** [comment]
I think fixing google-cloud-go is the "best" fix, so if that is easy that is great. However to clarify my suggestion if changing that library is hard: when `length == 0`, call `ObjectHandle.Attrs()` *instead* of calling `ObjectHandle.NewRangeReader()`. This would be similar to `s3blob.NewRangeReader` which [returns a special `newMetadataReader` result in this case](https://github.com/google/go-cloud/blob/master/blob/s3blob/s3blob.go#L172).

**Comment by vangent** [comment]
Sounds reasonable to me. We'll get ModTime for 0-length reads via Attrs; we still won't get it for >0-length reads, pending the fix for GoogleCloudPlatform/google-cloud-go#1091.

**Comment by vangent** [comment]
I'm marking this fixed; there's still the same issue for non-zero length reads, but it's blocked by GoogleCloudPlatform/google-cloud-go#1091.

**Comment by vangent** [comment]
Issue #335 is the new one I just filed.
