### ISSUE TITLE
blob: http.ServeContent support

### ISSUE THREAD

**Issue by Merovius** [google/go-cloud#3142]
### Is your feature request related to a problem? Please describe.

I would like to serve blob contents via HTTP. I would like to support caching and range-requests. The simplest way to get that would be to use [http.ServeContent](https://pkg.go.dev/net/http#ServeContent), together with setting the `ETag` and `Content-Type` header. However, that requires a `ReadSeeker`, to determine the size (and do Content-Type sniffing, but that can be prevented by setting the header pre-emptively).

Duplicating the logic `ServeContent` implements based on getting the necessary information from `*blob.Reader` and `*blob.Attributes` directly is pretty cumbersome.

### Describe the solution you'd like

The easiest solutions I can imagine, by preference are

1. Adding a `Seek` method to `*blob.Reader`. This is probably infeasible for backwards compatibility with 3rd party drivers
2. Adding a separate `NewReadSeeker` method to `*blob.Bucket` which returns an `io.ReadSeeker`

### Describe alternatives you've considered

It might be possible to add a more flexible `ServeContent` implementation to `net/http` (i.e. go even further up the stack for even more re-usability) but given the API surface that would probably need and given how reluctant the Go project is to add API surface, this seems like a long-shot.

It would be possible to add a helper to `gocloud.dev` which re-implements the logic of `http.ServeContent` based on a blob. That way, it at least only has to happen once. This is less flexible than having `ReadSeeker` blob though, as the latter can also be used with other code which needs to seek. But it would serve me just as well.

Arguably, `io.ReaderAt` is a similarly interesting interface to support, but it's at least not as immediately important to me.

**Comment by vangent** [comment]
I did some investigation. It does not appear to be easy to implement `io.ReadSeeker` on top of the major providers.

* GCP returns an `io.Reader` (https://pkg.go.dev/cloud.google.com/go/storage#Reader) and doesn't look like they plan to change it (https://github.com/googleapis/google-cloud-go/issues/1124).
* Azure returns an `io.ReadCloser` (https://pkg.go.dev/github.com/Azure/azure-storage-blob-go/azblob#DownloadResponse.Body).
* S3 returns an `io.ReaderCloser` (https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#GetObjectOutput).

As such, I don't think it makes sense for Go CDK `blob` to expose this.

I *think* it should be possible to create an `io.ReadSeeker` from an `io.Reader` plus a length, which we do have. I spent a a few minutes looking for this and haven't found it yet though.

**Comment by Merovius** [comment]
My current solution is this:

```go
type object struct {
	ctx    context.Context
	bucket *blob.Bucket
	key    string
	attr   *blob.Attributes

	r    *blob.Reader
	offs int64
}

func newObject(ctx context.Context, b *blob.Bucket, key string) (*object, error) {
	attr, err := b.Attributes(ctx, key)
	if err != nil {
		return nil, err
	}
	return &object{
		ctx:    ctx,
		bucket: b,
		key:    key,
		attr:   attr,
	}, nil
}

func (o *object) Read(p []byte) (n int, err error) {
	if o.r == nil {
		r, err := o.bucket.NewRangeReader(o.ctx, o.key, o.offs, -1, nil)
		if err != nil {
			return 0, err
		}
		o.r = r
	}
	n, err = o.r.Read(p)
	o.offs += int64(n)
	if err == io.EOF {
		o.r.Close()
		o.r = nil
	}
	return n, err
}

func (o *object) Seek(offs int64, whence int) (int64, error) {
	switch whence {
	case io.SeekStart:
	case io.SeekCurrent:
		offs += o.offs
	case io.SeekEnd:
		offs = o.attr.Size - offs
	default:
		panic(fmt.Sprintf("invalid whence %d passed to Seek", whence))
	}
	if offs < 0 || offs > o.attr.Size {
		return o.offs, errors.New("seeking to invalid offset")
	}
	o.offs = offs
	return offs, nil
}

func (o *object) Close() (err error) {
	if o.r != nil {
		err = o.r.Close()
	}
	o.r = nil
	return err
}
```

This isn't super nice and it probably isn't super performant. But it shows that in principle, it should be possible to do this.

Ultimately, all of this is just HTTP. As long as you have `Range` requests, it should be possible to support both `ReadSeeker` and `ReaderAt`.

Another solution for my problem I've considered (but not yet tried) is to implement [fs.FS](https://pkg.go.dev/io/fs#FS) on top of a `*blob.Bucket` and use [http.FileServer](https://pkg.go.dev/net/http#FileServer) with that - in theory, that doesn't need seeking. And after all, every problem in Computer Science can be solved with another layer of indirectio. But really, I'd be happier if a couple of such layers could be unwound, given that they apparently hide important capabilities.

**Comment by vangent** [comment]
Have you considered using `SignedURL` and letting the provider serve the blob over HTTP?

**Comment by Merovius** [comment]
@vangent I have. That doesn't work with `fileblob`, which I want to support.

**Comment by vangent** [comment]
`fileblob` does kind of support `SignedURL`: https://pkg.go.dev/gocloud.dev@v0.25.0/blob/fileblob#URLSigner

**Comment by vangent** [comment]
Take a look at https://github.com/google/go-cloud/pull/3145 and let me know what you think.

I am a bit unsure if this should get committed here, as it really has nothing to do with Go CDK or `blob`. It's just an implementation of a `io.ReadSeekCloser` given an `io.ReadCloser`.

**Comment by Merovius** [comment]
> `fileblob` does kind of support `SignedURL`: https://pkg.go.dev/gocloud.dev@v0.25.0/blob/fileblob#URLSigner

I don't understand. AIUI this provides an API to create URLs, but I don't see how that would solve the problem. The client must still be able to reach a web server under that URL, which brings me back to square one - how to build a web server which can serve a `*blob.Bucket` well.

> Take a look at #3145 and let me know what you think.

I don't think this is a good idea. If there is a multi-gigabyte blob and a user makes a range-request for a chunk towards the end, it requires reading the entire blob before serving the request.

At the core, the existence of `*blob.Bucket.NewRangeReader` (and the fact that it's the base method used) implies that there already is first-class support to read a specific range of bytes. To me, that implies that in principle, it should be possible to implement `ReadSeeker` and `ReaderAt` for all blob backends.

But, ultimately, I don't even necessarily need a `ReadSeeker`. I just want to avoid having to copy `http.ServeContent` to support range requests and cache headers and all.

**Comment by vangent** [comment]
Yea, you are right that `NewRangeReader` should be sufficient. I'm not sure how efficient it will be in various scenarios, especially if (offset=0, length=-1) is provided, it will re-read potentially large amounts of the `blob` after `Seek`.

Take a look at https://github.com/google/go-cloud/pull/3145 and let me know what you think. It adds `Seek` to `blob.Reader`. I'm not aware of any providers implemented outside of this repo, but regardless it's a change in the concrete type, not the driver, so it should be fine.

**Comment by vangent** [comment]
(if you could patch the PR and give it a try that would be awesome!)

**Comment by vangent** [comment]
I think I was clever enough to make it so that `http.ServerContent`'s pattern of doing ` Seek` to the end to figure out the `ContentLength`, then a `Seek` back to the beginning, is free (i.e., no extra reads). I can't make any promises about the content sniffing part, it's quite likely that at least some providers will read a big chunk of the blob for the sniff, and then re-read it for the actual content.

**Comment by Merovius** [comment]
The content sniffing can be prevented by setting `Content-Type` manually, so that's totally fine.
I'm going to try it out later today.

**Comment by Merovius** [comment]
I tried this out using

```go
	p := strings.TrimPrefix(path.Clean(r.URL.Path), "/")
	attr, err := h.storage.Attributes(r.Context(), p)
	if err == nil {
		br, err := h.storage.NewReader(r.Context(), p, nil)
		if err != nil {
			log.Printf("NewReader(%q) = %v", p, err)
			http.Error(w, "Internal Server Error", http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", br.ContentType())
		w.Header().Set("ETag", attr.ETag)
		http.ServeContent(w, r, p, br.ModTime(), br)
		return
	}
```

And `curl -H 'Range: bytes=512-1023'  -v <url>` sets all the right headers and satisfies the range request. So, as best I can tell, this seems to be working great.
