### ISSUE TITLE
blob/fileblob: file permissions are inconsistent

### ISSUE THREAD

**Issue by calebbrown** [google/go-cloud#3165]
### Describe the bug

The file permissions used when creating files and directories are inconsistent:

They are as follows (before umask is applied):

- Directories: `0o777` (created via `os.MkdirAll`)
- Blobs: `0o600` (created via `ioutil.TempFile` and moved in-place)
- Attrs: `0o666` (created via `os.Create`)

This means that while the dirs can be traversed and the attrs can be read, the blob itself is inaccessible.

### To Reproduce

Using code like:

```go
b, err := blob.OpenBucket(ctx, "file:///output/)
if err != nil {
  return err
}
defer b.Close()

w, err := b.NewWriter(ctx, "test/hello_world.txt", nil)
if err != nil {
  return err
}
if _, err := w.Write([]byte("hello, world!")); err != nil {
  return err
}
if err := w.Close(); err != nil {
  return err
}
```

We see file permissions like the following when run as root:
```shell
$ ls -l /output/path
drwxr-xr-x 2 root root  4096 Sep 14 15:32 .
drwxr-xr-x 3 root root  4096 Sep 14 15:32 ..
-rw------- 1 root       root              13 Sep 14 15:28 hello_world.txt
-rw-r--r-- 1 root       root             212 Sep 14 15:28 hello_world.txt.attrs
```

## Expected behavior

Either:
- files created by `fileblob` are created using the filemode `0o666` and have umask applied; or
- files and dirs can have custom permissions set.

Ideally I should see the following when running `ls` with a root umask of `0o022`:
```shell
$ ls -l /output/path
drwxr-xr-x 2 root root  4096 Sep 14 15:32 .
drwxr-xr-x 3 root root  4096 Sep 14 15:32 ..
-rw-r--r-- 1 root       root              13 Sep 14 15:28 hello_world.txt
-rw-r--r-- 1 root       root             212 Sep 14 15:28 hello_world.txt.attrs
```

### Version

0.25, 0.26

### Additional context

We are using code similar to above inside a Docker container. We mount a volume in the container for fileblob to write into, even though the host user has access to the folder, the container uses uid=0, gid=0, which makes the blobs unreadable even though the rest of the file structure is.

**Comment by calebbrown** [comment]
I'm happy to do the work myself of adding something like the following during `Close()` when the tempfile is moved, if this is deemed acceptable:

```go
umask := syscall.Umask(0)
syscall.Umask(umask)
err := os.Chmod(filename, fs.FileMode(0o666 & ^umask))
```

**Comment by vangent** [comment]
Hmm. I'm not sure I like the `syscall` approach as I'm not sure that's portable...?

https://stackoverflow.com/questions/35337046/ioutil-tempfile-and-umask discusses this same issue but there's no great answer there.

Perhaps the best approach is to stop using `ioutil.TempFile` and instead use `file.Create` with a timestamp suffix or something.

https://cs.opensource.google/go/go/+/refs/tags/go1.19.1:src/os/tempfile.go;drc=f78efc0178d51c02beff8a8203910dc0a9c6e953;l=18
https://cs.opensource.google/go/go/+/refs/tags/go1.19.1:src/os/tempfile.go;drc=334a591a3f4d868368913328b3e81ddf5b0f46fa;l=42

Happy to take a PR for this.
