### ISSUE TITLE
[Q] getting delivery_attempt from gocloud.dev/pubsub

### ISSUE THREAD

**Issue by garan82** [google/go-cloud#3168]
I'm using gocloud.dev/pubsub to work with google cloud pubsub and I'm wondering if delivery_attempt  from gcp pusub is accessible from gocloud.dev/pubsub wrapper? I couldn't find it anywhere, and if it's not accessible via API, is there a way to pull this info?

Thank you!

**Comment by vangent** [comment]
It is not directly accessible, as it's not a cross-provider concept. If you need to access it I think you should be able to use`As`:
https://gocloud.dev/concepts/as/

Example:
https://github.com/google/go-cloud/blob/master/pubsub/gcppubsub/gcppubsub_test.go#L249

**Comment by garan82** [comment]
Thanks!
