### ISSUE TITLE
[question] Cross cloud deployment (without terraform?)

### ISSUE THREAD

**Issue by vsoch** [google/go-cloud#3171]
Hi! I was attracted to this project because it looks like you have nice interfaces to communicate with storage (and a few other flavors of things) across clouds. However, for deployment of something to an instance (e.g., GCP compute engine vs. AWS EC2) it looks like you fallback to using terraform (in your guestbook example):

https://gocloud.dev/tutorials/guestbook/

Are there any plans for a unified API (akin to storage) to interact with compute? Even for very basic deployments? Thanks!

**Comment by vangent** [comment]
No. We have explicitly stayed out of the deployment space; there are other products (like Terraform).

https://github.com/google/go-cloud/blob/master/internal/docs/design.md#developers-and-operators has some discussion.

**Comment by vsoch** [comment]
Thanks! I'm surprised that Terraform is the only game in town.

**Comment by vangent** [comment]
https://google.com/search?q=terraform+alternatives

:-)

**Comment by vsoch** [comment]
I'm not looking for infrastructure as code or complex servers - I want a simple Go SDK that can bridge clouds. I know how to use Google and I've done those searches - do you have a specific suggestion?

**Comment by vangent** [comment]
I guess I am not clear what you are looking for. I thought you were looking for Go APIs to deploy things to Cloud compute infrastructure. The search links to several beyond Terraform, including Pulumi, Kubernetes, Cloudify.

**Comment by vsoch** [comment]
- Kubernetes: is a specific orchestration tool - it's great but overly complex for my needs! I'm wanting to interact with Google Cloud Compute Engine, and AWS EC2, for example
- Pulumni looks neat, but also seems to require deploying its "platform" first (e.g., `pulumi up`)
- Cloudify also seems to be a platform? I'm not an enterprise manager I'm a developer that wants to install an SDK, plug in some credentials, and get to work!

Sorry if we aren't communicating well, but I don't see all the tools that you are suggesting that are simple clients to interact with Cloud APIs given API tokens - all appear to be fairly complex setups.

**Comment by vangent** [comment]
Yea sorry. I think the fact that all the cross-platform deployment solutions are relatively complex is a) a reason we want to stay out of that space, and b) an indication that the problem is in fact somewhat complex. It might be possible to do very simple things simply, but almost everyone transitions from that to doing something not-so-simple, and having something simple that people have to throw away when their use case gets more complicated is not great.

I haven't used all of the above, but Terraform is pretty simple to get started with.

**Comment by vsoch** [comment]
Gotcha, thanks!

**Comment by praneetloke** [comment]
@vsoch 

> Pulumni looks neat, but also seems to require deploying its "platform" first (e.g., pulumi up)

Not really. It's similar to Terraform, except, you can use its Go SDKs to deploy infrastructure on several cloud providers.

You might also want to checkout [Klotho](https://klo.dev).
