### ISSUE TITLE
Unexpected pseudo-version used with current trunk commit

### ISSUE THREAD

**Issue by AaronFriel** [google/go-cloud#3176]
If I run `go get gocloud.dev@8e881d1a26277fb4f4a54a175a7d27f12e87fa68` to try out the change in #3175, the version resolved is `v0.26.1-0.20221021211714-8e881d1a2627`.

That's unexpected, because v0.27.0 was released so the pseudo-version should be greater than or equal to it as the most recently released version. It looks like something unusual happened and the commit associated with that tag is **not** the commit that's part of master history. [That commit](https://github.com/google/go-cloud/tree/v0.27.0) "does not belong to any branch on this repository, and may belong to a fork outside of the repository.".

This causes some issues with trying the update as if any dependencies depend on 0.27.0, the Go version resolution policy prefers 0.27.0 over the pseudo-version.

Would it be possible to tag commit 8e881d1a26277fb4f4a54a175a7d27f12e87fa68 with a named prerelease version, like `0.28.0-beta.1`?

**Comment by vangent** [comment]
TBH I am not sure how this happened or how to fix it. Presumably it will go away during the next release...?

Until then, can you try things out on a fork?

**Comment by AaronFriel** [comment]
Yeah that's fine! It's a fluke of Go module version resolution, the tag `0.27.0` isn't in the history of the main branch, so it finds `0.26.0`. I've seen it happen myself when someone manually tags a release using the commit on a branch that then gets squashed or rebased onto the main branch.
