### ISSUE TITLE
blob: add IBM Cloud Object Storage support

### ISSUE THREAD

**Issue by dalcorta** [google/go-cloud#3177]
### Is your feature request related to a problem? 
I would like to be able to read from IBM Cloud Bucket using this library.  IBM supports a sdk in golang but I would like to use this library to be able to make it platform agnostic.

### Describe the solution you'd like

Implement IBMs sdk in this package 

### Describe alternatives you've considered

I tried IBM go sdk for cloud storage but would like to fuse it in one code base.

### Additional context

[https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-using-go](IBM Cloud Object Storage SDK)

**Comment by vangent** [comment]
Sorry, this is unlikely to happen.

Per https://cloud.ibm.com/docs/cloud-object-storage/api-reference?topic=cloud-object-storage-compatibility-api, IBM Cloud Object Storage "supports a subset of the S3 API" -- could you try using `s3blob`?

In fact the Go examples on the page you linked to look like they are using the `aws` library:
https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-using-go#go-new-bucket
