### ISSUE TITLE
writer.Close()  failed and return PermissionDenied error

### ISSUE THREAD

**Issue by ddl-killer** [google/go-cloud#3179]
writer.Close()

Close writer failed.

error: 
code=PermissionDenied):
   gocloud.dev/blob.(*Writer).Close
        /go/pkg/mod/gocloud.dev@v0.24.0/blob/blob.go:341
  - googleapi: Error 403: ..........@...........iam.gserviceaccount.com does not have storage.objects.delete access to the Google Cloud Storage object., forbidden"

**Comment by vangent** [comment]
This is working as intended and expected.

Per https://pkg.go.dev/gocloud.dev/blob#Writer.Close, `Close closes the blob writer. The write operation is not guaranteed to have succeeded until Close returns with no error.`

In this case, it looks like you are trying to write on top of an existing blob, and GCS requires the `storage.objects.delete` permission to do that (https://stackoverflow.com/q/66129154), which makes sense.
