### ISSUE TITLE
internal/contributebot: add pull request linting

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#318]
See the [design doc](https://github.com/google/go-cloud/blob/master/internal/contributebot/DESIGN.md#pull-request-linting) for this check.

(Continuation of #216)

**Comment by shantuo** [comment]
- [ ] Add check run for license headers of added files
- [ ] Add check run for go.mod lint
- [ ] Add first differing commit message linting (issue reference, format, etc.)
- [ ] Add check run/comment for adding new contributor to CONTRIBUTORS file.
