### ISSUE TITLE
docstore: add support for custom data types

### ISSUE THREAD

**Issue by thomascristofaro** [google/go-cloud#3190]
### Is your feature request related to a problem? Please describe.

I'm trying to use custom data types in database model (like [gorm](https://gorm.io/docs/data_types.html)), but it seems impossible, ex.:
```go
type customFieldString struct {
	Value   string
	Filter  string
	Opts    []int
}
type dbModel struct {
	field1  string
	field2  customFieldString
}
```
At the moment `dbModel.field2` would be decoded/encoded like a struct.
I couldn't find any way to use it like a string (using `dbModel.field2.Value`)

### Describe the solution you'd like

I'd like a way to decode/encode a custom types. 
It might be an interface. You could define and manage in codec.go.

I already forked your project and I tried this implementation:
1. I defined two interfaces in [codec.go](https://github.com/google/go-cloud/blob/e942f3c339f0eb617ac4dbc7f37cc4e5920ee7cc/docstore/driver/codec.go)
```go
type CustomMarshaler interface {
	CustomMarshal(enc Encoder) error
}
type CustomUnmarshaler interface {
	CustomUnmarshal(dec Decoder) bool
}
```
2. I added the code to manage the interfaces in [encode](https://github.com/google/go-cloud/blob/e942f3c339f0eb617ac4dbc7f37cc4e5920ee7cc/docstore/driver/codec.go#L118) and [decode](https://github.com/google/go-cloud/blob/e942f3c339f0eb617ac4dbc7f37cc4e5920ee7cc/docstore/driver/codec.go#L379) functions:
```go
func encode(v reflect.Value, enc Encoder) error {
        ...
        if v.Type().Implements(customMarshalerType) {
		return v.Interface().(CustomMarshaler).CustomMarshal(enc)
	}
	...
}

func decode(v reflect.Value, d Decoder) error {
	...
	if reflect.PtrTo(v.Type()).Implements(customUnmarshalerType) {
		if v.Addr().Interface().(CustomUnmarshaler).CustomUnmarshal(d) {
			return nil
		}
		return decodingError(v, d)
	}
	...
}
```
3. Now we just have to implement the interfaces in the main code:
```go
func (f customFieldString) CustomMarshal(enc Encoder) error {
	enc.EncodeString(f.Value)
	return nil
}

func (f *customFieldString) CustomUnmarshal(dec Decoder) bool {
	s, ok := dec.AsString()
	if ok {
		f.Value = s
	}
	return ok
}
```
4. I tested with codec_test.go

What do you think? It could be an helpful implementation or you don't need it?

**Comment by vangent** [comment]
Can you implement `encoding.TextMarshaler`? Won't that do the same thing?

**Comment by thomascristofaro** [comment]
Yes, with `encoding.TextMarshaler` you'll do the same thing.
I used the wrong example.

we can change the example with a float type value:
```go
type customFieldFloat struct {
	Value   float
	Filter  string
	Opts    []int
}
```
In this case I don't think `encoding.TextMarshaler` can help us, personally I wouldn't translate all data type in string.
In gorm, we just should implement the interfaces scanner/valuer

**Comment by vangent** [comment]
`encoding.BinaryMarshaler`? My point is that I'm not sure why we need to create a new marshaler interface, the codec already supports several and you can choose one of them to implement for your type.

**Comment by thomascristofaro** [comment]
Yes, I understand your point, but `encoding.BinaryMarshaler` can't help me, the data on db won't be understandable by human.
My point is just about numbers (int and float) and booleans. 
I have to codec these kind of variable with `encoding.TextMarshaler`?
There aren't others marshaler for these types?

**Comment by vangent** [comment]
What would these other marshalers marshal to other than text or binary?

**Comment by thomascristofaro** [comment]
Int, float and boolean

**Comment by vangent** [comment]
OK. TBH, this doesn't seem that important to me, but the fix you've suggested also seems straightforward, and it sounds like you've implemented it already. Can you send a PR for me to review?

**Comment by vangent** [comment]
I think the answer here is to please use `Text` or `Binary` marshaller.
