### ISSUE TITLE
how to use with localstack?

### ISSUE THREAD

**Issue by tsolodov** [google/go-cloud#3192]
I am trying to migrate from AWS libraries to go-cloud.

I am trying to make `go-cloud` to connect to local sqs service running on http://localhost:4566

I tried to play with URL, but don't see any attempts to connect:
```
	topicName := "awssqs://localhost:4566/000000000000/queue.fifo?region=us-west-2&awssdk=v2"
	topic, err := pubsub.OpenTopic(ctx, topicName)
	if err != nil {
		return err
	}
	return nil
```
Error(it looks like the request goes to AWS API endpoint:
```
{"error": "pubsub (code=Unknown): operation error SQS: SendMessageBatch, https response error StatusCode: 403, RequestID: 4a136f8f-bdf5-53ba-a2ae-33aad97767da, api error InvalidClientTokenId: The security token included in the request is invalid.", "errorVerbose": "pubsub (code=Unknown):\n    gocloud.dev/pubsub.newSendBatcher.func1\n        .... go/pkg/mod/gocloud.dev@v0.27.0/pubsub/pubsub.go:331\n  - operation error SQS: SendMessageBatch, https response error StatusCode: 403, RequestID: 4a136f8f-bdf5-53ba-a2ae-33aad97767da, api error InvalidClientTokenId: The security token included in the request is invalid."}
```

+ I am running port-forward to localstack deployment running on local kind k8s cluster, any new TCP connection is seen in console. I do not see any attempts to connect to `localhost:4566`:
```
 kubectl port-forward -n default svc/localstack 4566


Forwarding from 127.0.0.1:4566 -> 4566
Forwarding from [::1]:4566 -> 4566

```

**Comment by vangent** [comment]
Per https://pkg.go.dev/gocloud.dev/pubsub/awssnssqs#URLOpener, the hostname/port in the URL sets the queue URL, not the endpoint.

Perhaps try setting the endpoint parameter?
https://pkg.go.dev/gocloud.dev/aws#ConfigFromURLParams

**Comment by tsolodov** [comment]
Thanks!

Works with: 
```
&endpoint=127.0.0.1:4566&disableSSL=true
```
