### ISSUE TITLE
pubsub: visibility timeout set to 0 on Nack for SQS

### ISSUE THREAD

**Issue by dubonzi** [google/go-cloud#3193]
We have migrated from using the SQS SDK to Go CDK and are already in production with it. Our queues have a 5min visibility timeout but after taking a look at the source code I found that calling Nack sets the visibility timeout for that message to 0.

Our processing involves calling external services and we had a problem last night where one of them was degraded, so the 0 timeout made it so the messages were being retried almost instantly, which caused the service to degrade even further. 

Why isnt the visibility timeout being respected? I read through https://github.com/google/go-cloud/issues/2871 but didn't really understand the reasoning. Spawning goroutines doesn't seem like a good solution since a lot of messages can get held up which could increase our memory usage unexpectedly.

Edit: would it be possible to maybe make it configurable via a URL param like its done for `waittime` and `raw`? Something like `bypassVisibilityTimeout` (true/false).

**Comment by vangent** [comment]
Makes sense; sent a PR for a "NackLazy" mode. In that mode, `Nack` doesn't do anything, and the message will be retried after its existing visibility timeout expires.

**Comment by dubonzi** [comment]
Awesome! I was gonna work on PR for it but you were fast heheh.

Looking at the `gcppubsub` code, I see the same is done by modifying the message deadline. I don't have experience with it, but would it be possible to also support the same configuration for it?

**Comment by vangent** [comment]
Yup, will do for `gcppubsub`.

> Also, will not 'Nacking' not trigger the warning message 'A pubsub.Message was never Acked or Nacked' ?

That message happens if you never call `Nack`. The implementation here is that you call `Nack`, but the driver code does nothing with it. So, you won't see that warning.

(You could get similar behavior by not calling nack at all in your app, but then you would see the warning).
