### ISSUE TITLE
pubsub: ability to customize/disable logging

### ISSUE THREAD

**Issue by dubonzi** [google/go-cloud#3196]
### Is your feature request related to a problem? Please describe.

Might be applicable to other packages aswell.

Right now, as far as I can see, the standard `log` package is being used for logging without the ability to customize or even disable it. We use a different format for logging and the plain text format this package prints is breaking our log parsing. 

### Describe the solution you'd like

The package should provide a way to customize its logging, with the option to disable it altogether if necessary. Maybe a good solution could be having a way to pass in a logger implementation based on a common interface defined by the package.

### Describe alternatives you've considered

I haven't tried alternatives because I couldn't really think of any.

**Comment by vangent** [comment]
Which logging are you referring to? I don't see much:

```
$ grep -r "log\." | grep -v "_test.go"
pubsub.go: log.Printf("A pubsub.Message was never Acked or Nacked%s", caller)
mempubsub/mem.go:               log.Print("warning: message sent to topic with no subscribers")
```

IIUC, neither of those should really happen in a normal and well-written application.

(We've largely tried to not log for the reasons you describe).

**Comment by dubonzi** [comment]
While waiting for https://github.com/google/go-cloud/issues/3193 's release, we started skipping calling `Nack` for messages that failed to be processed, which means "A pubsub.Message was never Acked or Nacked" is being logged. Even then, since the issue's solution does just that, the log will still be printed for each message. 

I guess a way to disabling logging would be sufficient.

**Comment by vangent** [comment]
> Even then, since the issue's solution does just that, the log will still be printed for each message

That's not true. If your application calls `Nack`, it won't be printed.

The Go CDK doesn't do any logging other than a few cases like the above where it's a clear application bug. There's no `INFO` logging. As such, I don't think it's worth the complexity to provide hooks to disable it or format it.

If you prefer, I believe you can use https://pkg.go.dev/log#SetOutput to send the output of the standard logger through a formatter or to `io.Discard`. Note that this affects anything using the standard logger in your app though, not just Go CDK.

**Comment by dubonzi** [comment]
> That's not true. If your application calls Nack, it won't be printed.

Oh that was my misunderstanding then, thanks for clarifying!

> If you prefer, I believe you can use https://pkg.go.dev/log#SetOutput to send the output of the standard logger through a formatter or to io.Discard.

Haven't thought about that, should be ok for us to do it.
