### ISSUE TITLE
secrets/azurekeyvault: Use DefaultAzureCredential to load credentials

### ISSUE THREAD

**Issue by yorinasub17** [google/go-cloud#3198]
### Is your feature request related to a problem? Please describe.

Currently the [DefaultClientMaker](https://github.com/google/go-cloud/blob/master/secrets/azurekeyvault/akv.go#L160) for the `azurekeyvault` driver for `secrets` has logic to use either the Azure CLI Credentials or Environment Credentials, presumably carried over from the legacy `autorest` logic.

This has a problem where it doesn't support Azure Managed Identity or AKS Workload Identity based credentials, as those aren't based on CLI or environment variables.

### Describe the solution you'd like

In the new `azidentity` package, there is a [DefaultAzureCredential](https://github.com/Azure/azure-sdk-for-go/blob/f8cb16d25c435299b972737b2021aa1854d95e07/sdk/azidentity/default_azure_credential.go#L31) which will use a credential chain to select the proper credential depending on what is configured. Switching to this will allow selecting the configured credentials for the environment, and also add support for the aforementioned missing creds types, without requiring an additional input parameter or logic in `go-cloud`.

The least disruptive change would be to replace the `azidentity.NewEnvironmentCredential` call with `azidentity.NewDefaultAzureCredential`, but since `DefaultAzureCredential` includes the CLI credentials in the chain, I believe we could just replace the whole routine and remove the need for the `AZURE_KEYVAULT_AUTH_VIA_CLI` env var.

Happy to open a PR if this makes sense!

### Describe alternatives you've considered

Currently I'm working around this by manually loading the keeper using the driver calls directly, providing it the manually constructed client:

```go
		creds, err := azidentity.NewDefaultAzureCredential(nil)
		if err != nil {
			return nil, err
		}

		parsed.Scheme = "https"
		vaultURI := parsed.String()

		return azurekeyvault.OpenKeeper(
			func(keyVaultURI string) (*azkeys.Client, error) {
				return azkeys.NewClient(keyVaultURI, creds, nil)
			},
			vaultURI, nil,
		)
```

But this weakens the benefit of using a library like gocloud.dev, so would be great if it can be addressed in the library!

**Comment by vangent** [comment]
Thanks for the report. IIRC I made a similar change for `blobl/azblob`. Using `azidentify.NewDefaultAzureCredential` sounds good, sent a PR.

I am amazed at how much churn the Go libraries for Azure have. I am constantly having to rewrite code to keep up. Google and Amazon are much more stable.
