### ISSUE TITLE
internal/contributebot: allow webhook listener to rotate secrets

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#320]
In the case of a [GitHub webhook secret](https://developer.github.com/webhooks/securing/#setting-your-secret-token) being compromised, the webhook listener should be able to rotate the secret without dropping messages. The idea would be that the webhook listener would receive a new secret, accept both for a while, the secret would be changed on GitHub side, and then the listener would be notified to stop accepting the old secret. Ideally, this could happen without restarting the listener.

**Comment by zombiezen** [comment]
Do the simplest thing possible: redeploying is fine, document the process.

**Comment by shantuo** [comment]
Right now we can do redeploying. One possible option is to use runtimevar+kms to rotate the secrets.

**Comment by shantuo** [comment]
Redeploying is fine for now. I think there are several options:

1. Add a staging status for the updated one and flip when the key is updated.
2. Use runtimevar+kms to manage and upload the key.
3. Issue multiple keys, let the app store the past keys, and have a way to mark a certain key invalid, this may be combined with 1 or 2.

I'll do some experiments.
