### ISSUE TITLE
pubsub: configure concurrency for receive/send

### ISSUE THREAD

**Issue by dubonzi** [google/go-cloud#3203]
### Is your feature request related to a problem? Please describe.

Is it possible to configure the amount of goroutines used for receiving and sending messages while using the `pubsub` package?

I see that I can call each implementation's `OpenSubscription` and pass an options object with these settings, but not when using the generic package. Is there a way we could make it work? Maybe through a query variable in the uri.

I'm raising this issue because the queues i'm consuming (sqs at the moment) have a low number of messages being sent, which leads to a very high number of empty receives, increasing costs for us. For comparison, before migrating to this package, I had only 2 goroutines receiving from the queue, which was enough for the throughput we currently have.

### Describe the solution you'd like

A way of configuring the concurrency for receiving and sending messages

### Describe alternatives you've considered

I thought about refactoring to use specific implementations, but I think that would maybe defeat the purpose of the `pubsub` package, since we use rabbitmq for local tests instead of sqs, and it's been working well with that.

**Comment by vangent** [comment]
What do you mean by "the generic package"? The concrete type in the base package doesn't have any constructors, you can only create instances using the driver-specific constructors.

From your description, IIUC you don't actually care about the number of goroutines; rather, you want to reduce the number of calls to `ReceiveMessage`. Is that accurate? If so, try setting the `WaitTime` parameter (`waittime` in the URL) to a longer duration: https://pkg.go.dev/gocloud.dev@v0.27.0/pubsub/awssnssqs#SubscriptionOptions.

**Comment by dubonzi** [comment]
Setting `waittime` increased the overall latency of the application, cpu usage and gc time. I'm not sure why, it was the only change made and didn't make sense since this should have reduced the amount of outgoing calls to AWS.

My application has an infinite `for` calling `subscription.Receive` and feeds messages received from it to a channel which is being consumed by a pool of worker goroutines. It was working well using the AWS SDK directly and I didn't change it after migrating to Go CDK. Is there some adaptation I should have made for Go CDK?

**Comment by vangent** [comment]
> having more configurable parameters via the URL

I have been adding these on demand, so if there's something in particular you want it's relatively easy to add. It's add in the driver-specific code though, since the URLs are driver-specific.

**Comment by vangent** [comment]
> Setting waittime increased the overall latency of the application, cpu usage and gc time.

I'm not sure why this would be happening either. IIRC, `pubsub` starts with an expected number of messages of 1, with concurrency 1 goroutine calling `ReceiveMessage`. It will ramp up to bigger batches and more parallelism if there are lots of messages, but it sounds like your queue doesn't have a lot of traffic so I wouldn't expect it to ramp up.

Would it be possible for you to patch Go CDK to add some debug logging near here:
https://github.com/google/go-cloud/blob/master/pubsub/awssnssqs/awssnssqs.go#L999

to see how often the application is calling AWS.ReceiveMessage and with what parameters?

**Comment by dubonzi** [comment]
> Would it be possible for you to patch Go CDK to add some debug logging near here:

I can try to setup something locally to test it out. 

I took another look at the source code, I dont yet have a lot of knowledge but I saw a few constants that seem to be used to determine if `ReceiveMessage` should be called again, `desiredQueueDuration` and `expectedReceiveBatchDuration`.

Since my application is basically always calling `pubsub.Receive` (I have 200 worker goroutines and they are never fully busy), does that mean it'll try to fetch as many messages as fast as possible? If true, would setting `waittime` to 20s cause the package to have more open connections to aws since it might have to wait the whole 20s before returning? It _could_ maybe explain the increase in active goroutines and cpu usage after I added `waittime` to the URL. This is just a guess of course.

**Comment by vangent** [comment]
> does that mean it'll try to fetch as many messages as fast as possible 

I don't think so. There's a lock:
https://github.com/google/go-cloud/blob/master/pubsub/pubsub.go#L546

so no matter how many goroutines you have calling `Receive`, only one of them will be actively doing something inside that loop.

You could add some debug logging inside `pubsub.Receive` as well if you want to verify that.

**Comment by vangent** [comment]
Interesting. Can you add some more logging inside pubsub.go `updateBatchSize` to see what it's doing and returning? That's the function that's supposed to dynamically tune how many messages we're looking to read at a time based on recent throughput. Given 1 message read, I wouldn't expect it to do much. And, log something near line 667 (	`batches := batcher.Split(nMessages, s.recvBatchOpts)` ) to see what we're passing to that function (`nMessages`) and what it's returning.

I'll also see if I can repro this more on my side.

**Comment by vangent** [comment]
I think I've been able to reproduce something that doesn't look right using `mempubsub`. I'm still trying to figure out exactly what tickles it.

Out of curiousity, why do you have a reader separate from the worker pool? Why not

```
for i := 1; i <= maxWorkers; i++ { // (maxWorkers = 3 during the tests)
    go func() {
                 msg, _ := pubsub.Receive(ctx)
                 log.Printf("started processing [ %s ]\n", msg.Data)
		time.Sleep(time.Second * 5) // added this to simulate processing since I was running locally
		log.Printf("finished processing [ %s ]\n", msg.Data)
                msg.Ack()
        }
    }()
}
```

I don't think it will make a difference (unless possibly if `msgChan` has a buffer), but it's simpler.

**Comment by vangent** [comment]
See https://github.com/google/go-cloud/pull/3205 for a test that does bad things with `mempubsub`. It reads as fast as possible, and writes a message every 333ms, so given that `mempubsub` sleeps for 250ms when there's no message there, it should settle down with a batch size of 2. It doesn't, the batch size goes to very large values.

**Comment by vangent** [comment]
FYI, I think the original request in this bug to be able to configure concurrency isn't correct. The `pubsub` concrete type is doing a bad job of estimating your throughput, and thus driving the concurrency high. It shouldn't do that.

**Comment by vangent** [comment]
@dubonzi I think that I've fixes this, can you try again with the latest commit?

**Comment by dubonzi** [comment]
I just did a quick test and seems like the latest commit fixed it, or at least improved it by quite a lot. With the same test scenario as before, there were a max of 2 calls to `ReceiveBatch`, I let it run for a while and it didn't ramp up like before. Im going to see how it performs in production and will report back later.

Thanks for taking a look at this!

**Comment by dubonzi** [comment]
> FYI, I think the original request in this bug to be able to configure concurrency isn't correct. The `pubsub` concrete type is doing a bad job of estimating your throughput, and thus driving the concurrency high. It shouldn't do that.

I didn't know it tried to estimate the throughput at the time, now it makes sense that isn't really a reason to be able to configure it, since it's being calculated by `pubsub`.

**Comment by dubonzi** [comment]
Big improvement overall! Application latency also went down. Guess we can close this.
![image](https://user-images.githubusercontent.com/795838/211321659-6089c095-cdb9-4623-8c86-23f5229f46aa.png)

**Comment by vangent** [comment]
Awesome, glad that worked. Thanks for working with me to figure out what the problem was!
