### ISSUE TITLE
all: migrate aws-sdk-go to aws-sdk-go-v2

### ISSUE THREAD

**Issue by AaronFriel** [google/go-cloud#3220]
### Is your feature request related to a problem? Please describe.

Migrating to the new SDK places the project on surer footing, using the currently supported SDK and reduces module weight. See: https://aws.github.io/aws-sdk-go-v2/docs/migrating/

### Describe the solution you'd like

Updates to packages such as blob/s3blob to use the new SDK.

### Describe alternatives you've considered

n/a - alternatives are absurd, i.e.: reimplement AWS SDK from scratch.

### Additional context

The AWS SDK for Go is still in GA, that is, there is no immediate risk of the aws-sdk-go v1 beocming unsupported. 

That said, the newer SDK reduces dependency weight and is likely to be more actively maintained.

**Comment by vangent** [comment]
Already done?

E.g.,

https://pkg.go.dev/gocloud.dev@v0.28.0/blob/s3blob#OpenBucketV2

https://pkg.go.dev/gocloud.dev@v0.28.0/blob/s3blob#URLOpener
("Use "awssdk=v1" to force using AWS SDK v1, "awssdk=v2" to force using AWS SDK v2, or anything else to accept the default.")

**Comment by AaronFriel** [comment]
Ah, my issue is intended to describe a migration that involves removing the aws-sdk-go dependency, as it's ~250MiB. As it stands, from a dependency size and security perspective right now we've got the worst of both. 

From a compatibility perspective, of course I understand needing to gracefully migrate clients over to awssdk=v2.

**Comment by vangent** [comment]
Sorry, I'm not sure how to make that happen and maintain backwards compatibility.... and I'm not sure of the timeframe in which it would be OK to drop v1.

**Comment by AaronFriel** [comment]
That makes sense.

I was looking at why CI takes so long to build a project and `gocloud.dev` was a substantial portion of the CI time and cache usage. Updating to the v0.28 which from my PR & your help removed `azure-sdk-for-go` reduced the dependency weight by about 500MiB.

This is not an urgent issue, if you think it makes sense to close because it's premature feel free. I think this would be a good goal for some vNext in the future or a v1/v2 release of gocloud.dev. There are some really heavy packages in the dependency graph.

**Comment by vangent** [comment]
This is a known issue and not likely to change, sorry. It's inherent in having a multi-cloud library that we're going to have dependencies from multiple cloud providers (and in some cases, multiple dependencies even from one cloud provider).

If at some point AWS announces they are no longer supporting `v1`, I would be OK with removing the `v1` code in Go CDK, but I don't think that will happen for O(years) and probably wouldn't help that much anyway (it might get rid of another 500MB, but you're still including GCS, Azure, etc.).

If you have ideas on how to reduce the dependency graph while still keeping support for multiple providers, let me know. I believe it is only a CI issue, at runtime Go won't load libraries you aren't using.

**Comment by AaronFriel** [comment]
You're right that it's primarily a CI and developer loop issue. Starting with a clean cache or when switching between projects using different versions of gocloud.dev causes large download times, poor developer experience.

For what it's worth the PR you helped move across the finish line removed 500MiB of Azure dependencies. Perhaps it's worth revisiting: why do we have `awssdk=v2` and `awssdk=v1` when the latter can be made a drop-in replacement for the former? Are there defaults this library isn't setting that it could set, so that awssdk=v1 can be removed and that query parameter made obsolete?

**Comment by vangent** [comment]
> the latter can be made a drop-in replacement for the former

It can't though. The constructors and various `As` functions include types that are from either `v1` or `v2`. I could get rid of `v1`, but it would require all users of Go CDK to update their code to use AWS v2 in order to keep using Go CDK, which I'm not really comfortable doing. I felt more comfortable with that for Azure because a) I believe there are fewer users, although it's hard to be sure, and b) Azure has been very aggressive about the upgrade, essentially stopping support for the old version while the new one was still in beta (twice), while AWS (as far as I can tell) continues to support both.

I work for Google so I'm not super in touch with what AWS is doing; if there's some evidence that some high percentage of users have updated to the AWS V2 APIs or will be forced to do so soon that would be good to know.

**Comment by AaronFriel** [comment]
That makes sense, thanks! 

I'd still be interested in a future v1/v2 release that removed legacy cloud APIs, but understand that's far enough off that it doesn't make sense to track in this issue.

**Comment by khrm** [comment]
@vangent Amazon has announced the end of support for v1.
Can we now remove this?

https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-go-v1-on-july-31-2025/

**Comment by khrm** [comment]
I created a new issue to track this. If any help is required on this, then please inform.
