### ISSUE TITLE
all: run Windows CI

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#323]
It would be good to run the tests on Windows to shake out any development issues with using this library with Windows. [Appveyor](https://www.appveyor.com/) seems to be the preferred way to do this.

**Comment by peter-evans** [comment]
Travis now supports windows so I tested the build and there are a number of issues as you can see here:
https://travis-ci.org/peter-evans/go-cloud/jobs/445444398

I'm trying to tackle the `cannot find package "example.com/foo"` errors. The cause of the error is the forward slash in the package path. I attempted to fix it using `filepath.FromSlash` which converts to an os-specific separator, but then for some reason it escapes the back slash twice at some later point.

**Comment by zombiezen** [comment]
@peter-evans Cool! Thank you for looking into this! We would really appreciate having the Windows build!

Those are the Wire tests, which run a semi-simulated Go build. The slash in the import path is correct: Go import paths don't change even if OS path separator is different. But in examining the tests, they do translation back and forth between slash-separated and OS-specific paths. It's quite plausible it's incorrect right now, so you would need to examine the data flow to progress.

**Comment by zombiezen** [comment]
@peter-evans I believe I have fixed the path separator issue in the Wire tests in #616, but I don't have a Windows machine I can confirm with right now. Please give it another try and see if you still run into issues.

**Comment by vangent** [comment]
I send #621 to try enabling the Windows build, and it looks like all tests passed! So I don't think there's anything more to do here.

**Comment by zombiezen** [comment]
Sadly, it does seem like there is more work: https://travis-ci.com/google/go-cloud/jobs/156718327

Rolling back with #622

**Comment by vangent** [comment]
@peter-evans feel free to take another look at this!
