### ISSUE TITLE
blob: Minio Support

### ISSUE THREAD

**Issue by safaci2000** [google/go-cloud#3240]
### Is your feature request related to a problem? Please describe.

Support for Open Source "Bucket" libraries like ceph and minio would be great.  

It would be particularly useful for testing/validating behavior to avoid the need of having a cloud resource as a dependency for a test.

### Describe the solution you'd like

Add support for minio OR provide documentation on how this can already be accomplished

### Describe alternatives you've considered

Attempted to use S3, but couldn't find a way to configure it.

**Comment by vangent** [comment]
You should be able to use Minio via the S3 driver: https://min.io/product/s3-compatibility. Same for ceph: https://docs.ceph.com/en/latest/radosgw/s3/.

https://github.com/google/go-cloud/issues/1526 has an example config I think.
