### ISSUE TITLE
gcerrors: Allow external modules to use gcerr.Error 

### ISSUE THREAD

**Issue by telnet2** [google/go-cloud#3242]
### Is your feature request related to a problem? Please describe.

I am attempting to create blob support for Oracle Cloud Object Storage. There are functions that need to return the `gcerr.Unimplemented` error code. However, `gcerr.New` is defined in the `internal/gcerr` package, which cannot be imported from external modules. Therefore, we cannot use `gcerrors.Code` to extract the error code in a standardized way.

### Describe the solution you'd like

**Option 1:** Add `gcerrors.New` function so that external packages can create `gcerr.Error` 
**Option 2:** Create a new `Error` structure similar to `gcerr.Error`, and add a support for the new `Error` structure to `gcerrors.Code`.

Or, is it recommended to use `bucket.ErrorCode`?

**Comment by vangent** [comment]
I think you should be able to use `s3blob` for Oracle Cloud Object storage:
https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm

**Comment by telnet2** [comment]
> I think you should be able to use `s3blob` for Oracle Cloud Object storage: https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm

There was a few advantages using the OCI GO SDK directly, for example, using policy-based authentication instead of creating custom secret keys. I confirmed with Oracle folks that the compatibility API didn't support it.

**Comment by vangent** [comment]
Does this answer your question?
https://github.com/google/go-cloud/issues/2779#issuecomment-636418168

**Comment by telnet2** [comment]
duplicate to #2779
