### ISSUE TITLE
blob: user-agent header is incorrect

### ISSUE THREAD

**Issue by tritone** [google/go-cloud#3244]
### Describe the bug

I noticed that when using GCS blob methods, the user-agent header sent to the server(`google-api-go-client/0.5 go-cloud/blob/0.1.0`) references an old version of the library rather than the current one. This is confusing for debugging.

I think this needs to be updated with each library release: https://github.com/google/go-cloud/blob/7b4db4c8657791210bc999f09b713e9ac1401b05/internal/useragent/useragent.go#L27 . I have no idea where the incorrect version of google-api-go-client is coming from, though.

### To Reproduce
Run the following with `GODEBUG=http2debug=1` enabled:
```
func main() {
	ctx := context.Background()
	b, err := blob.OpenBucket(ctx, "my-bucket")
	if err != nil {
		log.Fatalf("OpenBucket: %v", err)
	}
	defer b.Close()

	attrs, err := b.Attributes(ctx, "file.txt")
	if err != nil {
		log.Fatalf("b.Attributes: %v", err)
	}
	log.Printf("attrs: %+v", attrs)
}
```
In the log output I see the following header sent to the server: `Transport encoding header "user-agent" = "google-api-go-client/0.5 go-cloud/blob/0.1.0"`

## Expected behavior

User agent header describes the correct version of the library.

### Version

gocloud.dev v0.29.0
cloud.google.com/go/storage v1.29.0
google.golang.org/api v0.110.0

**Comment by tritone** [comment]
Okay, can we reopen this as a feature request, then? It makes it much easier to debug and reproduce customer issues if an accurate library version is reported. FWIW, in the GCS client libraries we use the current library release; e.g storage currently sends `gcloud-golang-storage/1.29.0`. The AWS SDK seems to do something [similar](https://github.com/aws/aws-sdk-go/blob/e2d6cb448883e4f4fcc5246650f89bde349041ec/aws/corehandlers/user_agent.go#L13) and adds in the language version as well.

**Comment by vangent** [comment]
What's the difference between `cloud.google.com/go/storage` and "the GCS client libraries"? Go CDK uses the regular Go client for GCS, so I would have thought that if it was reporting the version correctly, we'd at least get that.

(Acknowledged that the Go CDK == `gocloud.dev` version is hardcoded and incorrect).

**Comment by vangent** [comment]
Bumped the useragent header to `0.32.0` as part of the latest release.
