### ISSUE TITLE
blob/s3blob: escapeKey converts "//" incorrectly

### ISSUE THREAD

**Issue by sides-flow** [google/go-cloud#3246]
### Describe the bug
The escapeKey function doesn't escape the key correctly when using a folder with the name `/`.

I have the following s3 bucket:
<img src="https://user-images.githubusercontent.com/88621685/236699384-3cf0e577-2447-49d4-bacd-54106535219e.png" width="400" height="300" />

The `test/` folder contains:
<img src="https://user-images.githubusercontent.com/88621685/236699514-6cf0641e-d12e-46d1-99c1-a71631acd5df.png" width="400" height="300" />

The `/` folder inside `test/` contains:
<img src="https://user-images.githubusercontent.com/88621685/236699534-554210eb-33a3-492f-a77e-d6b309bca7a6.png" width="400" height="300" />

Diagram:
```
my_bucket:
- test/
    - /
      index.html
```

When I use `bucket.List(nil)` to iterate over the objects and try to read the object `s3://my_bucket/test//index.html`, I encounter the error `blob (key "test//index.html") (code=NotFound): operation error S3: GetObject, https response error StatusCode: 404, RequestID: ...`

When debugging the code, I discovered that the `escapeKey` function turns the key from `test//index.html` into `test/__0x2f__index.html`:
![image](https://user-images.githubusercontent.com/88621685/236699709-29597d35-0d12-4ed9-b269-1acc8157aaf4.png)

When I skip over the call to `escapeKey`, the method is successful and I get a `reader` that lets me read the file.

### To Reproduce
Here is a small sample I wrote to reproduce the error. Unfortunately, you would need to create the bucket yourself...
```go
package main

import (
	"context"
	"fmt"
	"io"
	"strings"

	"gocloud.dev/blob"
	_ "gocloud.dev/blob/s3blob"
)

func main() {
	connectionString := "s3://my_bucket?region=us-east-1&awssdk=v2"
	bucket, err := blob.OpenBucket(context.TODO(), connectionString)
	if err != nil {
		panic(err)
	}

	iterator := bucket.List(nil)
	current, err := iterator.Next(context.TODO())
	for err == nil {
		if current.IsDir || !strings.Contains(current.Key, "index.html") {
			current, err = iterator.Next(context.TODO())
			continue
		}

		fmt.Printf("Object: '%s'\n", current.Key)
		reader, err := bucket.NewRangeReader(context.TODO(), current.Key, 0, 100, nil)
		if err != nil {
			panic(err)
		}
		data, err := io.ReadAll(reader)
		if err != nil {
			panic(err)
		}
		fmt.Printf("Data: '%s'\n", string(data))

		current, err = iterator.Next(context.TODO())
	}
	if err != io.EOF {
		panic(err)
	}
}

```

## Expected behavior

The `NewRangeReader` function should not fail with `404`.

### Version

```
go 1.19

require gocloud.dev v0.29.0
```

**Comment by vangent** [comment]
Hmm, I wonder if S3 behavior changed.

I don't remember the details, but the S3 driver in Go CDK explicitly escapes the second "/" in "//":
https://github.com/google/go-cloud/blob/master/blob/s3blob/s3blob.go#L913

I have a feeling that if I comment that line out, your test will work, but some other test will fail :-|.

If I have time I'll play around with it.

**Comment by sides-flow** [comment]
> I have a feeling that if I comment that line out, your test will work, but some other test will fail :-|.

This is exactly why I opened an issue rather than a PR, I feel like I'm not knowledgable enough to fix it in a way that will support all cloud providers, and was afraid to break something else...

I appreciate your help :)
Let me know if I can help somehow...

**Comment by vangent** [comment]
It seems like S3 fixed a bug here, so I removed the escaping, please try again!
