### ISSUE TITLE
`blob/s3blob`: add support for deleting multiple objects with a batch API call

### ISSUE THREAD

**Issue by ryanworl** [google/go-cloud#3260]
### Is your feature request related to a problem? Please describe.

I have a high throughput workload that requires deleting many objects in S3, and deleting them one-at-a-time uses a significant amount of resources. I've already parallelized this process, but supporting the S3 `DeleteObjects` API would batch multiple deletes together. GCS and Azure Blob Storage also have similar APIs.

### Describe the solution you'd like

I propose adding a new API:

`func (b *Bucket) DeleteMany(ctx context.Context, keys []string) error`

which attempts to use the cloud-specific optimized API where available, or deletes serially where the batch API is not available.

### Describe alternatives you've considered

* Deleting concurrently in multiple Goroutines: 
  * I've already done this. It uses a lot of resources.
* Deleting using the batch APIs in the cloud-provider's SDK:
  * This defeats the purpose of using gocloud.

**Comment by challenger14** [comment]
Code Resource and Transformation Environment, or CReATE. It uses DevSecOps
tools and continuous integration/continuous delivery pipelines to develop shared services
and capabilities without extensive development experience.

**Comment by vangent** [comment]
Sounds legit, I'll take a look.

**Comment by vangent** [comment]
> GCS and Azure Blob Storage also have similar APIs

They do? Can you point to them? I don't see one for GCS (e.g., https://stackoverflow.com/questions/30101669/multi-object-deleteion-google-cloud-storage-go) or for Azure (e.g., https://github.com/Azure/azure-storage-blob-go/issues/201).

> It uses a lot of resources

Can you clarify what you mean by this? What resources?

**Comment by ryanworl** [comment]
> Can you point to them?
Here is the GCS one (more generic than just deletes it seems): https://cloud.google.com/storage/docs/batch

I'm not sure about the Azure one, but I am pretty sure it exists as a colleague at a previous job implemented this for deletes across S3, GCS, and Azure Blob in Java.

> Can you clarify what you mean by this? What resources?
This uses significantly more Goroutines and connections than necessary. I'm deleting tens-of-thousands of objects per second continuously.

**Comment by vangent** [comment]
Hmm, I think I'm going to pass on adding this, as there doesn't seem be real support in Go except in S3.

Can you use a worker pool to limit the concurrency and connections?

https://gobyexample.com/worker-pools
