### ISSUE TITLE
azblob: fails to build on Dragonfly

### ISSUE THREAD

**Issue by bep** [google/go-cloud#3266]
Even in [v0.30.0](https://github.com/google/go-cloud/releases/tag/v0.30.0)

See #3261

**Comment by vangent** [comment]
What's the error? Is it still in `github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blockblob` ?

If so, please file a bug for them. All I can do is update the dependency.

In #3261 you said "This is fixed upstream" so I assumed that updating all dependencies would fix it. If it hasn't, can you be more specific about what "upstream" is?

**Comment by bep** [comment]
So, the errors are the same

```
# github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blockblob
../gomodcache/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v1.0.0/blockblob/chunkwriting.go:273:15: undefined: mmb
../gomodcache/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v1.0.0/blockblob/chunkwriting.go:279:65: undefined: mmb
../gomodcache/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v1.0.0/blockblob/chunkwriting.go:281:22: undefined: mmb
../gomodcache/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v1.0.0/blockblob/chunkwriting.go:287:39: undefined: mmb
../gomodcache/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v1.0.0/blockblob/chunkwriting.go:293:18: undefined: newMMB
../gomodcache/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v1.0.0/blockblob/chunkwriting.go:303:37: undefined: mmb
• core: Total in 127.46s …
error running command: exit status 1

Exited with code exit status 1
```

When I said "fixed upstream" I meant that the issue I opened in the Azure repo above was closed as fixed with a commit, but I guess that fix hasn't made it into a release yet (I haven't checked).

So, the more general problem is that we (that includes me) don't test these build tags as part of the daily CI builds, so we end up getting these errors very late when we do a binary release. I will try to fix this on my end so I don't have to "revert go-cloud" so frequently.

**Comment by vangent** [comment]
SGTM. Can you link to the Azure issue you're referring to?

I don't know how to test on Dragonfly; https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job#choosing-github-hosted-runners doesn't include it.

**Comment by bep** [comment]
@vangent the link is in my comment above (https://github.com/Azure/azure-sdk-for-go/issues/20885).

As to testing, I'm more referring to the smoke tests in the form of `GOOS=foo GOARCH=bar go build` for all variants that you're supposed to support. That Hugo supports Dragonfly comes with some history, but I have kept it because it ... looks cool. And it's just a  BSD Unix variant.

**Comment by vangent** [comment]
Can you point me to the Hugo smoke tests that manage that?

I tried this locally and got an error but a different one than you quoted:

```
$ cd blob/azureblob
$ GOOS=dragonfly go build
# runtime
/usr/lib/google-golang/src/runtime/googleexit.go:81:6: exit defined in both Go and assembly
```

**Comment by bep** [comment]
>Can you point me to the Hugo smoke tests that manage that?

There's none. I will try to add some, but currently this fail on release. I have had to revert the `go-cloud` upgrade on the last 2 Hugo releases.

**Comment by vangent** [comment]
OK, how about how you reproduced the error above? I can't do it locally.

**Comment by bep** [comment]
@vangent I'm out travelling, but will add one such test to the Hugo CLI tests when I get back home. And, looking at this issue, I should have done that before opening this issue, but I'm learning.

**Comment by bep** [comment]
I have added `GOARCH=amd64 GOOS=dragonfly go install` to Hugo's CI build.

Which fails on "bump gocloud.dev from 0.24.0 to 0.30.0" https://github.com/gohugoio/hugo/pull/11172

https://github.com/gohugoio/hugo/actions/runs/5432106017/jobs/9878929559?pr=11172

**Comment by vangent** [comment]
I tried to do the same, but it seemed to pass:

https://github.com/google/go-cloud/pull/3268

Any idea what I've done wrong?

**Comment by bep** [comment]
>It doesn't look like the Azure fix has been pushed yet.

I looked, it's not in a released tag.

I'm closing this issue; Dragonfly is rather exotic, and I have a test for it and I can just wait for a version that goes green.

**Comment by vangent** [comment]
The next build should work.
