### ISSUE TITLE
pubsub/awssnssqs: Support SNS:PublishBatch in SendBatch for SNS Topic

### ISSUE THREAD

**Issue by perrydunn** [google/go-cloud#3285]
SNS provides a PublishBatch endpoint similar to SQS's SendMessageBatch which the [pubsub SQS driver already supports](https://github.com/google/go-cloud/issues/2615). I'd like to see SNS:PublishBatch supported (for performance).

**Comment by vangent** [comment]
Thanks for the pointer.
