### ISSUE TITLE
Support for Redis, Memcache drivers

### ISSUE THREAD

**Issue by zubairalam** [google/go-cloud#3297]
### Is your feature request related to a problem? Please describe.
I tried to look for integration of Redis, Memcache in go-cloud repo. But couldn't find something to get started with.

### Describe the solution you'd like
A driver to connect with Redis / Memcache. Should work with GCP, AWS, Azure etc.

If this already supported in some way, then please let me know how I can achieve this.

notifying @vangent

**Comment by vangent** [comment]
What would that look like? Doesn't memcache have the same API regardless of which provider it's being run on?

Go CDK doesn't cover the provisioning/operational aspects (https://github.com/google/go-cloud/blob/master/internal/docs/design.md#developers-and-operators) if that's what you're looking for.

Maybe you could give an example of an API that's available in GCP/AWS/Azure that Go CDK could provide an abstraction for.
