### ISSUE TITLE
blob/fileblob: bucket.List is not working for /tmp folder

### ISSUE THREAD

**Issue by ducquangkstn** [google/go-cloud#3304]
### Describe the bug

- blob/fileblob: bucket.List is not working for /tmp folder
### To Reproduce

- `echo "aaa" > /tmp/report.txt`
- run the 
```go
bucket, err := fileblob.OpenBucket("/tmp", nil)
if err != nil {
  panic(err)
}
it := bucket.List(&blob.ListOptions{Prefix: "report.txt"})
for {
  obj, err := it.Next(context.TODO())
  if err == io.EOF {
     break
  } else if err != nil {
     panic(err)
  }
  fmt.Println(obj.Key)
}
```
## Expected behavior

- It should printout `report.txt`
### Version

0.33.0
### Additional context

I am using Mac OS

**Comment by vangent** [comment]
That exact thing works for me on Linux, and the unit tests should cover this as well (and run on MacOS).

Can you try again without the `Prefix` option and see what it prints? Does it work in a different directory other than `/tmp`? 

You're going to have to help me debug this since I can't reproduce it.

**Comment by luongthanhlam** [comment]
I'm not sure why but changing `/tmp` to `/private/tmp` fixes the issue on MacOS

**Comment by vangent** [comment]
What happens if you do

```
$ cd /tmp
$ pwd
$ ls
```

in a terminal on your MacOS? And same for `/private/tmp`.

**Comment by vangent** [comment]
```
lrwxr-xr-x@  1 root  wheel    11 Sep  2 00:35 tmp -> private/tmp
```

It looks like `/tmp` might be a symbolic link on MacOS; `os.WalkDir` does not follow symbolic links:
https://pkg.go.dev/path/filepath#WalkDir
