### ISSUE TITLE
all: Remove indirect dependency to `github.com/prometheus/prometheus`

### ISSUE THREAD

**Issue by gunturaf** [google/go-cloud#3312]
### Is your feature request related to a problem? Please describe.

Currently, this library requires `contrib.go.opencensus.io/exporter/stackdriver` in its go.mod file,
however, the version used here (v0.13.14) imports `github.com/prometheus/prometheus`, while in reality it does not need to import the whole prometheus, just a little copy is OK which done by me via https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/316

I think it's beneficial if this library upgrade its usage to the `master` branch of `contrib.go.opencensus.io/exporter/stackdriver`.

### Describe the solution you'd like

Upgrade `contrib.go.opencensus.io/exporter/stackdriver` to `master` branch, since that library is now deprecated and no new tag was created since the above MR was merged.

### Describe alternatives you've considered

Replace stackdriver exporter to similar library since OpenCensus is now deprecated anyway.

### Additional context

https://github.com/google/go-cloud/blob/master/go.mod#L28C10-L28C10

**Comment by vangent** [comment]
When is the next tag/release for `contrib.go.opencensus.io/exporter/stackdriver` going to happen? Can't we just wait for that?

**Comment by gedw99** [comment]
Al their repos are dead 

https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/

anyone know what’s happening?

**Comment by gedw99** [comment]
https://opentelemetry.io/blog/2023/sunsetting-opencensus/

It’s now in Otel basically

**Comment by gedw99** [comment]
@vangent 

are you going to port or bridge ?

https://github.com/open-telemetry/opentelemetry-go/tree/main/bridge/opencensus Is the bridge.

my 2 cents.. port . Don’t know if your insulated at an API level inside CDK

**Comment by vangent** [comment]
The right answer here is to port to using OpenTelemetry. There is already an issue open for that (#2877) so I'm going to close this one; I don't think pointing to a `master` branch of a deprecated library is appropriate.
