### ISSUE TITLE
blob/fileblob/fileblob.go NoTempDir defaults to true and causes EXDEV cross device link errors

### ISSUE THREAD

**Issue by sshort** [google/go-cloud#3314]
### Describe the bug

This commit added the NoTempDir option to the fileblock OpenBucket method - which is good.  
https://github.com/google/go-cloud/commit/9b62f468b3e4ad99156130d1bdcf3b0055dcb880

The previous behaviour was to create temp files in the same folder as the target file, after this commit, the default behaviour is to use the OS temp dir for temp files. 

When the target file is not on the same file system device as the OS temp dir, this causes cross device link errors when the file is Renamed in the fileblob Close method.

This was a **breaking** change. 

### To Reproduce

Write to a file://some-path-on-a-different-device-than-tmp.

## Expected behavior

No errors should be returned and the target file should be written to the requested location

### Version

v0.34.0

**Comment by vangent** [comment]
Sorry about the breaking change. I believe the new behavior is more correct, as the old behavior resulted in stranded/extra tmp files in the actual directory, while the new (default) behavior does not.

https://github.com/google/go-cloud/issues/3294 has some discussion of the tradeoffs.

Can you either set NoTempDir, or set the `TMPDIR`environment variable to a directory on the same mountpoint?

**Comment by sshort** [comment]
Thanks for quick response.   My additional comments

* I agree that using the OS temp dir is the preferred approach, but it is customary to bump the major version for breaking changes.  Maybe this is the way things are in the golang world!

* I have implemented a workaround using NoTempDir.  The problem is that code was agnostic as to which storage engine it was using, s3:// or file://,.  Since blob.OpenBucket does not support the fileblob Options, I now have to check the usr scheme and call the right storage mechanisms OpenBucket methof.

* it would be possible to check for EXDEV errors after the rename and then copoy the file so that it works seamlessy for the end user.

**Comment by vangent** [comment]
> it is customary to bump the major version for breaking changes

Fair, but it is arguable whether this is a breaking change. The APIs backwards compatible. The behavior changed, but in a relatively minor way (not many users affected).

Also, this library is "in development" (https://go.dev/doc/modules/version-numbers#in-development) as its version start with "0".

> The problem is that code was agnostic as to which storage engine it was using, s3:// or file://,. Since blob.OpenBucket does not support the fileblob Options, I now have to check the URL scheme and call the right storage mechanisms OpenBucket method

You can set `no_tmp_dir` in the `file://` URL to enable the `NoTempDir` option.

**Comment by tv42** [comment]
I find it hard to think of the new behavior as "more correct", as all systems touch have a separate /tmp and this code will never work with defaults now :-(

**Comment by vangent** [comment]
To be pedantic, this behavior was changed in https://github.com/google/go-cloud/pull/3287. The referenced one just added the `NoTempDir` option to allow going back to the previous behavior.

> I find it hard to think of the new behavior as "more correct", as all systems I touch have a separate /tmp and this code will never work with defaults now

It works with defaults unless your `/tmp` is on a different mount point than your `fileblob` base. If that's the case, you need to use the `NoTempDir` option, or set the `TMPDIR` environment variable to move your `/tmp`.


I still feel like this is better behavior than what happens with `NoTempDir`, which is that those extra temp files can be created and not cleaned up.
