### ISSUE TITLE
runtimevar: support `env` url

### ISSUE THREAD

**Issue by giautm** [google/go-cloud#3316]
`runtimevar` provides super-easy way to load a value from external environments into the application. It already support `constants`, and `file`. But it doesn't support `env` yet. The implement is simple. But also brings the flexible of using a single API for all suppose.

### Describe the solution you'd like

I hope to see a new package `gocloud.dev/runtimevar/envvar`. The use `os.Getenv()` to load the variable.

`env://VARIABLE?decoder=string`

For the context, we used `runtimevar` package as [the HCL resource here](https://atlasgo.io/atlas-schema/projects#data-source-runtimevar). We also already add `getenv()` function following the Go-style to load the variable. But, builtin-support for `runtimevar` is really helpful

**Comment by vangent** [comment]
What if I add a new constructor / URL parameter to `constantvar`?

E.g.,

```
rtv := constantvar.New(environment_variable_name string, decoder *runtimevar.Decoder)
```

and

```
rtv, err := runtimevar.OpenVariable(ctx, "constant://?envvar=hello+world&decoder=string")                                                           
```

Note: the value would be frozen at initialization time, if the environment variable value was changed after that it would not be reflected in the `runtimevar.Variable`.

**Comment by vangent** [comment]
Yep I tried that out, looks good.
