### ISSUE TITLE
Using AWS, how do we enable compression and decompression of upload and dwonload?

### ISSUE THREAD

**Issue by lizhifengones** [google/go-cloud#3333]
I'm using openebs+ velero + velero-plugin to upload and download csi snapshots.
I found that velero-plugin uses gocloud to connect to aws, but velero-plugin does not seem to enable gocloud's compression capability.
I plan to submit PR to velero-plugin, so how can gocloud enable compression and decompression for upload and download?

**Comment by vangent** [comment]
Can you point to where in the AWS Go library documentation this feature is referenced? Depending on how it's configured, you may be able to set a default somewhere, or you may need to use `As` (https://gocloud.dev/concepts/as/) to get access to the underlying AWS objects to set it. There's nothing in Go CDK explicitly about it.

**Comment by lizhifengones** [comment]
> Can you point to where in the AWS Go library documentation this feature is referenced? Depending on how it's configured, you may be able to set a default somewhere, or you may need to use `As` (https://gocloud.dev/concepts/as/) to get access to the underlying AWS objects to set it. There's nothing in Go CDK explicitly about it.

I'm not sure I fully understand what you mean, this is where velero-plugin uses gcclond,

https://github.com/openebs/velero-plugin/blob/cea57783e3ed887d2b7b0e7bafc436ff26bd9a7b/pkg/clouduploader/conn.go#L240

Meanwhile, it was my problem, I didn't understand the usage of `AS` API. :(

**Comment by lizhifengones** [comment]
> Can you point to where in the AWS Go library documentation this feature is referenced? Depending on how it's configured, you may be able to set a default somewhere, or you may need to use `As` (https://gocloud.dev/concepts/as/) to get access to the underlying AWS objects to set it. There's nothing in Go CDK explicitly about it.

Sorry, can you give an example of using compression as API? I didn't find the demo.

**Comment by vangent** [comment]
> gocloud's compression capability

What are you referring to here? There is no compression capability in Go CDK explicitly.
https://github.com/search?q=repo%3Agoogle%2Fgo-cloud+path%3A%2F%5Eblob%5C%2F%2F+compression&type=code

You will need to look at the AWS documentation to see how to do it. Once you know how to do it with AWS directly, I can help with how to do it using Go CDK and `As`.

**Comment by lizhifengones** [comment]
> > gocloud's compression capability
> 
> What are you referring to here? There is no compression capability in Go CDK explicitly. https://github.com/search?q=repo%3Agoogle%2Fgo-cloud+path%3A%2F%5Eblob%5C%2F%2F+compression&type=code
> 
> You will need to look at the AWS documentation to see how to do it. Once you know how to do it with AWS directly, I can help with how to do it using Go CDK and `As`.

thank you for your reply.
