### ISSUE TITLE
docstore/mongodocstore: pauses before getMore

### ISSUE THREAD

**Issue by eqinox76** [google/go-cloud#3338]
### Describe the bug

I see very long pauses while iterating over a simple query result from mongodb.

### To Reproduce

When i query all elements from a simple collection (~17k elements overall ~4MB) with the following code
```
	coll, err := docstore.OpenCollection(ctx, collectionString)
	if err != nil {
		log.Fatal(err)
	}
	iter := coll.Query().Get(ctx)
	for {
		var job Job
		err := iter.Next(ctx, &job)
		if err != nil {
			if err == io.EOF {
				return result, nil
			}
			return nil, err
		}
		result = append(result, &job)
	}
```
Measurements show that there are pauses in the `iter.Next()` call. 
Checking with wireshark i see patterns like
![image](https://github.com/google/go-cloud/assets/5861557/77ca2db6-9ba4-4ee7-aa5c-39957f6c6561)
Looking deeper into the pauses i see always that, the client acknowledges receiving data from the database and seconds later sends the `getMore` request to the mongo database. 
```
9483	6.303594	172.28.84.99	192.168.138.16	TCP	72	42042 → 27017 [ACK] Seq=255 Ack=17282044 Win=17787 Len=0 TSval=3413796243 TSecr=228505663
9484	7.963113	172.28.84.99	192.168.138.16	TCP	190	42042 → 27017 [PSH, ACK] Seq=255 Ack=17282044 Win=17787 Len=118 TSval=3413797902 TSecr=228505663 [TCP segment of a reassembled PDU]

Content of the TCP PSH:
0000   76 00 00 00 11 00 00 00 00 00 00 00 dd 07 00 00   v...............
0010   00 00 00 00 00 61 00 00 00 12 67 65 74 4d 6f 72   .....a....getMor
0020   65 00 bd cb 2f dd ab f5 48 0e 02 63 6f 6c 6c 65   e.../...H..colle
0030   63 74 69 6f 6e 00 05 00 00 00 4a 6f 62 73 00 03   ction.....Jobs..
0040   6c 73 69 64 00 1e 00 00 00 05 69 64 00 10 00 00   lsid......id....
0050   00 04 cf ac 68 52 dd 73 4e 66 b7 eb e8 50 c0 de   ....hR.sNf...P..
0060   e6 ec 00 02 24 64 62 00 09 00 00 00 49 6d 70 6f   ....$db.....Impo
0070   72 74 65 72 00 00                                 rter..
```
There are no network retransmissions or similar problems between those two tcp packages. The database server and client machine also show no signs of stress. I tested on two different client machines and see the same pattern.

## Expected behavior

Continuous stream of data with pauses due to network or database. No pauses due to the client.

### Version
- gocloud.dev v0.29.0
- gocloud.dev/docstore/mongodocstore v0.29.0

### Additional context

Suspecting the `go.mongodb.org/mongo-driver` i wrote and tested the following:

```
func TestMongoGet(t *testing.T) {
	info := Info{}
	ctx := context.Background()
	mongoClient := lo.Must(mongo.Connect(ctx, options.Client().ApplyURI(MONGO_SERVER_URL)))

	coll := mongoClient.Database("Importer").Collection("Jobs")
	cur := lo.Must(coll.Find(ctx, bson.M{}))

	for cur.Next(ctx) {
		info.Add(ts)
	}
}
```
But that is behaving as expected. Delivering an continuous stream of data.

I am struggling with debugging this issue in the gocloud code. Any pointers would be appreciated!

**Comment by eqinox76** [comment]
v0.34.0 shows the same behavior.

**Comment by vangent** [comment]
I'd try adding some logging near here: https://github.com/google/go-cloud/blob/master/docstore/mongodocstore/query.go#L124 to see if you can determine where the pauses are coming from. I am also not familiar with the docstore/mongodocstore code, but it looks like we're just iterating calling cursor.Next and then decoding it.

**Comment by eqinox76** [comment]
Thank you for the pointer. After some more debugging and some dead ends i think i understand whats happening. Especially the golang trace is helpful:
![image](https://github.com/google/go-cloud/assets/5861557/5211626d-19f4-4134-8ac7-6628c1f90481)
The green-pink-brown stacks are io operations (syscall.read from within go.mongodb.org/mongo-driver/mongo.(*Cursor).Next:133). 
The light blue stacks are decode operations (gocloud.dev/docstore/mongodocstore.decodeDoc:125).

I would have expected the documents to be decoded from the moment the first element of a batch arrives. But it seems the mongo driver waits for the complete batch to arrive. Thereafter the gocloud decode operation is applied to all elements and only then the next batch is requested. That explains the above pattern in the io graph.

Not much that can be done about it. Using `func (c *Cursor) TryNext(ctx context.Context) bool` as a noneblocking alternative could be feasible. This would allow decoding to continue while the next batch is already in flight. But that would require at least parallelized code.

Thanks for having a look and helping me understand the issue.

**Comment by eqinox76** [comment]
Thank you for the pointer. After some more debugging and some dead ends i think i understand whats happening. Especially the golang trace is helpful:
![image](https://github.com/google/go-cloud/assets/5861557/5211626d-19f4-4134-8ac7-6628c1f90481)
The green-pink-brown stacks are io operations (syscall.read from within go.mongodb.org/mongo-driver/mongo.(*Cursor).Next:133). 
The light blue stacks are decode operations (gocloud.dev/docstore/mongodocstore.decodeDoc:125).

I would have expected the documents to be decoded from the moment the first element of a batch arrives. But it seems the mongo driver waits for the complete batch to arrive. Thereafter the gocloud decode operation is applied to all elements and only then the next batch is requested. That explains the above pattern in the io graph.

Not much that can be done about it. Using `func (c *Cursor) TryNext(ctx context.Context) bool` as a noneblocking alternative could be feasible. This would allow decoding to continue while the next batch is already in flight. But that would require at least parallelized code.

Thanks for having a look and helping me understand the issue.
