### ISSUE TITLE
docstore:  should support (in) comparison operator

### ISSUE THREAD

**Issue by coryschwartz** [google/go-cloud#3352]
The query operators supported by go-cloud is a more restrictive set than any of its drivers.

In my application, I want to query for documents with a key that matches any of several keys, and I am surprised that I cannot do this in a single call. I want to do something similar to this:

SELECT * WHERE KEY IN ('val1', 'val2'...)

I can think of a couple of ways this could be done:

I can add additional `.Where` clauses, but this has the effect of AND'ing the clauses together, so I cannot use multiple Where's to select for multiple keys with the existing operators. The docstring tells us drivers should AND these together. https://github.com/google/go-cloud/blob/master/docstore/driver/driver.go#L192

One solution, although I suspect this isn't the most efficient way to do this, there could be an `Or`. If there was an or operator, then we could do this.

```
iter := coll.Query().Or("Key", "=", "val1").Or("Key", "=", "val2")
```

Maybe a better way to do this is just to support additional operators. Personally, this would be my preferred solution. 
currently, only the following are supported: https://github.com/google/go-cloud/blob/master/docstore/query.go#L65

```
var validOp = map[string]bool{
	"=":  true,
	">":  true,
	"<":  true,
	">=": true,
	"<=": true,
}
```
We could simply throw an 'in' operator into this list, and then adjust the individual drivers.

When I look at the query operators supported by each of the supported drivers, they all have a richer set of operators and they all include the 'in' operator I'm hoping to use.

https://www.mongodb.com/docs/manual/reference/operator/query/#std-label-query-projection-operators-top
https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/query/keywords#in
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html#Expressions.OperatorsAndFunctions.Syntax
https://firebase.google.com/docs/firestore/query-data/queries#in_not-in_and_array-contains-any

I can think of at least one reason why you *shouldn't* do this request. If you're going to support adapters any less-featured docstores in the future, you might want to keep the supported features to a minimum subset.

If you'd accept it, I'd be happy to attempt a PR to add an 'in' operator to the validOp and adjust the drivers, although I don't have easy access to all of the supported databases to properly test every driver.

**Comment by jba** [comment]
You should be looking at [Firestore](https://cloud.google.com/firestore/docs/query-data/queries#in_and_array-contains-any) rather than Firebase. But Firestore has `in` too.

This plan seems feasible as long as you stick to the common behavior of all the drivers.
@vangent can help you with the details of creating a PR for us, and he and I can review it.

**Comment by coryschwartz** [comment]
I have the PR up for in/not-in operations. It's failing tests, and I think that's caused by the lack of support in the replay files. If someone could point me in the right direction for how to generate those, or or add those to this PR, that would be helpful for getting the tests to pass.

If someone wants it, I can probably also add the array-contains operations -- I saw some comments about that.

**Comment by vangent** [comment]
@jba I went ahead and merged this in, please let me know if you have feedback.
