### ISSUE TITLE
pubsub: support NATS jetstream

### ISSUE THREAD

**Issue by pitabwire** [google/go-cloud#3353]
The in tree version of nats pubsub driver does not currently support jetstream. I created https://github.com/pitabwire/natspubsub a jetstream supported version [here](https://github.com/pitabwire/natspubsub) any feedback is highly appreciated. It currently passes the conformance tests and tries to allow as much customization of the nats supported configuration as possible. 

This was mostly inspired by the limitations experienced in resolving the issues https://github.com/google/go-cloud/pull/3001 and https://github.com/google/go-cloud/issues/1559

**Comment by vangent** [comment]
Thanks! I don't think there's anything for go-cloud to do here, the presence of this bug will help others looking for this to find your repo.

The comments on https://github.com/google/go-cloud/issues/1559 are still relevant if it's easy to fold this in to the in-tree version.
