### ISSUE TITLE
pubsub/awssnssqs: duplicate key in map literal

### ISSUE THREAD

**Issue by cadams93** [google/go-cloud#3354]
Since a commit to the upstream `aws-sdk-go` library, the `pubsub/awssnssqs` package fails to build with the error:

```
../../../../../gocloud.dev/pubsub/awssnssqs/awssnssqs.go:987:2: duplicate key "AWS.SimpleQueueService.NonExistentQueue" in map literal
```
See: https://github.com/aws/aws-sdk-go/pull/5101

This appears to be due to the introduction of `buggyQueueNotFoundErrorCode` as a solution to an unrelated SQS error handling issue: https://github.com/aws/aws-sdk-go-v2/issues/2348 (see https://github.com/google/go-cloud/commit/53ccd8db26a14fd2a40bfcb28af1a1ceba4663f4#diff-657f9542b2a012c5bc40f808f592db272175a0cfade32cbe6eb7cb5112b40d70R987)

### To Reproduce

1. Create a basic application importing v0.35.0 (latest as of report).
2. Update `aws-sdk-go` to latest `main` commit.
3. Attempt to build the application. 

### Expected behavior

Sample application builds without error.

### Version

Latest released v0.35.0.

### Additional context

We discovered this issue in an application that is using GOPATH for dependency resolution. This will only be an issue present for users whose applications resolve to the latest `aws-sdk-go` release based on other explicit versioning requirements within the module - it will become an issue when `gocloud.dev` bumps the minimum version to include the `aws-sdk-go` change though. 😅

**Comment by vangent** [comment]
Grr. AWS is killing me.

**Comment by vangent** [comment]
https://github.com/aws/aws-sdk-go/commit/87f2688a108037b955757f47e6be8fe016eb03d1

BREAKFIX is breaking my break fix.

**Comment by jufemaiz** [comment]
Dare I ask if a release is forthcoming ? v0.35.1 for example? 😬
