### ISSUE TITLE
pubsub/azuresb: support workload identity auth method

### ISSUE THREAD

**Issue by tsolodov** [google/go-cloud#3359]
### Is your feature request related to a problem? Please describe.

Currently the only supported method is SharedKey (connection string), add AKS [workload identity](https://learn.microsoft.com/en-us/azure/aks/learn/tutorial-kubernetes-workload-identity) support

### Describe the solution you'd like

Implement additional auth methods using Azure golang SDK (creds)

How to use:
depends on method(Workload, kubelet, Service), set ENV variables:
`AZURE_SERVICEBUS_HOSTNAME` - to trigger new method

For service principal auth, set ENV variables described [here](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.environmentcredential?view=azure-dotnet)

If you use workload/kubelet identities,  ENV variables are injected by AKS, some details can be found [here](https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview?tabs=dotnet)

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by tsolodov** [comment]
PTAL? Can someone please approve CI run for my PR ?

**Comment by tsolodov** [comment]
Hi @vangent , thank you for merging PR. Do you have any insight when next release will happen?

**Comment by vangent** [comment]
No, but you can start using it now, you don't need to wait for a release.
