### ISSUE TITLE
secrets/hashivault: read token from file

### ISSUE THREAD

**Issue by gawsoftpl** [google/go-cloud#3377]
### Is your feature request related to a problem? Please describe.

Always have to set env variables VAULT_TOKEN with vault token. When I login to vault server I generate short living token and write to file. I would like to store that token in file and read from file by go-cloud library.

### Describe the solution you'd like

[link to function](https://github.com/google/go-cloud/blob/1c8e1d883f11d45a096b97e1f5cf492860058317/secrets/hashivault/vault.go#L96)

```golang
func getVaultToken() string {
	serverToken := os.Getenv("VAULT_SERVER_TOKEN")
	if serverToken != "" {
		return serverToken
	}

	vaultToken := os.Getenv("VAULT_TOKEN")
	if vaultToken != "" {
		return vaultToken
	}

	vaultToken := readFromFile(os.Getenv("VAULT_TOKEN_FILE"))
	if vaultToken != "" {
		return vaultToken
	}

	return ""
}
```

### Additional context
In pulumi when I develop the stack my vault token expired and I have to set env from beginning. Read from file will be better dev experience.

**Comment by vangent** [comment]
`getVaultToken` is only called once when you create your `Keeper` instance, so IIUC you'd still need to restart your server whenever the token expires. Unless your application creates new `Keeper` instances all the time.

Why is it easier to write the token to a file than to set it in the environment? In general we don't want to encourage people to write secrets/tokens/etc. to disk as it's not very secure.

**Comment by gawsoftpl** [comment]
I login to vault by certificate via pkcs11 and write token to ~/.vault-token
I think that better way will be simple

```sh
USERNAME="user"
KEY_TOKEN="cert"

response=`curl -E "pkcs11:token=$KEY_TOKEN" \
    -s -X POST \
    --data "{\"name\": \"$USERNAME\"}" \
    ${VAULT_ADDR}/v1/auth/cert/login`

echo $response
token=`echo $response | jq -r ".auth.client_token"`

echo $token
```

```sh
export VAULT_TOKEN=`vault-login`
```

**Comment by vangent** [comment]
OK, that should work today with no change.
