### ISSUE TITLE
New Project: Docstore Query Gen for Go CDK

### ISSUE THREAD

**Issue by bartventer** [google/go-cloud#3387]
Hello Go CDK team,

I've recently developed a new project that I believe could be beneficial to the Go CDK community. It's called Docstore Query Gen, and it's designed to provide type-safe query generation for Go CDK Docstore, inspired by [go-gorm/gen](https://github.com/go-gorm/gen).

The project is hosted on GitHub at [https://github.com/bartventer/docstore-gen](https://github.com/bartventer/docstore-gen)

The goal of Docstore Query Gen is to make it easier for developers to write type-safe queries for Go CDK Docstore, reducing the risk of runtime errors due to incorrect query syntax. It uses code generation to achieve this, similar to how go-gorm/gen works for GORM.

I would appreciate it if you could take a look at the project and consider referencing it in your documentation or elsewhere, if you find it useful. I'm also open to any feedback or suggestions you might have.

Thank you for your time and for the great work you're doing with Go CDK!

Best regards, Bart

**Comment by vangent** [comment]
Thanks, I added a link!
