### ISSUE TITLE
runtimevar: Consider getting rid of Decoder as part of the interface

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#339]
**Currently:**

- Provider implementations take a Decoder when creating a Variable.
- Each provider implementation then uses the Decoder against the raw bytes it reads for the variable, receiving an interface{}.
- runtimevar returns a Snapshot, which contains the variable value as an interface{} type.
- 

**Cons:**
1. Each provider must implement the call to the Decoder.
2. The API user must cast the value to its real type, and must be careful to provide a Decoder for that type; no compile-type typechecks.

**Alternative 1**
Change the Driver to return variable values as []byte, and do the Decode in runtimevar itself.
--> This addresses con #1 but not con #2.

**Alternative 2**

- Change the Driver and runtimevar to return []byte, and require the API user to decode as needed. E.g., for a string variable it will just be "string(val)".
- We can still provide common decode functions, but they can be strongly typed instead of returning interface{}.

**Comment by zombiezen** [comment]
@cybrcodr, wanna chime in?

**Comment by cybrcodr** [comment]
The rationale for having decoding be part of the driver is that we envisioned 2 different personas -- ops and app developer.  Ops persona dictates how configurations are stored and which backend services to use.  This means that they dictate the format of the stored value and hence should provide/dictate the corresponding decoded Go type as well.  It is simpler for the application developer if for every stored value for a specific config variable that there is only one corresponding decoded Go type for it.

Just a side note.  The initial implementation of the GCP driver didn't have the Decoder as part of creating the Variable (then called Config).  It was part of the WatchOptions.  See cafe30328fd8b25fd476b3b8cf73f069d35d77e3.  The idea at the time was to use JSON as the default as it's easier to use string-based config data with the gcloud tool.

**Comment by vangent** [comment]
Thanks, and thanks for the offline discussion. I understand the intent better now.
