### ISSUE TITLE
all: Request for new tag including 'Offset' feature in docstore

### ISSUE THREAD

**Issue by bartventer** [google/go-cloud#3392]
Hi,

I've added an Offset feature in this PR ([#3385](https://github.com/google/go-cloud/pull/3385)) that's now merged. Could a new tag be created to include this feature?

If it's of interest, Semantic Release could be a useful tool for automatic versioning: https://github.com/semantic-release/semantic-release. I'd be happy to open a PR to update the CI workflow to include it.

Thanks,
Bart

**Comment by vangent** [comment]
Done.
