### ISSUE TITLE
blob/s3blob: s3ForcePathStyle stopped working in v0.39.0

### ISSUE THREAD

**Issue by caarlos0** [google/go-cloud#3472]
### Describe the bug

This was flagged by [goreleaser's tests][build] when dependabot opened the pr updating from v0.38 to v0.39.

[build]: https://github.com/goreleaser/goreleaser/pull/5080

I'm not sure if this is expected and just not documented, or if it is in fact a bug.

### To Reproduce

open a bucket (can be a local minio for example) using `s3ForcePathStyle`.

## Expected behavior

To work.

### Version

v0.39.0

### Additional context

Error:

```
open bucket s3://basic?endpoint=http%3A%2F%2Flocalhost%3A32812&region=us-east&s3ForcePathStyle=true: unknown query parameter "s3ForcePathStyle"
```

Also, forcing `awssdk=v1` makes it work again.

**Comment by vangent** [comment]
Please see the release notes (https://github.com/google/go-cloud/releases/tag/v0.39.0). This release changed the default for AWS URLs from their v1 SDK to their v2 SDK. Some parameters are different, `s3ForcePathStyle` is one that doesn't seem to exist for v2.

You should either update the URL to work with v2 (possibly just dropping that parameter will fix it?), or add `awssdk=v1` (which will work for now, but support will be dropped at some point, the release notes proposed 6 months).

**Comment by caarlos0** [comment]
yes, I saw the release notes, and also that forcing v1 works, my point was that the specific breaking change is not documented anywhere.

also, just dropping that part of the URL doesn't work (at least not with minio).

**Comment by vangent** [comment]
OK. Yes, I didn't try to document every specific URL parameter that wouldn't work anymore, just "Most URLs should continue to work, but in some cases you may need to add awssdk=v1 to force V1 explicitly."

**Comment by vangent** [comment]
> just dropping that part of the URL doesn't work (at least not with minio

Please try to figure out what's needed to get V2 to work with Minio (I'm not sure). It's possible we need to add support for more URL parameters for V2.

**Comment by dmotylev** [comment]
It seems `s3ForcePathStyle` has been moved to https://github.com/aws/aws-sdk-go-v2/blob/0cbb5aa17f9078cb45dc0e82d3e1d0abee3744a9/service/s3/options.go#L147-L150

**Comment by vangent** [comment]
Added, see https://github.com/google/go-cloud/pull/3491.

**Comment by stanhu** [comment]
@vangent Would you consider aliasing adding an alias for `s3ForcePathStyle` with `use_path_style` for backwards compatibility? We've had a few customers hit backup failures due to this URL change after we upgraded to v0.39.0.

**Comment by vangent** [comment]
Sure, that sounds reasonable; will send a PR.

**Comment by stanhu** [comment]
@vangent Thanks so much!
