### ISSUE TITLE
aws: lost "forcePathStyle" query parameter in AWS SDK V2

### ISSUE THREAD

**Issue by SebouChu** [google/go-cloud#3476]
### Describe the bug

In 0.39.0, S3 URLs now use the V2 of the AWS SDK by default. Therefore, we lost the `s3ForcePathStyle` query parameter. 

Based on [their documentation](https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/endpoints/#immutable-endpoints), we might be able to reproduce the behavior of this parameter by allowing to set the `HostnameImmutable` endpoint option.

### To Reproduce

Based on [GCK documentation](https://gocloud.dev/howto/blob/#s3-compatible), having an S3URL with `s3ForcePathStyle` will crash. And removing the parameter might break operations like OpenBucket when endpoint host should not be changed.

## Expected behavior

Operations should work with SDK V2, without the removed `s3ForcePathStyle`, and adding the support of a new parameter to set `HostnameImmutable`

### Version

GCK 0.39.0

**Comment by vangent** [comment]
See #3472 and https://github.com/google/go-cloud/pull/3473.

**Comment by SebouChu** [comment]
thanks @vangent! I didn't see the closed issue about this, sorry :(
