### ISSUE TITLE
No way to support blob/blob in compatible storage like minio with v2 aws sdkgo

### ISSUE THREAD

**Issue by khrm** [google/go-cloud#3490]
Please use a title starting with the name of the affected package, or \"all\",
followed by a colon, followed by a short summary of the issue. Example:
`blob/gcsblob: not blobby enough`.

You can use `go bug` to have a cool, automatically filled out bug template, or
fill out the template below.

### Describe the bug
It's more of a regression than a bug. If we remove aws sdk v1, we won't have a way to support the minio or other compatible storage using blob/blob. Obviously, blob/s3blob will work but we lost out on blob abstraction.

### To Reproduce
You can use `play.min.io:9443` and try to run with aws sdk v2 and blob. There's no way. We definitely need a query param to solve this.

## Expected behavior

A query param like we have in aws sdk v1 `s3ForcePathStyl`.

**Comment by vangent** [comment]
See https://github.com/google/go-cloud/pull/3473...?
