### ISSUE TITLE
aws: disable rate limits by default with AWS

### ISSUE THREAD

**Issue by stanhu** [google/go-cloud#3496]
### Describe the bug

After upgrading to go-cloud v0.39.0, one of our users reported:

```
operation error S3: PutObject, failed to get rate limit token, retry quota exceeded, 0 available, 5 requested
```

Terraform also has more details in https://github.com/hashicorp/terraform-provider-aws/issues/36024#issue-2161155725. It seems the AWS team discussed this specific issue in https://github.com/aws/aws-sdk-go-v2/issues/1665#issuecomment-2004339077. 

The bottom line is that SDK v2 adds new client rate limits, and users may hit this after switching from SDK v1. I recommend disabling these rate limits by default (as done in https://github.com/hashicorp/aws-sdk-go-base/pull/977/files) and provide a way to configure them if desired.

### To Reproduce

I haven't tried this yet, but I imagine if you make lots of PutObject requests in quick succession you will hit these client rate limits.

## Expected behavior

No rate limit errors.

### Version

Which version(s) of the Go Cloud modules are you seeing the bug with?

v0.39.0

**Comment by stanhu** [comment]
@vangent Thank you for the quick review and merge!

Do you know when you might want to cut a new tag? Otherwise I'll just use the pseudo-version.

**Comment by vangent** [comment]
done

**Comment by stanhu** [comment]
@vangent Thank you!
