### ISSUE TITLE
Secrets Keeper for GCP that does not require KMS and just uses the GCP vault.

### ISSUE THREAD

**Issue by jarrodhroberson** [google/go-cloud#3502]
### Secrets Driver that does not require GCP KMS service.

A driver that just uses the normal GPC Secrets service.

### Describe alternatives you've considered

Just using the non-gocloud.dev Secrets client provided by GCP but that defeats the purpose of using gocloud.dev in the first place.

**Comment by vangent** [comment]
Can you point to the Go client for the Secrets client you're referring to?

**Comment by jarrodhroberson** [comment]
> Can you point to the Go client for the Secrets client you're referring to?

you mean the one called `secretsmanager`

https://pkg.go.dev/cloud.google.com/go/secretmanager

Current implemenation is NOT accessing the `secrets` Google Cloud Platform, it is Cloud Key Management.

At least name the existing implementation "Cloud Key Management" or at LEAST "KMS" or something semantically correct, since it actually uses.

https://pkg.go.dev/cloud.google.com/go/kms/apiv1

and NOT `secretsmanager`

**Comment by vangent** [comment]
The Go CDK `secrets` package "provides an easy and portable way to encrypt and decrypt messages"; the interface has `Encrypt` and `Decrypt`. It doesn't store secrets. That matches what GCP KMS provides, but not what GCP Secret Manager provides.
