### ISSUE TITLE
blob/fileblob: make errors returned by URLSignerHMAC.KeyFromURL recognizable

### ISSUE THREAD

**Issue by a-gierczak** [google/go-cloud#3504]
### Is your feature request related to a problem? Please describe.

Pretty small change request, to make errors returned by URLSignerHMAC.KeyFromURL identifiable by `errors.Is`

### Describe the solution you'd like

https://github.com/google/go-cloud/blob/master/blob/fileblob/fileblob.go#L1021

I'd change the returned errors in the linked function to:

```go
var (
    ErrSignatureExpired = errors.New("signature expired")
    ErrInvalidSignature = errors.New("invalid signature")
)

...

if err != nil || time.Now().Unix() > exp {
	return "", ErrSignatureExpired
}

if !h.checkMAC(q) {
	return "", ErrInvalidSignature
}

```

### Describe alternatives you've considered

Custom URLSigner implementation - but it's such a minor thing, that it'd be an overkill not to use the built-in one :)

**Comment by vangent** [comment]
This doesn't seem portable; other providers just return an error. How would you use this?
