### ISSUE TITLE
blob: require atomicity and isolation

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#352]
I propose that we require blob implementations to have atomicity and isolation properties. The isolation property would mean that all the writes would be hidden from readers until `Close` is called. Typically, isolation would be implemented by having writes go to a temporary key. The `Close` method would be atomic, thereby preventing race conditions between a writer and readers. Usually, `Close` would rename the temporary key to the name given in the call to `bucket.NewWriter()`. The rename operation would have to be atomic for this to work. To find out if this is feasible, we'll have to do a survey of cloud providers to see if they support efficient, atomic key renaming.

**Comment by vangent** [comment]
Do the underlying provider implementations have these properties already? If so, don't we get it for free? If not, what's the rationale for adding this on top?

Or is this something that some providers have, and others don't, and you are suggesting we make it consistent in the go-cloud blob wrapper?

**Comment by ijt** [comment]
I don't think the underlying provider implementations provide these properties already.

One rationale for adding them on top is that they would prevent race conditions between readers and writers, and make for more deterministic behavior.

I can see a case for making this optional though for users who want less complexity or overhead. Maybe we could have something called `atomicblob` or `acidblob` built on top of `blob`.

**Comment by ijt** [comment]
This functionality would also help in the case of failed and aborted blob writes (issue #222). With atomicity, it's possible to keep the previous value for the key. Without atomicity, we have to delete the the value if there has been a partial write, and that probably isn't good.

**Comment by zombiezen** [comment]
As discussed offline a few weeks back, #222 is not contingent on this: the semantics of stopping an in-progress upload do not need this. Strongly consistent object listing (#241) or reading of content is not supported by S3, for instance.

This issue either needs clarity on what guarantees we want to enforce (and should be tested via conformance tests), or otherwise closed out as obsolete. @ijt, assigning to you to resolve.

**Comment by ijt** [comment]
Okay, closing it out.
