### ISSUE TITLE
blob/fileblob: support Unicode characters in key names

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#37]
From a comment on PR #33:

> I wanted to err on the side of ensuring that the names would be valid and not have special meaning on the filesystem. In particular, something like colon can potentially allow `C:/foo.txt` to do bad things on Windows. I'd be happy to open a bug to support Unicode characters and fix if there's demand.

This is that bug. @shantuo

**Comment by vangent** [comment]
This is fixed now, as part of #588.
