### ISSUE TITLE
blob: Consider refactoring blob.WriterOptions and driver.WriterOptions to reduce duplication

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#381]
They seem to be pretty similar, and it feels like most times we add an option to one, we'll add it to the other and have to copy. Perhaps one could be embedded in the other? Or could we use a single struct? 

I think the rationale for having two was that ContentType is in blob.WriterOptions (so the caller can override), but not in the driver.WriterOptions (because it's passed to the driver explicitly, sometimes after auto-detection).

**Comment by zombiezen** [comment]
From triage meeting:

- Cyclic imports are a concern
- `ContentType` is present in one or another
- Not wanting to show driver details in blob package godoc

**Comment by vangent** [comment]
Can we get a small design doc with the alternatives? Then we can review & decide what to do.

Also, this is specifically for blob, but I expect we'll see a similar pattern for other portable APIs so we should document what we come up with as best practices.

**Comment by shantuo** [comment]
The current decision is to keep the status quo. Closing for now and we can revisit it once more alternatives come to mind.
