### ISSUE TITLE
wire: improve the names of the generated variables.

### ISSUE THREAD

**Issue by e-nikolov** [google/go-cloud#383]
Right now wire names the variables holding provided values based on their types and if there are collisions in those names, it adds a counter to the name. So if there are Clients coming from 3 different packages, we'd have client, client2, client3. 

I think the generated code could be better if the package is also taken into consideration when naming a variable. For instance if we have redis.Client and mongo.Client, the variables should be redisClient and mongoClient instead of client and client2.

Edit.: Looking at the code, there seems to already be a todo for this:
https://github.com/google/go-cloud/blob/master/wire/internal/wire/wire.go#L676

**Comment by zombiezen** [comment]
Thanks for reporting! @vangent is working on this in #386.
