### ISSUE TITLE
mysql: instrument connection with OpenCensus

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#389]
We should add [OpenCensus instrumentation](https://opencensus.io/guides/integrations/sql/go_sql/) to any SQL dialers. This should not change the API AFAICT.

(Idea came from a [tweet](https://twitter.com/odeke_et/status/1032491251566706688) by @odeke-em.)

**Comment by odeke-em** [comment]
Roger that, thanks for the tag @zombiezen. I'll also rope in @basvanbeek who wrote the SQL wrapper and could be of help too.

**Comment by basvanbeek** [comment]
Hi @zombiezen, feel free to ping me if I can be of service.

**Comment by ijt** [comment]
Looking at the [example](https://opencensus.io/guides/integrations/sql/go_sql/), I'm not sure I understand what the SQL integration buys if you still have to manually write all those `trace.StartSpan()` calls.

**Comment by odeke-em** [comment]
@ijt in the example the created spans like:
* `iCtx, iSpan := trace.StartSpan(ctx, "InsertNames")`
* `fCtx, fSpan := trace.StartSpan(ctx, "Find")`
are just tertiary spans meant to give distinguishable information about what is occuring lest the observer won't know what's going on

Below, I have annotated some of the spans that the integration gives you out of the box
![ocsql-detailed-trace](https://user-images.githubusercontent.com/4898263/45174240-2f958c80-b1bf-11e8-978f-4482486b5c8f.png)

If you remove the tertiary spans, you'll just see bare the `sql:*` spans like the ones I've marked with arrows. Hope this makes sense.

**Comment by ijt** [comment]
Got it, thanks for explaining.
