### ISSUE TITLE
internal: travis builds are flaky

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#393]
I see lots of failures like this:

# cd .; git clone https://github.com/golangci/golangci-lint /home/travis/gopath/src/github.com/golangci/golangci-lint
Cloning into '/home/travis/gopath/src/github.com/golangci/golangci-lint'...
fatal: unable to access 'https://github.com/golangci/golangci-lint/': GnuTLS recv error (-9): A TLS packet with unexpected length was received.
package github.com/golangci/golangci-lint/cmd/golangci-lint: exit status 128
The command "go get -u github.com/golangci/golangci-lint/cmd/golangci-lint" failed and exited with 1 during .

Retry fixes.

**Comment by zombiezen** [comment]
I'll take a look and see if this is solved by getting the Go Modules proxy working.

**Comment by zombiezen** [comment]
In order to determine the proper new dependencies that need to be included, I am blocked on golang/go#27664.

**Comment by zombiezen** [comment]
Determined the new dependencies and they're not available under suitable licenses. Cutting the [Gordian Knot](https://en.wikipedia.org/wiki/Gordian_Knot) and just removing the linter run.
