### ISSUE TITLE
testing: travis failure on missing ocsql dependency (proxy?)

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#403]
Travis is failing on https://github.com/google/go-cloud/pull/400 with the following message:

`go: github.com/basvanbeek/ocsql@v0.0.0-20180627133915-d946a62502e3: unexpected status (https://storage.googleapis.com/go-cloud-modules/github.com/basvanbeek/ocsql/@v/v0.0.0-20180627133915-d946a62502e3.info): 404 Not Found`
https://travis-ci.com/google/go-cloud/jobs/144211484

Is it something to do with the proxy that was recently introduced?

**Comment by shantuo** [comment]
The proxy seems stale, `github.com/basvanbeek/*` is not in the proxy bucket.

**Comment by zombiezen** [comment]
This was a newly added module. For any new dependency, we do need to do due diligence to ensure that it is released under a compatible license and that we host a version to reduce service dependencies. #318 tracks adding the appropriate checks to Contribute Bot to give a friendlier message.

I have now added `github.com/basvanbeek/ocsql` to the proxy. Feel free to reopen if this does not work.
