### ISSUE TITLE
blob: support signed url

### ISSUE THREAD

**Issue by vardef** [google/go-cloud#404]
```go

//SignedURLOptions allows you to restrict the access to the signed URL.
type SignedURLOptions struct {
	// Expires is the expiration time on the signed URL. It must be
	// a datetime in the future.
	// Required.
	Expires time.Time
	// ContentType is the content type header the client must provide
	// to use the generated signed URL.
	// Optional.
	ContentType string
}


// Bucket provides read, write and delete operations on objects within it on the
// blob service.
type Bucket interface {
         //....other operations


	// SignedURL returns a URL for the specified object. Signed URLs allow
	// the users access to a restricted resource for a limited time
	SignedURL(bucket,key string,opts *SignedURLOptions) (string,error)
}


```

**Comment by vardef** [comment]
Currently not supported, is there any plan？

**Comment by zombiezen** [comment]
Hi @vardef! This sounds like a reasonable feature request, but we would have to do a bit of investigation to see how we would support this portably across providers. In particular:

- Would this need to run an HTTP server for `fileblob`? What would the semantics be?
- Do S3, GCS, and Azure all support this? Are the options roughly the same?

**Comment by vardef** [comment]
@zombiezen  not need to run an Http server,Just signature ,different cloud provides it in different ways,but basically almost

**Comment by jezell** [comment]
Yeah this is pretty essential for both uploads and downloads from web apps. Really silly to pass any traffic from browser through server when you can go direct to S3.

**Comment by vangent** [comment]
We're planning this for our next sprint, so in the next few weeks.
