### ISSUE TITLE
samples: make it possible to use jaeger for tracing when running guestbook locally

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#409]
Currently traces are only exported when the guestbook app is deployed to GCP or AWS, but not locally. [Jaeger](https://www.jaegertracing.io/) would allow users to try out tracing without having to deploy.

There are two main possibilities:
1. Put this functionality into `-env=local`
2. Make a new environment: `-env=jaeger`

To make this possible, there would need to be a new server type, probably `server/jaegerserver` similar to `sdserver` and `xrayserver`.

**Comment by shantuo** [comment]
Trace should work when running locally for Stackdriver, it will be reported to the console. I never tried with Xray though.

**Comment by ijt** [comment]
@shantuo , in that case I suggest we go with option 2: add -env=jaeger. Or do you think that would make the example too complex?

**Comment by shantuo** [comment]
OpenCensus supports a variety of exporters, we should probably do more investigation to decide which platform should be added next. Perhaps #410 can give us more flexibility on this as the `server` package contains many moving parts.

**Comment by ijt** [comment]
This is too low priority. Closing it.
