### ISSUE TITLE
server: add a `driver` field taking a to-be-defined `driver.Server`

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#410]
For some purposes such as running on App Engine, it may be useful to have the additional flexibility afforded by having a `Driver` field on `server.Server`, something like this:

```
type Server struct {
	reqlog        requestlog.Logger
	healthHandler health.Handler
	te            trace.Exporter
	sampler       trace.Sampler
	once          sync.Once
	server        *http.Server
	driver        driver.D  // <- Add this line
}
```
where `server/driver.D` is defined like this:
```
package driver 
type D inferface {
	func Serve(http.Handler)
}
```

**Comment by vangent** [comment]
Some more context/details:

[server.Server.ListenAndServe](https://github.com/google/go-cloud/blob/master/server/server.go#L85) creates an `http.Server` and calls ListenAndServe on it. The caller never gets access to the http.Server, so can't set any options on it.

#354 requests setting some options on the http.Server, which we could do, but I don't think it's a good idea to set a subset of options without giving the user the ability to override them or to set other options.

@zombiezen has suggested it `server` be refactored to:

* Have a concrete type backed by a driver interface (similar to `blob`), as described above.
* Server which would take the existing Options and do things like wrap the handler, etc.,
* One implementation of the driver would be for http.Server. It would likely provide a static function to create an http.Server with default options, and then a constructor for the driver that takes the http.Server, thus allowing the caller to set additional options on it if needed.
* There may be other implementations of the driver for AppEngine, etc. (#210 may be related).
