### ISSUE TITLE
sql/ocsql: allow configuration of ocsql instrumentation

### ISSUE THREAD

**Issue by basvanbeek** [google/go-cloud#416]
Currently `ocsql` is included with all trace options enabled. This means that sql queries and query parameters are annotated in spans, which can be undesirable from a security concern as well as a performance one (high cardinality annotations or heavily annotated spans do not sit well with all tracing backends in high QPS systems). This is why default `ocsql` is much more conservative and has all extra trace options disabled. 

I think it would be best to have the conservative default mirrored in Go cloud as well as the ability for consumers to set the configuration of `ocsql` when using Go cloud.

Happy to provide a PR if I can be guided a bit on how Go cloud wants configuration done (would this be part of rdsmysql.Params and cloudmysql.Params?)

**Comment by vangent** [comment]
Thanks for noting this @basvanbeek !

@ijt , can you take a look?

**Comment by ijt** [comment]
Sure, looking.

**Comment by ijt** [comment]
I'm thinking we can add a `[]TraceOption` parameter to the `Open` funcs in the mysql packages.

**Comment by zombiezen** [comment]
This is not fixed. RDS still does not allow the configuration to be passed in.

https://github.com/google/go-cloud/blob/f4c33a8eb84a6b8164d6be83bcde0bfe79a49a0b/mysql/rdsmysql/rdsmysql.go#L129-L131
