### ISSUE TITLE
blob: creation of *blob.Bucket from URLs

### ISSUE THREAD

**Issue by sargun** [google/go-cloud#423]
It would be nice if someone could provide a URL, and that would return a *blob.Bucket. If this project standardized on a schema like:

* Google Cloud: `gcp://mybucket/`
* S3: `s3://mybucket/`
* S3: `s3://AWS_ACCESS_KEY_ID: AWS_SECRET_ACCESS_KEY@mybucket/`
To specify region, maybe something like:
* S3: `s3://AWS_ACCESS_KEY_ID: AWS_SECRET_ACCESS_KEY@mybucket/?region=us-east-1`

**Comment by vangent** [comment]
Hi @sargun , thanks for the suggestion! Do you have a specific use case for this feature?

If I understand correctly, to avoid having to compile in all provider drivers, this would require each provider driver to "register" a URL prefix and a parser, something like:

```
RegisterURL("s3", func(s string) (*blob.Bucket, error) {
  // Parse the rest of the URL
})
```

**Comment by sargun** [comment]
@vangent I would be fine with the current approach where we implicitly include the drivers, and they do their registrations in init(). The primary use case is around configuration, and initialization of the drivers. Today, I have to implement configuration for each blob driver and all of the inputs independently. 

If we look at the RDBMS community, they've solved this to a degree with DB URLs: https://github.com/xo/dburl -- in that, the ORM can usually be initialized based on some URL schema as opposed to bespoke configuration inputs per backend.

**Comment by vangent** [comment]
OK, thanks for the context. We'll discuss this for our next Sprint, so expect the next update in a couple of weeks.

**Comment by zombiezen** [comment]
Next steps here would be to have a more precise design of what these locators would look like and how these strings would be dispatched to bucket-opening functions.
