### ISSUE TITLE
wire: functions calling wire.Build after assigning a variable are silently erased in output

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#428]
This came up in the following situation:
```go
// setupGCP is a Wire injector function that sets up the application using GCP.
func setupGCP(ctx context.Context, flags *cliFlags) (*application, func(), error) {
        traceOpt := withNoTraceOptions()
        // This will be filled in by Wire with providers from the provider sets in
        // wire.Build.
        wire.Build(
                gcpcloud.GCP,
                applicationSet,
                gcpBucket,
                gcpMOTDVar,
                gcpSQLParams,
                wire.Value(traceOpt),
        )
        return nil, nil, nil
}

func withNoTraceOptions() ocsql.TraceOption {
        return func(o *ocsql.TraceOptions) {}
}
```
Running `go generate` here resulted in `wire_gen.go` not containing a `setupGCP` function anymore, because of the assignment to traceOpt. 

This assignment was made necessary by Wire's rejection of `wire.Value(withNoTraceOptions())` since it contains a function call and is therefore too complex by Wire's standards. Maybe the error message should suggest that such assignments be moved out of the injector function and placed in package scope.

**Comment by vangent** [comment]
setupGCP is an invalid injector function; injectors must consist of only the call to `wire.Build` (possibly wrapped in a `panic`) and an optional `return`.

`wire` should report this an an error, though, instead of silently dropping the entire function.
