### ISSUE TITLE
pubsub: lease behaviour

### ISSUE THREAD

**Issue by nfisher** [google/go-cloud#432]
Apologies not sure this is the correct location to post this but I'm using the Go library to verify pubsubs lease behaviour and I'm not sure how much of what I'm seeing is library vs service based. I suspect it's more related to the latter in which case if you can guide me to the best forum to ask about this it would be appreciated! 😄

#### What did you do?
 
1. Created 1 publisher which publishes a single message to a topic containing a single subscription with a 60s ack deadline.
2. Created 2 subscribers P1 and P2 which subscribe to the above topic/subscription.
3. P1 starts, receives message, and dies (log.Fatal) 10s after startup and prior to ack'ing the message.
4. P2 starts [sub.Receive](https://godoc.org/cloud.google.com/go/pubsub#Subscription.Receive) callback loop ~10s after P1 startup.
5. P2 receives message after P1 dies.

#### What did you expect to see?

For step 5 I expected to see P2 receive the message close to the "ack deadline" less the 10s delay.

#### Reproducible test case

https://github.com/fresh8/domsub/
Run `GOOGLE_PROJECT_ID=YOUR_PROJECT make s2` replacing YOUR_PROJECT with an appropriate GCP project.

#### What did you see instead?

The message was received ~10s after P2 died.

Below is an example output from `make s2` run outlined in the reproducible test case.
```
$ make s2
# <!-- snip drain and publish -->

# <!-- P1 starts at 01:53:57 -->
2018/09/12 01:53:57 main.go:34: starting subscriber b9954b24b1af4fcf9bbfde92904e26ad
[b9954b24b1af4fcf9bbfde92904e26ad] 2018/09/12 01:53:57 main.go:37: subscribing to scenario fresh-8-staging domsub
[b9954b24b1af4fcf9bbfde92904e26ad] 2018/09/12 01:53:57 main.go:48: sleep before starting for 0s
[b9954b24b1af4fcf9bbfde92904e26ad] 2018/09/12 01:53:57 main.go:58: sleep before stop for 10s
[b9954b24b1af4fcf9bbfde92904e26ad] 2018/09/12 01:53:57 main.go:73: sleep before ack for 30s
[b9954b24b1af4fcf9bbfde92904e26ad] 2018/09/12 01:53:57 main.go:97: entering receive loop
# <!-- P1 receives message at 01:54:02 -->
[b9954b24b1af4fcf9bbfde92904e26ad] 2018/09/12 01:54:02 main.go:99: received 203633335783895 hola señor!
# <!-- P1 dies at 01:54:07 -->
[b9954b24b1af4fcf9bbfde92904e26ad] 2018/09/12 01:54:07 main.go:61: Yippee ki-yay

# <!-- P2 starts at 01:53:57 (same time as P1) -->
2018/09/12 01:53:57 main.go:34: starting subscriber dfa34cd9a1bb44c1ac12fbd9881adbdd
[dfa34cd9a1bb44c1ac12fbd9881adbdd] 2018/09/12 01:53:57 main.go:37: subscribing to scenario fresh-8-staging domsub
[dfa34cd9a1bb44c1ac12fbd9881adbdd] 2018/09/12 01:53:57 main.go:48: sleep before starting for 10s
[dfa34cd9a1bb44c1ac12fbd9881adbdd] 2018/09/12 01:54:07 main.go:58: sleep before stop for 1m0s
[dfa34cd9a1bb44c1ac12fbd9881adbdd] 2018/09/12 01:54:07 main.go:73: sleep before ack for 0s
[dfa34cd9a1bb44c1ac12fbd9881adbdd] 2018/09/12 01:54:07 main.go:75: entering ack loop
[dfa34cd9a1bb44c1ac12fbd9881adbdd] 2018/09/12 01:54:07 main.go:97: entering receive loop

# <!-- P2 receives message 11s after P1 died at 01:54:07 -->
[dfa34cd9a1bb44c1ac12fbd9881adbdd] 2018/09/12 01:54:18 main.go:99: received 203633335783895 hola señor!
[dfa34cd9a1bb44c1ac12fbd9881adbdd] 2018/09/12 01:54:18 main.go:88: acking 203633335783895 hola señor!
[dfa34cd9a1bb44c1ac12fbd9881adbdd] 2018/09/12 01:55:07 main.go:65: canceling context
[dfa34cd9a1bb44c1ac12fbd9881adbdd] 2018/09/12 01:55:07 main.go:102: left receive loop
[dfa34cd9a1bb44c1ac12fbd9881adbdd] 2018/09/12 01:55:07 main.go:92: left ack loop
```

Does this mean that in addition to "ack deadline" pubsub also uses TCP teardown for lease expiration? I didn't see an obvious reference to this behaviour in the documentation here;

* https://cloud.google.com/pubsub/docs/pull
* https://cloud.google.com/pubsub/docs/faq

The reason I ask is that I would like to ensure other delays like GC won't lead to a lease expiry in a similar fashion to what was discovered above.

#### System details

```
go version go1.11 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/nathanfisher/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/nathanfisher/workspace/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
GOROOT/bin/go version: go version go1.11 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.11
uname -v: Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65
lldb --version: lldb-902.0.79.7
  Swift-4.1
```

**Comment by vangent** [comment]
Sorry for the confusion, but this is the wrong Github project for this report.
You want:
https://github.com/GoogleCloudPlatform/google-cloud-go/issues/new
