### ISSUE TITLE
all: test that Go Cloud works with the Go 1.11 runtime for App Engine

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#462]
Ping steren when it is confirmed to work.

**Comment by vangent** [comment]
I confirmed that `server.Server` and `gcpblob` work. Notes on internal Google bug b/112000376.
Will file a separate issue for making sure `cloudsql` works on AppEngine, it requires some changes.

**Comment by steren** [comment]
Please link to the issue for `cloudsql` here.

**Comment by vangent** [comment]
Issue #494.
