### ISSUE TITLE
gcp: DefaultCredentials does not allow for passing in scopes

### ISSUE THREAD

**Issue by daenney** [google/go-cloud#466]
Working through the examples I noticed that [`gcp.DefaultCredentials()`](https://github.com/google/go-cloud/blob/master/gcp/gcp.go#L70) always sets the `cloud-platform` scope, which is basically "super duper admin"which feels a little extreme. It doesn't let you pass in scopes, even though the underlying function it calls [`oauth2.google.FindDefaultCredentials`](https://godoc.org/golang.org/x/oauth2/google#FindDefaultCredentials) does take a variadic `scopes` argument.

Given the recommendation in GCP is usually to create service accounts with a limited scope how does this interact when credentials are given that have not been granted that scope? Say for example in the tutorial case, if I were to give it a service account that just had `https://www.googleapis.com/auth/devstorage.read_write`, would it work? Does it automatically downgrade to the scopes of the issued service account, or will this cause an error when requests are made?

If it's the latter case, would a PR that updates `DefaultCredentials` to accept a variadic `scopes` be welcome? It would be nice to not have to do the credential load dance yourself with the oauth2 library just to be able to tweak the scopes.

**Comment by shantuo** [comment]
Thanks for the feedback. Currently one can use the oauth2 package to assemble the correct scope. It may be not a good enough user experience like you mentioned.

I would say if we are going to support it, it should probably be a separate method, like `CustomCredentials`, and let `DefaultCredentials` remain to be the shortcut. Similar situation may also happen for `DefaultProject` and others, I'm not sure yet.

We'll discuss the scope of this change in our next sprint planning, which is next week and decide what to do next.

**Comment by daenney** [comment]
Thanks for the response. I think naming it `CustomCredentials` is a bit odd, I'm not looking to load custom credentials, I'd still be calling oauth2's `FindDefaultCredentials` and have that machinery work, just with the ability to pass in scopes.

So more something like this:

```go
func DefaultCredentials(ctx context.Context, scopes... string) (*google.Credentials, error) {
	var err error
	var adc *google.Credentials
	if len(scopes) == 0 {
		adc, err := google.FindDefaultCredentials(ctx, "https://www.googleapis.com/auth/cloud-platform")
	} else {
		adc, err := google.FindDefaultCredentials(ctx, ...scopes)
	}

	if err != nil {
		return nil, err
	}
	return adc, nil
}
```

This preserves the behaviour of the shortcut while allowing for custom scopes.

**Comment by shantuo** [comment]
Yes, you are right. Feel free to send us a PR if you like, thanks!

**Comment by challenger14** [comment]
I’m not sure what we’re looking at here, defaultcredentials defaultproject. I’m very new to programming, I seek a tutor or mentour to explain how all of this works. Well, I think datamunching  would be an alternative, just add come ploynominal coloumns and EXE, right?

**Comment by zombiezen** [comment]
Echoing the comment I left on #498:

The general recommendation is for service account privilege to be limited by IAM, not by oauth2 scopes.

`gcp.DefaultCredentials` is a thin shim for `google.FindDefaultCredentials`, which can already take in a custom scope. The reason `gcp.DefaultCredentials` exists is to provide a convenient default provider to put in most GCP server Wire graphs. The point of Wire is that if someone needs more customization for their application over what we are providing for common cases, they can just add their own custom provider to their graph.

Thus, I am inclined to keep `DefaultCredentials` as it is now.

**Comment by daenney** [comment]
That's a fair point. Thanks!
