### ISSUE TITLE
runtimevar: add WatchOptions and defaultWait to the concrete type

### ISSUE THREAD

**Issue by shantuo** [google/go-cloud#485]
Consider let the concrete type defines a WatchOptions with a WaitTime, and a defaultWait, user can choose provide a custom WaitTime or leave it. The concrete type will use the user provided or defaultWait and pass it into drvier.WatchVariable. The driver.WatchVariable can always expect to receive a meaningful WaitTime.

One downside may be exposing types that are not always used, e.g. constantvar wouldn't use WaitTime.

**Comment by vangent** [comment]
I looked into this a while ago and there was some reason why it was harder than I expected. Unfortunately I don't remember what it was, will have to retry.
