### ISSUE TITLE
wire: Generated file fails goimports linter

### ISSUE THREAD

**Issue by gracenoah** [google/go-cloud#493]
Wire sorts imports alphabetically [here](https://github.com/google/go-cloud/blob/8163be07c118a1370c0a78386afd0d630f5b032f/wire/internal/wire/wire.go#L180), however this does not always translate into lint-valid imports.

E.g.

```go
// +build wireinject

package main

import (
	"context"
	"fmt"
	"time"

	"cloud.google.com/go/civil"
	"github.com/google/go-cloud/wire"
)

func main() {
	fmt.Printf("Running since %s\n", InitializeNow())
}

func ProvideNow(ctx context.Context) civil.Date {
	return civil.DateOf(time.Now())
}

func InitializeNow() civil.Date {
	panic(wire.Build(context.Background, ProvideNow))
}
```

The generated file has the following

```go
// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
        "cloud.google.com/go/civil"
        "context"
        "fmt"
        "time"
)

// Injectors from main.go:
// ...
```

Using [gometalinter](https://github.com/alecthomas/gometalinter) with `{"Enable": ["goimports"]}` you'll see
```
$ gometalinter 
wire_gen.go:1::warning: file is not goimported (goimports)
```

The diff after `goimports -w wire_gen.go`

```
import (
-       "cloud.google.com/go/civil"
        "context"
        "fmt"
        "time"
+
+       "cloud.google.com/go/civil"
)
```

Suggested solution is to update [wire.go here](https://github.com/google/go-cloud/blob/8163be07c118a1370c0a78386afd0d630f5b032f/wire/cmd/wire/main.go#L91)

Original
```go
p := filepath.Join(pkgInfo.Dir, "wire_gen.go")
// write
```

Updated
```go
p := filepath.Join(pkgInfo.Dir, "wire_gen.go")
options := imports.Options{
	Comments:   true, // Default
	TabIndent:  true, // Default
	TabWidth:   8,    // Default
	FormatOnly: true,
}

out, err = imports.Process(p, out, &options) // Uses golang.org/x/tools/imports
// check error then write
```

If people agree with this approach I can create a PR for it.

**Comment by vangent** [comment]
Hi @gracenoah , thanks for checking out `wire`!

It's probably not necessary to run your lint checks on generated code, as this kind of thing might keep happening.

Wire does call the equivalent of `gofmt` [here](https://github.com/google/go-cloud/blob/8163be07c118a1370c0a78386afd0d630f5b032f/wire/internal/wire/wire.go#L58); if you want to send a PR to call the equivalent of `goimports`, that would be the place to add it (not in the command-line tool).

Thanks!

**Comment by gracenoah** [comment]
Thanks for the reply @vangent .

After some more research I found this issue https://github.com/alecthomas/gometalinter/issues/270#issuecomment-386317548 which is in line with what you said.

I updated my configuration so it looks like `{"Enable": ["goimports"], "Exclude": ["wire_gen.go"]}` which no longer causes problems.

You may close this issue you think it is out of scope.

**Comment by vangent** [comment]
Ack, thanks!
