### ISSUE TITLE
wire: tutorial doesn't mention wire

### ISSUE THREAD

**Issue by rogpeppe** [google/go-cloud#515]
The [blog post](https://blog.golang.org/wire) announcing Wire points to "a [tutorial](https://github.com/google/go-cloud/tree/master/samples/tutorial) that walks through using Wire in a simple application". However, the linked tutorial doesn't mention Wire.

**Comment by vangent** [comment]
Thanks for the report; you are right. It should point here:
https://github.com/google/go-cloud/tree/master/samples/wire

**Comment by enocom** [comment]
The CL into the blog is [here](https://go-review.googlesource.com/c/blog/+/141137).

**Comment by enocom** [comment]
The updated post has been published.

@rogpeppe Thanks for catching this.
