### ISSUE TITLE
server: specify behavior of calling ListenAndServe multiple times

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#516]
After doing a deep dive into the server package with @clausti, I am unclear as to what the correct semantics of calling `ListenAndServe` ought to be, especially with the presence of `Shutdown`. In particular, we should address:

1. Is it permissible to call `ListenAndServe` multiple times on a single server?
2. If so, then is it permissible to call `ListenAndServe` concurrently? What is the expected behavior of `Shutdown` after multiple `ListenAndServe` calls?
3. If not, is it undefined behavior or an error to call `ListenAndServe` multiple times?

**Comment by eliben** [comment]
@shantuo unassign yourself if you don't have time to deal with this. Maybe we should then add a "good first issue" label on it?

**Comment by shantuo** [comment]
I remember I once dug into the `net/http` package but didn't find any definition on this behavior, not sure whether this is a documentation issue.
