### ISSUE TITLE
wire: don't work with go modules [go v.1.11.1]

### ISSUE THREAD

**Issue by Terminator637** [google/go-cloud#517]
When I run the wire command, I get the following:
```
...
/home/terminator/.gvm/pkgsets/go1.11.1/global/pkg/mod/github.com/ory/dockertest@v3.3.2+incompatible/dockertest.go:13:2: could not import github.com/cenkalti/backoff (cannot find package "github.com/cenkalti/backoff" in any of:
                /home/terminator/.gvm/gos/go1.11.1/src/github.com/cenkalti/backoff (from $GOROOT)
                /home/terminator/.gvm/pkgsets/go1.11.1/global/src/github.com/cenkalti/backoff (from $GOPATH))
...
and many many other dependencies...
```
wire looks at GOPATH and GOROOT instead of modules dir, what am I doing wrong?

**Comment by vangent** [comment]
Try 

```
export GO111MODULE=on
```

?

**Comment by Terminator637** [comment]
> Try
> 
> ```
> export GO111MODULE=on
> ```
> ?

Thanx, it works!

**Comment by vangent** [comment]
@zombiezen shouldn't this work with the default?

**Comment by gbrlsnchs** [comment]
I have the same issue even with `GO111MODULE` set to `on`. I'm also using `go1.11.1`, on Ubuntu 18.04. The output is the same: a bunch of unimportable modules that come from dependencies...

**Comment by Terminator637** [comment]
Now i got these errors in random. Once in works, two times got errors, next time it works, and so on.

**Comment by gbrlsnchs** [comment]
@zombiezen No, vendoring the dependencies did not work, unfortunately. I still get the same kind of output @Terminator637 has mentioned in this issue's description.

**Comment by zombiezen** [comment]
#78 is now fixed, and I believe this to be a dupe. Please reopen this bug if you are still experiencing issues.
