### ISSUE TITLE
wire: Please break Wire out into it's own repo.

### ISSUE THREAD

**Issue by breerly** [google/go-cloud#527]
Hey there, one of the authors from [go.uber.org/dig](https://github.com/uber-go/dig) and [go.uber.org/fx](https://github.com/uber-go/dig) here.

Wire looks supremely useful - can you break this library out into it's own independently versioned repository? I'd love to prototype an application framework based on Wire, but would be hesitant to do so without a standalone semantically versioned package.

**Comment by vangent** [comment]
This is a duplicate of #513.
