### ISSUE TITLE
contributebot is failing

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#531]
I'm creating this issue without the required "component: description" to taunt it.

https://pantheon.corp.google.com/logs/viewer?interval=NO_LIMIT&project=go-cloud-contribute-bot&organizationId=433637338589&minLogLevel=0&expandAll=false&timestamp=2018-10-11T23:49:59.941000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22container%22%20resource.labels.cluster_name%3D%22contributebot-cluster%22%20resource.labels.namespace_id%3D%22default%22%20resource.labels.project_id%3D%22go-cloud-contribute-bot%22%20resource.labels.zone:%22us-central1-c%22%20resource.labels.container_name%3D%22contributebot%22%20resource.labels.pod_id:%22contributebot-worker-%22&scrollTimestamp=2018-10-11T23:49:52.000000000Z

{
 insertId:  "1thef2rg29jkbj4"  
 labels: {…}  
 logName:  "projects/go-cloud-contribute-bot/logs/contributebot"  
 receiveTimestamp:  "2018-10-11T23:49:54.089133279Z"  
 resource: {…}  
 severity:  "ERROR"  
 textPayload:  "2018/10/11 23:49:52 Failed processing pull_request event d7eb67e0-cdaf-11e8-88a2-142334b6ac65: Get https://api.github.com/repos/google/go-cloud/pulls/530: fetch GitHub installation token: Post https://api.github.com/installations/297694/access_tokens: dial tcp 192.30.253.116:443: i/o timeout
"  
 timestamp:  "2018-10-11T23:49:52Z"  
}

**Comment by vangent** [comment]
Oh ContributeBot, you cheeky monkey. Apparently it was only a transient failure.

**Comment by zombiezen** [comment]
This reminds me though: we should add in some monitoring/alerting to make sure that Contribute Bot does not fall too far behind on its work queue. I'll investigate.
