### ISSUE TITLE
blob: do not use relative path to access conformance testdata

### ISSUE THREAD

**Issue by shantuo** [google/go-cloud#532]
This will fail if the provider implementation resides outside the main repo, e.g. https://github.com/google/go-cloud/blob/master/blob/s3blob/s3blob_test.go#L58

**Comment by vangent** [comment]
Yea, there is a [TODO](https://github.com/google/go-cloud/blob/master/blob/drivertest/drivertest.go#L272) to use go-bindata to inline them as source.
