### ISSUE TITLE
blob/fileblob: support signed URLs

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#546]
This is a feature we'd like to develop, but don't want to block #530's submission on it. It's important that our local implementations continue to provide the functionality for testing features.

`fileblob` should take in a URL or an interface to a signed URL creator, as well as providing some implementation (in-process or out-of-process HTTP handler) that serves signed blob URLs. We might want to make this optional, as some applications may very well be fine without having signed URLs for their blobs, but it should be Easy™️ to do.

/cc @clausti @vangent

**Comment by vangent** [comment]
Next step on this is a design proposal for how to do it.

**Comment by vangent** [comment]
This is fixed!
