### ISSUE TITLE
all: iterators should be consistent

### ISSUE THREAD

**Issue by jba** [google/go-cloud#565]
There are going to be many iterators in Go Cloud. They should have a consistent look and feel. [These guidelines](https://github.com/GoogleCloudPlatform/google-cloud-go/wiki/Iterator-Guidelines) are a good starting point, but require tweaking. Suggestions:

- For the function that returns the iterator, use the plural of the thing iterated over. E.g. `Bucket.Blobs`. Adding the word `List` is redundant. Using _only_ `List` (as in the current `Bucket.List`) could be ambiguous. In the special case of `blob.Bucket`, it seems that all the methods assume blobs, so maybe it's okay there.

- The iterator type itself should be named _Thing_`Iterator`, e.g. `BlobIterator`. In the name `ListIterator`, the word `List` conveys no information, since all iterators are presumably the result of listing things. (It's like the `Get` in `GetAttributes`.)

- The `Next` method should indicate that it's done by returning a sentinel error. The guidelines linked above use an error that is Google-specific. Go Cloud should either use `io.EOF` or define its own.

**Comment by jba** [comment]
I looked for the rationale for using `iterator.Done` instead of `io.EOF` in the Google Cloud Libraries for Go, and couldn't find a good one. I'm in favor of `io.EOF`. Are there objections?

**Comment by vangent** [comment]
SGTM

**Comment by vangent** [comment]
From discussion elsewhere: as part of using `io.EOF`, the concrete implementation of Bucket.Next should handle empty `ListPaged` results from drivers by calling `ListPaged` in a loop until it returns `io.EOF`.

**Comment by vangent** [comment]
@jba is there more you want to do here, or can this issue be closed?

**Comment by jba** [comment]
We haven't discussed the first two bullet points. To be concrete, I propose:

- Renaming `Bucket.List` to `Bucket.Blobs`
- Renaming `ListIterator` to `BlobIterator`

**Comment by vangent** [comment]
Personally I like `Bucket.List` better than `Bucket.Blobs`. I agree that the "List" in `ListIterator` isn't necessary, although I don't think it hurts. Maybe ask around for more opinions....

**Comment by jba** [comment]
Let me suggest that we write a few more of these (pubsub, etc.). We then may notice that iterators come up often, and we may then see the value in some sort of standardization.

Or that may not happen. Most of the iterators in the cloud client libraries are for admin-like things (list all the topics, list all the tables, etc.)

**Comment by eliben** [comment]
Do we have a better idea on the plans here now? We're nearing the point of no-breaking-changes so if we really must rename something it has to happen very soon. In any case, currently the number of blob users is nontrivial so it would be a shame to break them

**Comment by jba** [comment]
I'll give up on this.
