### ISSUE TITLE
blob: add support for content-md5

### ISSUE THREAD

**Issue by myml** [google/go-cloud#569]
### Is your feature request related to a problem? Please describe.

add support for [Content-md5](https://tools.ietf.org/html/rfc1864)

### Describe alternatives you've considered

```go
type WriterOptions struct{
    ContentMD5 string
    ...
}
```

**Comment by jba** [comment]
Confirmed that the three major cloud providers support this on blob write.

**Comment by vangent** [comment]
Thanks for the contribution @myml ! This will be in our next release.
