### ISSUE TITLE
mysql: OpenCensus instrumentation not used

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#590]
For example, in the `cloudmysql` package, the driver is wrapped here:

https://github.com/google/go-cloud/blob/11bb776c80e5cc8abaa6c9aead66d5c1129c9632/mysql/cloudmysql/cloudmysql.go#L95

but is not wrapped in the `Connect` method, which is what is called to create new connections:

https://github.com/google/go-cloud/blob/11bb776c80e5cc8abaa6c9aead66d5c1129c9632/mysql/cloudmysql/cloudmysql.go#L79

**Comment by zombiezen** [comment]
For reference, #400 is the PR that introduced the instrumentation.

**Comment by vangent** [comment]
@ijt is this addressed by your upcoming changes?

**Comment by ijt** [comment]
@vangent , do you mean a fixed version of #511?

**Comment by vangent** [comment]
Yes.

**Comment by ijt** [comment]
I think this should be fixed in a separate PR.
