### ISSUE TITLE
wire: the "Binding Values" example does not work

### ISSUE THREAD

**Issue by VadimKulagin** [google/go-cloud#595]
### Describe the bug

In the Wire README there is an example:
```go
type Foo struct {
    X int
}

func injectFoo() Foo {
    wire.Build(wire.Value(Foo{X: 42}))
    return Foo{}
}
```

And there is a note:
> The generated injector would look like this:

```go
func injectFoo() Foo {
    foo := Foo{X: 42}
    return foo
}
```

But in fact, this example does not work and an error occurs when calling "wire":
```bash
$ wire 
/path/to/wire.go:81:1: inject injectFoo: value example.com/dev/project.Foo can't be used: X is not declared in package scope
wire: generate failed
```

What am I doing wrong? Why is this error displayed?

### To Reproduce

See above

## Expected behavior

> The generated injector should look like this:

```go
func injectFoo() Foo {
    foo := Foo{X: 42}
    return foo
}
```

### Version

I tried v0.4.0 and master.

### Additional context

go version go1.11 darwin/amd64

**Comment by vangent** [comment]
Yes, this looks like a bug introduced as part of #405.
