### ISSUE TITLE
blob/tests: add some concurrency tests

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#626]
Add some conformance tests that use the `blob` API concurrently and make sure things work.

**Comment by eliben** [comment]
The record/replay infrastructure we currently use for blob testing (`go-vcr`) doesn't deal well with non-determinism, and concurrent tests will produce non-deterministic orders of requests/responses.

We'll be looking into using `httpreplay` for blob conformance tests

**Comment by eliben** [comment]
@vangent would you like to see additional concurrent tests beyond #1952?

**Comment by vangent** [comment]
Nope, LGTM!
