### ISSUE TITLE
all: design proposal for how to introduce metrics and tracing into APIs

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#629]
E.g., `blob` should export some basic, opencensus metrics and allow debug logging to be enabled.

Questions include:

- What should be in the concrete type vs in driver implementations.
- Should we even log? (some argue that libraries shouldn't log at all).
- What's the right way to enable logging? `Printf` like function in `Options`? An interface provided in `Options`? `log.Printf`?
- What metrics should [`blob`, `runtimevar`, `pubsub`] export?

**Comment by ijt** [comment]
If we add logging, can we please make it optional? Spammy logs are a nuisance.

**Comment by vangent** [comment]
I think I would vote for adding an optional `Printf`-like function in `Options`, and adding some logging in the concrete type, specifically at places where it is calling the driver. Logging would be optional because by default the `Option` would be `nil`. Tests could pass `t.Logf`.

We could also add `t.Log` statements to the conformance tests; along with some logging in the concrete type/driver implementations, that would make debugging conformance tests much easier (important for someone adding a new provider).

**Comment by jba** [comment]
> Tests could pass `t.Logf`.

That will make tests very chatty. I often add print statements at specific locations to help be debug. That will make those much harder to use.

**Comment by vangent** [comment]
> That will make those much harder to use

Why? You would use `t.Log` instead of `Printf`. Do you mean that it would be hard to find your specific log statements?

I've found the opposite -- every time I want to debug something in the conformance test, I end up adding a bunch of print/log statements in the conformance test code helping me narrow down where the error is coming from; some basic logging about what the test is doing would help.

**Comment by jba** [comment]
Yes, it would be hard to find my specific statements. All other log lines are noise at that point.

Since I rarely need to print the same things for different bugs, I'm skeptical that there is a single, really valuable set of log statements. But I guess that's an empirical question. I'm not opposed to trying it if you really want to.

**Comment by jba** [comment]
Tracing is discussed in #1126 and metrics in #1130.
