### ISSUE TITLE
internal/contributebot: update to use Go Cloud pubsub

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#637]

**Comment by zombiezen** [comment]
@jba @ijt Ping, I do think this would be a good case study of the Pub/Sub API.

**Comment by jba** [comment]
I'll do it.

**Comment by zombiezen** [comment]
Thanks @jba!

**Comment by ijt** [comment]
The code there looks like it would be a good fit for `ReceiveConcurrently`.
