### ISSUE TITLE
pubsub: add conformance tests

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#639]

**Comment by ijt** [comment]
Grabbing this to get a bit more confidence in the new GCP PubSub driver (https://github.com/google/go-cloud/pull/705).

**Comment by vangent** [comment]
> I think it will make sense to apply the conformance tests to @jba's new `fakepubsub`/`mempubsub` package (#673) as part of the scope of this issue, as a quick way to get a sense of whether the tests are usable.

Yup -- in fact, jba@'s tests in #673 are probably a good start for tests that should be in the conformance test suite.
