### ISSUE TITLE
internal/proxy: eliminate possibility of conflicts

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#661]
Currently, if two contributors to Go Cloud attempt to update the module proxy, each trying to add a new dependency, they may accidentally break each others' pull request builds. It would be better if the script effectively only appended to the GCS bucket instead of deleting values to avoid this possibility, however infrequent.

**Comment by zombiezen** [comment]
@vangent, one straightforward fix I just thought of: the first step of updating the proxy could be `gsutil cp gs://go-cloud-modules "$tgp"`. That way, any subsequent steps would be additive. WDYT?

**Comment by vangent** [comment]
Straightforward fix SGTM. Maybe just leave a comment that occasionally we should skip that step to trim the gsutil bucket down to what we're actually using.
