### ISSUE TITLE
pubsub: inject bundlers into NewTopic and NewSubscription

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#665]
Currently these constructors take their own options structs and create bundlers behind the scenes, but they would be more flexible if they would accept bundlers as arguments instead. That would mean that the handlers these constructors currently hide as anonymous funcs would have to be made public funcs in the `pubsub` package, with comments saying that they are meant for driver use only.

**Comment by vangent** [comment]
@jba FYI

This would look something like:

```
package pubsub

// ...
func NewTopic(d driver.Topic, b driver.Bundler)
```

```
package driver

// ...
type Bundler interface {
  Add(item interface{}, size int)
  Flush()
}
```

I don't think the handlers would need to be exposed in the `pubsub` package, as they aren't needed for the interface that the concrete type uses.

**Comment by vangent** [comment]
To do record/replay tests for providers, you need to have reproducible requests; I think having a dynamic bundler, or even a time-based bundler, will make that difficult.

**Comment by vangent** [comment]
`pubsub.NewTopic` is already a driver-only API, so I don't think this is changing our user-facing API. We could add `Bundler()` to the driver interface instead?

**Comment by ijt** [comment]
Based on the feedback from @vangent, this is no longer a priority. Closing it for now.
