### ISSUE TITLE
pubsub: no longer block on Ack() calls

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#678]
As per @rsc's comment, it doesn't make sense to do different things conditionally on whether an Ack call succeeds, so we may as well remove the `error` return and no longer block in these calls.

**Comment by rsc** [comment]
What is the model for why an Ack RPC might fail? If Ack is failing then probably Receive should cut out, no? I mean, if you can't Ack anything, why bother continuing to Receive things?

**Comment by ijt** [comment]
If there is a network partition then the Receive calls will start failing once the messages in the queue are exhausted. We don't have to do anything extra for the to happen.

**Comment by vangent** [comment]
After thinking about this more, I'm not sure I agree with the change.

If an ack fails, users may want to do things like:
-- retry the ack
-- revert something they did while processing the message (probably a bad idea, but...?)
-- log
-- add metrics

It might be useful to imagine what the docstring on the `Ack` function should say. Something like

```
Ack returns immediately, but actual acks may be processed asynchronously and are not guaranteed to succeed.
```

? As a user, that would not make me feel good about using it. I also don't like the asynchronous part; it seems to violate our approach of making the API synchronous and letting the user decide when they want to introduce concurrency.

**Comment by ijt** [comment]
Another possibility: add a callback that can handle this case in a user-specified way.

```go
package pubsub

type Subscription struct {
    // ...
    OnAckFailure: func(ids []driver.AckID, err error)
}
```

**Comment by jba** [comment]
As a data point, `cloud.google.com/go/pubsub` has turned ack failures into receive failures for a while, and no one has complained.

Retries should be handled by the driver. If the driver returns an error, we should assume it's unrecoverable. That should be the general principle for all driver implementations, because retry logic is going to be provider-specific.

We should add OpenCensus metrics around all our driver calls.

Logging the error from Receive would be logging the ack error.

**Comment by vangent** [comment]
> add a callback that can handle this case in a user-specified way
IMHO that's not an improvement over the simple blocking call.

> turned ack failures into receive failures
What exactly does this mean? Does the ack keep getting retried in the background, and receive keeps failing until the ack eventually succeeds? This seems fragile, a malformed ack of some kind could break your subscription entirely. Maybe that never happens.

> Retries should be handled by the driver
Agreed.

I guess I'm just nervous about the assertion that no user's code will ever want/need to know when an ack was sent, and whether it succeeded. Maybe it is true, but it's not a no-brainer to me.

**Comment by ijt** [comment]
I still don't know what sort of error could occur in SendAcks that would make sense to send back as the error result of Receive if Receive was going to succeed otherwise.

Conversely, if Receive was also going to fail then is it supposed to return some combination of its own error and the one from SendAcks?

What @vangent is saying has the advantage of being straightforward and consistent with the rest of the API. Since no one seems to like the callback idea, I'm inclined to go back to blocking Ack().

**Comment by ijt** [comment]
It's probably worth mentioning that we came to an agreement about not blocking on `Ack` during a meeting yesterday. The idea is that acks should be retried if there is a transient failure, but a non-transient failure should put the associated `Subscription` object into an unusable state where all calls to its `Receive` method return an error that can somehow be identified as non-retryable.
