### ISSUE TITLE
all: decide whether to have common Client types

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#679]
In a review for the `pubsub` design, @rsc pointed out that there is some boilerplate in the `acmepubsub` example given there, having to do with `Client` methods that create `Topic`s and `Subscription`s, and that it seems a bit strange to not have a `Client` type in the concrete `pubsub` API.

The `blob` package similarly has no `Client` type in its concrete API, so the same question applies to it. Let's discuss and see if Go Cloud should have standard `Client` types for these sorts of packages.

**Comment by vangent** [comment]
Duplicate of #970.
