### ISSUE TITLE
pubsub: specify behavior of calling Ack multiple times on a message

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#688]
In the design doc and in the current set of stubs, `*Message.Ack`'s doc comment currently does not specify whether it is acceptable to call `Ack` multiple times on a single message. I would advise for it to be idempotent, much like [`context.CancelFunc`](https://godoc.org/context#CancelFunc).

**Comment by ijt** [comment]
Agreed, I'll update it.

**Comment by ijt** [comment]
Thinking about this a bit more, there isn't much a provider could reasonably do in response to a second ack other than leaving it acknowledged and possibly returning an error to say it was already acked.

**Comment by ijt** [comment]
I suggest we leave this unspecified until we find a popular provider that does something surprising in the case of redundant acks.

**Comment by zombiezen** [comment]
I'm not saying in the provider side. I'm saying that the concrete type should specify whether this is a no-op, a panic, or something else. I'm strongly in favor of no-op.

**Comment by ijt** [comment]
No-op may be the most reasonable option since we have no way to return errors from `Ack` now.

To avoid hiding bugs, I suggest we also keep a histogram of the numbers of times messages are acked in OpenCensus.

**Comment by ijt** [comment]
Filed https://github.com/google/go-cloud/issues/816

**Comment by zombiezen** [comment]
I don't agree that it's a bug to call it multiple times. Imagine something like:

```go
msg, err := sub.Receive(ctx)
if err != nil {
  return err
}
defer msg.Ack()
if err := doThing(msg); err != nil {
  return err
}
// Acknowledge message delivery before sending some lossy signal below.
msg.Ack()
// Do some additional non-essential processing of the message.
if err := doPostprocessing(msg); err != nil {
  return err
}
return nil
```

It's quite useful to depend on the idempotency property for control flow reasons like that above, where you can `defer` the acknowledgement as well as call it explicitly.

**Comment by ijt** [comment]
I don't believe this example. Why would anyone bother to do non-essential yet time-consuming post-processing of a message that would make it exceed an ack deadline? If we need a way to extend ack deadlines then let's just add that.

Let's assume that multiple acks on a message are a programmer error, and panic for now. As @zombiezen pointed out in our offline discussion, starting this way means we have the option to move to no-op later as a non-breaking change whereas going the opposite way would be more disruptive.
