### ISSUE TITLE
internal/pubsub: deal with error returned from SendAcks

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#695]
Currently the code does nothing in this case.
Should we:
* log
* panic
* increment a counter
* send it to Open Census
* something else
?

**Comment by jba** [comment]
If you can't ack, then you're wasting your time receiving and processing messages. They're all going to be redelivered anyway.

`cloud.google.com/go/pubsub` fails Receive if the ack RPC fails (https://code.googlesource.com/gocloud/+/master/pubsub/iterator.go#449). 

The action of retrying the RPC is the driver's responsibility. We should assume an error from `driver.SendAcks` is unrecoverable.

**Comment by ijt** [comment]
When would acking fail other than a network partition that would also cause Receive to fail?

**Comment by jba** [comment]
I thought we resolved this verbally, but we never wrote it down. I guess we should discuss it again.

I think the right thing to do on a non-retryable error from SendAcks is to have it returned from the next call to Receive. It should also be permanent, in other words, all subsequent calls to Receive for that Subscription return the same error immediately.

The rationale is that if acking is failing, whatever work the program is doing is wasted; the work is going to happen again.

> When would acking fail other than a network partition that would also cause Receive to fail?

I don't think it's useful to speculate about failure modes like this. It's really hard to understand how these distributed, high-throughput services work. For example, it could be that the acks go to a different place than where the received messages come from. We should code assuming the worst case, that the errors from Receive and SendAcks are independent.

**Comment by jba** [comment]
@ijt @vangent let's try to settle this soon since it's one of the last unfinalized bits of pubsub behavior .

**Comment by vangent** [comment]
IMHO we should clearly document the behavior for `Receive` under failure modes. For example, if the provider implementation is based on polling a server, and the server is down/unreachable, does `Receive` just stay blocked until a poll succeeds? Or does it return an error? Or does it block for some amount of time and eventually give up? The behavior for `SendAcks` failures should fit into whatever semantics we describe for `Receive`. For example, if `Receive` always just blocks forever if the server is down, then it seems like `SendAcks` failures should cause `Receive` to stop returning messages until `SendAcks` succeeds. If `Receive` returns an error immediately, then having it do so when `SendAcks` fails seems reasonable.

> The action of retrying the RPC is the driver's responsibility

This is no longer necessarily true, is it? The concrete type does retries if the driver returns errors for which `IsRetryable` returns true.

**Comment by jba** [comment]
I think the behavior should always be the same for anything with outgoing RPCs: it retries retryable errors indefinitely, or until the context it's given is done. The definition of retryable is up to the driver, and the doneness of the context is up to the caller -- they can cancel or set a timeout.

This is how Receive already behaves, as does the batcher handler that calls SendAcks. But we drop the SendAcks errors on the floor (after retrying). 

I don't agree that Receive should block until SendAcks succeeds, although I could see us adding some flow control just so we don't run out of RAM. But I think that's somewhat orthogonal to this issue, which is what to do when SendAcks fails "for good" (i.e. the error isn't retryable). 

It sounds like you're not opposed to that error surfacing in Receive, so I'll make a PR for that and we can discuss further there.
