### ISSUE TITLE
pubsub/gcppubsub: allow logging of pull errors

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#713]
Quoting @zombiezen , in his review of https://github.com/google/go-cloud/pull/705, referring to the call to `s.client.Pull(ctx, req)`:

> Unfortunately, this error will never get seen by the end user, but it could be helpful for debugging. We could add a hook to the constructor to the effect of:
> 
> ```go
> // A type that implements ErrorLogger reports errors that occur while receiving a batch.
> type ErrorLogger interface {
>   LogError(context.Context, error)
> }
> ```
> 
> (Probably with some filtering for transient errors or such.)

**Comment by vangent** [comment]
We need to come up with a unified plan for logging & metrics, across all Go Cloud APIs. https://github.com/google/go-cloud/issues/629 is tracking that; I think this is  a dupe of that.

@ijt if you agree, please close as a dupe.

**Comment by zombiezen** [comment]
I believe it to have a bit more nuance: at the moment, the current design of the package hides errors, whereas most other packages in Go Cloud report errors to the caller. I believe this case can inform the outcome of #629, but I believe them to be separate issues.

**Comment by ijt** [comment]
I have a bad feeling about "hides errors". It makes me think I should get rid of the retry loop in the GCP PubSub driver and either move it to the concrete API or just allow it to propagate up. Applications will typically be processing messages in a loop, so they will keep on making receive calls anyway. They can decide to log it, bail out, increment a counter, whatever they like.

**Comment by jba** [comment]
I'm confused about this. Pull will either result in a retryable error, in which case we'll retry it (that's not hiding it!); or it will result in a non-retryable error, in which case it will be returned from `RetrieveBatch` and then from `pubsub.Receive`. Maybe this issue isn't taking #730 into account?

**Comment by ijt** [comment]
Closing as a dup of #629 for now. If we find that this really needs to be handled as a special case we can reopen it.
