### ISSUE TITLE
mempubsub: OpenTopic and OpenSubscription should return concrete types

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#714]
See https://github.com/google/go-cloud/blob/ba6cdfb00c3d227ebaa0243978d0b9860b9f60e7/blob/fileblob/fileblob.go#L98 for a precedent.

We might decide to change how we're doing this, but if we do then it should be done consistently across all the Go Cloud packages.

**Comment by jba** [comment]
I started doing this, but ran into a problem.

`OpenSubscription` takes a topic, which is the topic it subscribes to. The actual implementation adds the subscription to the topic's list of subscriptions:
```
   tt := t.(*topic) 
   ...
   s := &subscription{
        topic:       tt,
        ackDeadline: ackDeadline,
        msgs:        map[driver.AckID]*message{},
        ctx:         ctx,
        cancel:      cancel,
    }
    tt.mu.Lock()
    defer tt.mu.Unlock()
    tt.subs = append(tt.subs, s)
```
This works when the `t` argument to `OpenSubscription` is a `driver.Topic`, because I can just assert it to my own implementation, as in the first line above. But if the arg is a `*pubsub.Topic`, I don't know what to do.

**Comment by vangent** [comment]
Name the topics, keep a map of them, and then `OpenSubscription` takes a
name?

**Comment by ijt** [comment]
Right, because, pubsub.Topic.driver is a private field and you can't access it from the mempubsub package.

The root of the problem seems to be that `mempubsub.OpenTopic` and `mempubsub.OpenSubscription` are misnomers. They actually create topics and subscriptions rather than opening existing ones. One way to fix this would be to add a `mempubsub.Broker` with `CreateTopic` and `CreateSubscription` methods.

Oh, haha, @vangent just independently came up with roughly the same thing.

**Comment by ijt** [comment]
Something like this:

```go
package mempubsub

type Broker struct {
  tops map[string]top2
  subs map[string]sub2
}

type top2 struct {
  t *pubsub.Topic
  dt *topic
}

type sub2 struct {
  s *pubsub.Subscription
  ds *subscription
}

func (b *Broker) CreateTopic(ctx context.Context, name string) {
  dt := &topic{}
  t := pubsub.NewTopic(ctx, dt)
  b.tops[name] = top2 {t, dt}
}

func (b *Broker) CreateSubscription(ctx context.Context, topicName, subName striing) {
  tt := b.tops[topicName].dt
  ctx, cancel := context.WithCancel(context.Background())
  ds := &subscription{
          topic:       tt,
          ackDeadline: ackDeadline,
          msgs:        map[driver.AckID]*message{},
          ctx:         ctx,
          cancel:      cancel,
  }
  tt.mu.Lock()
  defer tt.mu.Unlock()
  tt.subs = append(tt.subs, ds)
  s := pubsub.NewSubscription(ctx, ds)
  b.subs[subName] = sub2{s, ds}
}

func OpenTopic(b *Broker, name string) (*pubsub.Topic, error) {
  t2 := b.tops[name]
  if t2 == nil {
    return nil, fmt.Errorf("topic not found: %s", name)
  }
  return t2.t, nil
}

func OpenSubscription(b *Broker, name string) (*pubsub.Subscription, error) {
  s2 := b.subs[name]
  if s2 == nil {
    return nil, fmt.Errorf("subscription not found: %s", name)
  }
  retrun s2.t, nil
}
```
