### ISSUE TITLE
blob/fileblob: rename to fakeblob?

### ISSUE THREAD

**Issue by clausti** [google/go-cloud#720]
In considering the implementation for https://github.com/google/go-cloud/issues/546, there is a large difference between what I'd design for a `fileblob` that is really `fakeblob`, intended only for testing and local dev use, versus `fileblob` that is a first-class sibling to `gcsblob` or `awsblob`. And there seems to be considerable ambiguity right now about which use case to design for. 

Having a signed URL api for `fileblob` as a first-class/non-test provider seems like it would require us to make guarantees that are kind of intense. Or we could rename it to make it very clear what the intention for that package is, and _caveat emptor_. 

This has been [previously considered](https://github.com/google/go-cloud/pull/673#discussion_r233605383) a couple of times with no changes to the naming, but I think the signed URL implementation requires that we commit to an intention for `fileblob` one way or the other, and it seems like the intention is (and has been) that it's a dev blob, despite the name.

**Comment by vangent** [comment]
My 2 cents: `fileblob` is for testing and local dev use. However, I think the latter still means it needs to be a first-class sibling (depending on what you mean by first class).

-- We may not expect anyone to use `fileblob` in a production deployment. (Although, I am not sure about this; there are probably on-prem deployments that use NFS or other fileshares for storage. Also, there's something similar for Kubernetes).

-- Nevertheless, if an application uses `blob.SignedURL`, and a developer wants to run the application locally, we need `fileblob` to support some form of `SignedURL`.

So, I am inclined to close this as "No" -- do not rename.

We should separately discuss what kinds of intense guarantees you're thinking of. I t may be OK to have best-effort functionality (in the same way that "saving" a blob to `fileblob` has fewer 9s than "saving" a blob to GCS or S3).
