### ISSUE TITLE
all: support RPC retry

### ISSUE THREAD

**Issue by jba** [google/go-cloud#730]
We should establish a common pattern for retrying RPCs. It can't be done completely in the concrete implementations because different providers will have different notions of what is retryable.

@vangent suggested:

- Drivers should provide an `IsRetryable` function or method that takes an error and returns a bool and, if true, a duration. (The duration is to support providers whose RPCs return sleep hints.)

- There should be common code in `internal` that implements exponential backoff.

Alternative designs:

- _Have drivers be responsible for retry._ This puts too much burden on driver implementers.

- _Wrap errors._ Return errors that are annotated or wrapped to indicate whether they are retryable. E.g. if an error has an `IsRetryable` method that returns true, it is retryable; otherwise assume it isn't. This also makes it too hard and error-prone to write a driver, since the wrapping has to be done at every error return.

**Comment by ijt** [comment]
+1 to the driver interface function. That seems clear and discoverable.
