### ISSUE TITLE
pubsub: write a Kafka driver

### ISSUE THREAD

**Issue by jba** [google/go-cloud#732]
As per @spf13.

**Comment by jba** [comment]
I'm going to remove this from Sprint 20 because the vanity import path has higher priority.

**Comment by garukun** [comment]
Not sure if this is right issue to start a discussion, the original [design on pubsub](https://github.com/google/go-cloud/blob/master/internal/docs/pubsub/design.md) mentions Confluent Kafka only. @jba, @zombiezen, I'm wondering if there are plans to support a "homebrew" Kafka deployment? Also, are there plans to integrate the Shopify/sarama (more defacto library in the Kafka world) to this package.

**Comment by zombiezen** [comment]
@ijt, what's the current state here?

**Comment by jba** [comment]
We haven't started exploring Kafka yet. We certainly intend that our integration will work with any Kafka deployment, not just hosted ones like Confluent. That's what we've done for RabbitMQ.

When we dig deeper, we'll evaluate whether Shopify/sarama is the right package for us to use.

**Comment by ijt** [comment]
+1 to what @jba wrote.

**Comment by jasongerard** [comment]
I'm doing a lot of work in go with kafka right now. I'd love to lend a hand to this.

**Comment by jba** [comment]
@jasongerard That would be great! You should start by browsing around the pubsub tree. The Rabbit driver will probably be the closest match, in that we'll want it to be tested against a local Kafka instance rather than a cloud service. 

Our current plan is to have contributed drivers live outside this repo, but we are considering giving them `gocloud.dev` import paths. So in your case, you'd create a repo that contained your driver package at top level, and we would make "gocloud.dev/pubsub/kafkapubsub" point to it.

Although your driver won't live in this repo, we'd still like to help you as much as possible, and we would like to review the code.

**Comment by jasongerard** [comment]
@jba sounds good. I'll start digging through the other implementations and hit back with questions as needed.

**Comment by vangent** [comment]
Hi @jasongerard have you started this? If not, I'm going to take a look.

**Comment by vangent** [comment]
I've started on this.

**Comment by h7kanna** [comment]
What go library is being considered for this ? Sarama or https://github.com/segmentio/kafka-go ?

**Comment by vangent** [comment]
I started with `segmentio/kafka-go` because the API seemed nicer, but I think it's one level of abstraction too high for us; in a way, it's trying to do something similar to what we're doing, building a nice Go API on top of the provider API. I also had issues making it performant. So, I'm currently using Sarama.

I have a PR that passes all of the conformance tests, but am still working out some issues with how/if `Ack` should work with Kafka's "index".
