### ISSUE TITLE
pubsub: consider removing context arg from New{Topic,Subscription}

### ISSUE THREAD

**Issue by jba** [google/go-cloud#733]
The `pubsub.NewTopic` and `pubsub.NewSubscription` methods take contexts. These are used only to provide a context to background driver methods (`SendBatch` and `SendAcks` respectively). The usage is unusual, since generally (but not universally), a context arg should not be used outside the lifetime of its function.

The only advantage of the arg is that it gives users some control over the underlying RPC. But I'm not sure if this extra degree of freedom is useful. Users can already cancel out of individual calls to `Send` and `Receive`, and they can call `Close` on Topics and Subscriptions when they want to stop using them.

I recommend removing the two context args.

@ijt @vangent @zombiezen

**Comment by zombiezen** [comment]
The convention we've had up to this point (somewhat cargo-culted from GCP client libraries, funny enough) that opening a connection or resource always takes a Context, just because it may need a Context to open it up. The fuzzy rule I've followed is that anything that does or could do I/O should take a Context.

**Comment by jba** [comment]
Exactly! And since the concrete types take driver types as args, and _the driver constructor does all the I/O_, there's no need for a context in the concrete type constructors.

At least, that's how pubsub is set up.

**Comment by vangent** [comment]
+1 for no `ctx` on the concrete type constructor; that's similar to `blob` as well.

**Comment by zombiezen** [comment]
/me re-reads the initial comment more carefully and examines the code.

Yes. I misunderstood this to be `acmepubsub.NewTopic(...)`. Sorry for the noise!
