### ISSUE TITLE
blob: check errors via an interface function, not an error subtype

### ISSUE THREAD

**Issue by jba** [google/go-cloud#744]
As per #730, blob drivers should provide a method to determine whether an error is retryable. The `Error` type would no longer do this, and maybe it should be removed.

**Comment by vangent** [comment]
Nit: for `blob`, it's not `IsRetryable` (currently the concrete type doesn't do any retries, although driver implementations might). It's `IsNotExistsError`.

**Comment by vangent** [comment]
Fixed in #748.
