### ISSUE TITLE
doc: add a section to the design doc about errors

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#749]
-- Wrap errors so that users can't peek into the provider-specific error details. Don't double-wrap.
-- All errors should be prefixed with the package name (e.g., `blob: fail`); we can do this as part of the wrapping.
-- For cases where we want to distinguish types of errors (e.g., `blob` has `NotExists`), the driver interface should have a function to do the check (e.g., `IsNotExists(err error) bool`. The concrete type should pass such functions the raw error that the driver generated (not a wrapped error).

**Comment by jba** [comment]
We should provide `As` or `Unwrap` on the error type as an escape hatch.
