### ISSUE TITLE
pubsub: remove driver Close methods

### ISSUE THREAD

**Issue by jba** [google/go-cloud#753]
It's unclear what the driver package's `Topic.Close` and `Subscription.Close` methods should do. 

We suggest that Topics and Subscriptions be created via `OpenXXX` methods which take some sort of closeable, connection-oriented value like a client or a gRPC `ClientConn`. Since the caller establishes the connection, they should be responsible for closing it. Also, they may want to reuse the connection for multiple Topics and Subscriptions. If `Topic.Close` closed the connection, that would invalidate all the other opened Topics. The alternative would be to reference-count the connections so only unused ones were closed. That would add a lot of complexity to the driver, and we want to keep them as simple as we can.

If the `Close` methods don't close the connection, it's not clear what is left for them to do. I suppose some driver implementation might have a client-side per-topic or per-subscription resource that they want to clean up (perhaps background goroutines), so we can leave the `Close` methods there and document their purpose. Or we could just remove them.

If a driver implemented a `Client` type with `OpenTopic`, `OpenSubscription` and `Close` methods, it probably wouldn't need `Topic.Close` or `Subscription.Close`. See #679.

**Comment by ijt** [comment]
I see. These `foo.OpenXXX` functions can return a cleanup func like in [`rsdmysql.Open`](https://github.com/google/go-cloud/blob/752f53caf6a49658f4fcbad2a9d08e0583a136fb/mysql/rdsmysql/rdsmysql.go#L62). That means we can get rid of the `Close` methods on the `Topic` and `Subscription` interfaces.

**Comment by vangent** [comment]
@ijt -- I don't think that's a better option. If you have cleanup to do, `Close` is more straightforward than an `Open` that returns a cleanup function.

I think @jba's point here is that there's no cleanup to do, so we can just get rid of them. For reference, `blob.Bucket` does not have a `Close`.

**Comment by jba** [comment]
@vangent: agreed.

**Comment by ijt** [comment]
I disagree. There is cleanup to do. See for example https://github.com/google/go-cloud/blob/5c0f0216e6467cc2d3ff95189cb580bc8dfd4751/internal/pubsub/gcppubsub/gcppubsub.go#L85.

**Comment by ijt** [comment]
Also, they seem equally straightforward to me, with the cleanup function having the advantage that it's obvious if you're not doing it.

**Comment by jba** [comment]
@ijt That cleanup is buggy, for the reason I gave above: someone might use the same client for multiple topics, then close the first topic, and be unable to use the second topic. The best way to avoid these sort of bugs is for the cleanup to happen in the same code that does the setup, e.g.
```
client := ps.NewClient(...)
defer client.Close()
t1 := gcspubsub.OpenTopic(...)
t2 := gcspubsub.OpenTopic(...)
```

**Comment by jba** [comment]
> Also, they seem equally straightforward to me, with the cleanup function having the advantage that it's obvious if you're not doing it.

That's a good point, but it's not idiomatic Go. We usually provide a `Close` method. See `os.File`, `sql.DB`, `net.Conn` and many others.
