### ISSUE TITLE
pubsub: replace `Close` methods with cleanup funcs returned from `Open` funcs

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#756]
This is related to https://github.com/google/go-cloud/issues/753.

The `rdsmysql` package shows an example of how to do this: https://github.com/google/go-cloud/blob/master/mysql/rdsmysql/rdsmysql.go#L62.

**Comment by vangent** [comment]
I'm not convinced we should do this. Why is it better than `Close`?

**Comment by jba** [comment]
In the linked code, I'd prefer if you just reminded people to close the `sql.DB`. That type already has a `Close` method, and that is the only cleanup you require, so I don't think there's anything else to do.

It's analogous to a function that opens and returns an `*os.File`. Everyone who uses that type knows that you call `Close` on it when you're done with it.

**Comment by ijt** [comment]
We decided against this during a meeting today. Closing the issue.
