### ISSUE TITLE
pubsub: determine when to fail on non-existent resources

### ISSUE THREAD

**Issue by jba** [google/go-cloud#759]
If the `OpenXXX` methods are asked to open non-existent resources, should they fail immediately, or should failure happen only when the resource is used?

Checking during open requires an RPC and a chunk of code, so it makes it harder to implement a driver, which we want to avoid. While users will know sooner that they made a mistake, they are already used to seeing errors only on first use, since at least on Amazon and GCP, there is no "open" step&mdash;you just provide a string and start using the resource.

So for simplicity, I'd suggest failing on first use. Or more precisely, not having drivers do anything special in any of their methods: just pass through to the provider, or in the case of Open, just create client-side data structures.

**Comment by vangent** [comment]
+1 for fail on first use. `Open` should be lightweight.

**Comment by jba** [comment]
Decision: `OpenXXX` methods don't fail. Add `Topic.Exists`.

**Comment by ijt** [comment]
Okay, we determined it. Closing this out.
