### ISSUE TITLE
all: add Azure support

### ISSUE THREAD

**Issue by vsekhar** [google/go-cloud#76]
For post-launch.

**Comment by zombiezen** [comment]
@VPashkov You should check over at Azure/azure-sdk-for-go#2296. Folks may already be working on this.

**Comment by joshgav** [comment]
@VPashkov we (Azure Go team) aren't able to work on this quite yet but would be happy to support you! Please do open issues in our repo or use https://github.com/Azure/azure-sdk-for-go/issues/2296 for questions, and would be great if you could @-mention me @jhendrixMSFT @marstr @vladbarosan in PRs, we'd love to review :) Thank you!

**Comment by vsaroopchand** [comment]
Disclaimer: Although I work for Microsoft, my comments represent my own personal interest in this project.

I can help with the implementation as well. Just out of curiosity, the TerraForm Azure Provider does a great job wrapping the Azure Management SDK for Go, see config.go

https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/config.go

For Azure Storage (Blob as an example) requires distinct steps:

1)	Authenticate with ServicePrincipal
2)	Provision a Resource Group (requires a Resource Group Name or Random Generated)
3)	Provision a Storage Account (requires a Storage Account Name or Random Generated)
4)	Retrieve the Access Keys to the Storage Account
5)	Create a Container (Based on Access Levels)
6)	Create / Upload Blob

Should the implementation automatically provision Resource Name, Storage Accounts or will this be supplied by the caller (exists)?    

@VPashkov – lets connect so we can coordinate our efforts.

**Comment by zombiezen** [comment]
Awesome, sounds good!

@vsaroopchand Take a look at the AWS and GCP implementations as well as [design.md](https://github.com/google/go-cloud/blob/master/internal/docs/design.md). Implementations should assume that provisioning has happened. Feel free to send questions to our [mailing list](https://groups.google.com/forum/#!forum/go-cloud).

**Comment by vsaroopchand** [comment]
I have a question on Reader.go (https://github.com/google/go-cloud/blob/master/blob/blob.go); there is no operation to return the read bytes? How should the retrieved bytes be returned?

**Comment by vangent** [comment]
Hi @vsaroopchand,

Reader.Read reads into the slice of bytes it is passed, p. There's an explanation of io.Reader and examples here:
https://tour.golang.org/methods/21

HTH!

BTW, PR #311 is providing a conformance test for Blob implementations which you should be able to use to test yours.

**Comment by vsaroopchand** [comment]
I committed a proposal for Azure Blobs (Block Blob) in my fork, [see](https://github.com/vsaroopchand/go-cloud/commit/f511f2d611f1acb8d4f7c3c5e348ee19e194f74f)

Here are some observations:
1)	This implementation wraps Block Blob; there are other types of blobs, [see ](https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs)
2)	I added a Settings type “AzureBlobSettings” for the various settings needed to read & write. It is definitely more than gcs and s3 hence the wrapper
3)	Caller must supply the autorest.Authorizer using one of the numerous ways to perform authorization. The sample uses a Service Principal for simplicity.
4)	Access key can be supplied otherwise it will be fetched from the Storage Account.
5)	Moniker ‘bucket’ is dropped for ‘container’ to keep with Azure naming and documentation
6)     Integration tests will be forthcoming 

Questions:
1)	Do you intend to support multiple file writes per one writer instance? 
2)	Do you intend to support listing all files within a container?

**Comment by zombiezen** [comment]
A `driver.Writer` will only operate on the blob that was specified at creation, but it may receive multiple calls to `Write` as per the [`io.Writer` interface](https://golang.org/pkg/io/#Writer).

Listing all blobs in a bucket is not yet supported. The feature is tracked in #241.

**Comment by vangent** [comment]
RE integration tests, it might be worth waiting for https://github.com/google/go-cloud/pull/311, which provides a conformance test for blob.Bucket. Assuming Azure uses HTTP, you should be able to use go-vcr to record/replay the tests similar to what is being done for S3 and GCS (see for example blob/s3blob/s3blob_test.go in the PR).

**Comment by vsaroopchand** [comment]
Ok, I can wait on #311 . I am also rethinking about the use of a Service Principal  vs. ConnectionString for Authentication. I feel the developer/client should manage AccessKey/ConnectionStrings. Using ConnectionString/SasToken removes the need for the Settings Wrapper and greatly simplifies the bucket initialization logic. I implemented both options for now.

**Comment by vsaroopchand** [comment]
Just an FYI, I changed the implementation to use the new storage [package ](https://github.com/Azure/azure-storage-blob-go/tree/master/2018-03-28/azblob). The original implementation which used **github.com/Azure/azure-sdk-for-go/storage** was moved to sub-folder /azureblob2 for reference and will be deleted at some point.

**Comment by vsaroopchand** [comment]
I was able to use the conformance test for Azure and results looks promising. 

Results:
PASS
ok  github.com/google/go-cloud/blob/azureblob	1.846s
Success: Tests passed.

I am gearing up to send my first pull request after some refactoring. Please look over if you want.

**Comment by philippgille** [comment]
@vangent:

1.5 months ago:

> Expect to hear more about next steps from us in the next few weeks.

(https://github.com/google/go-cloud/pull/427#issuecomment-423653123)

Any progress on this?

**Comment by vangent** [comment]
We are making progress on this but don't have an ETA for Azure support.

@philippgille, are you wanting to use Go Cloud with Azure?

**Comment by philippgille** [comment]
Not currently, but maybe in the future. `go-cloud` is on my radar for use in *multi-cloud* deployments, but doesn't seem to fit the bill as long as Azure isn't supported. When looking at multi-cloud strategies of enterprises, they always include the "big three": AWS, Azure and GCP.

**Comment by vangent** [comment]
@philippgille -- agreed. Follow this issue for updates.

**Comment by vsaroopchand** [comment]
@vangent I am still interested in helping with Azure support (if you need the help).

**Comment by vangent** [comment]
Hi @vsaroopchand ! At this point we are ready for your contribution, so we'd be delighted if you are ready & willing to refresh your earlier PR and re-send it.

Please let us know if you have any questions or comments!

**Comment by vsaroopchand** [comment]
Certainly, I will resume work by updating the original PR.

**Comment by vsaroopchand** [comment]
Opened the following issues to simplify ServiceBus PubSub driver

Add Exists test on Queue, Topic & Subscription
https://github.com/Azure/azure-service-bus-go/issues/96
 
Add support for SendBatch on Topic
https://github.com/Azure/azure-service-bus-go/issues/97
 
Add support for Bulk Dispositions on Subscription
https://github.com/Azure/azure-service-bus-go/issues/98
