### ISSUE TITLE
pubsub: Subscription.Shutdown(ctx) 

### ISSUE THREAD

**Issue by jba** [google/go-cloud#766]
At one point we considered a `Shutdown` method for `Subscription` that would replace `Close`. It would take a context so users could choose between allowing the outstanding `SendAcks` to complete, and stopping them (via cancel or timeout).

In the current implementation there is no way to stop a `SendAcks` call (since it takes `context.Background`). That's probably fine, but `Shutdown` is an alternative that gives the user more control.

**Comment by ijt** [comment]
If I recall correctly, this would entail:
1. Removing the Close method from driver.Subscription and pubsub.Subscription.
2. Adding a Shutdown method to pubsub.Subscription as described above.

**Comment by jba** [comment]
We already removed the Close from driver.Subscription.

We could either rename pubsub.Subscription.Close to Shutdown, or leave it. But the main thing is to add a Context arg.

**Comment by ijt** [comment]
Also, wouldn't we also want to change `Topic.Close()` to `Topic.Shutdown(ctx)` for consistency?

**Comment by jba** [comment]
> If there are still goroutines that have been spawned by `Batcher.AddNoWait` then are we meant to leak them if the context passed into `Shutdown` is canceled?

No, their contexts must get canceled as well.

> Also, wouldn't we want to change `Topic.Close()` to `Topic.Shutdown(ctx)` for consistency?

We haven't decided on Shutdown as a name, AFAICT. 

Since`Topic.Close` also involves long-running operations that the user might want to cancel, it should have the same name and also have a context arg.

Looks like you picked the name Shutdown, which is OK with me if we all agree.

**Comment by ijt** [comment]
I don't hear any objections to the Shutdown name. It seems like a reasonable choice.
