### ISSUE TITLE
all: use a better replay tool

### ISSUE THREAD

**Issue by jba** [google/go-cloud#770]
With the existing replay tool, order of RPCs matters, making concurrent tests unusable. The tool also doesn't have a way to capture state that may vary between runs, like times and random numbers.

Replace with `cloud.google.com/go/httpreplay` and/or `cloud.google.com/go/rpcreplay`.

**Comment by vangent** [comment]
The underlying replace tool we're using, `github.com/dnaeon/go-vcr`, doesn't enforce ordering, but we [added it explicitly](https://github.com/google/go-cloud/blob/master/internal/testing/replay/replay.go#L60). The default non-ordered matching was not sufficient to write tests. For example, a test like this:

1. Read blob "foo" --> expect error
2. Write blob "foo"
3. Read blob "foo" --> expect success
4. Delete blob "foo"
5. Read blob "foo" --> expect failure

has the same HTTP request for "read blob foo" three times, but with three different responses.

We already use `cloud.google.com/go/rpcreplay` for non-HTTP replay. I am not sure why we didn't use `cloud.google.com/go/httpreplay` to begin with, but there may be a good reason.

That said, I would be delighted if we could simplify this and make it less fragile for concurrent tests.

**Comment by jba** [comment]
> I am not sure why we didn't use `cloud.google.com/go/httpreplay` to begin with, but there may be a good reason.

An excellent one: it didn't exist.

**Comment by jba** [comment]
> the same HTTP request for "read blob foo" three times, but with three different response

I think (hope) that my tool would look for responses sequentially. The only way to screw it up would (should) be if you wrote the same request concurrently; but then your test would have a race condition, I believe.

I'll try to replace go-vcr with httpreplay and see how it goes.

**Comment by vangent** [comment]
@eliben is working on this, he's already converted GCS and S3.

**Comment by vangent** [comment]
Only a couple more before we can delete the go-vcr dependency!

**Comment by eliben** [comment]
TODO: factor out creation of replay directory - it's repeated in all the users of httpreplay

**Comment by eliben** [comment]
This is currently blocked by #1971

**Comment by eliben** [comment]
... and blocked (to some degree) by #1973
