### ISSUE TITLE
blob: modify NewReader/Writer to not return errors

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#771]
Instead, return errors lazily through Read/Write.

This is consistent with `OpenBucket` not returning an error until the first operation. Today, `driver.NewRangeReader` is required to return a `NotFound` error immediately, which means it must make an RPC/start reading.

I propose we change the constructor functions to not include an error, e.g.:

```
func (b *bucket) NewReader(...) *Reader
func (b *bucket) NewWriter(...) *Writer
```

on both the concrete type and the driver. All errors would be returned on the first `Read/Write`. Some drivers might get the error during construction of the `Reader/Writer`, and would stash until until the `Read/Write`.

**Comment by ijt** [comment]
Are you sure this isn't a premature optimization?
If we keep the error and add a `LazyErrors` bool field to the options struct then we could keep fast failure on providers that support it, and let users opt out if they can't afford the overhead of that initial RPC.

**Comment by vangent** [comment]
It's not really meant as an optimization, more of a simplification of the interface for users. It's one fewer error to worry about.

I don't think we should make the semantics "some providers fail fast, others do not" -- we want consistent semantics across providers as much as possible.

**Comment by ijt** [comment]
I buy the argument about consistency, but I'm not convinced that it's helpful to delay the errors. I would rather see fail-fast everywhere as the default.

**Comment by vangent** [comment]
Yea OK. This seems fine.
