### ISSUE TITLE
blob: support chunking of reads via the concrete type

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#778]
Imagine a user trying to read a huge blob and stream it somewhere. Today, they would have to implement their own chunking of the blob: determine the size, read first chunk via `NewReader` offset/length, etc. By default, drivers try to download the whole blob.

We should support chunking in the concrete type, emitting a series of calls to the driver when needed.

**Comment by jba** [comment]
I don't see why this would be necessary. 

Let's take S3 as an example. When you call NewRangeReader from s3blob, it makes an RPC to S3 and gets back a response that includes the body (contents) of the data, as an `io.ReadCloser`. Not a `[]byte`. How much data has actually been read onto the client box at that point? Probably just a network buffer's worth. 

Now the user calls the reader's `Read` method, passing in a 4K `[]byte`. That will be filled from the buffer. If the buffer doesn't have enough data, there will ultimately be a network read on the TCP connection to get more bytes. Ordinary TCP flow control will make sure that the client machine's buffers don't overflow. 

If the user keeps reusing the same 4k `[]byte` in calls to `Read`, there will never be more than 4K of the contents in userspace at a time, regardless of how large the actual blob is.

I'd imagine that every provider delivers blob content like this: they write the bytes to the TCP connection, and let TCP take care of chunking, buffering, flow control, etc.

All that said, there is value to be added in the form of retrying when reading a large object. We had several complaints about that and eventually built something that uses ranges to re-start reading (https://code.googlesource.com/gocloud/+/master/storage/reader.go#125). But that is a discussion for a different issue.

**Comment by vangent** [comment]
I find your analysis convincing. Closing.
