### ISSUE TITLE
blob: consider allowing drivers to implement Read/Write instead of NewReader/NewWriter

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#779]
Today drivers have to implement `NewReader/Reader`, which means that they effectively have to implement chunking themselves. For some drivers, this is natural; e.g., `filebob` can easily return a `Reader` for the file, and `gcsblob` uses a GCS library that exposes a `Reader` with internal chunking. For others, it is not; e.g., `s3blob` fetches the whole blob in one query today and then returns a reader over it. In general, implementing a `Reader` is tricky.

Same for `NewWriter/Writer`.

Perhaps we should allow driver implementations to provide simpler `Read/Write` functions instead of `Reader/Writer`, and handle the chunking in the concrete type.

#778 is related.

**Comment by vangent** [comment]
Another approach for this would be to provide a helper that converts a `Read` or `Write` function into a `Reader/Writer`. The `driver.Bucket` interface would stay the same, but provider implementations could use the helper if the underlying provider impl doesn't easily support chunking for a `Reader/Writer`.

**Comment by jba** [comment]
I'd suggest you take a look at the reader code for GCP (https://code.googlesource.com/gocloud/+/master/storage/reader.go#82), and make sure you can do what you need in a provider-agnostic way.

**Comment by vangent** [comment]
@jba's analysis on #778 has convinced me this isn't necessary.
