### ISSUE TITLE
runtimeconfigurator: test hangs when run locally in replay mode with no internet connection

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#793]
### To Reproduce

Turn off wifi, unplug ethernet.
```
cd runtimevar/runtimeconfigurator
go test -v
```

At this point it hangs. Hit ctrl-\ to get a stack trace. That shows that it hangs in `grpc.DialContext`.

## Expected behavior

The test should pass.

### Version

a36581c5b990d15cef1835c94f3cbf11f5f78cce

**Comment by vangent** [comment]
Isn't this a bug in the replayer?

**Comment by ijt** [comment]
@vangent, I don't think so. The `newHarness` function is creating a new gRPC connection using a hard-coded address on a different machine: https://github.com/google/go-cloud/blob/413d959165870d5a1b5706b859ac0517223d9ccc/runtimevar/runtimeconfigurator/runtimeconfigurator_test.go#L56

**Comment by vangent** [comment]
It's calling `setup.NewGCPgRPCConn`, which is here:

https://github.com/google/go-cloud/blob/413d959165870d5a1b5706b859ac0517223d9ccc/internal/testing/setup/setup.go#L116

and it ends up creating the `conn` with `opts` that it got from the `replayer`. I would think that those options are supposed to make it not actually connect to the endpoint.

**Comment by vangent** [comment]
Here's the replayer documentation that says this is how you're supposed to do it:
https://godoc.org/cloud.google.com/go/rpcreplay#hdr-Replaying

**Comment by ijt** [comment]
@vangent, looking again, I think you're right about this. I'll see if I can confirm with a smaller example involving only the replayer.

**Comment by ijt** [comment]
This is taking too long. I think let's just assume it's a bug in the replayer. I don't want to spend more time on it right now.

**Comment by vangent** [comment]
I filed https://github.com/GoogleCloudPlatform/google-cloud-go/issues/1239 for `rpcreplay` to look into this.
