### ISSUE TITLE
batcher: panic in Shutdown

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#799]
```
$ cd internal/pubsub
$ for i in $(seq 100); do go test -count=1 --run Example_sendReceiveMultipleMessages; done
```

> panic: sync: WaitGroup is reused before previous Wait has returned [recovered]
>         panic: sync: WaitGroup is reused before previous Wait has returned.
> github.com/google/go-cloud/internal/batcher.(*Batcher).Shutdown(0xc000120230)
>         /usr/local/google/home/rvangent/go/src/github.com/google/go-cloud/internal/batcher/batcher.go:127 +0x5f
> github.com/google/go-cloud/internal/pubsub.(*Subscription).Close(0xc0000da4b0, 0x3b9aca00, 0xc0000da4b0)
>         /usr/local/google/home/rvangent/go/src/github.com/google/go-cloud/internal/pubsub/pubsub.go:191 +0xac
> github.com/google/go-cloud/internal/pubsub_test.Example_sendReceiveMultipleMessages()

**Comment by jba** [comment]
I'm not sure how the panic is possible, unless Shutdown is called more than once. 

I'll make it idempotent.

**Comment by vangent** [comment]
> I'm not sure how the panic is possible, unless Shutdown is called more than once.
> 
> I'll make it idempotent.

I believe the panic was because `wg.Add` was called after `wg.Wait` or something like that. The `Add` was being called like this: `go Add` so there was a race.
