### ISSUE TITLE
pubsub: add tests that set maxHandlers >= 2 and run them with -race in Travis

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#820]
We'll need one for sending to a topic and another for acking messages.

There will have to be a way to set maxHandlers in Topics and Subscriptions to make this work.

**Comment by vangent** [comment]
Please also update the docstring for `SendBatch` to make it clear that driver implementations need to support multiple concurrent calls to it (and similar for other driver APIs that don't have this).

**Comment by vangent** [comment]
@jba is adding a test for RabbitMQ that tests this; I think it should be moved to be a conformance test as part of this issue.

**Comment by jba** [comment]
The tricky part is: we don't want to expose `maxHandlers` as a knob to users, but the conformance test is in a different package so if we give it the knob, we expose it to everyone. 

In the past I've named exported symbols `Internal...` and documented that they shouldn't be used. (e.g. https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/iam/iam.go#L102). When I've done that before there was no reason for a user to call those functions anyway; in the current case, we'd clearly be exposing a knob that someone might want to turn.

An alternative is to just set `maxHandlers` to some small number greater than 1.

**Comment by vangent** [comment]
It seems to me we should do some benchmark testing to find a "good" value for `maxHandlers`, and use that all the time (including tests). I'm not sure what the value of exposing the knob to tests but not externally is.

Note that an alternative way to manage this in tests is to inject a different bundler, so you can more precisely control what it does (even setting `maxHandlers` to a value > 1 will not guarantee anything in terms of concurrency of calls to the driver).

**Comment by ijt** [comment]
@vangent, I don't know how we could find a value of `maxHandlers` that would work well for all pubsub providers. The best setting could vary depending on the bandwidth of the connection as well.

**Comment by vangent** [comment]
How do you plan to reconcile that with "we don't want to expose `maxHandlers` as a knob to users"? Or do you think it will be modified dynamically in some way?

Regardless, I still think that you are going to end up wanting to be able to inject a fake bundler in tests, so that you can test what you want to test without the "real" bundler getting in the way.

**Comment by ijt** [comment]
@vangent, yes, I was thinking it could be adjusted dynamically.

Ideally I guess we would want to start sending the next batch immediately after the current batch has been sent, before the response comes back for the current batch's RPC. I doubt whether gRPC makes this possible, but it's probably worthwhile for us to have a clear picture in mind of what the optimal strategy would do.

**Comment by vangent** [comment]
Different drivers set different handlers now, and all tests run with `--race`.
