### ISSUE TITLE
wire: unable to be used inside of a Go Module?

### ISSUE THREAD

**Issue by metaldrummer610** [google/go-cloud#821]
I'm using Go modules for dependency management in my project, and I have been unable to get the `wire` command to work properly. I should note this project is *not* is my GOPATH.

When I execute `wire`, I get the following message:

```
go [list -e -json -compiled -test=false -export=false -deps=true -tags=wireinject -- .]: exit status 1: go: cloud.google.com/go@v0.30.0: unrecognized import path "cloud.google.com/go" (https fetch: Get https://cloud.google.com/go?go-get=1: read tcp 10.100.40.164:52428->216.58.217.238:443: read: connection reset by peer)
        go: cloud.google.com/go@v0.26.0: unrecognized import path "cloud.google.com/go" (https fetch: Get https://cloud.google.com/go?go-get=1: read tcp 10.100.40.164:52428->216.58.217.238:443: read: connection reset by peer)
        go: error loading module requirements

wire: generate failed
```

However, if I run `wire` outside of the module, it works just fine and I'm able to use the tool no problem.

I've tried various versions of go-cloud (v0.6.0, v0.5.0, v0.2.0) and they all show this behavior.

I saw #235 and it was _similar_ but not quite the same issue. Have any of you seen anything like this before?

**Comment by zombiezen** [comment]
No. @metaldrummer610, are you certain that you have rebuilt Wire with a commit past 95bbfbd8a51a07fd10e2e1ae9af45765ca0f6a62 (like v0.6.0)? (Just trying to eliminate possibilities here.)

The error message that you're seeing seems to imply some network issue while attempting to fetch the meta tags from `cloud.google.com/go`. Are you behind a firewall or some other proxy?

**Comment by metaldrummer610** [comment]
@vangent I tried `go build`, but it didn't work because wire is generating some functions that are missing otherwise.

@zombiezen I tried it again just now at home (was at the office earlier) and running wire worked just fine. I'll try again tomorrow at the office to see if it is some weird network issue. I had a sneaking suspicion it might have been a network issue since it was saying it couldn't reach https://cloud.google.com/go.

**Comment by metaldrummer610** [comment]
I tried it again at work, and it seems to work just fine now. I'll have to reach out to our network team to see if they were blocking those calls to cloud.google.com for some reason. I'll go ahead and close this, and will reopen if the problem comes back.

Thanks for the help and the quick responses!
