### ISSUE TITLE
Move cloud provider implementations to dedicated repositories

### ISSUE THREAD

**Issue by vsekhar** [google/go-cloud#86]
Post launch. Possibly "post 1.0" of the APIs.

Generic code should `import golang.org/x/cloud`.

Cloud-specific code (e.g. code written to be fed into Wire) should import additional cloud-specific repositories (to be determined) to make use of pre-written wirings for GCP, AWS, etc.

**Comment by jba** [comment]
Is `golang.org/x/cloud` where we want to end up? `golang.org/x` is for projects that ultimately should be elsewhere, like the standard library. At least that's how it's commonly perceived.

**Comment by zombiezen** [comment]
It's possible that the generic APIs (concrete type + driver) could end up there, but that would have to go through the Go proposal process. Even if it did, the structure would largely remain the same no matter whether Cloud landed in x/ or as a standalone import path: the provider implementations should be on a separate release cycle (much like the Terraform provider model).

**Comment by vangent** [comment]
This is stale; we are moving to use a custom import domain. Some providers will stay in our repo, others can be in other repos.
