### ISSUE TITLE
all: Travis takes 12m to run, want 5m

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#862]
Even after splitting wire out into its own github repository, it's taking an excessive amount of time for our tests to run.

**Comment by ijt** [comment]
See for example
https://github.com/google/go-cloud/pull/859/checks?check_run_id=36667973

**Comment by ijt** [comment]
To make this issue specific and actionable, let's set the target at 5m.

**Comment by vangent** [comment]
Which test is taking that long on Travis? It takes O(30 seconds) running locally (including `-race` and `-coverpkg ./...`).

**Comment by ijt** [comment]
Looks like it's possible to parallelize this: https://docs.travis-ci.com/user/speeding-up-the-build/

Also see https://gist.github.com/rajeshtaneja/52e62002f0ccf068524a.

**Comment by ijt** [comment]
Oh, hmm, I made a mistake. Those jobs are already running in parallel. See for example https://github.com/google/go-cloud/pull/859/checks?check_run_id=36684730. 

There is considerable variance in how long it takes these to run. Here's a run that took only 4min total: https://github.com/google/go-cloud/pull/859/checks?check_run_id=36684730.

**Comment by ijt** [comment]
One quick way to improve our Travis build time would be to drop the Windows builds until they become fast. Maybe we could run them less frequently, like on a daily basis.

**Comment by vangent** [comment]
Is the Windows build consistently slower than the others?

Another thing we could try is to only use `-coveragepkg` on one of the builds (e.g., Linux), and maybe the same for `-race`. I'm pretty sure the former slows things down a lot, and it doesn't add any value to do coverage 3x. Not sure how much `-race` slows things down but easy to check.

**Comment by ijt** [comment]
As discussed today during the standup, we can work around this for now by making the Windows builds run only on post-submit.
