### ISSUE TITLE
server/sdserver: NewExporter should return a cleanup function for Exporter.Flush()

### ISSUE THREAD

**Issue by garukun** [google/go-cloud#867]
### Describe the bug

Seems like with the current design of providing a StackDriver exporter, it's the clients responsibility to inject an exporter, and then remember to call `contrib.go.opencensus.io/exporter/stackdriver.Exporter.Flush()`. While `wire` supports cleanup, I thought it maybe good idea to augment `NewExporter` to also provide a cleanup function.

Not sure how this will affect existing users though; but, maybe, we can added a new provider that supports this.

## Expected behavior

When one inject a `stackdriver.Exporter`, she should expect the cleanup function should be returned as well so remind of her to call to flush.

### Version

v0.6.0

### Additional context

I'm happy to put together a PR if this is going along the right direction. :)

**Comment by zombiezen** [comment]
SGTM. I think the breakage risk here is acceptable (still pre-1.0), so feel free to modify existing providers.
