### ISSUE TITLE
pubsub: each cloud driver implementation should have examples

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#869]
The examples don't have to demonstrate how to use the concrete type; the concrete type examples should show that. The per-provider examples are for demonstrating how to use the provider-specific constructor.

For example, `gcppubsub` has:

```
func OpenTopic(ctx context.Context, client *raw.PublisherClient, proj gcp.ProjectID, topicName string, opts *TopicOptions) (*pubsub.Topic, error) {
```

An example would make it easier for a new user to figure out how to create a `raw.PublisherClient`.

**Comment by ijt** [comment]
jba@, are you still planning to do this? Do you mind if I grab it?

**Comment by vangent** [comment]
Thanks @ijt. The only one left is `mempubsub`, and I'm adding that in #1177.

**Comment by ijt** [comment]
Sounds good.
