### ISSUE TITLE
all: review godoc for formatting and clarity

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#896]
There are a bunch of places with bad formatting (e.g., things that look like bullet points in the code are collapsed onto a single line, accidental code blocks, etc.).

**Comment by vangent** [comment]
godoc -http=localhost:8080
  should work locally for me.

**Comment by shantuo** [comment]
I noticed this as well on godoc.org, maybe that's a bug on gddo rendering.

**Comment by vangent** [comment]
I've done a pass over runtimevar and blob and made a bunch of changes. We can make incremental changes after this, but I'm going to close this particular issue.
