### ISSUE TITLE
pubsub: split `pubsub.Message` and `driver.Message` into `InMessage` and `OutMessage`

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#903]
See the discussion on https://github.com/google/go-cloud/issues/657 for motivation.

**Comment by jba** [comment]
Or maybe `Message` and `ReceivedMessage`.

Or `SendMessage` and `ReceiveMessage`.

**Comment by vangent** [comment]
Another alternative would be to put `Topic` and `Subscription` in separate packages, then they could each have their own `Message`. E.g., `pub.Topic` and `sub.Subscription`.

**Comment by ijt** [comment]
We decided against this in a meeting. Closing the issue.
