### ISSUE TITLE
blob/all: consider supporting a base path during construction

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#909]
`fileblob` already has this since you give it a root dir, but other providers are assumed to be rooted at the top-level of the Bucket. The user can always add a prefix everywhere, but it might be useful to allow them to specify a prefix at construction time.

For example, I'm uploading stuff to my Bucket in a virtual folder `foo/bar`; I should be able to specify `foo/bar` at construction time and be confident that everything is scoped to `foo/bar` and below.

**Comment by zombiezen** [comment]
Yeah, it would be good to create a Bucket that wraps another bucket and prepends a prefix or otherwise performs deterministic string manipulation on the keys.

**Comment by vangent** [comment]
That's an interesting idea. I was thinking of just adding an `Option` to `gcsblob` and `s3blob` and passing it through to the concrete type.

**Comment by jba** [comment]
I don't think this sort of minor convenience feature has a place in blob, which is supposed to be somewhat minimal.

**Comment by vangent** [comment]
This might be useful for applications for which the entry point for the user is a URL. I.e., a command-line tool that takes a Go Cloud URL as an upload destination. The end user doesn't have access to code, so they can't do this themselves. Our current URL only allows target the base dir of the bucket. Allowing something like `s3://mybucket?base=foo/bar` would be more flexible.

I'm not sure how common this is; it maybe that people just have multiple buckets instead of a single bucket with directories.

**Comment by zombiezen** [comment]
@vangent The issue with passing options like that is that then every implementation would need to do this, versus having a "routing bucket" implementation that could do more fancy things with the key space, which I think is a more general solution and fits nicely in the Go "composition over specialization" design space.

**Comment by vangent** [comment]
Hmm, I intended my comment as a "requirements" / use case, not as an implementation suggestion.

For implementation, I think that `blob.OpenURL` could intercept the `base=` option from the URL and create a "routing bucket" as you describe, so provider implementations would never see the option.

Do you have another idea for how the "routing bucket" would get created from a URL?

**Comment by zombiezen** [comment]
I'm imagining something like (hand-wavy sketch):

```go
// NewBucketRouter returns a new bucket that uses another bucket as storage,
// but transforms any keys using the function given. The function must return the
// same results for the same key.
func NewBucketRouter(b *Bucket, mapKey func(key string) (string, error)) *Bucket
```

or if you want to get even fancier and support mapping to multiple physical buckets:

```go
// NewBucketRouter returns a new bucket that uses other buckets as storage
// based on the routing function given.
func NewBucketRouter(route func(key string) (*Bucket, string, error)) *Bucket
```

**Comment by vangent** [comment]
Yea that works if you are writing code, but not if you are just providing a URL.

E.g., the app looks like this:

```
b := blob.Open(config.Target)
... uses b...
```

and the user is providing `Target` in the config with something like `s3://mybucket`.

Yes, we could require every app to do something like:

```
b := blob.Open(config.Target)
if config.BaseDir != "" {
  b = NewBucketRouter(b, ...)
}
... uses b...
```

but if this is a reasonably common use case it seems like something we should make easier.
