### ISSUE TITLE
internal/secrets: Add more tests

### ISSUE THREAD

**Issue by clausti** [google/go-cloud#919]
Per a [discussion](https://github.com/google/go-cloud/pull/899#discussion_r239570657)  on the `localsecrets` implementation PR, we should add additional conformance tests for `secrets`. 

At minimum: 
- Verify that encrypting the same message with the same key twice doesn't result in the same encrypted bytes.
- Verify that different keys work (and again, don't result in the same encrypted bytes).

**Comment by vangent** [comment]
@shantuo did this the first one. I'll add the second.
