### ISSUE TITLE
blob: enforce MD5 integrity check in the concrete type

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#930]
Currently, the meaning of the `WriterOptions.ContentMD5` field is underspecified:

https://github.com/google/go-cloud/blob/623057483416703a7029ee5e7827cbab28171d48/blob/blob.go#L575-L577

Between this and the doc comment for `driver.WriterOptions`, Go Cloud does not specify:

- Whether the concrete type or the driver should be performing this check. (Currently it is up to the driver; the concrete type does nothing.)
- What the behavior of a `nil` `ContentMD5` is. (Currently driver-specific, but assumed to mean "don't check".)
- What happens if the bytes sent to the `Writer` don't match the MD5. (Currently driver-specific, and it's unclear what the behavior is.)

## Proposed Change

I would like to perform the integrity check in the concrete type, so that drivers can safely ignore the field without being nonconformant. An error would be returned in `Close`, and the concrete type would cancel the Context passed to the driver's `NewTypedWriter` method so as to abort the write so it has no effect. Drivers can pass along the MD5 header to their underlying network service so as to guarantee the integrity of the bytes in transit.

Of course, this new behavior should all be reflected in the documentation and conformance tests. AFAICT the only new conformance test is to verify that writing a blob that does not match MD5 does not change an existing blob.

/cc @vangent @shantuo

**Comment by vangent** [comment]
SGTM.
