### ISSUE TITLE
all: consider adding Snap Package support

### ISSUE THREAD

**Issue by mikeroyal** [google/go-cloud#932]
I was thinking in the install and setup could be improved for Ubuntu and other Linux distros by having a [snap package](https://snapcraft.io/) version. If it's not a priority would you mind if I made the snap as a contribution?

[Crafting your first snap](https://tutorials.ubuntu.com/tutorial/create-your-first-snap#0)

[Build and test snap](https://snapcraft.io/build)

[Getting Started snap template](https://github.com/snapcrafters/fork-and-rename-me)

**Comment by vangent** [comment]
Go Cloud provides libraries, not applications. From a brief glance, Snaps are for applications....?

**Comment by mikeroyal** [comment]
Yeah, looking at the project again snaps may not be best for this project. I will close this issue.
