### ISSUE TITLE
pubsub: set maxHandlers to different values for different providers

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#943]
The settings can be obtained from https://github.com/google/go-cloud/issues/870 for gcp, mem, and rabbit.

**Comment by vangent** [comment]
Let's wait on tuning this until we're done with other performance work for pubsub like making concurrent `ReceiveBatch` calls, etc.

**Comment by eliben** [comment]
@vangent please update w/ latest status/plans or close

**Comment by vangent** [comment]
This is done.
