### ISSUE TITLE
all:  documenting design pattern for constructors and make packages consistent with it

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#970]
@jba 
@zombiezen 

We seem to have several patterns for how driver implementations expose their constructors. We should document our preference and aim for consistency unless there are good reasons for variance.

- `blob` has `OpenBucket` at the top level. This seems simplest to me.
- `runtimevar/paramstore` has a `Client` struct ([here](https://github.com/google/go-cloud/blob/master/runtimevar/paramstore/paramstore.go#L42)). `Client` then exposes `NewVariable`, which is how you get an instance of the concrete type.
  - I think we can just get rid of this intervening type and have `NewVariable` take whatever is being passed to `NewClient`.
- `pubsub/mempubsub` has a `Broker` ([here](https://github.com/google/go-cloud/blob/master/internal/pubsub/mempubsub/mem.go#L39)) and then `NewTopic` takes an instance of the `Broker`.

**Comment by jba** [comment]
I'm in favor of removing `mempubsub.Broker`. That was my original design.

I don't know if we can make this a hard-and-fast rule. We may want a client-like type if there are many things that are shared among the resources. But as a guideline, I'm fine with it.

**Comment by vangent** [comment]
@jba -- I think this was my suggestion. At the time, I thought it was necessary in order to do the kinds of conformance tests we need (IIRC, the previous version had no  way to connect specific topics to specific subscriptions). If there's a better way that enables the tests we need but gets rid of `Broker`, let's at least try it out.

**Comment by jba** [comment]
If we removed `Broker`, we would need a global map of topics by name. That would violate @zombiezen's rule about no global state. But since I think of `mempubsub` as test code, that doesn't bother me.

I started the PR. Let me know if it's worth finishing.

**Comment by zombiezen** [comment]
I don't believe that any naming scheme is necessary for `mempubsub`, and thus no global state. The sketch I made to Robert was:

```go
package mempubsub

// Topic is an in-memory topic that can have in-memory subscriptions created.
type Topic struct {
  *pubsub.Topic

  // ...
}

// NewTopic creates a new in-memory topic with no subscriptions.
func NewTopic() *Topic { /* ... */ }

// NewSubscription returns a new subscription to the topic.
func (t *Topic) NewSubscription() *pubsub.Subscription { /* ... */ }
```

One could also get fancy with `As()` methods and instead make `NewSubscription` just take in a `*pubsub.Topic`:

```go
package mempubsub

// NewTopic returns a new in-memory topic.
func NewTopic() *Topic { /* ... */ }

// NewSubscription returns a new in-memory subscription.
// NewSubscription panics if the passed in topic did not come from mempubsub.
func NewSubscription(*pubsub.Topic) *pubsub.Subscription { /* ... */ }
```

**Comment by vangent** [comment]
Of those options, I like the second better than the first.

Before making this change, it would be good to have some conformance tests that require different combinations of topics/subscriptions (e.g., 1 topic with 2 subscriptions, 1 topic with a subscription from a different topic, ...?), so that we can make sure we can support that. It's possible we'll end up with some kind of map of topics/subscriptions in the test harness.

**Comment by jba** [comment]
> it would be good to have some conformance tests that require different combinations of topics/subscriptions

Happy to take that on, but let's agree on what it would look like. There was some discussion [here](https://github.com/google/go-cloud/issues/861#issuecomment-443441508). WDYT?
