### ISSUE TITLE
pubsub: add cross-cloud examples

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#978]
These should go into the top-level `samples` directory once `pubsub` moves out of internal.

Some ideas:
* `pub`: command line tool to publish a message to a topic, like `pub -env=gcp -t "/fully/qualified/path/to/topic" "message"`
* `sub`: command line tool to tail from an existing subscription, like `sub -env=aws -s "SQS queue URL"`

**Comment by ijt** [comment]
Here's some additional detail about how these commands could look:

```
pub new $topic   # creates a new topic
pub del $topic    # deletes an existing topic
pub send $topic "body of message" [-a "key1:val1,key2:val2"]   # sends a msg to an existing topic
```

```
sub new $topic $subscription  # creates a new subscription to an existing topic
sub del $subscription   # deletes an existing subscription
sub recv $subscription  # receives from an existing subscription (tail -f style)
sub recv -n 10   # receives 10 messages from an existing subscription
```
They could all take a `-env=[gcp|aws|rabbit|etc]` flag or maybe an environment variable like `$ENV` or `$GOCLOUD_ENV`.

**Comment by vangent** [comment]
Why `new` and `del`? Those aren't in our APIs...

> They could all take a -env=[gcp|aws|rabbit|etc] flag or maybe an environment variable

Maybe pubsub should support URLs like `blob` does....
https://godoc.org/gocloud.dev/blob#Open
